umbraco/UmbracoDocs

Documentation/Reference/Management-v6/Services/LocalizationService.md

I've added all Methods to the Umbraco.Core.Services.LocalizationService documentation

Update LocalizationService (v6+), adding all Methods

---

Documentation/Reference/Management-v6/Services/ContentService.md

Added new/missing methods, completing the description of the ContentService (for now).
Sorted all methods, similar to the (order of the) methods in the ContentService.

Update ContentService - added all missing methods

---

Documentation/Reference/Management-v6/Services/ContentService.md

Minor update: _ markup for all optional parameters. Also added brackets [ ] to make it as obvious as possible (in case the reader is unfamiliar with italic markup marking optional parameters...).

Minor update: _ markup for all optional parameters

---

Documentation/Reference/Templating/Macros/Razor/using-dictionary-items.md

I'm not 100% sure but I think the library namespace is missing

umbraco.GetDictionaryItem -> umbraco.library.GetDictionaryItem

---

Extending/Property-Editors/index.md
Getting-Started/Backoffice/index.md

Changing Headers

---

Getting-Started/Setup/Install/install-umbraco-with-nuget.md

This is a really relevant example. :)

Update install-umbraco-with-nuget.md - more relevant example

---

Tutorials/Creating-a-Property-Editor/index.md

Includes a change to the package name which makes it unique.

Small changes to creating a property editor

---

Add-ons/UmbracoForms/Developer/Working-With-Data/index.md

Updated the Razor snippet for working with data from Umbraco Forms to dynamic Razor from the old DynamicNode Razor

Fixes:#237: Updated the Razor snippet for working with data from UF

---

Reference/Plugins/creating-resolvers.md

A wrong variable name was used

Fixed resolvers documetation

---

Tutorials/Creating-Basic-Site/Creating-Master-Template-Part-2.md

Replaced with a link to Forms.

Removing reference to contour

---

Umbraco-as-a-Service/Getting-Started/Baselines/index.md

Mimic the PR from here: https://github.com/umbraco/.comDocumentation/pull/2

Update baselines docs

---

Getting-Started/Code/Creating-Forms/index.md

Some minor punctuation/grammar corrections.

Creating-Forms/index.md - punctuation corrections

---

Tutorials/Creating-a-Property-Editor/index.md
Tutorials/Creating-a-Property-Editor/part-2.md
Tutorials/Creating-a-Property-Editor/part-3.md
Tutorials/Creating-a-Property-Editor/part-4.md

Mainly typos and missing bits + pieces/words.

Updates to the Property Editor tutorial

---

README.md
Reference/Cache/index.md
Reference/Cache/updating-cache.md
Reference/Config/index.md
Reference/Config/webconfig/index.md
index.md

I was on a roll, so ran through some more files :)
Just let me know if it's too nit-picky :)

More fixes for typos, formatting and wording

---

Reference/Security/index.md

See http://issues.umbraco.org/issue/U4-7032

Adds Security reference doc - for custom back office user auth.

---

Implementation/Rest-Api/index.md
Implementation/index.md

These are initial docs for the REST API package that will be released alongside 7.3.0

Adds Rest api docs

---

Reference/Templating/index.md

Hi - It's me again - just doing my rounds... :-)

Correct the casing of HTML

---

Reference/Templating/Mvc/child-actions.md

resolving simple typo

---

Documentation/Reference/Templating/Mvc/forms.md

I added a section on how to display success messages... I explained two different ways.

Display success messages added

---

Reference/Routing/WebApi/authorization.md

Forgot that the backend needs different routing, and this pages wasn't mentioning it.

added link to routing information

---

Getting-Started/Setup/Server-Setup/Load-Balancing/index.md

Corrected the link to the CodeGarden 15 session on Load Balancing

Fixed Load Balancing video link

---

Reference/index.md

Fix broken link that seems to work on https://our.umbraco.org/documentation/Reference/

Broken link to REST api's

---

Reference/Templating/Macros/Partial-View-Macros/index.md

It wasn't clear where to search for the MacroParameters.

added MacroParameter example

---

Reference/Querying/DynamicPublishedContent/index.md

DynamicPublishedContnet to DynamicPublishedContent

Fixed typo

---

Umbraco-as-a-Service/Set-Up/Working-Locally/index.md

Fix broken link to download GitExtensions

---

Tutorials/Creating-Basic-Site/Outputting-the-Document-Type-Properties.md

Just fixing a typo in the documentation.

Changed 'viola' to 'voila' for the intended meaning

---

Reference/Routing/Request-Pipeline/outbound-pipeline.md

Should be merged in when we merge: https://github.com/umbraco/Umbraco-CMS/pull/1243

Updating docs for URL provider

---

Getting-Started/Setup/Server-Setup/Load-Balancing/flexible.md
Getting-Started/Setup/Server-Setup/azure-web-apps.md
Getting-Started/Setup/Server-Setup/index.md

Updated some docs which also has to do with: http://issues.umbraco.org/issue/U4-8371

Azure, examine and flexible LB updates

---

Extending/Healthcheck/index.md

For when it gets merged into 7.5.0

Adds healthcheck docs

---

Implementation/Controllers/index.md

I believe it was a copy mistake and it should be Umbraco Api Controllers.

Fixed small typo in the Controller documentation

---

Add-ons/UmbracoCourier/Developer/index.md
Add-ons/UmbracoForms/Editor/index.md
Getting-Started/Code/Subscribing-To-Events/index.md
Getting-Started/Data/Data-Types/index.md
Getting-Started/Data/Defining-content/index.md
Implementation/Controllers/index.md
Implementation/Custom-Routing/index.md
Implementation/Default-Routing/Controller-Selection/index.md
Implementation/Default-Routing/Execute-Request/index.md
Implementation/Default-Routing/Inbound-Pipeline/index.md
Implementation/Rest-Api/index.md
Reference/Config/ExamineSettings/index.md
Reference/Config/tinyMceConfig/index.md
Reference/Management/Models/index.md
Reference/Plugins/index.md
Reference/Querying/UmbracoHelper/index.md
Reference/Routing/Authorized/index.md
Reference/Routing/WebApi/index.md
Reference/Templating/Masterpages/index.md
Reference/index.md
Tutorials/Creating-a-Property-Editor/index.md

I used the following website to trawl 100 pages of the documentation to check and fix any typos i could find. It doesn't cover the entire documentation but it's a start.
[Online Spell Check Tool](http://www.internetmarketingninjas.com/online-spell-checker.php)

Typo fixes

---

Products/UmbracoForms/Developer/Configuration/index.md
Products/UmbracoForms/Developer/index.md

Adds new config section & lists out our new config setting for AntiForgery token (more of the other config values need to be added here too)

Forms - AntiForgery Config Setting

---

Umbraco-Cloud/Set-Up/Config-Transforms/index.md

http://issues.umbraco.org/issue/UAASSCRUM-602

UAASSCRUM-602 Update documentation for Vendor specific transform

---

Add-ons/UmbracoForms/Developer/Extending/Adding-a-Exporttype.md
Add-ons/UmbracoForms/Developer/Extending/index.md

This needs to be reviewed with Forms code & that the samples are easy to read, work & best practise etc...

Adding documentation for creating Form Export Providers

---

Reference/Common-Pitfalls/index.md
Reference/index.md

Part of core sprint task - see review board for details U4-9098

Document the do's and don't do's in Umbraco

---

Reference/Common-Pitfalls/index.md

The "Umbraco" property is an UmbracoHelper, not an UmbracoContext.
A few typos.

Fixed typos and incorrect info.

---

Getting-Started/Setup/Install/install-umbraco-manually.md

Spell check Word: wizard.

---

Umbraco-Cloud/Set-Up/Working-With-UaaS-Cli/index.md

Minor stuff like typos, formatting etc.

Updates to  UaaS-CLI guide

---

Umbraco-Cloud/Getting-Started/index.md

I have updated Umbraco Cloud documentation so it reflects our currently setup with starter plan and professional plan. I also added documentation about the live environment has initial authorization until it has been paid.

Updated Umbraco Cloud documentation

---

Umbraco-Cloud/Set-Up/Working-Locally/index.md

Made it a bit more clear that we are using Source Tree in this example.

Update working locally docs

---

Getting-Started/Setup/Server-Setup/azure-web-apps.md

Removes reference to directory @see https://our.umbraco.org/forum/developers/extending-umbraco/74731-examine-corruption-issues

Updates to Azure best practices.

---

Reference/Templating/Mvc/partial-views.md

Please verify documentation I added is correct

CachedPartial - added contextualKeyBuilder param

---

Reference/Routing/Request-Pipeline/inbound-pipeline.md

I believe the intended meaning was 'and' by the sentence structure.

fix typo and grammar

---

Add-ons/UmbracoForms/Developer/Rendering-Scripts/index.md

Recently missed this step totally as it was stuck at the bottom of the page with nothing to highlight it. Adding the code snippet draws your eye to it. It helps.

Added renderscripts macro code to highlight it needs adding.

---

Umbraco-Cloud/Set-Up/Working-With-UaaS-Cli/index.md

This update adds a section about the configuration file, as I couldn't find anything about it — so I thought I'd better put it somewhere that would be easy to find for the next guy or girl :-)

UaaS-CLI doc update

---

Reference/Querying/UmbracoHelper/index.md

Added the missing @ and closing bracket

If sample markup correction

---

Reference/Config/umbracoSettings/index.md

Fixes #U4-7101 and a little confusion I had with this one myself. Having checked through the code I believe this setting does very little these days however the existing documentation was miss leading. Feel free to sanity check it :)

Correcting ContinouslyUpdateXmlDiskCache description

---

Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Grid-Layout/Render-Grid-In-Template.md

…tml and Model.Content.GetGridHtml approaches..
see http://issues.umbraco.org/issue/U4-9850

Promote the HtmlHelper methods over the obsolete CurrentPage.GetGridHtml

---

Umbraco-Cloud/Upgrades/index.md

I have added Deploy where it says Courier so it says Deploy / Courier please let me know if you want me to remove the Courier word completely

Updated the updates documentation

---

Reference/Config/umbracoSettings/index.md

To go with this PR for core: https://github.com/umbraco/Umbraco-CMS/pull/1939 - obviously please only pull in this one if and when the main one for the code updates is accepted.

Updated details on white and black lists for file uploads

---

Getting-Started/Setup/Upgrading/version-specific.md

Reverts umbraco/UmbracoDocs#452

Revert "Added line break, to fix formatting."

---

Umbraco-Cloud/Troubleshooting/Moving-From-Courier-To-Deploy/index.md

Fix typo on page "Moving from Courier to Deploy"

---

Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Nested-Content.md

Swapped the table to use a list

Nested Content docs update - Swapped table to list

---

Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Nested-Content.md

_Appears that MarkdownDeep doesn't support targeted language code blocks._

Nested Content - Amended the code blocks

---

Products/UmbracoForms/Developer/Extending/index.md

I spotted a couple of spelling mistakes whilst reading the docs so I thought i'd just correct them quickly.

Fixed minor spelling mistakes

---

Getting-Started/Setup/Upgrading/version-specific.md

revesed corrected to reversed.

Typo corrected

---

Reference/Management/Services/DataTypeService.md

Just want to add few lines to docs for PreValues, and just checking process of Pushing :-).

Added all methods for PreValues get

---

Umbraco-Cloud/Set-Up/index.md

I have add documentation for the limitation on hostnames per environments.

Added documentation for limitations on hostnames

---

Reference/Security/Setup-Umbraco-for-a-Fips-Server/index.md

Revised the FIPS documentation to remove the requirement of re-compiling Lucene.net and instead setting the flag at PreApplicationStart.  This is a much less intrusive method and allows Lucene.net to continue to be pulled in via Nuget.

U4-9792 - Revised the FIPS documentation for new PreAppStart method of setting Lucene.net

---

Reference/Packaging/package-actions.md

Added package actions documentation which has been provide by Sebastiaan.

Added package actions documentation

---

Add-ons/UmbracoCourier/Developer/DataResolvers.md
Add-ons/UmbracoCourier/Developer/PackagingAndExtraction.md
Products/UmbracoCourier/UsingCourier.md

Changes to grammer and missing words in documentation.

Grammar and Spelling

---

Reference/Querying/MemberShipHelper/index.md

update to index.md

---

Reference/Querying/MemberShipHelper/index.md

Link provided by Shannon and added to the documentation.

Adding link to the API documentation for this subject

---

Reference/Routing/custom-routes.md

Pretty much a copy & paste job from @shazwazza blog post on this.
This may need expanding out further with an example for the Virtual Content stuff, the Articulate stuff probably a bit too complex as an example its doing a lot as the route can be changed dynamically inside Umbraco.
Not sure if much or if any changes/improvements have been made since the post, so if you can give it the once over @Shazwazza to be sure that would be great.

Custom MVC Routing - Copy from Shans BlogPost

---

Reference/using-ioc.md

Here's my attempt at offering Unity advice :)

Updated with Unity example

---

Reference/Querying/UmbracoHelper/index.md

Added missing documentation of new TruncateByWords method

Added TruncateByWords

---

Add-ons/UmbracoForms/Developer/Extending/Adding-a-Type.md

This has not been shipped yet - when we release Forms 6.0.3 we can then merge this doc PR in please.

Adds docs about overriding providers a new feature in 6.0.3

---

Umbraco-Cloud/Troubleshooting/Moving-From-Courier-To-Deploy/index.md

Adding in the 
* /bin/Our.Umbraco.Courier.DataResolvers.dll
to be removed aswell.

Missing a file that needed to be deleted

---

Umbraco-Cloud/Set-Up/SMTP-settings/index.md

I've added documentation about SMTP service and Umbraco Cloud.

SMTP on Cloud

---

Umbraco-Cloud/Troubleshooting/Structure-Error/index.md

Deploy marker is in data folder and not in data/revisions :)

Updated Getting environments in sync

---

Umbraco-Cloud/index.md

I changed (a an easy) to (an easy).

Small grammar correction

---

Add-ons/UmbracoForms/Editor/Creating-a-Form/index.md

It's at the end of this sentence: "Similar to most create actions in the Umbraco backoffice, you'll have to click the ellipses on the forms tree/folder and that will show you the create option."

Added a full stop (dot) at the end of a sentence.

---

Add-ons/UmbracoForms/Installation/upgrade.md

Fixed grammar issue

---

Add-ons/UmbracoForms/index.md

yes i did - in the last sentence --> OSS company day

added space

---

Umbraco-Cloud/index.md

Added to the setup

---

Umbraco-Cloud/Getting-Started/Migrate-Existing-Site/part-3.md

After you run echo > deploy-export, you need to run additional echo> deploy in order to generate UDA files. :)

Updated "generate UDA files" section

---

Extending/Property-Editors/value-converters.md

the example of the interface code was incomplete

added missing return value

---

Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Multiple-Textbox.md

was searching for multiple textstrings... until i found out its name is repeatable textstrings...

actual name of the datatype is Repeatable textstrings

---

Umbraco-Cloud/Getting-Started/index.md

also adds space after the ## and # characters for headings

adds link to "log in to the Umbraco Cloud portal"

---

Umbraco-Cloud/index.md

also makes headers display in bold in github markdown

fixes typos

---

Add-ons/UmbracoForms/Developer/Email-Templates/index.md

replaces the three backtick with tabs the whole way down the file. I think that fixes the issue at #606 https://github.com/umbraco/UmbracoDocs/issues/606
Also fixes the heading in github markdown

Fixes issue #606 (Email templates page not displaying properly in our.umbraco) - I think

---

Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Textbox.md

The typed example on line 23 throws a Compilation Error unless it is wrapped in parentheses

Fixes broken example code on Textbox.md

---

Reference/Searching/Examine/overview-explanation.md

Remove the old broken link and add links to other working videos.

Add links to Examine videos

---

Getting-Started/Setup/Server-Setup/Load-Balancing/files-shared.md
Getting-Started/Setup/Server-Setup/Load-Balancing/flexible.md
Getting-Started/Setup/Server-Setup/azure-web-apps.md

http://issues.umbraco.org/issue/U4-10503
https://our.umbraco.org/forum/contributing-to-umbraco-cms/88804-should-umbraco-be-able-to-work-out-that-its-running-on-azure-and-apply-sensible-defaults#comment-280782

Add umbracoLocalTempStorage for umb7.7.3+

---

Reference/using-ioc.md

Fixes https://github.com/umbraco/UmbracoDocs/pull/508

Formatting fixes

---

Reference/using-ioc.md

Added a missing WebApi dependency resolver, mentioned the names of the NuGet packages these samples use & explicitly state what change needs to go into the Global.asax file.

Improve the AutoFac integration documentation

---

Getting-Started/Backoffice/index.md

Reuse is a single word, not a hyphenated compound.

Fix grammar (re-use)

---

Reference/Searching/Examine/overview-explanation.md

Changed the Lucene link and the link to Arron Powell's website

Fixing broken links

---

Umbraco-Cloud/Set-Up/Team-Members/index.md

Fix syntax + minor grammar fixes

---

Reference/Config/umbracoSettings/index.md

Added documentation about Securty => userNameIsEmail

Added documentation about Securty => userNameIsEmail

---

Add-ons/UmbracoForms/Developer/index.md

Teeny-weeny typos and Markdown-cleanups

Update Forms' Developer index page

---

Umbraco-Cloud/Set-Up/Working-With-UaaS-Cli/index.md

Just some small changes :)
Including:
- Show Linux some love (works just fine, by the way. I've tested it on Solus and Ubuntu)
- Saying that Git is required seems more correct than a "Git client"
Note to self: Editing files directly on Github is very confusing because of all the red and green hightligts.

My two cents on UaaS-Cli

---

Getting-Started/Code/index.md

https://our.umbraco.org/documentation/Getting-Started/Code/

Update Code overview to match the navigation

---

Reference/Security/Security-settings/index.md
Reference/Security/index.md

I have merged #643 into this PR and made some changes for review

Added some security documentation (revised)

---

Reference/Security/Security-settings/index.md
Reference/Security/index.md

Took some time to do a little write up about the security settings in Umbraco

Added some security documentation

---

Umbraco-Cloud/Getting-Started/Baselines/index.md

Update headings to match "old heading" - to avoid 404 requests.

Restructure baseline docs

---

Getting-Started/Setup/Install/index.md
Getting-Started/Setup/Install/install-umbraco-with-vs-code.md

* Adds direct link to VS Code IIS Express extension
* Adds in note that installing IIS Express is optional - as the VS Code extension will do it automatically now

Updates Install.index.md overview page for IISExpress

---

Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/index.md

A number of descriptions were missing for the built-in property editors

Missing property editors

---

Add-ons/UmbracoForms/Developer/Themes/index.md

Misc. typos, missing text, formatting.

Update Themes docs for Umbraco Forms

---

Getting-Started/Code/Umbraco-Services/index.md

I can´t find anything on this, so could not write further documentation.

Added ConsentService

---

Reference/Templating/Modelsbuilder/Understand-And-Extend.md

Nobody copies those samples anyway, right? :-)
Well, just in case they do...

Correct `DateTime.MinDate` to `DateTime.MinValue`

---

Umbraco-Cloud/Troubleshooting/Content-Deploy-Error/index.md

Updates Content-Deploy-Error

---

Getting-Started/Setup/Server-Setup/Load-Balancing/flexible.md

Fixed the link to the web.config section for umbracoLocalTempStorage

Fixed the link to the web.config section

---

Getting-Started/Setup/Install/install-umbraco-with-nuget.md

To resolve issue #674 using @nul800sebastiaan suggestion to remove it completely from this page.
Spotted the open #297 PR along a similar line, so up to yourselves on which is preferred. Removing it entirely is likely easier for maintainability?

Removed specific .NET framework version.

---

Reference/Templating/Mvc/forms.md

Example would return a syntax error because of missing ";"

Fixed syntax error

---

Getting-Started/Setup/Requirements/index.md

Added text to include VS in the local development section for getting started

Added visual studio and link to local development section

---

Reference/Security/Security-settings/index.md

I thought it did nothing, but I found out that it does something when you try to change a password from code

Added documentation for allowManuallyChangingPassword

---

Reference/Config/applications/index.md

Adding some basic documentation for the application.config file. Tried not to get into the details around creating an application/section but have concentrated on the purpose of this file and how changing it can impact Umbraco

#214 application.config Documentation

---

Extending/Property-Editors/value-converters.md

Mostly a lot of "a" that should be "an" :)

Tiny Updates to doc for Value Converters

---

Reference/Config/webconfig/index.md

This value is set on all our Umbraco Cloud projects. So worth documenting

Added umbracoDisableElectionForSingleServer docs

---

Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Date.md

Added some more details about the format setting of this DataType

Added more details about the Date property

---

Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Date-Time.md

Fixed typo and added some more details about the format setting of this DateTime datatype

Fixed typo + added some more details

---

Getting-Started/Code/Umbraco-Services/index.md
Reference/Management/Services/ConsentService.md

Fixing #698 
Maybe we should add examples before merging this in?

Added basic ConsentService info

---

Getting-Started/Setup/Install/install-umbraco-with-vs-code.md

It's no longer needed, as the folder isn't there. :)

Remove install folder text

---

Reference/Common-Pitfalls/index.md

@ not required when the code is already in C# mode

---

Add-ons/UmbracoForms/Editor/Defining-and-Attaching-Prevaluesources/index.md

reduce subheadline sizes to not be confused with headlines

reduce subheadline sizes

---

Reference/Config/umbracoSettings/index.md

This PR contains several things : 
- Formatting of code examples
- Marked a setting as obsolete in v7
- Added new settings

Umbraco settings update

---

Umbraco-Cloud/Deployment/Deployment-Webhook/index.md

Fixed the spelling of "successful" and changed the abbreviation JSON to capitals.

Fixed typos and abbreviation case.

---

Reference/Config/dashboard/index.md

Fixed broken examples link

---

index.md

I also re-phrased the description of the Umbraco Cloud section to make it more concise.

Change UaaS to Umbraco Cloud

---

Extending/Backoffice-Tours/index.md

I've fixed a few typos and tried to re-phrase some of the sentences.

Fixed various typos and re-phrasing.

---

Reference/Management/Models/Content.md
Reference/Management/Models/ContentType.md
Reference/Management/Models/DataTypeDefinition.md
Reference/Management/Models/Media.md
Reference/Management/Models/MediaType.md

on all the pages that have the typo

updated .level description

---

Getting-Started/Setup/Server-Setup/Load-Balancing/files-shared.md

Fixed broken link to ASPNET35_HostingDeploymentGuide

Fixed broken link to Hosting Deployment Guide

---

Reference/index.md

A couple of small changes, adding fullstops, capitals, things like that. Nothing major.

Update References page with a couple of small wording & punctuation fixes.

---

Reference/Templating/Mvc/child-actions.md

Fixed the broken stack overflow link

Fixed the broken stack overflow link

---

Reference/Querying/DynamicPublishedContent/index.md

Adding a link to Microsoft docs about intellisense as someone new might think it's an Umbraco feature.

Updating DynamicPublishedContent page

---

Reference/Security/Setup-Umbraco-for-a-Fips-Server/index.md

Don't think this link ever worked :o

Another broken link

---

Reference/Config/index.md

Removed UrlRewriting.config as the website no longer exists and the file has been removed from default install.
Added information about each file and also where they can be found within the folder structure.
New config files have also been added to the config folder which should be added at some point.

Updating config page.

---

Extending/Healthcheck/index.md

@Jeavon just spotted this one. Any reason why the old link goes via Google?

Fixed external link

---

Reference/Security/index.md

The Microsoft link that used to be there has apparently removed some information and now only talks about tech support scams

Changed phising link to wikipedia

---

Reference/Templating/Macros/Xslt/Snippets/Getting-a-series-of-unique-random-numbers.md

Replacement URL seems to refer to the same article ;)

Fixed broken link

---

Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Textbox.md

Damiaan Peeters told me in another PR I made that we're trying to get rid of Dynamic code examples so therefore I modified this file to only show the typed example.

Removing "CurrentPage" example of rendering

---

Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/True-False.md

Marked the dynamic example as being obsolete and added a text explaining that the dynamic approach is not the recommended one.

Mark Dynamic as obsolete

---

Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Textbox.md

Like we agreed on the other PR's I made :-)

Changed the text to reference the common pitfalls document

---

Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/CheckBox-List.md

The dynamic method has been marked as being obsolete and I have added a text explaining the approach is not recommended

Marking dynamic approach as obsolete

---

Reference/Common-Pitfalls/index.md

There were a couple of typos and some grammar issues that needed improving for readability :)

Updated index.md typos/grammar

---

Reference/Security/index.md

Spotted this one while reading the docs - very tiny typo

Really small typo in index.md

---

Extending/Section-Trees/trees-v7.md

Example from https://gist.github.com/perploug/7334403

Updated example from perploug gist

---

Tutorials/Creating-a-Property-Editor/part-4.md

typo correction

---

Extending/Property-Editors/index.md

*I know!* They said there were no more typos :-)

Fix a wee typo

---

Umbraco-Cloud/Upgrades/Moving-From-Courier-To-Deploy/index.md

Removed 'we' before web.config

Removed typo from instructions

---

Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/index.md

Apparently forgot to reference the .md file when submitting my PR for the textarea datatype. Do'h! :)

Link to the "Textarea" documentation

---

Umbraco-Cloud/Set-Up/Manage-Domains/index.md

Specifying hostnames in **Culture and Hostnames** is not a must. It is only required if you are using a multisite setup.

Update text regarding culture and hostnames

---

Umbraco-Cloud/Set-Up/Media/index.md

Exclude media from deployments

---

Getting-Started/Setup/Install/index.md

added extra information if you want to run windows on mac

Update Install docs

---

Umbraco-Cloud/Getting-Started/Migrate-Existing-Site/part-1.md

I freaked out when I read "Empty content ... and the media recycle bin"
I was wrong.  It is not the Content which needs to be removed, it is both recycle bins. I missed the last 's' in the sentence.
Just a suggestion to make clear what need to happen, please start the line with "empty the recycle bins... "

Empty the recycle bins versus empty content 

---

Umbraco-Cloud/Getting-Started/Migrate-Existing-Site/part-2.md

To move a complex visual studio project involves more knowledge.
This is only true if the uaas-cmd tools works flawless (see internal support ticket #36980).

Mention the Visual studio setup

---

Reference/Config/umbracoSettings/index.md

I had a use for this setting today and discovered that it was actually not documented - So here it is :)

Documenting the "showDeprecatedPropertyEditors" setting

---

Add-ons/UmbracoForms/Developer/Field-Types/index.md

Documenting the DatePickerYearRange setting :-)

Document the setting on the datePicker

---

Add-ons/UmbracoForms/Developer/Magic-Strings/index.md

Based on some own research and forum topics like https://our.umbraco.com/forum/umbraco-forms/79371-capture-current-page-name-on-submission

Update the docs with some example of magic strings

---

Umbraco-Cloud/Headless/Headless-Net-Client/Query.md
Umbraco-Cloud/Headless/Headless-Net-Client/console.md
Umbraco-Cloud/Headless/Headless-Net-Client/website-framework.md
Umbraco-Cloud/Headless/Headless-Net-Client/website-managed.md
Umbraco-Cloud/Headless/Headless-Net-Client/website-static.md

@hemraker @jmayntzhusen I tried to run through the Headless documentation and update to reflect the current state of the .net core client library. Do either of you two want to review these changes?

Documentation updated to reflect the changes made for Headless

---

Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/index.md

Added alias for all default propertyeditors in the list view.
Easier to overview all of them.

Added alias for all default propertyeditors

---

Umbraco-Cloud/Troubleshooting/Structure-Error/index.md

In some places, we said that you should run `echo> deploy` in `/data/revisions` folder which is not true.

Updating "Aditional Notes" and "Getting env in.."

---

Getting-Started/Code/Source-Control/index.md

changed genuinely to generally

word change.

---

Reference/Routing/IISRewriteRules/index.md

Spelling mistake

---

Reference/Packaging/index.md

Changed wording of sentence to make more sense.

Fixed grammatical errors

---

Development-Guidelines/breaking-changes.md
Development-Guidelines/building-angular-project.md
Development-Guidelines/project-structure.md
Development-Guidelines/test-driven-flow.md
Development-Guidelines/umbraco-web.ui-client.md
Development-Guidelines/working-with-code.md
Extending/Language-Files/index.md
Extending/Section-Trees/index.md
Extending/index.md
Getting-Started/Backoffice/index.md
Getting-Started/Data/Data-Types/default-data-types.md
Getting-Started/Setup/Install/install-umbraco-with-microsoft-webmatrix.md
Getting-Started/Setup/Server-Setup/Load-Balancing/index.md
Getting-Started/Setup/Server-Setup/Load-Balancing/traditional.md
Getting-Started/Setup/Upgrading/upgrading-to-v7.md
Implementation/Controllers/index.md
Reference/Common-Pitfalls/index.md
Reference/Config/umbracoSettings/index.md
Reference/Querying/IPublishedContent/Properties.md
Reference/Routing/Authorized/index.md
Reference/Routing/WebApi/authorization.md
Reference/Routing/WebApi/index.md
Reference/Routing/index.md
Reference/Routing/surface-controllers.md
Reference/Searching/Examine/overview-explanation.md
Reference/Security/index.md
Reference/Templating/Macros/Partial-View-Macros/index.md
Reference/Templating/index.md
Tutorials/Creating-a-Custom-Dashboard/index.md
Umbraco-Cloud/Set-Up/Team-Members/index.md

- decided to go with the naming format already used in the navigation menu 'backoffice'

- consistent naming for backoffice.

---

Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/index.md

Fixed more stuff introduced in #976

---

Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/index.md

Fixed more stuff introduced in  #1000 and #976

---

Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/index.md

Added `Umbraco.Decimal` to the list of core property editors.

Add docs for Umbraco.Decimal

---

Reference/Events/EditorModel-Events.md

In v7.7.10 this event got added to the EditorModelEventManager class

Added sending user model description

---

Umbraco-Cloud/Frequently-Asked-Questions/index.md

The original text mentioned that you could use Lets Encrypt, but you would need to manually update it yourself, as this is now what Umbraco Latch does, it seems sensible to update the FAQ :)
Issue: #1006

issue: #1006 - Added information about Umbraco Latch to the Cloud FAQ

---

Tutorials/Add-Google-Authentication/index.md

1. Fixed the broken image link in Add Google Authentication index.md
2. Also added links to Visual Studio, Google and Umbraco to enhance the documentation

Fixed broken link in Add Google Authentication doc

---

Umbraco-Cloud/Set-Up/Config-Transforms/index.md

Rewrite section about config transforms for package developers

---

Umbraco-Cloud/Troubleshooting/Deployments/Path-too-long-exception/index.md

Added steps on how to fix the "path too long" issue.

Updating Path too long docs

---

Tutorials/Multilanguage-Setup/index.md

Added a few tweaks make it more readable.

Grammatical fixes

---

Getting-Started/Backoffice/Sections/index.md

Adding an intro, the Section diagram and some more text to make things a bit clearer, hopefully.

Sections page update

---

Getting-Started/Backoffice/Sections/index.md

I have tweaked the sections page to mention user groups, member types and member groups

Tweaked the sections to mention user types, member types and member groups

---

Add-ons/UmbracoForms/Developer/Configuration/index.md

This lists all the currently known configuration keys in the latest version of forms along with a brief explanation of what each key does.
The wording or grammar may need tidying up, as this is not my strong point :-P
Hope this helps you out @sofietoft & @jmayntzhusen

Adds in all the config keys for Forms

---

Contribute/index.md

A number of changes, happy to discuss them all :) 
Just trying to fill in some blanks for people who might not know how to setup Git etc.

Updates to the contribute page

---

Reference/Routing/WebApi/index.md

Just making a couple of links more accessible.
Changing 'here' to more descriptive wording

Update to Web API page

---

Reference/Routing/custom-routes.md

This is supported since v7.3. So it should be clear from documentatoin

Added version number since when custom routing is supported

---

Reference/Cache/IServerMessenger.md
Reference/Cache/applicationcache.md
Reference/Cache/cache-refresher-t.md
Reference/Cache/cache-refresher.md
Reference/Cache/index.md
Reference/Cache/updating-cache.md

Can be merged now.
Being discussed in #208

Cache updates

---

Reference/Templating/Macros/Xslt/45-XML-Schema.md

Removed dead link to old wiki

---

Tutorials/Starter-kit/Index.md

Just some wording changes and trying to make the final paragraph read a bit better. Not sure I've succeeded in doing that. Open to suggestions.

Update to the Starter Kit page

---

Umbraco-Cloud/Upgrades/index.md

Reverts umbraco/UmbracoDocs#1066

Revert "Add clarification on opting our of upgrades"

---

Getting-Started/Code/Umbraco-Services/index.md
Getting-Started/index.md

- Removed a few .'s on Getting Started for consistency.
- Tweaking wording and grammar (too many "dashes") on Umbraco Services page as well as updated a link.

Misc grammar and punctuation

---

Add-ons/UmbracoCourier/CommonIssues.md
Add-ons/UmbracoCourier/DataIntegrity.md
Add-ons/UmbracoCourier/UsingCourier.md
Add-ons/UmbracoCourier/index.md
Add-ons/index.md
Contribute/index.md
Tutorials/Add-Google-Authentication/index.md

Some typos and grammatical errors.
Contributed as a part of Hacktoberfest 2018

Fix some Typos and Grammatical Errors

---

Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Tags-vpost-7.4.md
Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Tags.md
Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/tags-vpre-7.12.md

This PR has the changes requested in the comments of #1053
I needed to created a new PR as the last one was done using the browser. This one has an extra file for docs pre 7.12

Tags storage type

---

Development-Guidelines/Coding-Standards/jquery-guidelines.md
Development-Guidelines/Coding-Standards/js-guidelines.md
Development-Guidelines/building-angular-project.md
Development-Guidelines/working-with-code.md
Extending/Backoffice-Tours/index.md
Extending/Embedded-Media-Provider/index.md
Extending/Healthcheck/index.md
Extending/Language-Files/Language-Files-For-Packages/index.md
Extending/Section-Trees/index.md
Extending/Section-Trees/sections.md
Extending/Section-Trees/trees-v7.md
Getting-Started/Backoffice/Sections/index.md
Getting-Started/Backoffice/index.md
Tutorials/Creating-Basic-Site/Articles-Parent-and-Article-Items.md
Tutorials/Creating-Basic-Site/Conclusions-Where-Next.md
Tutorials/Creating-Basic-Site/Creating-Master-Template-Part-1.md
Tutorials/Creating-Basic-Site/Creating-Master-Template-Part-2.md
Tutorials/Creating-Basic-Site/Creating-Your-First-Template-and-Content-Node.md
Tutorials/Creating-Basic-Site/Document-Types.md
Tutorials/Creating-Basic-Site/Outputting-the-Document-Type-Properties.md
Tutorials/Creating-Basic-Site/index.md
Tutorials/Creating-a-Custom-Dashboard/index.md
Tutorials/Creating-a-Property-Editor/index.md
Tutorials/Creating-a-Property-Editor/part-2.md
Tutorials/Creating-a-Property-Editor/part-3.md
Tutorials/Creating-a-Property-Editor/part-4.md
Tutorials/Multilanguage-Setup/index.md
Tutorials/Starter-kit/Index.md
Tutorials/index.md

In the spirit of Hacktoberfest, I went through a good portion of your Docs and updated little grammar and spelling mistakes I found. 
Enjoy! :+1:

Small grammar updates

---

Add-ons/UmbracoForms/Developer/Configuration/index.md

fixed typos in index.md

---

Extending/Health-Check/index.md

Quick update for the folder name so that the section appears as "Health Check" in navigation, to match the name used in Umbraco. Also added a missing code snippet around an attribute name and updated the section name as well for consistency.

Updated health check folder name and word usage

---

Add-ons/UmbracoCourier/CommonIssues.md

Updated Courier version no & valid nightly build download link

---

Contribute/Pull-Requests/index.md

Images paths were not updated and were pointing to the folder one level higher than they should do

Fixed images paths

---

Add-ons/UmbracoForms/Installation/license.md
Getting-Started/Setup/Upgrading/general.md

PR for issue #764 - a simple find and replace for Contour.

Replaces "Contour" with "Umbraco Forms"

---

Reference/Events/ContentService-Events.md

Remove hash from heading on this page: https://our.umbraco.com/documentation/Reference/Events/ContentService-Events

Remove hash from heading

---

Reference/Routing/Request-Pipeline/IContentFinder.md

We can here access `UmbracoContext` from contentRequest instead of using the singleton `UmbracoContext.Current`.
I think it should be the preferred one in this case, but you might check with Shannon :)

Access UmbracoContext from PublishedContentRequest

---

Extending/Content-Apps/index-v8.md

Adds an example of how to do a Content App as a C#

Adds the V8 Cake Content App as a C# example

---

Getting-Started/Data/Creating-Media/index.md

The image is below the text, but the text says "....give them the aliases seen above".  I have updated this to "below".

Correcting location of image.

---

Extending/Content-Apps/index-v8.md

I started off just making a typo fix, but I have also added spaces before code comments, reworded a few little bits to ( hopefully ) improve the understand for someone new and finally I renamed the test app filenames, removing the "My" and adding the word "Cake" so that the file names reflect the name of the demo apps.

A few suggested changes

---

Extending/Content-Apps/index-v8.md

Current info was a little bit confusing for me, I didn't know whether should I add "show" directive under 'contentApps' item or on the same level as Content Apps definition.

Added more specific info about placing 'show' directive

---

Contribute/index.md

One word needed moving and while I was in there, I made some of the grammar more consistent so that numbered bullet points all begin with capitals rather than a mix across the page and also so that bullets where some ended with a full stop and some didn't now all end with full stops. :)

Small changes to word order and grammar

---

Reference/Config/umbracoSettings/index.md

showDeprecatedPropertyEditors belongs to the Content section

moved showDeprecatedPropertyEditors

---

Umbraco-Cloud/Headless/index.md

Improve grammar

---

Reference/Templating/Masterpages/index.md

I removed unnecessary commas to improve overall readability and clarity. Also fixed a handful of other grammatical errors.

Remove unnecessary commas

---

Add-ons/UmbracoForms/Developer/Magic-Strings/index.md
Add-ons/UmbracoForms/Developer/Working-With-Data/index.md

Updated articles about Magic strings, and how to work with record data.

Umbraco Forms Documentation update

---

Add-ons/UmbracoCourier/UsingCourier.md

Fixed minor grammatical errors to improve readability

Fixed grammar

---

Implementation/Default-Routing/Execute-Request/index.md

Update index.md - grammar fixes

---

Contribute/Markdown-Conventions/index.md

Fixes #1168 
- update the guideline to include internal links for current folder and other relative paths

update internal link guideline

---

Reference/Management/Models/Content.md

Added meta data in order to fix:

Added meta data to Content.md

---

Development-Guidelines/umbraco-web.ui-client.md

Please review @marcemarc @jmayntzhusen

umbraco-web.ui-client.md: Add missing backtick

---

Reference/Security/Security-settings/index.md

Correction in Security-settings/index.md

Fixes in Security Settings Documentation

---

Getting-Started/Design/Rendering-Media/index.md

Corrections in Rendering-Media/index.md

Fixed typo in Rendering Media Documentation

---

Tutorials/Creating-a-Custom-Dashboard/index.md

Some small grammatical changes and small typo fixes

Updates to 'Creating a Custom Dashboard' page

---

Tutorials/Multilanguage-Setup/index.md

Some grammatical updates / typo fixes and spacing issue on sentence below an image

Updates to 'Multilanguage Sites' tutorial

---

Tutorials/Starter-kit/Index.md

Update to the 'The Starter Kit' page

---

Umbraco-Cloud/Set-Up/Media/index.md

Using the latest version of the packages and their config files.

Update the Umbraco-Cloud/Set-Up/Media page

---

Getting-Started/Code/Debugging/Logging/index-v8.md

This PR contains detailed documentation about using Serilog in V8.
Currently this is a WIP/draft & will update this message or ask for feedback/review once I am done :)

V8 - Logging/Serilog specifics

---

Reference/Management/Models/RelationType.md
Reference/Management/Models/index.md

Added the model definitions of the RelationType model. Most of the text taken from the Summary comments in the code :)

Relation Type model definition

---

Reference/Config/umbracoSettings/index-vpost7.5.0.md
Reference/Config/umbracoSettings/index-vpost7.6.0.md
Reference/Config/umbracoSettings/index-vpost7.6.2.md
Reference/Config/umbracoSettings/index-vpost7.8.0.md
Reference/Config/umbracoSettings/index-vpre6.0.0.md
Reference/Config/umbracoSettings/index-vpre7.0.0.md
Reference/Config/umbracoSettings/index-vpre7.2.7.md
Reference/Config/umbracoSettings/index.md

Introduced some version information in different files + code cleanup of the index file

UmbracoSettings version cleanup

---

Umbraco-Cloud/Headless/Headless-Node-Client/index.md

I used this file for some testing, so might as well submit my changes 😉

Added languages to the fenced code blocks

---

Tutorials/Creating-a-Custom-Dashboard/index.md

removed extra word and added paragraph about client dependency and running without debugging

removed extra word and added paragraph

---

Umbraco-Cloud/Troubleshooting/Log-files/Enable-Logging.md

Temp article, on how to enable logging on Cloud

How to enable logging on Cloud

---

Getting-Started/Setup/Server-Setup/Load-Balancing/flexible-advanced.md
Implementation/Controllers/index.md
Implementation/Custom-Routing/index.md
Reference/Templating/Macros/index.md
Reference/Templating/Macros/managing-macros.md
Reference/Templating/Mvc/child-actions.md
Reference/Templating/Mvc/examples.md
Reference/Templating/Mvc/partial-views.md
Reference/Templating/Mvc/views.md

DO NOT MERGE THIS...  jeavon's commit is added to this :-o

Few small syntax highlighting fixes

---

Reference/Management/Services/DataTypeService/Index.md

Like some of my previous PRs, I've removed the method list, and improved the description a bit.
Now time for 🎅

Updated the documentation for the data type service a bit

---

Add-ons/UmbracoForms/Developer/Extending/Adding-a-Workflowtype.md

Update example with working one

---

Extending/Content-Apps/index-v8.md

As promised in https://github.com/umbraco/Umbraco-CMS/pull/3426 I have added a bit of documentation for the Content App badges

Documentation for Content App badges

---

Umbraco-Cloud/Databases/index.md

Update Databases docs

---

Reference/Config/webconfig/index.md

I noticed the XML snippet where still using the old code markup instead of the new and shiny XML formatting so I updated the code examples to make use of it 😃

Use the XML tag for XML snippets

---

Reference/Config/404handlers/index.md

Updated the code example to make use of the XML tag / Snippet 😃

Format the code snippet using the XML tag

---

Reference/Config/dashboard/index.md

Apart from formatting the XML code snippets I also fixed "area" and wrapped it in <> so it reads <area> - It was already marked as code but was not properly formatted.

XML formatting code and fixing minor glitch

---

Reference/Templating/Modelsbuilder/index.md

I considered using a tip instead but I think this is more like a note about the models builder project being an open source project on it's own more than a tip about something that can improve your code or what not.

Markup higlighted text as a note

---

Reference/Templating/Mvc/partial-views.md

The code examples have been aligned to make them easier to read

Aligning code examples

---

Reference/Templating/Mvc/examples.md

All code examples have now been marked as C#

Align other code examples with the last

---

Add-ons/The-Licensing-model/index.md

Updated Forms pricing

---

Reference/Querying/DynamicPublishedContent/Collections.md

Somewhere there was a "Notice", which I think was more appropriate to convert to a warning and there was a "Hint", which seems like a good fit for using a tip instead 😃

Markup code examples using C# syntax and add a tip and a warning

---

Reference/Searching/Examine/quick-start.md

Marked up code examples using C# and XML syntaxes and also converted notes to use the note syntax.

Code and notes markup

---

Umbraco-Cloud/Headless/Headless-Net-Client/website-static.md

For some reason the syntax highlightning appears a bit broken on this page - I think I have managed to sort it out now 😃

Fix syntax highligtning

---

Umbraco-Cloud/Headless/Headless-Net-Client/console/index.md

The code examples appears to be broken for some reason - I think I have managed to fix them 😃

Fix code examples

---

Umbraco-Cloud/Headless/Headless-Net-Client/website-framework.md

They appear broken for some reason but should be fixed now 😃

Fix broken code samples

---

Umbraco-Cloud/Databases/index.md

The first code example was not readable - Added the XML syntax prefix so it should work now 😃

Fix first code example

---

Tutorials/Creating-Basic-Site/CSS-And-Javascript.md

Currently the script code block just appears as a black box - This should make the content visible again 😃

Fix broken js code highlight

---

Getting-Started/Setup/Upgrading/version-specific.md

Based on the preview I can't figure out if the code examples that are a part of an indented list are actually going to be parsed and rendered correctly? Or it this something that needs to be fixed somewhere? - Anyway I have tried to markup the code examples using the appropiate syntax 😃

Attempt to update the code examples using the appropiate syntax

---

Getting-Started/Backoffice/Infinite-editing/index.md
Getting-Started/New-in-V8.md
Getting-Started/index-v8.md

First draft of V8 version of the Getting Started index page.
Added links to all current V8 Documentation.

V8 docs - Getting Started section

---

Reference/Config/webconfig/index.md

Adding some examples for appsettings that had none.

appsetting examples

---

Getting-Started/LogViewer/index-v8.md

First draft for the docs team to clean up - Adds in details about V8 LogViewer

V8 - LogViewer First Draft Doc

---

Getting-Started/Setup/Server-Setup/permissions.md

Update the permissions page

---

Tutorials/Creating-a-Custom-Dashboard/index.md

revert back to checking for 'Media or Content' in the comment to distinguish between the entity types

Fix tutorial for 7.13

---

Getting-Started/Setup/Upgrading/version-specific.md

Replaced the old link in version-specific.md file

Fixes #1548 Fixed the link in version specific upgrades 

---

Extending/Dashboards/index-v8.md

Have just read through the dashboard stuff for V8, all good stuff! - have made some tweaks to language and explanation, to hopefully make it clearer-erer

Reading through the V8 dashboard info

---

Umbraco-Cloud/Getting-Started/Migrate-Existing-Site/index.md

Documentation should state: " latest minor version of v.X"

Specify migration upgrade path

---

Add-ons/UmbracoForms/index.md

Adding a link to the Umbraco Apps page for Forms

Update to Forms page

---

Umbraco-Cloud/Getting-Started/index.md

Adding a link to the products page of Umbraco.com.

Update to Cloud page

---

Extending/Content-Apps/index-v8.md

It was a bit confusing to see two content app examples.

Updated the c# part of the tutorial to match the demoed word counter app

---

Tutorials/Porting-Packages-V8/index.md

As it appears to have done in last day or two!

Reflect v8 dev branch changing from 'temp8' to 'dev-v8'

---

Implementation/Composing/index-v8.md

Currently, this is a draft/WIP document for V8 Composers/Components & Collections

V8 composing

---

Getting-Started/Setup/Upgrading/general.md
Getting-Started/Setup/Upgrading/version-specific.md

... and updating note in general upgrading

Adding 7 to 8 notes to version specific docs

---

Umbraco-Cloud/Troubleshooting/Deployments/Path-too-long-exception/index.md

Fixing broken link

---

Reference/Events/ContentService-Events.md

Issue #1405 
Added in EmptyingRecycleBin, EmptiedRecycleBin, SavedBlueprint and DeletedBlueprint.
Worth double checking the RecycleBinEventArgs as I'm not 100% sure I've done that right!

Add RecycleBin and Blueprint events

---

Reference/Routing/Request-Pipeline/IContentFinder-v7.md
Reference/Routing/Request-Pipeline/IContentFinder.md

Needs a double check of the example (to make sure it works)

Updating Content Finder information for V8

---

Reference/Routing/custom-controllers-v7.md
Reference/Routing/custom-controllers.md

Need to double check the examples are correct

Updating Route Hijacking Custom Controller information

---

Umbraco-Cloud/Deployment/Deployment-Webhook/index.md
Umbraco-Cloud/Set-Up/Manage-Hostnames/Security-Certificates/index.md
Umbraco-Cloud/Set-Up/Manage-Hostnames/index.md
Umbraco-Cloud/Set-Up/Project-settings/index.md

The settings menu on a project has gotten a tiny update in the last release of the Cloud portal - this updates the references we have to it (but not in the videos though :-o )

Update items related to the updated Settings menu on Umbraco Cloud

---

Reference/Config/umbracoSettings/index.md

Adding docs on using GUIDs and XPaths, which are both better ways if using multiple environments on Umbraco Cloud.

Update errorpage info in umbracoSettings.config

---

Reference/Routing/custom-routes-v7.md
Reference/Routing/custom-routes.md

Update RenderModel to be ContentModel and register the custom route via a composer/component

Update Custom MVC Routes example to work with V8

---

Getting-Started/Code/Debugging/Logging/index.md

One for the docs team @sofietoft to add a link/mention to the Windows Store app I published/created to view those JSON log files in the same way as the backoffice logviewer

Adds link/mention to my Compact Log Viewer tool

---

Reference/Routing/Authorized/index-v7.md
Reference/Routing/Authorized/index.md

In addition to mapping the route you also have to register the controller with the LightInject DI container

V8-Update mapping an UmbracoAuthorizedController MVC backoffice route

---

Getting-Started/Setup/Upgrading/version-specific.md

I miss read the previous version. I thought the And was Add and then wondered why I was getting errors. 
I've also formatted the code snippets so it's all formatted the same.

Update to 7.6 specific instructions

---

Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Nested-Content/index.md

Just adding some additional documentation on how to extract addtional properties as show in the screenshots.
https://our.umbraco.com/documentation/getting-started/backoffice/Property-Editors/Built-in-Property-Editors/Nested-Content/

Extract additional properties

---

Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Nested-Content/index.md

... to previous PR https://github.com/umbraco/UmbracoDocs/pull/1645
We are already inside the code block 😁

Tiny update

---

Getting-Started/Setup/Install/install-umbraco-with-nuget-v7.md
Getting-Started/Setup/Install/install-umbraco-with-nuget.md

Update install guide for v8

---

Add-ons/UmbracoForms/Installation/Version-Specific.md

Making the install/upgrade process a bit clearer for others to follow.

Update to Umbraco Forms upgrade page

---

Implementation/Composing/index.md

Umbraco.Core.Components to Umbraco.Core.Composing

Update outdated namespace: Umbraco.Core.Components

---

Extending/Health-Check/index.md
Extending/Language-Files/Language-Files-For-Packages/index.md
Extending/version7-assets.md
Reference/Cache/cache-refresher-t.md
Reference/Cache/index.md
Reference/Config/BaseRestExtensions/index.md
Tutorials/Porting-Packages-V8/index.md
Tutorials/Starter-kit/Index.md

Stumbled upon of these, and thought I might as well fix the rest 😄

Fixed references to old branch names

---

Reference/Routing/IISRewriteRules/index.md

A very small change but it just gets rid of someone wondering what a YSOD is.

Update Url Rewrite page

---

Implementation/Composing/index.md

Adds in a code example for using collections.
Worth sanity checking @zpqrtbnk please
Also technical docs reviewer @marcemarc can you ensure my code sample reads fine, grammar & the example makes sense, gets the point across on what can be done & feel free to tweak/change if you feel it can be improved :)
Happy Easter all :)

Adds in example of using collections

---

README.md

Indefinite pronouns that end in -one are always singular

readme.md grammar mistake

---

Umbraco-Cloud/Troubleshooting/Log-files/index.md

I added a bit more about where to find it. I had a client that thinks it was in Kudu. 
Also added the part to make people aware that the environment will restart

Updated the docs about IIS logging on UC

---

Getting-Started/Setup/Server-Setup/Load-Balancing/flexible-advanced-v7.md
Getting-Started/Setup/Server-Setup/Load-Balancing/flexible-advanced-vpre-8.0.2.md
Getting-Started/Setup/Server-Setup/Load-Balancing/flexible-advanced.md

Some of this is dependent on either v8.0.2 or v8.1.0 - tbc, don't merge until confirmed

Added v8 info for advanced load balancing options

---

Development-Guidelines/breaking-changes.md

(This is for review of a D-team member as part of our current sprint)

Some updates for the breaking changes docs

---

Tutorials/Creating-Basic-Site/Document-Types/index.md

- Use **_Bold Italic_** for specific terms (could be linked later to a lexicon)
- Use [Exact Text] to indicate UI items
- Use "_Input value_"
- Shortened some sentences
- Reworked awkward wording
- Added a comment to indicate a content improvement
I looked at the markdown specifications but couldn't find any style guide for terms/ui/input so I tried to use what was already present. 
If accepted I will continue this style of work on the rest of the tutorial.

More consisting markup + readability improvements

---

Implementation/Unit-Testing/index.md

From discussion on https://github.com/umbraco/UmbracoDocs/issues/1627 and on forum thread https://our.umbraco.com/forum/umbraco-8/96366-unit-testing-v8.
Would be nice to have a section in the docs with som basic examples of how to get started with unit testing in Umbraco v8. This is just a start, hopefully others can join in and extend it further. I had to stop somewhere, because I kept coming up with new tests everytime I finished one, so this is just to get stuff going.
Will be great to hear your feedback!

init commit for unit testing docs

---

Getting-Started/Code/Debugging/Logging/index.md

Updates the logging page with more visible links to Windows & MacOS App Stores for desktop log viewer tool

Update with Compact Log Viewer Windows & OSX links

---

Umbraco-Cloud/Set-Up/Umbraco-Latch/index.md

We have updated the link to Upload certificates manually

Updated with the correct URL

---

Umbraco-Cloud/Upgrades/index.md

Jim and Jacob have decided that we should not have the do not upgrade list anymore. So there will not be new on this list. 
Jim and I will work with the list over the next couple of weeks.

The do not upgrade list does not exsist anymore

---

Umbraco-Cloud/index.md

Update wording on Cloud index page

---

Extending/Content-Apps/index.md

Use angular directives for umb-box

---

Reference/Management/Services/UserService/Create-a-new-user-vpre7.7.md
Tutorials/Creating-a-Property-Editor/part-2.md

fixes some of #1735

---

Getting-Started/Setup/Upgrading/v81-ipublishedcontent-changes.md
Getting-Started/Setup/Upgrading/version-specific.md

Updates to the 8.1 version specific upgrade notes to be clear about what changes to MB are necessary and link to a new document about the IPublishedContent changes

Changes to 8.1 upgrade notes

---

Umbraco-Cloud/Set-Up/Umbraco-Latch/index.md

Added information about the various states Umbraco Latch can be in.

Latch update

---

Getting-Started/Setup/Upgrading/migrating-to-v8.md

The sentence was missing a word - are

Grammatic fix

---

Implementation/Unit-Testing/index.md

* Added test examples for how to test UmbracoApiController.
* Added test examples for how to test IPublishedContentQuery. (UmbracoHelper.Content(x))

Temp 1627 additional test examples

---

Reference/Scheduling/index.md

This includes a working example of regularly emptying out the recycle bin

Background Task Runner example

---

Extending/Database/index.md

Updated the example to use a schema object and also added notes around the importance of ensuring immutability

Updated `Creating a custom Database table` with a safer example

---

Umbraco8FAQ.md

Change of wording to make deadlines more clear

---

Umbraco8FAQ.md

More updates to make communication more clear

---

Reference/Mapping/index.md

Right now the C# code snippets is broken on Our, I've changed the language from `cs` to `csharp` which should fix it

Update code snippets language

---

Umbraco-Cloud/Set-Up/Manage-Hostnames/Rewrites-on-Cloud/index.md

Corrected rewrite rule for well-known/acme-challenge, the previous one led to errors on Umbraco LATCH

Update Rewrite rules on Umbraco Cloud

---

Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/RadioButton-List/index.md

Removed second bracket ")" under **Without ModelsBuilder**

Fix syntax bug in code example

---

Add-ons/UmbracoForms/Developer/Magic-Strings/index.md

I've added the extra record variables that are replaced and a warning regarding the issue with Form field replacements: https://github.com/umbraco/Umbraco.Forms.Issues/issues/120. This also contains some formatting/styling changes.

Added extra record variables and Form field warning

---

Extending/Database/index.md

A small change. But insert a new headline let's us deep link to this particular section of the page 😄

Added extra headline

---

index.md

removed v7

---

Add-ons/UmbracoForms/Developer/Working-With-Data/index-v7.md
Add-ons/UmbracoForms/Developer/Working-With-Data/index.md
Add-ons/UmbracoForms/Developer/index-v7.md
Add-ons/UmbracoForms/Developer/index.md

Updated documentation for https://github.com/umbraco/Umbraco.Forms.Issues/issues/178
fixes #1765

Updated documentation for forms V8 - Working with Record data

---

Reference/Management/Services/RelationService/Index.md

This triggered me a bit.
I can see that the article needs to be updated/verified for V8. I'll do that one of the following days.

Update formatting in ReleationService

---

Extending/Backoffice-Tours/index.md

I've tested this article in v8, and there are no changes that need to be made.
I removed the "needsV8Update" flag.

Verifying Backoffice Tours for v8

---

Getting-Started/Data/Defining-content/index.md

Added an explanation of how defining fields in doctypes is related to what editors can do on a page.

End users perspective on doctypes

---

Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Grid-Layout/Render-Grid-In-Template-v7.md

this will allow me to modify the current page to v8 doc

Copy of current doc file v7

---

Getting-Started/Setup/Install/index.md

Adding final step in set up - following the installer.

Adding final step in set up

---

Contribute/index.md

Some grammatical fixes and some (missing?) links on `Contribute/index.md`

Propose grammatical fixes and links on Contribute/index.md

---

Reference/Routing/WebApi/authorization.md
Reference/Routing/WebApi/index-v7.md
Reference/Routing/WebApi/index.md
Reference/Routing/WebApi/routing.md

Reviewing and updating WebAPI docs for v8 as per issue #1876

Issue 1876 webapi

---

Implementation/Composing/index.md

Also uses "C#" over "c#" for consistency.

Several punctuation fixes.

---

Getting-Started/Setup/Server-Setup/permissions-v7.md
Getting-Started/Setup/Upgrading/general-v7.md
Reference/Config/webconfig/index.md

v8 modifications to some config and adding v7 version when needed.
Adding content to the general-v7.md that was accidentally missing from PR #1918 earlier today!
Thanks,
Carole :)

v8 modifications and v7 versions

---

Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Multiple-Textbox-v7.md

that will allow me to create an updated v8 version

v7 file created

---

Tutorials/Porting-Packages-V8/index.md

Changing some wording and making it a bit easier to understand. 
Made a change as it still mentioned the V8 was under development.
Also removed the final paragraph as everyone should be willing to update pages without the need to ask people to do it.

Update to Porting Packages page

---

Development-Guidelines/building-angular-project.md

Updating as per issue #1940 and discussion with @sofietoft

Linking to the contribution guidelines

---

Reference/Security/Security-hardening/index.md

Also exchanges the images with code snippets.
Makes it easier to maintain.

Update for Umbraco 8

---

Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Related-Links2.md
Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/index-v7.md
Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/index.md

Remove needsV8update label from article and updated some stuff on index pages

Update RelatedLinks article

---

Getting-Started/Data/Data-Types/index.md

Removed Episode related to V7.

Umbraco.tv Episode update

---

Getting-Started/Data/Data-Types/index-v7.md

Removed link to an episode that does not exist on TV.

Umbraco.tv Episode links update

---

Reference/Routing/Request-Pipeline/outbound-pipeline-vpre.8.1.md

Some code was appearing as text. I have moved it inside a code block

Move code inside code block

---

index.md

Hi @sofietoft ,
As per comment on #1979 , adding a second link to contributing guidelines.
Thanks,
C

updating links

---

Tutorials/Creating-Basic-Site/Conclusions-Where-Next/index-v7.md
Tutorials/Creating-Basic-Site/index-v7.md

Creating a new page for v7 and updating index for v8

Updating v8 link for tv

---

Getting-Started/Data/Data-Types/index.md

Making all Data Type references be the same case and small update to the intro text to hopefully make it read a bit better.

V8 - Update Data Types page

---

Implementation/Composing/index.md

This fixes the main part of issue https://github.com/umbraco/UmbracoDocs/issues/1974.

Mark SubscribeToContentServiceSavingComposer with IUserComposer

---

Tutorials/Creating-Basic-Site/index.md
Tutorials/Creating-a-Property-Editor/part-2.md

fixed some typos

---

Extending/Section-Trees/sections.md

Add some extra information about the new ability to add lang folders further down the app_plugin tree which was added in this PR #6153

Added extra info about the new ability to add lang folders further down the tree

---

Umbraco-Cloud/Set-Up/Config-Transforms/index.md

Since the rewrite structure is commented out in web.config you need to add xdt:Transform="InsertIfMissing" to rewrite.
Otherwise you will get and error in the deployment.

Adding xdt:Transform="InsertIfMissing" to rewrite

---

Tutorials/Creating-Basic-Site/Document-Types/index.md

Fixed the markup of a couple of terms and UI items I missed the last time.

Fixed missed markup

---

README.md

Removed the unnecessary ("available here") text as it was obvious because it was a hyperlink.

Removed unnecessary text

---

CONTRIBUTING.md
Umbraco-Cloud/Deployment/Hotfixes/Move-files-manually/index.md
Umbraco-Cloud/Deployment/Hotfixes/Using-Git/index.md

I stumbled upon these while reading some docs, so figured I'd send them right away...
_PS: I don't know what the policy around changing the CONTRIBUTING.md file is - but they're included in a separate commit so just cherry-picking the first one is a possibility._

Teeny tiny typos

---

Reference/Searching/Examine/Indexing/index.md

Just a small change to make it a bit easier to read.

V8 Custom Indexer

---

Reference/Querying/DynamicPublishedContent/index.md

Helping out with the issue #1875 
DynamicPublishedContent is not supported in v8, so removed the tag

Removed needsv8Update DynamicPublishedContent

---

Reference/Querying/DynamicPublishedContent/Properties.md

Helping out with the issue #1875 
v8 does not support DynamicPublishedContent, hence removing

Removed needsv8Update DynamicPublishedContent-Properties

---

README.md

Hello lovely docs people. While looking for a big and impressive addition I could make to the docs repo, I found two stray commas and had to take them out. Then a few other bits and bobs. Not the most exciting change but as you say, every little counts.

Grammar changes in the readme

---

Extending/Database/index.md

Some small changes and adding the meaning of DTO to the docs.

Update to wording in Extending - Database section

---

Reference/Templating/index-v7.md
Reference/Templating/index.md

This isn't showing the warning about check for V8 - but says that masterpages is still possible in V8 - which isn't so.

Update Templating landing page for V8

---

Contribute/Style-Guide/index.md

Not much, I know - but GitHub makes it sooo easy to submit a fix right when you see a typo :)

Fix two typos

---

Reference/Using-Ioc/index-v7.md

https://unitycontainer.github.io/api/Unity.IUnityContainer.html#Unity_IUnityContainer_RegisterFactory_System_Type_System_String_System_Func_Unity_IUnityContainer_System_Type_System_String_System_Object__Unity_Lifetime_IFactoryLifetimeManager_

Update UmbracoContext registration to use new RegisterFactory syntax

---

Reference/Management/Services/MediaService/Index.md

Ideally there should be examples for all the CRUD operations, but here are at least some more for creating media items.

Added two additional examples for the Media Service

---

Extending/Content-Apps/index.md

Making wording the same as other changes I've made e.g. instead of v8, it is now Umbraco 8.
Also making a small change to the wording for custom Content Apps

V8 Content Apps amends

---

Reference/Using-Ioc/index.md

The Services and Helpers page contains more indepth examples of using DI in different contexts and creating your own services to inject, so I think it's useful to link to that information from here...

Link to the more in depth examples of DI

---

Umbraco-Headless/API-Documentation/api/content/index.md
Umbraco-Headless/API-Documentation/api/content/type/index.md
Umbraco-Headless/API-Documentation/api/language/index.md
Umbraco-Headless/API-Documentation/api/media/index.md
Umbraco-Headless/API-Documentation/api/media/type/index.md
Umbraco-Headless/API-Documentation/api/member/group/index.md
Umbraco-Headless/API-Documentation/api/relation/index.md
Umbraco-Headless/API-Documentation/api/relation/type/index.md
Umbraco-Headless/API-Documentation/cdn/content/index.md
Umbraco-Headless/API-Documentation/cdn/media/index.md
Umbraco-Headless/API-Documentation/index.md
Umbraco-Headless/Getting-Started-API/index.md
Umbraco-Headless/Getting-Started-Cloud/index.md
Umbraco-Headless/Getting-Started-DotNetCore/index.md
Umbraco-Headless/index.md

Small changes to grammatical things.
Also, added a few comments here and there, marked with `//`.

Review of API docs

---

Getting-Started/Setup/Server-Setup/azure-web-apps.md

Updated, as per advice here https://github.com/umbraco/Umbraco-CMS/issues/5035#issuecomment-476477802

Add Lucence Directory factory key to web.config

---

Extending/Packages/Package-Actions/index.md

Also corrected some minor grammar

Corrected casing of allowDocumentType alias

---

Extending/Packages/Package-Actions/custom-package-actions.md

This should provide a good understanding of how to create package actions. I have added a list of current v8 open source packages that use package actions for examples.
Very curious to hear feedback on the "When to use a Package Action" section 🙂

Add custom package actions article

---

Extending/Packages/Creating-a-Package/index.md
Extending/Packages/Package-Actions/custom-package-actions.md
Extending/Packages/Package-Actions/index.md
Extending/Packages/index.md
Extending/Packages/package-types.md

Found a few broken links - and added cross links where there should have been some 🙂

Fix links and structure

---

Add-ons/UmbracoForms/Developer/Extending/Adding-a-Type-v7.md
Add-ons/UmbracoForms/Developer/Extending/Adding-a-Type.md

In the spirit of #1853 but I don't think specifically mentioned on there.
Hopefully I've done it better this time by combining the old as v7 and the new with updates into the one pull request. :)

Document update for v8

---

Add-ons/UmbracoForms/Developer/Extending/Adding-a-Fieldtype.md

Updated the `ValidateField` signature in the example to match v8

Updated the ValidateField signature

---

Umbraco-Heartcore/API-Documentation/Content-Delivery/content/index.md
Umbraco-Heartcore/API-Documentation/Content-Delivery/media/index.md
Umbraco-Heartcore/API-Documentation/Content-Management/content/index.md
Umbraco-Heartcore/API-Documentation/Content-Management/content/type/index.md
Umbraco-Heartcore/API-Documentation/Content-Management/language/index.md
Umbraco-Heartcore/API-Documentation/Content-Management/media/index.md
Umbraco-Heartcore/API-Documentation/Content-Management/media/type/index.md
Umbraco-Heartcore/API-Documentation/Content-Management/member/group/index.md
Umbraco-Heartcore/API-Documentation/Content-Management/member/index.md
Umbraco-Heartcore/API-Documentation/Content-Management/member/type/index.md
Umbraco-Heartcore/API-Documentation/Content-Management/relation/index.md
Umbraco-Heartcore/API-Documentation/Content-Management/relation/type/index.md

As there are many examples and this page is quite long, I thought I'd add a contents section with anchor links to help people find they are looking for.
If this is ok, I will also add it to the content management API documentation pages.

Heartcore: Adding a contents list to content delivery API

---

Extending/Section-Trees/sections.md
Reference/Config/applications/index.md

Adding the version removed as per issue https://github.com/umbraco/UmbracoDocs/issues/1810

Adding the version removed

---

Umbraco-Cloud/Troubleshooting/index.md
Umbraco-Cloud/Troubleshooting/troubleshooting-siteperformance.md

Added the troubleshooting guide an created a link for it on Troubleshooting Index page

Created Site Performance Troubleshooting

---

Umbraco-Heartcore/API-Documentation/Content-Delivery/index.md
Umbraco-Heartcore/API-Documentation/Content-Management/index.md
Umbraco-Heartcore/API-Documentation/index.md
Umbraco-Heartcore/Getting-Started-Cloud/Backoffice-Users-and-API-Keys/index.md
Umbraco-Heartcore/Getting-Started-Cloud/Creating-a-Heartcore-project/index.md
Umbraco-Heartcore/Getting-Started-Cloud/The-Umbraco-Backoffice/index.md
Umbraco-Heartcore/index.md

Was looking at docs and realised there wasn't SEO meta data on the Heartcore pages, so I added some basic info :)
Thanks,
Carole

Heartcore: Adding meta data

---

index.md

I noticed there was no Heartcore link in the main landing page content, so thought I would add it :)

Adding heartcore link

---

Extending/Packages/Creating-a-nuget-package/index.md
Extending/Packages/index.md

Initial documentation for creating a NuGet version of a package.

Adding Create-a-nuget-package page.

---

Getting-Started/Setup/Server-Setup/Load-Balancing/index.md

Closes: https://github.com/umbraco/UmbracoDocs/issues/2126

Update links in Load Balancing docs

---

Umbraco-Cloud/Set-Up/Working-With-Visual-Studio/index.md

Update docs with important info about what happens if you run the uaas.cmd tool as an administrator.

Update docs with important info.

---

Tutorials/Creating-an-XML-Site-Map/index.md

Just ran through the tutorial, few  changes I could suggest, I added a trim to the blacklisted doc types, removed an unused variable in the full example, changed the variables to implicitly typed (var), and updated the method calls for hasValue and Value to use FallBack.ToAncestors.

Update XML sitemap tutorial

---

Implementation/Unit-Testing/index.md

Found a typo in the Unit Testing Docs.
PublichedContentQuery should be PublishedContentQuery.

Typo: Publiched/Published -ContentQuery

---

Reference/Querying/IPublishedContent/IsHelpers/index-v7.md
Reference/Querying/IPublishedContent/IsHelpers/index.md

I have updated the IsHelper for `IPublishedContent` as requested in #1875.  I have renamed the existing documentation for `v7` and made a new one for `v8`.  Please let me know what you think :-)

IPublishedContent IsHelpers for v8

---

Umbraco-Heartcore/API-Documentation/Content-Delivery/content/index.md

Wrote up api reference docs for the new content filter endpoint in the Content Delivery API.
Note the API-Version is 2.1 for this specific endpoint.

API reference for Content Filter endpoint

---

Tutorials/Creating-a-Property-Editor/index.md

Could not merge the original branch because the original repo was deleted
closes #783

commit for #783 by @tienlx91

---

Reference/Using-Ioc/index.md

Just a small change as I wasn't sure was IoC meant so just made it a bit more obvious.

Update to IoC / dependancy injection page

---

Umbraco-Heartcore/Versions-and-updates/index.md
Umbraco-Heartcore/Versions-and-upgrades/index.md

Added details about upgrade on and related to Umbraco Heartcore projects.

Heartcore versioning and updates

---

Umbraco-Cloud/Frequently-Asked-Questions/index.md

We need the link updated as the new page is much better than the old one.

Update link to "try for free"

---

Reference/Config/index.md

To reflect that some of the pages don't exist anymore...

Update V8 Configuration landing page

---

Umbraco-Heartcore/Client-Libraries/Dot-Net-Core/index.md
Umbraco-Heartcore/Client-Libraries/index.md

Update .NET Core references to .NET Standard.

Update references to .NET client library

---

Reference/Templating/Mvc/views.md

Hi,
I believe a little correction is needed [here](https://our.umbraco.com/documentation/Reference/Templating/Mvc/views#accessing-member-data). It needs to be `Value()` rather than `GetPropertyValue()`
Poornima

Correction in the code about accessing member data

---

Reference/Templating/Mvc/partial-views-v7.md

Hi,
I have updated MVC Partial views for Umbraco v8. Let me know if any changes are required.
Refers issue [1877](https://github.com/umbraco/UmbracoDocs/issues/1877)
Poornima

MVC Partial Views - update to v8

---

Reference/Templating/Mvc/examples-v7.md
Reference/Templating/Mvc/examples.md

Hi team,
I have updated the MVC Views examples for v8. Let me know if it needs any more additions.
Refers issue [1877](https://github.com/umbraco/UmbracoDocs/issues/1877)
Poornima

MVC View example

---

Reference/Querying/MemberShipHelper/index.md

Hi,
I have verified the `MembershipHelper` documentation against v8.
This corresponds to issue #1875 
Poornima

Verified membershiphelper for v8

---

Reference/Templating/Mvc/querying-v7.md
Reference/Templating/Mvc/querying.md

Hi,
This is the PR for updated MVC Querying documentation for #1877 
Poornima

MVC Querying updated for v8

---

Extending/Content-Apps/index.md

Updated code example below "Creating a Content App in C#"
https://github.com/umbraco/UmbracoDocs/issues/2191

Updated Content-Apps/index.md

---

Tutorials/Creating-an-XML-Site-Map/index.md

Excluded Document Types seems a clearer label for document types that will be excluded...

Make Excluded DocType List more clear

---

Reference/Language-Variation/index.md

Stumpled upon this on Our and since the **Edit page** button is _right there,_ I hurried over here and fixed it :)

Fix a borked codesample

---

Implementation/Default-Routing/Execute-Request/index-v7.md
Implementation/Default-Routing/Execute-Request/index.md

https://github.com/umbraco/UmbracoDocs/issues/1873
- needsV8Update to false
- ContentModel instead of RenderModel
- Deleted DynamicPublishedContent

Updated the Default Routing: Execute Request page for v8

---

Reference/Templating/Mvc/child-actions.md

Hi,
I have verified the MVC Child actions for v8. This is for issue https://github.com/umbraco/UmbracoDocs/issues/1877
Poornima

Verified MVC Child actions for v8

---

Reference/Templating/Mvc/Forms/index.md
Reference/Templating/Mvc/Forms/tutorial-child-action.md
Reference/Templating/Mvc/Forms/tutorial-custom-markup.md
Reference/Templating/Mvc/Forms/tutorial-partial-views.md

Hi,
This is for issue #1877 . Verifying the MVC forms and tutorials against v8.
Poornima

Verify MVC forms documentation against v8

---

Reference/Config/applications/index-v7.md
Reference/Config/applications/index.md

Hi,
I have verified applications.config for v8.
Poornima

Verified applications.config against v8

---

Implementation/Services/index.md

Removed redundant call to base.InitializePage
Made siteService variable that is passed in to have lowercase s so it is different from the property which has uppercase S.

Updated CustomViewPage code example

---

Reference/Security/Security-settings/index.md
Reference/Security/index.md

Updated the main Security index article with links to more related articles, and re-arranged the links a bit.

Security docs

---

Implementation/Default-Routing/index-v7.md

Created a v8 default routing page and deleted DynamicPublishedContent since it doesn't exist in v8
https://github.com/umbraco/UmbracoDocs/issues/1873

Default routing

---

Reference/Security/auto-linking-v7.3.0.md
Reference/Security/custom-password-checker-v7.3.0.md

Updates these pagesfor v8 
* https://our.umbraco.com/Documentation/Reference/Security/custom-password-checker
* https://our.umbraco.com/Documentation/Reference/Security/auto-linking
... I'm unsure exactly how the metadata headers and file names work but i think it's correct?

updates docs for custom password checker

---

Extending/Property-Editors/value-converters.md

I noticed a typo while I was scanning this documentation. I have also added some markup to make it all a bit more readable.

Fixed a typo and added some mark up to make the documentation a bit more readable

---

Reference/Config/index.md

Noticed that Serilog config is missing some copy. I have added that.

Serilog config description - Incomplete Copy

---

Reference/Querying/Udi.md

Just changing reference from v7 and v8 to Umbraco 7 and Umbraco 8

Update to UDI Identifiers page

---

Extending/Property-Editors/Property-Actions/index.md

The link to language files is 404-ing. Fixed that.

Fix the url to language files

---

Extending/Property-Editors/Property-Actions/index.md

Just a quick copy edit on the intro section :)
N

Update Property Actions

---

Extending/Section-Trees/trees.md

Hi,
I have made some general improvements to readability in the documentation. Also there was a place where the routepath was wrong in context to the example. I have corrected that too.
Poornima

Section trees improve readability

---

Extending/Section-Trees/sections.md

I stumbled upon how we can add custom sections to the backoffice using a C# type in the core code. I think its worth having documentation around it!
Poornima

Added documentation on implementing a custom section as a C# Type

---

Extending/Section-Trees/trees-v7.md

App_Plugins wording updated in section trees section

---

Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Grid-Layout/Build-Your-Own-Editor.md
Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Grid-Layout/Settings-and-styles.md

App_Plugins wording updated in grid layout documentation

---

Reference/Config/dashboard/index-v7.md

App_Plugins wording updated for dashboard config v7

---

Reference/Config/dashboard/index-v7.md
Tutorials/Creating-a-Custom-Dashboard/index-v7.md

App_Plugins wording corrected in tutorial for custom dashboard

---

Reference/Config/dashboard/index-v7.md
Tutorials/Creating-a-Property-Editor/index-v7.md
Tutorials/Creating-a-Property-Editor/index.md

App_Plugins wording update in property editors section

---

Umbraco-Cloud/Upgrades/Manual-Upgrades/Manual-CMS-upgrade-v7.md
Umbraco-Cloud/Upgrades/Manual-Upgrades/Manual-CMS-upgrade.md
Umbraco-Cloud/Upgrades/Moving-From-Courier-To-Deploy/index.md

App_Plugins wording updated in Umbraco Cloud Uprades

---

Extending/Language-Files/index.md
Extending/Packages/Language-Files-For-Packages/index.md

Hi @sofietoft ,
As I suggested I am bringing consistency to the wording for `App_Plugins`. I am going to break down into PRs per section/folder as it would be easier for you to review and manage. 
Poornima

App_Plugins wording corrected in Language Files section

---

.github/valeStyle/Terms.yml

Hi,
I have added App_Plugins to the Vale terms as suggested.
Poornima

vale update to bring consistency for App_Plugins warning

---

Reference/Querying/IPublishedContent/ExtensionMethods/index.md
Reference/Querying/IPublishedContent/index-v7.md
Reference/Querying/IPublishedContent/index.md

https://github.com/umbraco/UmbracoDocs/issues/2289 
Update [IPublishedContent ](https://our.umbraco.com/documentation/Reference/Querying/IPublishedContent/)page. 
(v7) Extension Methods link to:  
https://our.umbraco.com/apidocs/v7/csharp/api/Umbraco.Web.PublishedContentExtensions.html 
(v8)  Extension Methods link to: 
https://our.umbraco.com/apidocs/v8/csharp/api/Umbraco.Web.PublishedContentExtensions.html

Update IPublishedContent extension methods link

---

Umbraco-Cloud/Frequently-Asked-Questions/index.md

Question: We mention database backup is offered up to 14 days and that there's a powershell script which can help with that. Is that still true?

Describe 30 days of filesystem backup for disaster recovery

---

Extending/Packages/Uploading-to-Our/index.md

The PR mentioned has been merged in and is now live so the warning has been removed.

Removed warning of PR

---

Tutorials/Creating-Basic-Site/Getting-Started/index.md

Small changes to the wording of the tutorial to hopefully make it a bit clearer. 
Adding CMS to the end of Umbraco in a number of places to make it clear it's the CMS, not the company.

Small updates to Creating-Basic-Site tutorial

---

Umbraco-Cloud/Set-Up/Going-live/index.md
Umbraco-Cloud/Set-Up/index.md

Added an article on going live as well as add a link to the article on the Setup page

Going Live article

---

Reference/Management/Services/ContentTypeService/Retrieving-content-types-v7.md
Reference/Management/Services/ContentTypeService/Retrieving-content-types-vpre8.4.md
Reference/Management/Services/ContentTypeService/Retrieving-content-types.md

Update the 'retrieving content types" page for v8

Retrieving content types update for v8

---

Reference/Routing/surface-controllers.md

This PR fixes issue https://github.com/umbraco/UmbracoDocs/issues/1781.

Document ValidateUmbracoFormRouteString attribute

---

Umbraco-Cloud/Databases/Cloud-Database/index.md

I have updated the docs so we tell in which section of the file the setting should be added.

Updated where the settings should be added for LocalDB

---

Reference/Management/Services/ContentTypeService/Retrieving-content-type-containers-v7.md
Reference/Management/Services/ContentTypeService/Retrieving-content-type-containers.md

Update [Retrieving content type containers](https://our.umbraco.com/documentation/Reference/Management/Services/ContentTypeService/Retrieving-content-type-containers) for v8

Retrieving content type containers

---

Umbraco-Heartcore/Client-Libraries/Dot-Net-Core/MVC-Sample/index.md

Fixed spacing

---

Umbraco-Heartcore/API-Documentation/Content-Management/language/index.md

Hi,
As mentioned in the title, fixed some typos in the language API page https://our.umbraco.com/documentation/Umbraco-Heartcore/API-Documentation/Content-Management/language/

Fixed typos and broken bookmarks for Heartcore Language API page

---

Umbraco-Cloud/Frequently-Asked-Questions/index.md
Umbraco-Cloud/Security/index.md

Describes:
HTTPS & Certificates
TLS protocol support & TLS ciphers
Firewall & Access restriction features

Security section for Umbraco-Cloud

---

Reference/Management/Services/MediaService/Index.md

spotted 2 small typos whilst reading this doc. :)

Typo spotted

---

Umbraco-Heartcore/API-Documentation/Content-Management/content/index.md

Heartcore - Content API typo fix

---

Umbraco-Cloud/Frequently-Asked-Questions/index.md
Umbraco-Cloud/Security/index.md
Umbraco-Cloud/index.md

Moving some stuff from Cloud FAQ into to new Security section, while making sure the two a linked together.

Cloud security section

---

Reference/Management/Services/MemberTypeService/Index-v7.md
Reference/Management/Services/MemberTypeService/Index.md

Belongs to: https://github.com/umbraco/UmbracoDocs/issues/2128
- Updated MemberTypeService

Update MemberTypeService for v8

---

Reference/Management/Services/MemberGroupService/Index-v7.md
Reference/Management/Services/MemberGroupService/Index.md

Belongs to: https://github.com/umbraco/UmbracoDocs/issues/2128
- Updated MemberGroupService

Update member group service for v8

---

Reference/Using-Ioc/index.md

As per the discussioon here https://github.com/umbraco/Umbraco-CMS/issues/7502 and here https://github.com/umbraco/UmbracoDocs/issues/2223

Removing section accessing LightInject container

---

Umbraco-Cloud/Deployment/Hotfixes/Move-files-manually/index.md
Umbraco-Cloud/Deployment/Hotfixes/Using-Git/index.md
Umbraco-Cloud/Deployment/Local-to-Cloud/index.md
Umbraco-Cloud/Getting-Started/Migrate-Existing-Site/index.md
Umbraco-Cloud/Set-Up/Working-Locally/index.md

Added a note about the changes to the free version of GitKraken

Added GitKraken Note

---

Add-ons/UmbracoCourier/Developer/Events.md
Add-ons/UmbracoCourier/Developer/index.md

Added Events section to Courier with one event - rebuild lucene indexes on deploy, and how to override that event.

Added Events section to Courier

---

Extending/Packages/Creating-a-nuget-package/index.md

Spaces aren't allowed in the ID name

Changing the ID as it causes build issues

---

Umbraco-Heartcore/API-Documentation/Content-Management/member/index.md
Umbraco-Heartcore/API-Documentation/index.md

Added info about the new endpoints for member password management.
Added a new section about member authentication
**NOTE** This has not been released yet

Heartcore member authentication and password management

---

Development-Guidelines/index.md
Development-Guidelines/test-driven-flow.md
Getting-Started/Backoffice/LogViewer/index.md
Getting-Started/Backoffice/Variants/index.md
Getting-Started/Code/Creating-Forms/index.md
Getting-Started/Code/Debugging/index.md
Getting-Started/Code/Source-Control/index.md
Getting-Started/Code/Subscribing-To-Events/index.md
Getting-Started/Code/Umbraco-Services/index.md
Getting-Started/Data/Defining-content/index.md
Getting-Started/Data/Scheduled-Publishing/index.md
Getting-Started/Data/Users/index.md
Getting-Started/Data/index.md
Getting-Started/Design/Rendering-Media/index.md
Getting-Started/Design/Stylesheets-Javascript/index.md
Getting-Started/Design/Templates/basic-razor-syntax.md
Getting-Started/Design/Templates/index.md
Getting-Started/Setup/Server-Setup/Load-Balancing/index.md
Getting-Started/Setup/Server-Setup/index.md
Getting-Started/Setup/Server-Setup/permissions.md
Getting-Started/Setup/Upgrading/index.md
Getting-Started/Setup/index.md

Adding meta titles and descriptions to pages that didn't have any :)

Adding more meta titles and descriptions

---

Extending/Packages/Creating-a-nuget-package/index.md

Adding an example of how you create a .nuspec file

Update to creating a nuget package documentation

---

Umbraco-Heartcore/API-Documentation/Content-Management/member/index.md

Noticed I missed adding the password endpoints links to the TOC

Add member password endpoints to toc

---

Reference/Config/index.md

Looks like the page has been updated and the needsV8Update can be removed.

Reference config

---

Reference/Querying/UmbracoHelper/index.md

/Reference/Querying/UmbracoHelper/ 
Tags fix

Tags fix on index.md

---

Reference/Management/Services/SectionService/Index-v7.md
Reference/Management/Services/SectionService/Index.md

Belongs to: https://github.com/umbraco/UmbracoDocs/issues/2128
- "Updated" UserService for v8

Update sectionservice v8

---

Umbraco-Heartcore/API-Documentation/Content-Delivery/content/index.md

Updated CDN contente responses to contain the new `_urls` property

Added _urls property to examples

---

Extending/Content-Apps/index-vpre8.6.md

Updated Content App article according to changes coming in Umbraco 8.6.
For reference: https://github.com/umbraco/Umbraco-CMS/pull/6670

Added new file for 8.6 updates on Content Apps

---

Reference/Management/Services/UserService/Update-user-information-v7.md

**Update: Update user information for v8**
- Added code blocks to both versios
- Changed ApplicationContext.Services.UserService to Services.UserService in UmbracoViewPage in the v8 version.

Update user information

---

Reference/Management/Services/UserService/Get-a-reference-to-a-user-v7.md
Reference/Management/Services/UserService/Index-v7.md

- Added code blocks to both versions
- Changed ApplicationContext.Services.UserService to Services.UserService in UmbracoViewPage in the v8 version.

Update Get a reference to a user

---

Umbraco-Heartcore/Client-Libraries/Dot-Net-Console/index.md
Umbraco-Heartcore/Client-Libraries/index.md

Added documentation for the .NET Console app and linked to the page on the Client Libraries index page as well

Added Console App

---

Reference/Management/Services/LocalizationService/Index-v7.md
Reference/Management/Services/LocalizationService/Retrieving-languages-v7.md
Reference/Management/Services/LocalizationService/Retrieving-languages.md

Update Retrieving languages for v8

Update Retrieving languages

---

Getting-Started/Data/index.md

The content page didn't match the tree view on the left hand side. Adding Scheduled Publishing and Users pages

Update Getting Started landing page

---

Getting-Started/Code/Subscribing-To-Events/index.md

Thought I would link to the relevant section to learn more about composing.

Linking to composer section

---

Extending/index.md

Update the content to match the content tree on the left hand side.

Update Extending landing page

---

Implementation/index.md

Matching the left hand tree with the right hand side content. 
The new sections could maybe do with icons applied but they work without for now. 
Also updated the order of the content on the right hand side as it didn't match the left hand tree.

Updating Implementation intro section

---

Implementation/index.md

FIxing formatting issue

---

Tutorials/Creating-Basic-Site/index.md
Tutorials/Multilanguage-Setup/index.md
Umbraco-Cloud/Cloud-API/index.md
Umbraco-Cloud/Databases/Local-Database/index.md

Hi,
I have added some SEO Info on some documentation pages. I will go through more in the coming days.
Poornima

Added SEO Info to some pages

---

Implementation/index.md

Seems to be some bugs in the way the rows are displaying. Hopefully this fixes it!

More formatting issues.

---

Tutorials/index.md

Reordering content to match content tree
Note - Creating a content app needs to be added to the content tree.

Tutorials Page update

---

Contribute/Issues/index.md
Contribute/Markdown-Conventions/index.md
Contribute/Pull-Requests/index.md
Contribute/adding-metadata.md
Contribute/file-naming-conventions.md
Contribute/index.md

Hi,
I have added SEO Metadata to contribute section. I have removed the `versionFrom` on some docs too in the same section. Let me know if its okay :-)
Poornima

Added SEO Metadata to Contribute section.

---

Add-ons/UmbracoForms/Editor/Creating-a-Form/index.md

https://our.umbraco.com/Documentation/Add-ons/UmbracoForms/Editor/Creating-a-Form/?fbclid=IwAR03YNuEw6QUXY0ANWfKCOkJ0dxsZ5ytk1NlsIWoJ4s4eOWcVlpQGgBUgVs/#select-page
added "which you can add in the Settings section under Document Types" after some feedback we got from an Umbraco user

added more detailt on how ot add a Form to a site.

---

Umbraco-Cloud/Upgrades/Migrating-from-7-to-8/index.md

Removed some of the mentions of specific versions and changed some to the latest version (8.6)

Made it more timeless

---

Reference/index.md

Sorting the order to match the content tree and also adding some of the missing content from the index page.

Update to Reference page

---

Umbraco-Cloud/Upgrades/Manual-Upgrades/Manual-CMS-upgrade.md

Added a note that Dashboard.config only applies to Umbraco 7 projects.

Addded note

---

Extending/Embedded-Media-Provider/index.md
Extending/FileSystemProviders/index.md
Extending/Section-Trees/index.md
Extending/Section-Trees/sections.md
Extending/Section-Trees/tree-actions.md
Extending/Section-Trees/trees.md

Hi,
More SEO Metadata added :-)
Poornima

SEO Metadata added

---

Extending/Property-Editors/value-converters.md

I think I missed out on this with my last PR #2447 
Poornima

SEO Info on Property Value Converters

---

Umbraco-Cloud/index.md

Just reordering the content to match the content tree

Update Umbraco Cloud index

---

Umbraco-Cloud/index.md

Removing link to Heartcore after suggestion from Sofie on Github.

Edit Umbraco Cloud page

---

Umbraco-Heartcore/index.md

Just reordering the content to match the navigation (once that PR is accepted).
https://github.com/umbraco/OurUmbraco/pull/571

Reordering Umbraco Heartcore page

---

Reference/Searching/Examine/Indexing/index.md

Have added a little extra clarity on the steps required to create the custom index, after feedback on the twitter. Essentially strategy here is to cross link to info on Components, Composition of IOC, but also word the 1.2.3. steps so hopefully it's clearer on the 'why' do each bit...

Update explanation of examples of registering a new Index

---

Extending/Packages/Creating-a-Package/index.md

We set the default license when creating a package, but would be good to have the author really consider which license to use and not just go with MIT without thinking about it.

Mention resource for picking a license

---

Umbraco-Cloud/Frequently-Asked-Questions/index.md

We have recently migrated all customer databases to keep 35 days of point in time to restore backups, updating docs to reflect that.

Updates point in time restore retention

---

Umbraco-Cloud/Set-Up/Upgrade-Umbraco-Cloud-Plan/index.md

I have just updated the email to be contact@umbraco.com so we say the same as here https://umbraco.com/contact-us/

Corrected the email

---

Getting-Started/Setup/Server-Setup/Load-Balancing/azure-web-apps.md

use pubic facing instead of front end to avoid confusing
typos and grammars
added tip about warming up servers when localdb is ignored.

Updates following review with Jeavon of the new settings

---

Extending/Backoffice-Search/index.md
Extending/index.md

I noticed one of the features is missing in docs, here is short docs about how to use that.
This is draft PR as I am sure it will need more work on that.

Feature docs/back office search

---

Extending/Macro-Parameter-Editors/index.md

Correction to the typo in product tag

---

Extending/Packages/Creating-a-nuget-package/index.md
Extending/Packages/Language-Files-For-Packages/index.md
Extending/Packages/Package-Actions/custom-package-actions.md
Extending/Packages/Package-Actions/index.md
Extending/Packages/Packages-on-Umbraco-Cloud/index.md
Extending/Packages/Uploading-to-Our/index.md
Extending/Packages/package-types.md

Added SEO metadata to packages documentation

SEO tags added to packages section

---

Extending/Section-Trees/tree-actions-v8.md

SEO tags added to tree actions v8 :-)

SEO tags added to tree actions v8

---

Getting-Started/Backoffice/index.md

Update missing word for clarity.

Missing verb on Umbraco Backoffice page

---

Extending/Section-Trees/sections.md

Per a discussion on Slack, I noticed the documentation doesn't really describe how to control the order of the sections. So here is some more information about that 😉

Added some more information about registering sections

---

Getting-Started/Backoffice/Content-Templates/index.md
Getting-Started/Code/Source-Control/index.md
Getting-Started/Data/Data-Types/default-data-types.md
Getting-Started/Data/Data-Types/index.md

SEO Metadata

---

Umbraco8FAQ.md

SEO metadata added to Umbraco 8 FAQ page

SEO metadata added to Umbraco 8 FAQ page

---

Reference/Searching/Examine/Quick-Start/index.md

Fixing the constant for `ExternalIndex`: https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Core/Constants-Indexes.cs#L8

Fix ExternalIndex constant

---

Reference/API-Documentation/index.md
Reference/Cache/examples/tags.md
Reference/Config/Serilog/index.md
Reference/Config/index.md
Reference/Debugging/index.md
Reference/Events/Application-Startup.md
Reference/Events/ContentService-Events.md
Reference/Events/DataTypeService-Events.md
Reference/Events/MediaService-Events.md
Reference/Events/determining-new-entity.md
Reference/Events/index.md

Heylo,
More changes (I know!!!!) to the SEO reference section. I have left out some docs requiring v8 update. But can always do that if needed :-)
Poornima

SEO Fixes to reference section

---

Umbraco-StarterKit/Uno-pedia/Umbraco-Backoffice/index.md

Also we should add links to other articles like:
- Link to "Manage Media Library", "Manage Users".. and perhaps also to the "Tour of the backoffice" article 🤔

Suggestion to the section descriptions

---

Getting-Started/Design/Rendering-Content/index.md

Updated the text 'Jannuary' to 'January'

Fixed the the Typo mistake

---

Reference/Management/Services/index.md

Added missing link to the ApplicationTreeService page

ApplicationTreeService link

---

Umbraco-Cloud/Set-Up/Manage-Subscriptions/index.md

I have added info that we need to be filled out when someone is creating a new profile on the shop, to be able to make a new invoice when we have moved the subscription

Add info that we need for invoces

---

Tutorials/Editors-Manual/Version-Management/Rollback-to-a-Previous-Versions/index-v7.md

Update Rollback to a Previous Version for v8

Rollback to a Previous Version

---

Umbraco-Uno/Uno-pedia/Widgets/index.md

Updated the text "webstes" to "websites"

Correction to Uno widgets overview 

---

Umbraco-Cloud/Upgrades/Manual-Upgrades/index.md

removed the part about opting out of manual upgrades

correction

---

Umbraco-Cloud/Troubleshooting/Log-files/index.md

Added a small note about the plan it is available for

Updated IIS logging article

---

Reference/Management/Services/EntityService/Index.md
Reference/Management/Services/index.md

Added EntityService

---

Reference/Management/Services/ExternalLoginService/Index.md
Reference/Management/Services/index.md

ExternalLoginService

---

Reference/Management/Services/MacroService/Index.md
Reference/Management/Services/index.md

Belongs to https://github.com/umbraco/UmbracoDocs/issues/847 
Add MacroService

MacroService

---

Reference/Routing/WebApi/index.md

Hi ,
I have added notes about  enabling attribute routing in web api controllers.
Poornima

Attribute routing on Web API

---

Reference/Events/MemberService-Events.md
Reference/Events/MemberService-Events/MemberService-Events.md
Reference/Events/index.md

Hi, 
I thought it would be good to add Member Service events to the events section.
Poornima

MemberService Events

---

Reference/Management/Services/NotificationService/Index.md
Reference/Management/Services/index.md

Add a NotificationService article

NotificationService

---

Reference/Events/EditorModel-Events/index.md

Update the example on this page to use the ContentSavedState - so people can see how to set a default value ONLY when a new page is created, and not when a particular field is left blank by the editor

Update EditorModel Events example to use ContentSavedState

---

Getting-Started/Setup/Server-Setup/Load-Balancing/index-v7.md

After clicking this link a few times I am now ready to fix it so I can save future clicks 😅

Let v7 LB article link to other v7 article instead of v8.

---

Reference/Management/Services/PackagingService/Index.md
Reference/Management/Services/index.md

Add PackagingService

---

Reference/Management/Services/TagService/Index.md
Reference/Management/Services/index.md

Add TagService

---

Umbraco-Uno/Creating-Content/index.md

Purged the smallest typo

---

Reference/Searching/Examine/examine-events.md

it's CreateScope not Create AND typo on autocomplete
fixes: https://github.com/umbraco/UmbracoDocs/issues/2597

Update scope creation example

---

Add-ons/UmbracoForms/Developer/Custom-Markup/index.md

Just rewording a sentence to make it a bit easier to understand.

Update to Custom Markup page for Forms

---

Umbraco-Uno/Creating-Content/Work-with-content/index.md

- Corrected a few grammatical errors.
- Made some subjective improvements.

A few improvements.

---

Umbraco-Cloud/Troubleshooting/Deployments/Structure-Error/index.md

I ran into a broken link. Good reason to start contributing. Fixed a spelling error too.

Fixed a broken link

---

Reference/Management/Services/TextService/Index.md
Reference/Management/Services/index.md

Belongs to https://github.com/umbraco/UmbracoDocs/issues/847 
Add TextService

Textservice

---

Reference/Management/Services/RedirectUrlService/Index.md
Reference/Management/Services/index.md

Belongs to https://github.com/umbraco/UmbracoDocs/issues/847 
Add RedirectUrlService

RedirectUrlService

---

Reference/Management/Services/ServerRegistrationService/Index.md
Reference/Management/Services/index.md

Belogs to https://github.com/umbraco/UmbracoDocs/issues/847
Add ServerRegistrationService

ServerRegistrationService

---

Extending/Packages/UmbPack/index.md

We have recently added some features to UmbPack, this PR adds info on how to use them 🙂
closes https://github.com/umbraco/UmbPack/issues/34

Add info on archive pattern and name override

---

Add-ons/UmbracoForms/Developer/Extending/Adding-a-Fieldtype.md

Adding the using statements as not everyone uses resharper and if you see errors because you've copied the code, you might think something has gone wrong.

Update to Adding a Fieldtype  page.

---

Add-ons/UmbracoForms/Developer/Extending/Adding-an-Event-Handler.md
Add-ons/UmbracoForms/Developer/Extending/index.md

I could have used an example like this when I first started working with Forms.

Feature - UmbracoForms: Add Event Handler reference page

---

Tutorials/Add-Google-Authentication/index.md

I was going through the tutorial and i missed a little bit flow in the end. Thats why i've changed it so there is more flow.

Changing auth Documentation

---

Tutorials/Add-Google-Authentication/index.md

Reverts umbraco/UmbracoDocs#2634
A little misshap on merging this, reverting and he will resubmit 🙂

Revert "Changing auth Documentation"

---

Tutorials/Add-Google-Authentication/index.md

Changing line in google auth documentation to get a better flow when following the tutorial

Updating Google Auth Docs

---

Extending/Property-Editors/value-converters.md

There was a typo in the Tutorial and I've changed it.

Updating Value Converter Documentation

---

Reference/Security/index.md
Reference/Security/password-reset.md
Reference/Security/reset-admin-password-v7.md
Reference/Security/reset-admin-password.md

There was an official but undocumented way to reset the password for the admin user

Admin password reset

---

Reference/Routing/surface-controllers-actions.md
Reference/Routing/surface-controllers.md

Hi,
This PR is for issue #2449 . Please can you review and let me know what you think? 
I have also added SEO metadata to surface controllers.
Poornima

Documentation for surface controller actions. 

---

Tutorials/Editors-Manual/Getting-Started-With-Umbraco/Copying-a-Page/index.md

Updates the formatting on this page, so that it displays the "info" content in an info box https://our.umbraco.com/Documentation/Tutorials/Editors-Manual/Getting-Started-With-Umbraco/Copying-a-Page/

Fixes formatting on an info box

---

Reference/Common-Pitfalls/index.md
Reference/Config/fileSystemProviders/index.md
Reference/Config/tinyMceConfig/index.md
Reference/Config/umbracoSettings/index.md
Reference/Config/webconfig/index.md

Hi,
I have added some SEO fixes to some pages.
Poornima

SEO fixes to some pages

---

Umbraco-Heartcore/Getting-Started-Cloud/Creating-a-Heartcore-project/index.md

A small Typo in the HeartCore Tutorial.

Small typo

---

Reference/Querying/UmbracoHelper/index.md

Belongs to https://github.com/umbraco/UmbracoDocs/issues/2200
Add GetMediaByTagGroup example

GetMediaByTagGroup

---

Reference/Searching/Examine/Indexing/index.md

Adding namespaces for all the code in the examples

---

Extending/Content-Apps/index.md

Added a note which explains which icon pack we use, and added an explanation on where to put the cs file when making a content app the C# way

Small corrections and notes in regards to content apps

---

Umbraco-Heartcore/Getting-Started-Cloud/Backoffice-Users-and-API-Keys/index.md
Umbraco-Heartcore/Getting-Started-Cloud/Deployment-workflow/index.md
Umbraco-Heartcore/Getting-Started-Cloud/GraphQL-Playground/index.md
Umbraco-Heartcore/Getting-Started-Cloud/The-Umbraco-Backoffice/index.md
Umbraco-Heartcore/Getting-Started-Cloud/index.md

(API keys, deployments, GraphQL playground, intro to cloud, intro to backoffice)

Added video links for articles - Heartcore

---

Extending/Content-Apps/index-vpre8.6.md
Extending/Content-Apps/index-vpre8.7.md

And some syntax cleanup in general.
New additions:
- How to add Content App to "Content Types" (Document Types)

New v8.7 version of Content Apps article

---

Umbraco-Cloud/Troubleshooting/Deployments/Dependency-Exceptions/index.md

Customer said it was a bit lackluster, and I agreed it was a bit short, he didn't see the fix and he skimmed for it.
I agreed and said it could perhabs use a headline that states "here is how to fix it"

Update index.md - Added a headline

---

Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Block-List-Editor/index.md

A minor update, but always great to show a valid markup 😄👍

Add missing end-closing h1 tag

---

Umbraco-Cloud/Set-Up/Manage-Hostnames/index.md
Umbraco-Uno/Going-live/index.md

Adding video to hostname section of Uno docs.

Adding video to hostnames on Uno "Going Live" page

---

Reference/Security/authenticate-with-AD.md

I gave just a couple of tips that would have been helpful to me!

provide a couple of tips

---

Reference/Config/umbracoSettings/index-vpost8.6.0.md

This pull request documents the KeepAlive configuration introduced in Umbraco 8.6 as discussed in #2710

Document KeepAlive configuration

---

UmbracoNetCoreUpdates.md

Please note this do not have to be merged before alpha 2 is ready

Prepare the netcore document for alpha 2

---

Umbraco-Cloud/Deployment/Deploy-Settings/index.md

Adds docs for **ExportMemberGroups** settings
Fixes #2708

Adds docs for ExportMemberGroups Deploy Setting in 3.4.0+

---

Reference/Routing/Authorized/index.md

Update code sample to include controller

---

Reference/Templating/Modelsbuilder/Control-Generation.md

I struggled a bit this week after reading this to understand the best way to install the full version of models builder as nuget doesn't seem to be referenced in the ModelsBuilder repository, and it took me a while to figure out which nuget packages to install.
So I thought I'd submit a PR with more detailed instructions in case anyone else has the same problem!  I also wanted to include a link to the package on Our, but I couldn't find it?  Only the old version of ModelsBuilder?

Extra info on installing full version of ModelsBuilder

---

Extending/Dashboards/index.md
Implementation/Composing/index.md
Implementation/Data-Persistence/index.md

I have fixed minor doc issues (as a participant in Hacktoberfest). Could you please check @sofietoft ?

updated doc

---

Reference/Templating/Modelsbuilder/configuration.md

PureLive is the default. At least in 8.6, 7 and 8

changed the default mb mode

---

Tutorials/Starter-kit/Lessons/3-Add-Open-Graph/step-4-v7.md
Tutorials/Starter-kit/Lessons/3-Add-Open-Graph/step-4.md

I got someone who was very confused the siteName variable was not picked up... and I was too until I realized this guide is under Starter Kit and depends on its variables. Added some notes to make it more clear what might go wrong

Added notes to troubleshoot some issues with OpenGraph implementation

---

Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Related-Links2.md

I often forget about this. I guess it would help others.

Warning message to use Umbraco.Web.Models

---

Umbraco-Cloud/Set-Up/Manage-Environments/index.md

of the environments will be added in and needs to be removed in

Updated with info about the order

---

Add-ons/UmbracoCourier/Developer/index.md
Contribute/Code-samples/index.md
Contribute/Style-Guide/index.md
Reference/UmbracoVolatile.md

Fixes typos: supress/suppresing to suppress/suppressing

Fixes typos: supress/suppresing to suppress/suppressing

---

Umbraco-Uno/Creating-Content/Customize-Your-Theme/index.md
Umbraco-Uno/Creating-Content/Manage-Media-library/index.md
Umbraco-Uno/Creating-Content/Navigation-menu/index.md
Umbraco-Uno/Creating-Content/Rich-Text-Editors/index.md
Umbraco-Uno/Creating-Content/Set-Up-Footer/index.md
Umbraco-Uno/Creating-Content/Work-with-content/index.md
Umbraco-Uno/Creating-Content/Working-with-widgets/index.md

fixes various typos.

---

Umbraco-Heartcore/Getting-Started-Cloud/API-Browser/index.md
Umbraco-Heartcore/Getting-Started-Cloud/Creating-a-Heartcore-project/index.md
Umbraco-Heartcore/Getting-Started-Cloud/Deployment-workflow/index.md
Umbraco-Heartcore/Getting-Started-Cloud/GraphQL-Playground/index.md
Umbraco-Heartcore/Getting-Started-Cloud/The-Cloud-Portal/index.md
Umbraco-Heartcore/Getting-Started-Cloud/The-Umbraco-Backoffice/index.md
Umbraco-Heartcore/Getting-Started-Cloud/Using-The-Forms-API/index.md

Fixes various typos

---

Add-ons/UmbracoForms/Editor/Creating-a-Form/index.md

* Adding a bit more information about how to gain accesso the forms if the user doesn't see it when they log in. 
* Changing some of the instructions. Removing the word hit and replacing it with click

Update to Create a form page

---

Add-ons/UmbracoForms/Developer/Prepping-Frontend/index.md

Just a couple of small updates to hopefully make the page read a bit better.

Small grammar changed to the Umbraco Forms.

---

CONTRIBUTING.md

Changing the branch reference from `master` to `main`

Changing branch reference

---

teaching.md
teaching2.md

Two articles for a course, they will be deleted after tomorrow and will not be visible on our.umbraco

Two small articles for a course
