- Documentation/Extending-Umbraco/Property-Editors/creating-tutorial4-v7.md
- Documentation/Reference/WebApi/index.md
As discussed here: https://our.umbraco.org/forum/umbraco-7/using-umbraco-7/64690-Simple-package-not-available-TextValue-Dropdown-List?p=1#comment218791 and here: https://our.umbraco.org/forum/umbraco-7/developing-umbraco-7-packages/48668-Creating-an-UmbracoAuthorizedJsonController some of the documentation hasn't been updated after this change to start all API paths with "umbraco/backoffice" in 7.0.2 http://umbraco.com/follow-us/blog-archive/2014/1/17/heads-up,-breaking-change-coming-in-702-and-62.aspx. I've done that here, though not searched the rest of the documentation for any other places it might need to happen.
> Fixed the API paths after the breaking change in 7.0.2

- Getting-Started/Data/Data-Types/index.md
Changed "commasepareted" to "comma-separated" in the "Checkbox list" section.
> Corrected typo in "Checkbox list" section.

- Getting-Started/Setup/Install/install-umbraco-with-nuget.md
I banged my head a few hours today to figure out why the standard ExcludeFilesFromPackage Item Group and siblings didn't work. I'm sure I'm neither first nor last, so I guess it could just as well be in the docs.
> Info on excluding files from publish

- Umbraco-as-a-Service/Set-Up/Media/index.md
ImageProcessor.Web does not require disabling the VirtualPathProvider in order for the cache to work. Disabling the provider is strongly discouraged as it will cause Umbraco to persist the media url in absolute format. This causes two issues:
1. ImageProcessor cannot now intercept the image request to the external site without using the /remote.axd prefix.
2. The media cannot now be shared across different urls.
Both the IFileystemProvider implementation and ImageProcessor.Web.Plugins.AzureBlobCache will automatically create containers if they do not exist so you do not have to manually create them.
https://github.com/JimBobSquarePants/ImageProcessor/blob/V2/src/Plugins/ImageProcessor.Web/ImageProcessor.Web.Plugins.AzureBlobCache/AzureBlobCache.cs#L100
> Update incorrect instructions.

- Reference/Cache/updating-cache.md
Not everyone has plugins in visual studio helping them.  Or the plug-ins don't work one day...
> missing namespace for generic GetCacheItem<> extention methods

- Reference/Querying/IPublishedContent/Collections.md
Not a problem for experienced developers, but possibly killing the experience for newbies if they copy and past without further checking.
> Fix typo/syntax in Collections.md, ".Where" section

- Umbraco-as-a-Service/Set-Up/Media/index.md
The `~/config/imageprocessor/cache.config` example had the URL, but in reality, it needs to be the container name for CachedBlobContainer and SourceBlobContainer
> Update AzureBlobCache config

- Getting-Started/Data/Members/index.md
These default member properties:
* umbracoMemberPassWordRetrievalAnswer
* umbracoMemberPasswordRetrivalQuestion
Have typos and are no longer present for default members in my version of Umbraco (v7.4.2)
> Removed default member props no longer present in 7.4.2

- Reference/Querying/UmbracoHelper/index.md
Change complies with other headers and samples in this document.
> Change in argument or ".Media()" to use int id instead of sample id.

- Umbraco-as-a-Service/Set-Up/index.md
I have updated the text for hostnames, so we tell people to point their sites at (e.g. mysite.s1.umbraco.io) instead of (e.g. mysite.umbraco.io)
> Updated the text about hostnames

- Add-ons/UmbracoForms/Developer/Field-Types/index.md
- Add-ons/UmbracoForms/Developer/index.md
Add new section under developer for Field Types - This adds info to the DatePicker to talk about the hidden field to store the date in a common/correct format for the server & how Pikaday.js lib is configured/setup to support locales for this
> DatePicker FieldType Doc

- Reference/Config/umbracoSettings/index.md
I believe this is the last remaining "build-in" typo in the docs, mentioned in this issue: http://issues.umbraco.org/issue/U4-5559#
> Fixed the last remaining build-in typo

- Reference/Config/fileSystemProviders/index.md
I wrote most of the reference for the configuration of the PhysicalFileSystem provider, but despite this being the way it should work, I cannot get it to work on my machine.
After I change the config I can save and edit new files, but I get an exception when trying to update old files.
Also old files are still pointing to the old url, so there must be a way to easily change the path of pre-existing files. But I don't know how to do it.
Addressed issue #218
> Created documentation page for fileSystemProviders.config

- Extending/Property-Editors/index.md
- Extending/Property-Editors/package-manifest.md
- Tutorials/Creating-a-Property-Editor/index.md
- Ports over the package.manifest docs from the old Belle doc page
- Updated with couple properties added `icon` & `group`
- Adds NEW info about how to use hosted JSON Schema to get autocomplete in VS Code & VS2015 when editing package.manifest files
> Package Manifest Docs

- Reference/Common-Pitfalls/index.md
Was using `@Model.Content.Site()` instead of `@Model.Site()`
> Update 'Too much querying' examples

- Reference/Routing/Request-Pipeline/outbound-pipeline.md
Clarifying that a UrlSegmentProvider cannot create new segments, so `/` characters are forbidden.
I discussed this with @zpqrtbnk on [a forum post on Our](https://our.umbraco.org/forum/extending-umbraco-and-using-the-api/81741-urlsegmentprovider-giving-this-document-is-published-but-its-url-would-collide-with-content-error)
> Clarifiying that UrlSegmentProvider docs

- Getting-Started/Setup/Install/Running-Umbraco-On-A-Mac.md
I use VMWare so thought it would be helpful to let others know that VMWare Fusion is a viable option to use when developing an Umbraco site as well as Parallels or Bootcamp.  All three options are viable in my opinion.
> Added VMWare to Running-Umbraco-On-A-Mac help.

- Extending/Custom-File-Systems.md
The referenced azure blob storage provider is superseded by the one from James.
> update the link of azure blob storage provider

- Reference/Routing/custom-controllers.md
Added example of passing through the normal Umbraco Model when setting up a Custom Model if inherited from RenderModel.
When trying to do this for the first time I found this bit of advice essential as it wasn't obvious and so had to be hunted down ;)
> Custom Model Advice

- Reference/Common-Pitfalls/index.md
This was raised in the comments on #400 - these docs need to say `Model.Content.Site()` as long as the default template inherits from `UmbracoTemplatePage`
> Revert to `Model.Content.Site` syntax

- Getting-Started/Setup/Upgrading/760-breaking-changes.md
The link to the IIS URL Rewrite page was broken. It was linking to this url https://www_iis_net/downloads/microsoft/url-rewrite. (with underscores in the hostname)
I think it was because of the angle brackets in the url.
> Fix the IIS Url Rewrite link on the 7.6.0 Upgrade page.

- Extending/Macro-Parameter-Editors/index.md
- Extending/Property-Editors/package-manifest.md
There was a missing `}` brace in the package.manifest definitions under the property editor and macro parameter sections:
```
propertyEditors: [
{
alias: "My.ParameterEditorAlias",
name: "Parameter Editor Name",
isParameterEditor: true,
editor: {
view: "~/App_Plugins/My.ParameterEditor/ParameterEditorView.html"           
}
]
```
Should be:
```
propertyEditors: [
{
alias: "My.ParameterEditorAlias",
name: "Parameter Editor Name",
isParameterEditor: true,
editor: {
view: "~/App_Plugins/My.ParameterEditor/ParameterEditorView.html"
}
}
]
```
I've also updated the indenting to make this clearer, and match with the rest of the examples.
Thanks!
> Fix typo in package.manifest definition

- Add-ons/UmbracoForms/Developer/Prepping-Frontend/index.md
Made the world a bit more secure, and make sure that if people copy-paste the code won't have "Blocked content"-error messages in their console because their website is running https, but they're non-https scripts
> Changed reference to CDN from http to https

- Extending/Property-Editors/package-manifest.md
- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Grid-Layout/Grid-Editors.md
I've primarily added some information about how to define grid editors through `package.manifest` files instead of `/config/grid.editors.config.js`, since this appear to be missing in the current documentation. The pull request also fixes a few typos and similar here and there.
Since the two updated pages have related information, I've added links back and forth at relevant positions. There are tested to be working on GitHub, but I'm not sure whether they will work once uploaded to Our Umbraco. So these probably require a quick review by one of you guys at the HQ ;)
> Added information about package.manifest and grid editors

- Reference/Management/Services/ContentService.md
This line had an additional "the" in the docs. This has now been removed.
> Removed unused "the" from docs

- Umbraco-Cloud/Deployment/Migrate-Existing-Site/index.md
While I was following the guide during a migration of the existing site, I deleted the `data/Revision/` folder completely as step 15 suggests. However, the next step 16 (`echo > deploy-export`) would then fail.
When I put back an empty `data/Revision/` folder the deploy export would work fine.
So I think the instructions should clarify that the folder needs to stay as an empty folder, rather than deleting it.
> Deleting the folder itself causes the next step to fail, so empty it instead.

- Extending/Healthcheck/index.md
- Reference/Config/HealthChecks/index.md
Obviously only to be applied if and when the health check scheduler work carried out at the retreat is merged into core, perhaps for 7.7.  Which is under [this PR](https://github.com/umbraco/Umbraco-CMS/pull/1983).
> Added documentation for healthcheck configuration and scheduler

- Getting-Started/Setup/Upgrading/version-specific.md
It was left in the nuspec per http://issues.umbraco.org/issue/U4-10443
> `CookComputing.XmlRpcV2` actually removed in 7.7.2

- Add-ons/UmbracoForms/Installation/license.md
Mainly clarifies that the development domains does not include subdomains other than `www` as discussed earlier today [on twitter.](https://twitter.com/greystate/status/941652006099447809)
> Update license docs for Umbraco Forms

- Getting-Started/Design/Templates/index.md
As @RenderSection has a code example, I feel that @section should have
one too.
https://our.umbraco.org/documentation/Getting-Started/Design/Templates/#template-sections
> Add clear example for @section usage

- Umbraco-Cloud/Deployment/Cloud-to-Cloud/index.md
'Activity Log' and 'View Details' are not highlighted as they are not as important (or required) as "Deploy changes".
> Make deploy description match the GIF

- Extending/Section-Trees/tree-actions.md
- Extending/Section-Trees/trees-v7.md
Answered a forum post on what each letter corresponded to for User Permissions, thought this used to be written down somewhere?
If not there is a table of them in this Pull Request, or did this change in the new User Group stuff, @Shazwazza @andybutland?
> Add table of User Permission Codes

- Reference/Config/webconfig/index.md
Added information about how to set the umbracoVersionCheckPeriod key to never let the backoffice check for updates. By default Umbraco ships with a value of '7' is not true because this key is not present in the default installation.
> Update index.md on key umbracoVersionCheckPeriod 

- Umbraco-Cloud/Troubleshooting/Duplicate-Dictionary-Items/index.md
Added info on how to create "deploy-repairdictionaryids" in /data folder. 
I already had few customer running deploy-repairdictionaryids which is not a valid command.
> How to create `deploy-repairdictionaryids`

- Getting-Started/Setup/Requirements/index.md
Some non-tech people seem to have the understanding that Umbraco won't work in Safari.
> Add Safari to the list of browsers

- Tutorials/Creating-Basic-Site/index.md
Changing the title on the 'Create a Master Template' links for part 1 and part 2. 
Just adding an 'a' to both
> Changing the title on links

- Reference/Routing/URL-Tracking/index.md
Make it clear that the Redirect Url Management dashboard doesn't implement rewriting rules, but IIS Rewrites do, and point people to the information on configuring them.
> Update wording around implementation of rewriting rules

- Add-ons/UmbracoForms/Developer/Extending/index.md
When working with forms adding a custom setting was something I ended up not been able to find via the documentation instead I found other peoples examples, adding a link here may help others find this information more readily.
Matt
> Add a link to adding a type on Provider model

- Add-ons/UmbracoForms/Developer/Magic-Strings/index.md
ParsePlaceHolders extension method doesn't currently include Record fields.  To do that you need to use StringHelpers.ParsePlaceHolders(record, content)
> Update index.md - expand on documentation for ParsePlaceHolders

- Reference/Templating/Macros/Xslt/Using-XPATH/XPath-Examples.md
Removed the last output row of subject //Track\[@rating >= 4] because the rating is 1 and therefore is not  equal or higher as 4
> XPATH Examples: Wrong output result

- Tutorials/Starter-kit/Index.md
Add a link to the documentation repo and also a link to the guide on how to contribute.
Fixing issue #695
> Adding links to the Contribute section

- Reference/Querying/MemberShipHelper/index.md
The `GetCurrentMember` method in MemberShipHelper wasn't documented.
https://github.com/umbraco/Umbraco-CMS/blob/7ee510ed386495120666a78c61497f58ff05de8f/src/Umbraco.Web/Security/MembershipHelper.cs#L365-L377
> Document GetCurrentMember method in MemberShipHelper

- Reference/Querying/MemberShipHelper/index.md
The method `GetCurrentMemberId` wasn't documented.
https://github.com/umbraco/Umbraco-CMS/blob/7ee510ed386495120666a78c61497f58ff05de8f/src/Umbraco.Web/Security/MembershipHelper.cs#L379-L391
> Document GetCurrentMemberId method in MemberShipHelper

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Nested-Content.md
This angular filter allows to get the name of  item picked with a content picker as name template. This was also in original docs and the filter is present in the current core version
https://github.com/umco/umbraco-nested-content/blob/develop/docs/developers-guide.md#name-template
> Document ncNodeName filter

- Extending/Section-Trees/trees-v7.md
- Extending/Section-Trees/trees.md
- Reference/Config/trees/index.md
Updating the reference page for trees.config configuration file, to contain details of the trees.config, and linking through to this information from the extending trees section.
> Adding information in the reference section for the trees.config file

- Umbraco-Cloud/Frequently-Asked-Questions/index.md
The regular expression for blocking access to the backoffice contains an error which makes it easy to get around it.
The problem is that the rule only prevents access to https://site.com/umbraco but not https://site.com/umbraco/#/somerandombackoffice part.
The updated RegEx should be: (^umbraco/backoffice/(.*)|^umbraco($|/$))
> Updated backoffice rewrite rule

- Reference/Config/webconfig/index.md
The current description for umbracoDisableElectionForSingleServer isn't correct since it is not required for load balancing at all. In fact it's not required for anything at all, and if it is set it will disable load balancing from working. It is not a setting that generally should be configured.
> Updates description for umbracoDisableElectionForSingleServer since it is currently incorrect

- Umbraco-Cloud/Set-Up/Manage-Domains/Security-Certificates/index.md
SSL is not a thing any more, SSL is depracated, at best we could change "SSL" to "TLS" but the technical name for it doesn't matter very much. Let's stick with "certificate" as the regular term to use for this.
> SSL is deprecated and we shouldn't pretend like we support it

- Getting-Started/Setup/Install/permissions.md
Common question over what is the Application Pool Identity account, which is the default now rather than Network Service in IIS
> Add details of Application Pool Identity Account

- Reference/Security/index.md
I've added specified all the dependencies as requested by the obsolete overload. Additionally I've removed the difference in how the method is written in the two locations is appears.
> BackOfficeUserManager.Create overload obsolete

- Getting-Started/Setup/Install/system-requirements.md
We've updated the File Permissions page to reference the IIS APPPOOL\appPoolName ... so since permissions seem to be mentioned here too
> Mention IIS APPPool\appPoolName

- Extending/index.md
Technically the link still works, but the old URL will redirect the user, so we might as well just use the new URL.
> Fixed link

- Development-Guidelines/building-angular-project.md
Figured I'd write a link scanner for the Our documentation. While still in development, this is the first page that it discovered with broken links ;)
> Fixed links to NodeJS and Grunt

- Add-ons/UmbracoForms/Developer/Custom-Markup/index.md
- Add-ons/UmbracoForms/Developer/Extending/Adding-a-Fieldtype.md
- Development-Guidelines/Coding-Standards/index.md
- Development-Guidelines/Coding-Standards/jquery-guidelines.md
- Development-Guidelines/Coding-Standards/js-guidelines.md
- Development-Guidelines/building-angular-project.md
- Development-Guidelines/umbraco-web.ui-client.md
- Development-Guidelines/working-with-code.md
- Extending/Embedded-Media-Provider/index.md
- Umbraco-Cloud/Troubleshooting/index.md
Various changes to some more doc files post codegarden flight #1
> Cloud computing edits to the docs

- Extending/version7-assets.md
- Getting-Started/Setup/Upgrading/version-specific.md
The blog post may still be relevant, so I've fixed the two links referring to the same blog post.
> Broken link as Umbraco changed their blog URLs

- Reference/Management/Services/TreeService.md
There is no class called `ApplicationTreeService`, as the `ApplicationTreeService` returns an instance of the `IApplicationTreeService` interface. I've updated the link to reflect that.
I'm not totally sure whether the rest of the text might need some adjustment as well. But now at least the link works ;)
> Fixed broken link

- Extending/Backoffice-UI-API-Documentation/index.md
- Reference/API-Documentation/index.md
- Reference/index.md
See issue: https://github.com/umbraco/UmbracoDocs/issues/845 #845 
Essentially if you are within the documentation pages, and using the navigation there isn't any scent that would lead you to the auto generated / API documentation for C# or Backoffice UI
So this PR adds a couple of 'Landing Pages' that sign post the existence of the documentation to the reference and to the extending sections...
> Increase the visibility of the existence of the API documentation

- Reference/Templating/Mvc/views.md
I just discovered that it's not documented anywhere that when you're trying to use @Umbraco.Field() from within a partial you need to pass the context to it otherwise you will not get any value. Therefore I added this information and a basic example.
See my discovery if you have the time to read this reply - At first I actually thought it was not possible so had to correct myself - It's been a while...:-) 
https://our.umbraco.org/forum/using-umbraco-and-getting-started/92301-change-url-on-image#comment-291932
> Add example of @Umbraco.Field() method in partials

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Grid-Layout/Render-Grid-In-Template.md
I added some sub-headlines to divide the document into two sections and make it more clear that @CurrentPage.GetGridHtml() and @Model.Content.GetGridHtml() are obsolete and highlighted "Html.GetGridHtml()" and "Use @Html.GetGridHtml" in order to make it easier to quickly distinguish that this is the recommended way of doing things.
> Added sub-headlines

- Reference/Config/umbracoSettings/index.md
From looking at a forum post, I found that the source code for the security section in the umbracoSettings.config file has a couple of undocumented settings which can be set if needed:
Forum post: https://our.umbraco.org/forum/core/general/23192-How-to-have-multiple-Umbraco-instance-login-sessions-without-conflict
SecurityElement source: https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Core/Configuration/UmbracoSettings/SecurityElement.cs
This change is to add these settings into the documentation, and updated the introduction to the security section so that it doesn't mention how many settings there are, as I noticed it was also out of date.
> Adding auth cookie settings for umbracoSettings.config security section

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Date.md
Marked the dynamic example as being obsolete and added a text explaining that the dynamic approach is not the recommended one.
> Mark Dynamic as obsolete

- Tutorials/Creating-a-Custom-Dashboard/index.md
I propose updating the Egghead link to point explicitly at the AngularJS fundamentals course since it's currently only pointing to the egghead homepage. Can be confusing for people to find the AngularJS course instead of the Angular course so it's better to be explicit about it.
> Update egghead link

- Extending/Language-Files/index.md
I added an example showing how attributes can be localized, which is also described in the documentation of the <localize> directive here https://our.umbraco.org/apidocs/ui/#/api/umbraco.directives.directive:localize
> Add example of localize attribute

- CONTRIBUTING.md
Untill now I have not needed to clone the repository in order to create PR's for the documentation. But now that I need to do a little bigger contribution (adding a new page etc.) I thought it would be better to clone the repo. Then I realized nothing is currrently mentioned about how to keep the fork in sync with the main repository like it is here on the Core repo: https://github.com/umbraco/Umbraco-CMS/edit/dev-v7/docs/CONTRIBUTING_DETAILED.md - So thought that I would add some details about it here too heavily inspired by the core text.
> Reuse a bit of the repo instruction from core

- Reference/Searching/Examine/quick-start.md
The recently added example for the fluent API had an error with the ordering. This should be done on the search query, not the results - which doesn't have an OrderBy method or extension.
This was introduced in https://github.com/umbraco/UmbracoDocs/commit/13212de060d35ebbbe98edaa417338083436b636#diff-d142ee10fd27747e8fd653df9b3b0ef1
Reference material: https://github.com/Shazwazza/Examine/wiki/Sorting-results
> Fixing example in Examine Fluent API

- Reference/Templating/Mvc/views.md
Added a variation of the "standard" about the dynamic approach being obsolete. Have not added "Obsolete" to the headline since it will be awfully long.
Could perhaps just switch "(dynamically)" with "(obsolete)" instead to highlight it already in the headline and then skip the bold "Attention" text?
> Add a note about @CurrentPage being obsolete

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Content-Picker2.md
I'm thinking it would make sense to link to the UDI documentation in case people hit this page wondering what UDI is in case they never heard about it before.
> Adding link to UDI documentation

- Reference/Querying/Udi.md
And by official definition I mean...I don't think anyone has ever agreed officially what it's short for, right? We just call it a UDI because it sounds like something that is unique for the way Umbraco identifies nodes...sort of, right? :)
> Added a note about UDI not having an official definition

- Getting-Started/Setup/Upgrading/version-specific.md
Since the release of 7.7.0 the e-mail has been used for logging in instead of the username but it does not seem to be mentioned anywhere so thought I would add a section about it and mention how to keep using the username instead if the change is causing too much confusion when people do upgrades.
> Mention that credentials usage has changed

- Umbraco-Cloud/Databases/index.md
I couldn't find this mentioned elsewhere in the docs, so I have added some basic details about this.
I have usually used this approach:
---------
Restore using LocalDB on Umbraco Cloud (.mdf instead of .sdf local db file):
C:\Windows\System32\inetsrv\config
Ensure loadUserProfile="true" and setProfileEnvironment="true".
https://blogs.msdn.microsoft.com/sqlexpress/2011/12/08/using-localdb-with-full-iis-part-1-user-profile/
> Add details about configurating LocalDB

- .gitignore
I found a few weird temp files were visible in Git after solving a merge conflict.
I've added a `.gitignore` file to prevent these from showing up in future.
Surprised this wasn't here already!
> Introduce gitignore file

- Add-ons/UmbracoForms/Developer/Magic-Strings/index.md
Discovered the hard way (and after searching a lot) that you cannot use dots in a sessionname for some sort of reason.
> Added some documentation about using Session-variables

- Tutorials/Starter-kit/Lessons/2-Add-a-Blog-Post-Publication-Date/part-3.md
The current example results in the following error System.Web.HttpCompileException (0x80004005): c:\Git\Sites\Umbraco-7-11-1\Views\MacroPartials\LatestBlogposts.cshtml(21): error CS0428: Cannot convert method group 'Count' to non-delegate type 'double'. Did you intend to invoke the method?
I'm no expert in LINQ but when adding .ToList() it works like it should. The code that should be replaced with the example from step three also converts the output using .ToList() - .Take(3) should also not be necessary to add since paging is already setup, which listes 3 posts pr. page.
I noticed this issue when I tried to re-create the error Nic got here https://our.umbraco.com/forum/using-umbraco-and-getting-started/93182-error-editing-partial-macro-in-the-umbraco-starters-guide - I have not heard …
> Correcting the code example in step three

- Add-ons/UmbracoForms/Developer/Prepping-Frontend/index.md
- Add-ons/UmbracoForms/Developer/Rendering-Scripts/index.md
- Add-ons/UmbracoForms/Developer/Themes/index.md
This addresses the need for an extra link to get the _Themes_ version of the information supplied here about rendering the Forms scripts when dependencies are rendered at the bottom of the page.
I opted for the Themes link first - open to discussions whether that makes sense :)
Closes #916  
Closes #948
> Issues 916 + 948

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Nested-Content.md
The NC item label documentation needs updating after the merge of PR [2457](https://github.com/umbraco/Umbraco-CMS/pull/2457/); the ncNodeName filter now supports media and members too, and the new ncRichText filter is missing from the docs.
> Update item label documentation

- Reference/Management/Services/MemberService.md
Added the methods `GetCount` and `GetPagedXmlEntries` to documentation.
> Update docs with missing methods in MemberService

- Umbraco-Cloud/Getting-Started/Baselines/Configuration-files/index.md
Examples include common transforms that has been seen done by a few project, where the changes was done directly in the web.config, but should rather have been done in a transform file
This is to make the process for when we are doing baseline upgrades more clear, and to help with some default config transforms
connects to https://github.com/umbraco/Concorde.BaselineChild.Service/issues/9 (requires HQ access)
> Updates baselinechild config with examples

- Add-ons/UmbracoCourier/Architecture/DataResolvers.md
- Add-ons/UmbracoCourier/Architecture/Provider-Configuration.md
- Add-ons/UmbracoCourier/CommonIssues.md
- Add-ons/UmbracoCourier/Developer/DataResolvers.md
- Add-ons/UmbracoCourier/UsingCourier.md
- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Grid-Layout.md
- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Grid-Layout/Settings-and-styles.md
- Getting-Started/Backoffice/index.md
- Getting-Started/Data/Data-Types/default-data-types.md
- Getting-Started/Setup/Upgrading/version-specific.md
- Reference/Config/umbracoSettings/index.md
- Reference/Templating/Macros/Xslt/Snippets/Tag-cloud.md
- Reference/Templating/Masterpages/umbracoimage.md
- Tutorials/Creating-a-Property-Editor/index.md
- Tutorials/Creating-a-Property-Editor/part-2.md
- Umbraco-Cloud/Deployment/Local-to-Cloud/index.md
- Umbraco-Cloud/Troubleshooting/Deployments/Structure-Error/index.md
- Umbraco-Cloud/Troubleshooting/FAQ/index.md
I have replaced all uses of the word 'datatype' with 'data type'.
Microsoft refers to them as data types [https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/data-type-summary](https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/data-type-summary)
And if you [google 'Umbraco datatype'](https://www.google.co.uk/search?q=umbraco+datatype) it says, Did you mean 'Umbraco data type'
> - renamed all instances of datatype with data type.

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/index.md
I have added `Umbraco.MemberPicker2` to the list, which is the default Member Picker in new Umbraco projects.
> Add docs for Umbraco.MemberPicker2

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Related-Links.md
I am not sure who named the new one, but as this is marked as obsolete it would make sense that we highlight clearly what people should now be using instead!
> Adding a link to the "new" Related Links data type

- Development-Guidelines/Coding-Standards/jquery-guidelines.md
- Development-Guidelines/Coding-Standards/js-guidelines.md
- Getting-Started/Setup/Install/install-umbraco-with-microsoft-webmatrix.md
- Getting-Started/Setup/Server-Setup/Load-Balancing/flexible.md
- Getting-Started/Setup/Server-Setup/Load-Balancing/traditional.md
- Reference/Config/ExamineIndex/index.md
- Reference/Config/umbracoSettings/index.md
- Reference/Searching/Examine/index.md
Picked up the few remaining areas (from PR #995) where "back-office" is used, it was only those that appear with the hyphen that were left, but now should all be in-line with the CMS, using "backoffice".
> Renamed back-office to backoffice.

- Umbraco-Cloud/Troubleshooting/Deployments/Structure-Error/index.md
- Renaming 'entity types' to 'entity' where it should be entity.
- Using 'alias' instead of 'unique identifier' since unique identifier is really the UDA/guid for these entities whereas the alias is obviously not unique when a collision occurs. It can be a bit confusing so its better to just stick with saying alias.
- Explaining a bit about extraction and elaborating on other things.
> Clearing up some things on structure errors.

- Getting-Started/Backoffice/index.md
Making each section consistent. Some had read more links, some just had heading links. I've added both on all sections where a child page was available. I've also changed some of the wording e.g. document type is now Document Type. Again, this was used in some paragraphs but not all.
> Update Getting Started landing page

- Reference/Events/EditorModel-Events.md
The editor model events are supported since 7.4 this should be clear from the documentation
> Added version number since when editor model events are supported

- Contribute/Markdown-Conventions/index.md
- Contribute/Pull-Requests/pr-through-a-fork.md
- Contribute/adding-metadata.md
- Contribute/file-naming-conventions.md
- Contribute/github-issues.md
- Contribute/index.md
* Move content to different files (PR-through-fork & labels)
* markdown-lint all the things
* move files about YAML & multiverion docs from root to the `Contribute` folder
> Make the index file lighter by splitting information into different files

- Development-Guidelines/building-angular-project.md
See the [Documentation page][docs] for where the link is failing.
-----
Thinking about this, would it be better to use one of the following instead (as per [guidelines])?
- `[nodejs.org](https://nodejs.org)`
- `https://nodejs.org`
[docs]: https://our.umbraco.com/documentation/Development-Guidelines/building-angular-project#nodejs
[guidelines]: https://github.com/umbraco/UmbracoDocs#external-links
> Fix link to NodeJS

- Reference/Events/determining-new-entity.md
Hashed should be removed from headings on this documentation page: https://our.umbraco.com/documentation/reference/events/determining-new-entity
> Remove hashed from headings

- Extending/Language-Files/index.md
Added in the three missing languages from this page, from the latest Umbraco version. These were:
- Chinese (Taiwan)
- Czech
- Turkish
Also made a couple of tiny text updates while on the page.
> Added in new languages and small text updates

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Grid-Layout.md
Fixed issue around Configuring Grid layout  link on the page
https://our.umbraco.com/documentation/getting-started/backoffice/property-editors/built-in-property-editors/grid-layout
> Issue around the link to "Configuring grid layout" fixed

- Reference/Management/Services/LocalizationService/Retrieving-languages.md
Per a discussion I had with @marcemarc a few months back, we decided that we should be using *retrieving* rather than *referencing*. It seems that I back then only renamed the file, but didn't update the title of page **#H5IS**
> Title should reflect the file name

- Reference/Templating/Modelsbuilder/Using-Interfaces.md
- Reference/Templating/Modelsbuilder/index.md
This adds a page to the ModelsBuilder section (in Reference/Templating) about using the interfaces ModelsBuilder creates when rendering content.
Work in progress, but adding the page makes it easy to add even more use-cases and examples :)
Closes #1151
> Start docs for using Modelsbuilder Interfaces

- Reference/Management/index.md
They should both use capital letters to match the official spelling.
> Should be ".NET" and "C#" (AKA upper case)

- Reference/Querying/UmbracoHelper/index.md
I removed the children part for the non-strongly typed version so the example works too
> Remove the children part as well here

- Reference/Management/Services/ContentTypeService/Index.md
- Reference/Management/Services/ContentTypeService/Retrieving-content-type-containers.md
- Reference/Management/Services/ContentTypeService/Retrieving-content-types.md
Added some information about retrieving content types and content type containers.
I have a general question about headlines. Should it be something like **Getting a single content type** or **Getting a Single Content Type**? Or something else?
Anyways - I've used fenced code blocks as these is now supported by Our (YAY :tada:). Also, with https://github.com/umbraco/OurUmbraco/pull/332 the documentation should look something like below:
>  Updated the documentation for the content type service

- Reference/Querying/IPublishedContent/ExtensionMethods.md
- Reference/Querying/IPublishedContent/Properties.md
- Reference/Querying/IPublishedContent/index.md
I have added the GetKey() extension method to the IPublishedContent page. I was not sure whether we need to create a new .md file for extension methods or just have it alongside properties give the extension method is used to retrieve the Guid of IPublishedContent.
Poornima
> Added the GetKey() extension method to IPublishedContent

- README.md
to the dedicated page in the 'Contribute' section
As per this issue:
https://github.com/umbraco/UmbracoDocs/issues/1238
> Removing the markdown guideslines in readme.md and replacing with a link

- Extending/Content-Apps/index-v8.md
There is probably a lot of work in updating old documentation pages with fenced code blocks, but there aren't really that many v8 pages yet - so I've now fixed the first one.
With fenced code blocks also comes syntax highlighting, which comes with a number of different issues for the JSON examples in this article. Per the JSON specification:
1. property names should be enclosed with double quotes
2. string values shopuld be enclosed with double quotes
3. comments are not part of the JSON specification
for both 1. and 2., no quotes or single quotes make the JSON invalid. As such, GitHub's syntax highlighting looks like as shown here:
So the big question is now: how much should we actually care about this? While some of the examples are invalid according to the JSON specification, JSON.net …
> Content Apps: added fenced code blocks for syntax highlighting

- Implementation/Data-Persistence/index.md
Remove unneccesary apostrophes - SurfaceControllers and UmbracoApiControllers are plural, not possessive, so no need for apostrophe.
> Remove apostrophes

- Reference/Querying/UmbracoHelper/index.md
Changed the line introducing the UmbracoHelper examples - had a grammatic error, so have edited to make the language more direct and succinct. No need to be overly verbose.
> Grammar changes - make it more succinct

- Tutorials/Starter-kit/Index.md
Found another one - `a content editors'` should be `a content editor's`, as the `a` makes it singular but `editors'` is the possessive plural. Since it's possisive singular, we want `editor's` instead
> Errant apostrophe

- Extending/Health-Check/index.md
The second code block isn't closed and so includes the next few headings of text, making it hard to read
> Healthcheck info - Missing end of coding block indication '''

- Umbraco-Cloud/Set-Up/Config-Transforms/index.md
We set `debug` to `true` and `CustomErrors` to `Off` only on Cloud environments. 
If you clone it down locally, you'll have Debug set to RemoteOnly and Compilation to False.
> Updated Debug and CustomErrors section.

- Reference/Querying/UmbracoHelper/index-vpre-730.md
- Reference/Querying/UmbracoHelper/index.md
The 'obsolete' versions of MemberHasAccess and IsProtected were displayed, there are now versions when you only have to pass in the path of the node (as that includes the id anyway!)
> Update Member helper methods on UmbracoHelper

- Reference/Templating/Modelsbuilder/Install-And-Configure.md
Changed a couple of instances where the button to click was ambiguous.
> specifies which button causes the rebuild action

- Extending/Section-Trees/tree-actions-v8.md
- Reference/Templating/Masterpages/umbracoitem-v8.md
This commit adds new v8 documentation that fixes the spelling mistakes in the source code, the issue is: https://github.com/umbraco/UmbracoDocs/issues/1303
This should only be merged in when the following core issue is merged:
https://github.com/umbraco/Umbraco-CMS/issues/4060
> Fixing the Separator typos in the help documentation

- Reference/Templating/Mvc/views.md
The first code example was indented and some of them were not formatted as c# making it inconsistent to look at.
> Aligning code examples

- Umbraco-Cloud/Set-Up/Config-Transforms/index.md
The code sample currently just appears as a black box where it's not possible to see the code. Adding the xml keyword should fix this.
> Add missing xml keyword to code formatting

- Getting-Started/Setup/Install/install-umbraco-manually.md
When skimming the page I noticed that there were two notes, which is actually suitable for being marked up as warning and note - I also removed the `` around the hosts file example.
I will add an issue about this piece of documentation needing to be updated to showcase using VSCode as the easy way and let people know that Webmatrix has been sunset by Microsoft.
> Minor adjustments to formatting

- Reference/Config/BaseRestExtensions/index.md
I have added some nicer code formatting for this piece of documentation and I have also added a warning about this piece of documentation only being relevant for Umbraco 6. And I have also added the YAML meta data about the versions.
Even thought the /Base concept has been around since... v3 I think it seems that the way to use /base changed in v6 where the restExtensions.config was renamed to baseRestExtensions.config also containing another syntax, which is the one referenced in this piece of documentation.
> Update code formatting and add version and a warning

- Umbraco-Cloud/Frequently-Asked-Questions/index.md
I changed the number of custom hostnames to 15 instead of 20 since we are not able to add more than 15 in the cloud interface.
Taken from cloud:
Manage hostnames
You can add up to 15 custom hostnames for each environment.
> Changed the number of custom hostnames to 15

- Tutorials/Creating-Basic-Site/Document-Types/index-v8.md
... mentioning that if none of the doc types are marked as `Allow as root`, all of them will be allowed to be created at root level.
> Adds a note block

- Reference/Routing/custom-controllers.md
The previous snippet has an example of a custom model, with a constructor that takes an IPublishedContent. This snippet utilized a custom model, but without using the constructor that was made in the previous example.
The proposed change will make the code more copy-pasteable.
> Correct initialization of custom model

- Extending/Section-Trees/Searchable-Trees/index-v7.md
- Extending/Section-Trees/Searchable-Trees/index-v8.md
- Extending/Section-Trees/Searchable-Trees/index.md
Updated 'remove ISearchableTree i' example to use a Composer - see issue: https://github.com/umbraco/UmbracoDocs/issues/1579
Not sure whether to tackle these all in one PR at the risk of blocking / conflicting with other updates, or to just pull them one at a time, when find a moment to update them...
> Update Application Starting example to use a composer for V8

- Reference/Events/EditorModel-Events/index-v7.md
- Reference/Events/EditorModel-Events/index.md
need to check examples work
(when we switch the automated generated docs to be for V8 we should update the overview of model sending classes here to instead point to autogenerated definitions
> V8 - Update EditorModelEvents

- Implementation/Composing/index.md
I followed this guide and saw it had the wrong name for the Custom Component.
> Incorrect reference in example

- Reference/Management/Services/UserService/Create-a-new-user.md
A colleague of mine pointed out that the text should probably read "...administered for the specific user, but rather for the user group(s)..." rather than "...administered for the specific user group, but rather for the user group(s)..." since permissions are now administered on the group level and not the user level, right? :-)
> Change "user group" to "user"

- Getting-Started/Backoffice/Sections/index.md
Capitalized the remaining instances of the proper name "Backoffice". Removed unnecessary word "do".
> Fix typos, remove word, capitalize Backoffice

- Implementation/Composing/index.md
> Fix typo in collection name: FilderedControllerFactory

- Reference/Routing/Authorized/index.md
There is missing first quotation mark at ->   /backoffice/cats/{action}/{id}"
> Missing quotation marks around the string fragment

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Tags/index.md
I found the page lacking a link to the UmbracoHelper reference where you can learn more on querying and working with the tags. This makes the current page frustrating because it shows up in search more prominently but misses this information.
> Add link to reference (more on tags)

- Implementation/Unit-Testing/index.md
Hi. I've corrected a few spelling mistakes on my original PR for the Unit Testing section of the Umbraco docs.
NOTE: I noticed that the last link in the bottom of the page on the documentationpage on Our does not work. First I thought it has a mistake in my PR but the source code looks fine, but the link gets wonky on our. https://our.umbraco.com/documentation/Implementation/Unit-Testing/. Please let me know how I can fix this.
> Fixed spelling mistake

- Getting-Started/Code/Debugging/Logging/index.md
The existing example only worked with some pre-release versions of v8. GetLogger was moved into CoreRuntime before v8.0 was released
> Update GetLogger example so that it works

- Umbraco-Cloud/Deployment/Content-Transfer/index.md
- Umbraco-Cloud/Deployment/Deploy-Settings/index.md
- Umbraco-Cloud/Deployment/Restoring-content/index.md
- Umbraco-Cloud/Deployment/Umbraco-Forms-on-Cloud/index.md
Forms will on Umbraco Cloud be handled as content / media instead of meta data.
I've updated the article to reflect this.
Also updated the "Content Transfer" article to include Umbraco Forms data.
> Updated article about Forms on Umbraco Cloud

- Getting-Started/Data/Defining-content/index.md
Some of the labels in the documentation were using old names.
> Updated label names as per Umbraco 8.0.2

- Extending/Dashboards/index.md
Dashboard removal import for `Umbraco.Core.Components` was incorrect and should be `Umbraco.Core.Composing`.
> Corrected import for Umbraco.Core.Composing

- Implementation/Services/index.md
This is very much WIP, and may suit rather a tutorial format, but my gut feeling is having one place to show off by example the different nuances of injecting services that people will run into when implementing a typical site would be useful.
Particular keen to suggest people follow the pattern of creating their own custom services for implementation logic, instead of writing code in Views or Controllers...
but not sure how much of that is my own preference, and whether this should be re-centred around using ModelsBuilder or if that is a separate 'good practice' outline...
Some of the examples could be improved upon, and need to do a sense check of wording...
but wanted to know if this seemed like a good idea etc - was in the right place - should be 3 different pages etc
> Add lots of examples around using Services with DI

- Getting-Started/Backoffice/Sections/index.md
- Getting-Started/New-in-V8.md
Added notes about Dictionary Items, which have been moved from Settings to Translation section in Umbraco 8.
> Umbraco 8: Dictionary items have been moved

- Reference/Mapping/index-vpre8.1.md
- Reference/Mapping/index.md
Initial documentation for UmbracoMapper, a new mapping tool replacing AutoMapper in Umbraco 8.1.
https://github.com/umbraco/Umbraco-CMS/pull/5087
> Add documentation about UmbracoMapper

- Getting-Started/Setup/Upgrading/version-specific.md
I updated the update instructions for 8.1 because they were unclear. They stated that we need to update `PropertyValueConverterBase` to `IPublishedPropertyType`. That's not true. Within this class the reference to `PublishedPropertyType` needs to be updated to `IPublishedPropertyType`.
> Updated the update instructions for 8.1

- Umbraco-Cloud/Set-Up/Umbraco-Latch/index.md
The formatting of the rewrite condition resulted in a black block and the condition also didn't correctly escape the dot, meaning it matched any character!
> Fixed rewrite condition

- Umbraco-Cloud/Getting-Started/Migrate-Existing-Site/index.md
I added info on changing the existing user email addresses if they are the same as a cloud user. This prevents a situation of confusion of what user someone is using. Happened to me yesterday and also locked out my colleague today.
If the wording isn't clear please let me know what you'd like to see different.
> Email clash when adding cloud user

- Reference/Searching/Examine/Quick-Start/index-v7.md
Amended v7 Fluent API example to convert ISearchResults to IEnumerable<IPublishedContent> so Url and Name are exposed.
Raised on forum https://our.umbraco.com/forum/using-umbraco-and-getting-started/98150-fluent-api-following-documentation-errors
> index-v7.md Examine Fluent Api example doesn't work

- Umbraco8FAQ.md
I have updated how long you can create Umbraco 7 projects on Umbraco Cloud.  The previous date was August 31st. We are pushing the cutoff date for new Umbraco 7 projects on Umbraco Cloud to the end of 2019 due to this blogpost
https://umbraco.com/blog/update-on-umbraco-81/
> I have updated the date for Umbraco 7 projects

- Contribute/Pull-Requests/index.md
I was originally thrown by the term 'often use' implied it was a blog like tutorial like 
https://umbraco.com/blog/the-umbraco-issue-tracker-process/
But I realised that was for CMS and not docs specifically :)
Let me know if I can improve this.
> Fixed broken link to UmbracoDocs labels

- Tutorials/index.md
I was going to create a content app tutorial but there already is one :) So just linking to it from tutorials section incase people are expecting it to be there with other tutorials.
> Adding content app tutorial link

- Getting-Started/Design/Rendering-Content/index.md
A tiny typo fix on the more `info -> querying` link
> updates a link with `//` to `/`

- Reference/Routing/Request-Pipeline/outbound-pipeline-vpre.8.1.md
Fixes missing quote and typo in variable name
> Fix typos in code examples

- Extending/Database/index.md
Without [PrimaryKeyColumn(AutoIncrement = true, IdentitySeed = 1)], there is no Primary key created in the table, so you cant insert new records to that table
> Fixed small typo and added PrimaryKeyColumn

- Getting-Started/Setup/Upgrading/migrating-to-v8.md
Just a simple reminder to go through the Umbraco 7 site for obsolete  Data Type properties before continuing with the migration, as it will otherwise fail. Could save someone from a headache while migrating...
> V8 Migration - Added information about obsolete Data Types

- Reference/Querying/IPublishedContent/IsHelpers.md
This adds the missing `modulus` parameter to the `.IsModZero()` and `.IsNotModZero()` helpers.
Also cleaned up the descriptions a bit and added information about the scenario where you've supplied a single string argument to an IsHelper and the condition evaluates to `false` - where an empty string gets returned.
Closes #1830
> Adds missing parameter to *ModZero IsHelpers

- Getting-Started/Setup/Server-Setup/azure-web-apps.md
The instructions for using Examine pre v0.1.80 with Azure were missing the second property which is required to use the 'Sync' behaviour.
I have added this missing property in.
> Added missing property to ExamineIndex instructions

- Reference/Templating/Modelsbuilder/Builder-Modes.md
There are currently two Models Builder extensions in the Visual Studio marketplace. One is deprecated, and there shouldn't be used.
This change makes sure to link directly to the new and correct Visual Studio extension.
> Added link for the Visual Studio extension

- Umbraco-Cloud/Frequently-Asked-Questions/index.md
**What**
Adding a new outgoing IP address to the the rewrite rules section.
**Why**
This is our only documentation where the end users can potentially find the outgoing IP addresses that websites are reaching out from.
**Suggestion**
We could think about this change as beloning to a a new networking or a security section where it would be much easier to find networking rules, AP addresses, firewall rules for sql, basic authentication and such.
> New dedicated workers public IP address

- Umbraco-Cloud/Set-Up/Team-Members/index.md
Clarified and added some info to this page: 
https://our.umbraco.com/documentation/Umbraco-Cloud/Set-Up/Team-Members/#team-member-permissions-in-the-umbraco-backoffice
In order to help better define the difference between Team Members and Backoffice Users, I included a link on the Team Members page to the Users page in the documentation.
> Updated Team Members info

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Color-Picker/index.md
The div style requires the # symbol in front of @hexColor to display the colour correctly.
> Update to Color Picker documentation

- Reference/Cache/examples/index.md
Adds a list of examples (currently just the one) to the caching folder.
This is to prevent a 404 that will otherwise occur.
> Add index to cache example folder

- Reference/Templating/Modelsbuilder/Builder-Modes.md
The section explained how to run the *Custom tool*, which was for the old Visual Studio extension. The new extension works slightly different, so I've updated the docs accordingly, as well as included a few more details.
> Models Builder - Updated the section about API mode

- Development-Guidelines/working-with-code.md
This [page](https://our.umbraco.com/documentation/Development-Guidelines/working-with-code) has same content twice, the first has some formatting issues:
This PR should hopefully fix that :)
> Page had duplicate content and formatting issues

- Reference/Events/ContentService-Events.md
The example component throws a `NotImplementedException` when terminating. This could cause other components to not terminate, as exceptions aren't caught while iterating through the components:
https://github.com/umbraco/Umbraco-CMS/blob/853087a75044b814df458457dc9a1f778cc89749/src/Umbraco.Core/Composing/ComponentCollection.cs#L37-L51
> Remove NotImplementedException from Terminate

- Getting-Started/Setup/Server-Setup/azure-web-apps.md
Config settings for Umbraco XML cache file and other TEMP files differ depending on Umbraco version used. Proposed change clarifies only one entry is required if on version 7.7.3+
> Clarifying Umbraco version settings

- Getting-Started/Code/Umbraco-Services/index.md
- Reference/Events/MediaService-Events.md
- Reference/Routing/Authorized/index.md
- Reference/Routing/custom-routes.md
This removes the remaining `NotImplementedException`s thrown in example components, as described in PR https://github.com/umbraco/UmbracoDocs/pull/1956.
> Removed remaining NotImplementedException from Terminate

- Reference/Routing/Request-Pipeline/outbound-pipeline.md
There was some code that was missing the code identifier so it was appearing as text rather than code.
> Put code in a code block

- Reference/Using-Ioc/index-v7.md
This is by far the easiest way to configure IoC in Umbraco v7. I'm not trying to plug the package I created or anything, it's just that all of the hard work is already done for people and it's super easy to use.
> Adds link to our.umbraco.ioc package

- index.md
Hello,
I was getting some links to contribution info for our Glasgow meetup tomorrow and realised this link on docs index page just links to the repo and not contributing info. I have updated it to link to contribution guidelines.
Thanks,
Carole
> Updating contribution link

- Reference/Searching/Examine/Quick-Start/index.md
As raised by a user on Slack, the existing introduction in the Examine Quick Start is misleading.
Currently it states 3 internal indexes ship with Umbraco and none of them should be used for front-end searches, but later contradicts itself and says to use the external index. Further, there are use cases for searching the member index on a website front-end.
Hopefully this clears things up - I tried to keep things as simple as possible but happy with advice on how the language can be improved!
> Clarifying purpose of core indexes in Examine Quick Start

- Getting-Started/Code/Source-Control/index-v7.md
- Getting-Started/Code/Source-Control/index.md
- Reference/Management/Services/LocalizationService/Retrieving-languages.md
- Reference/Management/Services/UserService/Index.md
I feel cheap for doing this, but it had to be done!
I've cleaned up the last remaining references to the legacy `our.umbraco.org` links in the source code, and updated them to the new `our.umbraco.com` domain.
I went a little nuts and did this for all the other repos too 🙈(sorry)
* https://github.com/umbraco/OurUmbraco/pull/491
* https://github.com/umbraco/Umbraco-CMS/pull/6695
> Updating references to our.umbraco.org

- Getting-Started/Backoffice/Sections/index.md
In Umbraco 8.2 the Translation section is by default accessible by users with admin access - https://github.com/umbraco/Umbraco-CMS/issues/6359
I've removed notes about both dictionary items and the Translation section.
Also added a link to the "Users" article, where permission on access to the sections is set.
> Update Sections article

- Extending/Content-Apps/index.md
There is a PR open at core for introducing content apps on members as well. There is discussion going on how big this breaking change is. 
The discussion is mainly sparked because this will break the C# Content app factory code example. Because this throws a exception when the item is not a media or content item. It would have been better to return null. 
But that would make the entire switch statement look strange. So I changed the example a bit to only show the app when on content items.
I also made clear from the description that content apps can be used on media as well
> Make C# app factory sample non breaking 

- Development-Guidelines/Coding-Standards/jquery-guidelines.md
- Development-Guidelines/Coding-Standards/js-guidelines.md
- Development-Guidelines/test-driven-flow.md
Corrected some grammatical mistakes and typos in documentation for development guidelines, as well as fixing capitalization errors to ensure consistency of terms.
> Fixed errors in development guidelines

- Reference/Querying/DynamicPublishedContent/Collections.md
Helping out with the issue #1875 
v8 does not support DynamicPublishedContent, hence removing.
> Removed needsv8Updatefrom DynamicPublishedContent-Collections

- Tutorials/Creating-a-Property-Editor/index.md
Signed-off-by: doomswatter <44559839+doomswatter@users.noreply.github.com>
I added the link to the Property Editors page after the first block of code containing "assetsService", and again at the end of the article.
Reference Issue #1790
> docs: add link - issue#1790

- Extending/Content-Apps/index.md
Default notification badge (when 'type' not set) uses Umbraco-blue, it's no longer turquoise.
> Update badge default color

- Umbraco-Cloud/Set-Up/Umbraco-Latch/index.md
Added note that describes what to do when LATCH isn't able to configure a valid SSL-certificate because of an active IPv6 address.
> Update "Umbraco Latch" document

- Extending/FileSystemProviders/Azure-Blob-Storage/index.md
The container key was missing from the security.config. Without that imageprocessor won't work with the blobstorage.
> Added missing key to make imageprocessor work again

- Reference/Templating/Mvc/views-v7.md
- Reference/Templating/Mvc/views.md
Lots of changes here. I've tested the snippets and replaced (or straight up removed) the ones that were no longer working in v8. While I've tried to explain in full how we access property data in v8, I'm worried I may have wandered into modelsbuilder territory. I did try doing all this on a clean install where I hadn't set it up though so hopefully I've avoided that. I hope this helps some!
> Updating MVC views file for v8 to get rid of the old Umbraco.Field 

- Reference/Routing/Request-Pipeline/IContentFinder.md
…
see https://github.com/umbraco/Umbraco-CMS/issues/5290
The convention to find urls via /urltocontent/alttemplatealias has been secretly dropped in V8.. just a note here of how to add it back in, following numerous forum questions!
> Update IContentFinder add a note about removal of ContentFinderByUrlAndTemplate in V8

- Reference/Events/Application-Startup.md
This adds the example code described in issue https://github.com/umbraco/UmbracoDocs/issues/1974, so it's easy to get started with custom events (without having to read the whole composing page).
> Add application startup 'Getting started' example

- Reference/Config/umbracoSettings/index.md
I fixed a typo in the security section there was a "t" missing in "the" after 7.1.5
> Fixed a typo

- Getting-Started/Setup/Server-Setup/azure-web-apps.md
These updates remove the FCN reference since that is not really relevant anymore, moves up the recommended configuration settings to make it more clear and adds the disabling overlapping appdomains setting. This is all relevant for both v7 and v8
> Updated docs for hosting on Azure

- Reference/Searching/Examine/examine-events.md
This page code does not get syntax highlighting with the ```cs, which also create uncompiling code in the ExamineComposer section, since the type paramter is not rendered on Our.Umbraco.
The code in the docs on Our does not combile, since ComponentComposer requires 1 type argument. 
Currently if you code and paste the ExamineComposer on this page (https://our.umbraco.com/documentation/Reference/Searching/Examine/examine-events) into your code, you will get these two error: 
- Using the generic type 'ComponentComposer<TComponent>' requires 1 type arguments
- 'ExamineComposer' does not implement interface member 'IComposer.Compose(Composition)'
However by using ```c# like all the other pages, we should both get syntax highlighting and hopefully also the missing type paramter.
> Code snippets does not get syntax highlighting.

- Tutorials/Creating-Basic-Site/Creating-Your-First-Template-and-Content-Node/index.md
- Pulled the markup inline with the previous tutorial page
- Added a tip for naming pages
- Added some punctuation and removed leading text to make some paragraphs easier to read.
> Updated markup and text improvements

- Getting-Started/Code/Debugging/Logging/index.md
The last word in the sentence “dashboard” does not end with a dot also there is no new line before the badges, which makes it look wonky on mobile device. See screenshot: https://paste.pics/e0c1c15790f75eaacdfe87392dd94b2d
> Logviewer apps on newline.

- Reference/Searching/Examine/examine-events.md
Instead of specifying the "ExternalIndex" string in the TryGetIndex method, use the Constants.UmbracoIndexes.ExternalIndexName.
> Change hardcoded index name to Constant.

- Umbraco-Cloud/Troubleshooting/troubleshooting-portal.md
Possibly the worlds smallest PR? Missing ‘a’ makes the sentence “You’ll need to wait bit” a little wired. :)
> Missing ‘a’ in sentence about failing deployment.

- Add-ons/UmbracoForms/Developer/Custom-Markup/index.md
Added a few notes to make it clear that conditional fields won't be shown when the criteria are met unless they have an ID on them.
> The ID is required for conditional fields

- Umbraco-Cloud/Cloud-API/index.md
Plan terminology has since changed yet the accepted variable names still remain. Added a note to the documentation to inform the user
> Update plan terminology information in Cloud API docs

- Getting-Started/Data/Data-Types/default-data-types.md
If you input a long string value into a "regular" Label (string) then you will get an error when you try to save & publish saying: "Unable to publish - String or binary data would be truncated.". This was easily fixed by changing the value type from Label (String) to Label (Long string). 
Would have been nice to find information about in the docs, hence this PR. :)
Cheers!
> Added info about Label (Long string).

- Reference/Common-Pitfalls/index.md
The example text for Singleton accessors is missing its closing _ for making the text italic.
> Missing closing _ in example.

- Reference/Language-Variation/index.md
Had a question about this today and couldn't find anything about it. Here is a small explanation and example of using it. 
Have created a new section under reference called `Language-Variation`, feel free to move it somewhere else.
> Add docs on IVariationContextAccessor

- Extending/Content-Apps/index.md
I created a PR to make it possible to set content app notification badges through a content app factory. This will be part of 8.3
This PR is the documentation for that functionality.
Dave
> Added docs about setting notifications badge through content app factory

- Extending/Packages/Package-Actions/custom-package-actions.md
- Reference/Language-Variation/index.md
- Reference/Searching/Examine/pdf-index.md
**csharp** 
gives better C# syntax highlighting that 
**cs**.
I did a search through the docs project and I think this is the only once.
Affected pages:
- https://our.umbraco.com/Documentation/Extending/Packages/Package-Actions/custom-package-actions
- https://our.umbraco.com/Documentation/Reference/Language-Variation/
- https://our.umbraco.com/Documentation/Reference/Searching/Examine/pdf-index/
> * Search and replace ```cs to ```csharp for better syntax highlightning.

- Reference/Querying/UmbracoHelper/index-v7.md
- Reference/Querying/UmbracoHelper/index.md
@sofietoft , Here is a WIP version of the UmbracoHelper Update. I am only half way through it verifying everything and still quite a bit to conquer. What are your early thoughts? I havent deleted the `'index-prev7.3` yet but we will have to do that I guess. I am not sure of the `versionFrom` on the v8 document. 
From what I can see UmbracoHelper in v8 does not have any ContentHelpers, so I have removed all of it. I have reached up till the Media section. We cant have `new Umbraco.Web.UmbracoHelper(Umbraco.Web.UmbracoContext.Current)` anymore by the looks of it.  Looks like you need to access the cache like [so](https://our.umbraco.com/Documentation/Implementation/Services/#implementing-the-service) in services, HTTP Handlers etc.  These are the most important changes I have found till …
> WIP UmbracoHelper v8 Update

- Extending/Packages/Creating-a-Package/index.md
- Getting-Started/Code/Debugging/index.md
- Implementation/Unit-Testing/index.md
- Reference/Events/EditorModel-Events/Customizing-the-links-box.md
- Reference/Scheduling/index.md
- Reference/Templating/Modelsbuilder/IPublishedContentModelFactory.md
As promised in https://github.com/umbraco/UmbracoDocs/pull/2146#issuecomment-566985625, I reviewed all the places we use :::warnings and depending on the context, place the warning before the code snippet. 
Also found some more minor tweaking:
* Typo: unnessecary > unnecessary
* Placed the section about ServiceContext Mocking in a tip.
* Placed BackgroundTaskRunner warning before code (as mentioned in previous discussion).
* Fixed broken warning on IPublishedContentModelFactory due to uppercase WARNING.
* Placed the warning for Debug in production above the xml snippet, since this is especially important!
* Changed EditorModelEventManager tip to warning since it made more sense in this case.
* Removed the word 'simply' in the Unit Testing Docs.
> Reviewed warnings, tips and spellings

- Getting-Started/Code/Umbraco-Services/index.md
The variable `cache` doesn't exists - it should be `contentCache`.
> Fix variable name for content cache

- Implementation/index.md
Not sure if the discontinued Rest-Api link on the https://our.umbraco.com/documentation/Implementation/ page should be removed or linked to the https://our.umbraco.com/documentation/Implementation/Rest-Api/ page, promoting Umbraco Heartcore. I went for the later option..
Anyway, It shouldn't link to a dead link (404).
> 404 link on Implementation index page.

- Reference/Routing/Request-Pipeline/outbound-pipeline.md
In the ProductPageUrlProvider docs the _siteDomainHelper is declared as a local field, for no reason at all (its unused). Maybe its been used in the past?
It should still be injected in the constructor since it is passed down to the DefaultUrlProvider, but it doesnt need to be locally declared in the ProductPageUrlProvider.cs.
> Remove unused _siteDomainHelper field.

- Tutorials/Creating-Basic-Site/Master-Template-The-Navigation-Menu/index.md
Uncommenting this line **WILL** actually show the @site.Name in the top navigation, 
so the word '_don't_' needs to be removed to fit the current logic.
Probably a leftover from a reversed logic in the passed 
(maybe in the past it was '**comment out** this line if you **don't** want...').
Cheers!
> Incorrent 'don't'-logic in comment in Navigation example.

- Implementation/Services/index.md
- Reference/Routing/Request-Pipeline/outbound-pipeline.md
In Umbraco v.8.1 the UrlProviderMode was renamed to just simply UrlMode. https://our.umbraco.com/documentation/Getting-Started/Setup/Upgrading/v81-ipublishedcontent-changes#url
These two pages in the docs does not seem to been updated with this info.
The **outbound-pipeline** page already had specific index page targeting 8.1.+ but the **services** page did not. I didn't create a specific pre-8.1 page for the services page since it was such a small change, but instead I extended the note with the renamed info. 
Is that fine? 
Or would you like me to update this PR with a specific page for pre-8.1?
> Update docs regarding renamed UrlMode from UrlProviderMode.

- Umbraco-Heartcore/Getting-Started-Cloud/The-Umbraco-Backoffice/index.md
In the article for Umbraco Backoffice for Heartcore, the links to the API Browser article and the Webhooks article looks interchanged. I have fixed that.
> Corrected links to API Browser and Webhooks

- Reference/Config/404handlers/index-v7.md
- Reference/Config/404handlers/index.md
The `404handlers.config` is obsolete. So it does not need v8 update and hence the tag can be removed
> Removed needv8update tag from 404handler.config

- Implementation/Unit-Testing/index.md
Added some test sample for the MembershipHelper.GetCurrentMember();
A bit more complexity than the previous tests, but I think it can be useful since it involves mocking a lot of different dependencies. 
The idea the the documentation page is to start of low level at the top and the further down you get on the documentation page the more complex test samples. Hope you like this approach.
Cheers! 🎉
> MembershipHelper Tests

- Extending/Section-Trees/trees.md
Hi team,
In the [Trees](https://our.umbraco.com/Documentation/Extending/Section-Trees/trees) page I have 
- added a link to the Constants.Trees.Groups API documentation
- Added an example of tree group in the backoffice
- Improved highlighting of some methods 
Poornima
> Added link to the Constants.Trees.Groups in API documentation and minor readability fixes

- Extending/Content-Apps/index.md
Use Umbraco Constants so that it is more consistent with other pages such as:
https://our.umbraco.com/documentation/Extending/Dashboards/
> Content apps: use umbraco constants

- Tutorials/Multilanguage-Setup/index.md
On the page https://our.umbraco.com/documentation/Tutorials/Multilanguage-Setup/, the title "Language Variants" links off to the variant page and its not very consistent with the rest of the site. I have added more copy to specifically say where one can read more about setting up and working with variants,
> Provide a bit more clarity on tutorial for multi-language set up

- Umbraco-Cloud/Set-Up/Umbraco-Latch/index.md
The PR describes the certificate for default umbraco.io domains - *umbraco.io. The PR also describes a default Let's Encrypt certificate for custom domains.
> Describe default certificates on Umbraco Cloud

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Grid-Layout/Grid-Editors.md
If https://github.com/umbraco/Umbraco-CMS/pull/6634 gets merged, this PR adds documentation for the feature.
> Adds documentation about name templates in grid editors

- Reference/Templating/Modelsbuilder/configuration.md
I can't recall which version this was changed in but certainly 8.5+
> Generated models namespace changed

- Tutorials/Creating-an-XML-Site-Map/index.md
To check each page against the excluded document types, the code needs to reference correctly the document's ContentType alias. The correct version is actually already in the final full code sample, but not in this individual step explaining the reasoning. This change makes everything consistent across the entire tutorial and the code can now run correctly.
> Add minor change to excludedDocumentTypes check

- Add-ons/UmbracoForms/Developer/Prepping-Frontend/index.md
Some of the frontend functionality for Forms requires jQuery.
I did some quick testing with an up to date version and things that use jQuery still work with a later version. So we should recommend people to use that.
Tested the following:
- Conditional fields
- Validation
- Datepicker field (pickaday has a jQuery dependency)
- Mandatory messages
> Update jQuery version

- Extending/Property-Editors/full-examples-value-converters.md
There was a bug in the code, the constructor name is wrong, I have fixed it.
> Fixed constructor name in the PVC example

- Extending/Property-Editors/Property-Actions/index.md
Hi,
I have fixed some typos and encouraged some consistency.
- 'build-in', shouldn't it be built-in?
- it was worded 'property-editor' in a place, shouldn't it be 'property editor'?
Poornima
> Fixed some typos in property actions

- Getting-Started/Setup/Server-Setup/Load-Balancing/index.md
* In v8, Slave is no longer a thing. It has been renamed to Replica, so we should not be using the term Slave anymore.
* Removed empty list-item in Scheduling and master election list
> Rename Slave to Replica i v8 Load Balancing docs.

- Extending/Dashboards/index.md
Hi,
The folder was worded 'app_plugins' and 'App_Plugins' in the same document. I have made it uniform to 'App_Plugins' 
There are at least 40 places in the whole documentation. I can do a replace wherever sensible but I think it will be worth having the lint check for the word like 'backoffice' long term. What do you think?
Poornima
> Bringing consistency to App_Plugins folder wording

- Reference/Routing/Request-Pipeline/inbound-pipeline-v7.md
- Reference/Routing/Request-Pipeline/inbound-pipeline.md
Don't know for sure but think it belongs to: https://github.com/umbraco/UmbracoDocs/issues/1873
Update inbound pipeline for v8
PublishedContentRequest --> PublishedRequest
Domain  --> DomainAndUri (and update description)
Removed RenderingEngine  since it's only MVC
Update how to subscribe 
Removed `needsV8Update`
> Update inbound request pipeline

- Extending/index.md
Hi, the packages link was missing, just think it wasn't added when we created the packages section
> Add link to packages pages from extending index.

- Implementation/Data-Persistence/index.md
There is a small issue on the [Data Persistence](https://our.umbraco.com/documentation/Implementation/Data-Persistence/) page. 
To get content from the ContentService GetById() should be used instead of Get() which not exists. :-)
> Update  Data Persistence page

- Umbraco-Heartcore/Getting-Started-Cloud/API-Browser/index.md
outputtet -> output
I suppose it could be also be outputted, both "output" and "outputted" are correct past-tense forms of output.
> Fixed grammar/typo

- Umbraco-Heartcore/API-Documentation/Content-Delivery/content/index.md
Some of the content endpoints in Heartcore have an optional `depth` querystring parameter, I've added a paragraph describing what it does.
> Added paragraph about the depth querystring

- Reference/Management/Services/ContentService/Index-v7.md
- Reference/Management/Services/ContentService/Index.md
This is for issue https://github.com/umbraco/UmbracoDocs/issues/2128. I have verified `ContentService` docs for v8. The `ConsentService` has separate docs for v7 and v8. But I have deviated from it as the `ContentService` only needed updated API docs link to v8. I can always make it consistent with `ConsentService` and have separate v7 and v8 pages.
> Verified ContentService documentation for v8

- Extending/Dashboards/index.md
Because it is necessary to override an Umbraco dashboard in order to change its permissions
Code source:
https://github.com/umbraco/Umbraco-CMS/issues/7737#issuecomment-593687756
> Add section for Override an Umbraco Dashboard

- Tutorials/Creating-a-Property-Editor/index.md
- Tutorials/Creating-a-Property-Editor/part-3.md
Issue: https://github.com/umbraco/UmbracoDocs/issues/2285
I added a _:::note_ on the first step of the tutorial, that Umbraco now has a built in markdown editor. As we've discussed @sofietoft, this tutorial is a nice tutorial for how to create your own property editor plugin from start to finish using AngularJs, html, custom configurations, injecting your own or 3rd party JavaScript libraries and using Umbraco’s native dialogs and services etc. but if all you are looking for is a markdown editor, then you don’t need to re-invent the wheel, you can just use the built-in editor. Hence this _:::note_.
I also added an example in step 3 of how to convert the markdown to html format and render it in a view. Aslo included a _:::note_ regarding the built-in Markdown editor and Models Builder.
> Added missing example from Property editor tutorial

- Add-ons/UmbracoForms/Developer/Working-With-Data/index.md
I changed "string" to guid for "FormID. because the interface has changed:
PagedResult<IRecord> GetApprovedRecordsFromForm(Guid formId, int pageNumber, int pageSize);
PagedResult<IRecord> GetApprovedRecordsFromFormOnPage(int pageId, Guid formId, int pageNumber, int pageSize);
PagedResult<IRecord> GetApprovedRecordsFromPage(int pageId, int pageNumber, int pageSize);
PagedResult<IRecord> GetRecordsFromForm(Guid formId, int pageNumber, int pageSize);
PagedResult<IRecord> GetRecordsFromFormOnPage(int pageId, Guid formId, int pageNumber, int pageSize);
PagedResult<IRecord> GetRecordsFromPage(int pageId, int pageNumber, int pageSize);
> Updated IRecordReaderService method signatures

- Getting-Started/Code/Debugging/Logging/index.md
Umbraco.Core.Composing.Current is not recommended as per this discussion (among others)
https://our.umbraco.com/forum/umbraco-8/96270-using-umbracohelper-in-a-custom-class-in-v8#comment-304427
so this showed a bad practice.
I'm not 100% my link to Composing is correct so this will need to be verified
regards
t
> Change example of accessing the logger to use DI instead of Umbraco.Core.Composer.Current

- Reference/Management/Models/Media.md
Add a reference to the documentation on querying Media from the cache, instead of the short explanation on why using an IMedia object is wrong.
> Added reference to cached media

- Umbraco-Cloud/Security/index.md
Describe how to enforce HTTP Strict Transport Security Header on Umbraco Cloud websites in order to achieve an A+ rating on ssllabs.
> Add HSTS - HTTP Strict Transport Security

- Add-ons/UmbracoForms/Developer/Extending/Adding-a-Type-v7.md
- Add-ons/UmbracoForms/Developer/Extending/Adding-a-Type.md
When overriding a Umbraco Forms Default Provider it is required that the custom class is public, otherwise the Reflection code won't pick up the overriden class.
For example:
`public class CustomOverridenSendEmail : Umbraco.Forms.Core.Providers.WorkflowTypes.SendEmail`
works, but a internal class does not:
`internal class SendEmailNoFrom : Umbraco.Forms.Core.Providers.WorkflowTypes.SendEmail`
The current documentation states that there is only a requirement that the WorkflowType Id should be the same, which is incorrect.
> Reflect public class requirement for overriding Default Umbraco Forms Providers.

- Getting-Started/Data/Members/index.md
I have updated the link to the video about members so it points to Umbraco 8 video documentation
> Updated URL to Umbraco 8 documentation

- Tutorials/Editors-Manual/Getting-Started-With-Umbraco/Copying-a-Page/index.md
Update Warning box: as this is not how relate to original works :( - it creates a relation in a table, so the two pages can be linked (e.g languages) but no coping goes on between them, after the first time.
> Change Relate to original warning

- Reference/Templating/Mvc/partial-views.md
Fixed a typo ("yer" => "year") in a code sample and rephrased a line or two.
> Updates to Cache section of Partial Views docs

- Getting-Started/Setup/Server-Setup/Load-Balancing/azure-web-apps.md
- Getting-Started/Setup/Server-Setup/Load-Balancing/index.md
* Describes what MainDom is and why it's needed and adds version specific information
* Changes headline `File system replication` to `Server configuration` and moves this section up because it's actually very important and updates this section with explicit links to each type of server design, this makes it much easier to find azure specific docs... these links were extremely hard to find.
We are still missing any docs/links to 'shared' file systems such as NAS/SAN. We don't mention this at all in the new v8 docs since everything now just points to this new `file-system-replication` document. I've linked the 'shared' file system to the file-system-replication#standalone-file-system link because that seems like its correct ... but then reading that it doesn't seem correct since i'm unsure …
> Load balancing updates

- Umbraco-Cloud/Set-Up/Working-With-Visual-Studio/index.md
I will suggest to have a section about how to work with IntelliSense and ModelsBuilder in the Visual Studio section of the documentation. According to the source below, and my own experiences this should be the way to do it 💪 
Source: https://our.umbraco.com/forum/umbraco-cloud/82156-models-builder-with-umbraco-cloud#comment-281518
> Adding section about ModelsBuilder and IntelliSense

- Reference/Routing/URL-Tracking/index.md
The change made in this [commit](https://github.com/umbraco/UmbracoDocs/commit/f745095f476fdc266454483b676225dcc068cdc6) removed important information that applies to v7 sites without creating multi-versions of the page. Adding this back in with a note that this doesn't apply to v8 sites.
> Re-added information about URL Tracking disabling if some packages detected.

- Extending/Backoffice-Tours/index.md
Adds in some examples of using `TourFilters` which allows you to filter out specific tours:
* by its alias
* a specific tour JSON filename
* or all JSON tours in an App_Plugin plguin/package
@sofietoft @marcemarc & the rest of the docs gang let me know if you need me to tweak or amend this example.
> Adds in example of using TourFilters to disable certain tours

- Implementation/Custom-Routing/index.md
I've noticed a pattern where people want to use a custom MVC controller, but follow the scent of 'custom routes', and end up on this page... which then seems to suggest you need to map a route to a custom MVC controller, which if you are coming from MVC background doesn't seem unusual, and you are not going to guess or search for the existence of route hijacking, so I've just added a note underneath mapping a route using a virtual node route handler to point in the direction of the by convention approach... so people can discover it is a thing.
> Cross link to Route Hijacking information

- Extending/Property-Editors/Declaring-your-property-editor.md
Right now we have the [**Package Manifest**](https://github.com/umbraco/UmbracoDocs/blob/master/Extending/Property-Editors/package-manifest.md) page that describes how to declare a property editor using `package.manifest` files.
It's also possible to declare property editors using C#, but I haven't been able to find anywhere it the documentation that mentions this. Based on community feedback, only few people seem to know about this part. So with this PR, it's my proposal that this new **Declaring your property editor** page will replace the **Package Manifest** page.
For now this PR only adds the new page, but doesn't update any existing files, as I'd like to hear first whether the documentation team agrees with my proposal.
> Added new page about declaring property editors

- Umbraco-Cloud/Set-Up/Umbraco-Latch/index.md
I've found that having a CAA record for a domain that does not allow Lets Encrypt to issue a certificate, can get the hostname stuck in the 'Initial' phase without any clue for the user of getting out of that phase. This can hopefully help debug this issue, if a user runs into it.
> Creating section about CAA and Umbraco Latch

- Extending/Packages/UmbPack/index.md
While in pre-release this should include the version number specification. Issue raised here: https://github.com/umbraco/UmbPack/issues/23
> Update install command to include version number

- Extending/Database/index.md
When you want to deploy a new website to the server, you need to clear the connection string from the Web.config file, in order to trigger the Umbraco installation. However, without the RuntimeLevel attribute, the composer will try to run even before the Umbraco installation. Since no connection string has been configured yet, the code in the composer that tries to execute the migration will fail. Adding this attribute prevents the composer from running too soon.
See also the discussion at https://github.com/umbraco/UmbracoDocs/issues/2350
> Add RuntimeLevel attribute to the Composer snippet

- Reference/Management/Services/TreeService/Index.md
needsV8Update  --> versionRemoved
As far as I know the ApplicationTreeService no longer exists in v8. 
Belongs to https://github.com/umbraco/UmbracoDocs/issues/2128
> TreeService

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Color-Picker/index.md
Based on a question on the Community Slack here is an example of how to get a colorpicker label and hex value when not using Modelsbuilder 🙂
> Add example of using the colorpicker without modelsbuilder

- Extending/Dashboards/index.md
Took me a while to get my Members dashboard working as I didn't realise that the section alias to use in the package.manifest is "member" not "members".  As this alias is the only one that differs from its English name I thought it would be helpful to add it to the examples, as well as adding a link to where you can double check what these aliases should be.
> Add link to where to find dashboard section aliases

- Umbraco-Cloud/Getting-Started/Migrate-Existing-Site/index.md
If you upgrade your project from a version prior to 7.6 without updating your property editors to the non-obsolete version, that stores UDIs rather than IDs you might run into issues when trying to transfer content to Umbraco Cloud as these pickers will have the wrong content. It is therefore important that customers know that if they want a project prior to v7.6 on Cloud, they might need to do a db migration as well - if they're using the obsolete pickers.
> Issues upgrading from a version prior to 7.6

- Reference/Searching/Examine/examine-events.md
- [AMEND] Amended the indexing example to demonstrate the use of a Scope wrapper when accessing an Umbraco Context
Based on response from Shannon on this forum thread https://our.umbraco.com/forum/using-umbraco-and-getting-started/102676-triggering-index-rebuild-via-hangfire-causes-objectdisposedexception-in-nucache
> [AMEND] Amend indexing example to use Scope.

- Reference/Routing/custom-controllers.md
The `MyProductViewModel` in the example code should inherit from `PublishedContentWrapped`.  There is no class called PublishContentWrapped.
> Fix syntax error - PublishedContentWrapped

- Extending/Packages/UmbPack/index.md
We have some options that take space seperates strings that don't work well with the path parameter, so have updated all examples in the docs to always be of form `umbpack [command] [path] [options]` 🙂
> Make UmbPack examples more consistent

- Extending/Database/index.md
Fixes...
The name 'RuntimeLevel' does not exist in the current context (Compiler Error CS0103)
... in line...
[RuntimeLevel(MinLevel = RuntimeLevel.Run)]
... when using Umbraco version 8.6.3.
> Fixes compiler error CS0103 in RuntimeLevel

- Reference/Angular/Services/eventsService/index.md
- Reference/Angular/Services/index.md
- Reference/Angular/index.md
Follow up from: https://github.com/umbraco/UmbracoDocs/pull/2620
This PR still contains visible links to usage of `eventsService`. Should these be converted to HTML comments? Or should we do something else? HTML comments are still visible in the source code when the documentation is rendered on Our.
> Added documentation for eventsService

- Reference/Management/Services/ContentService/Index.md
The examples still showed how to get a service reference in Umbraco 7, but as the page is now specifically for Umbraco 8, I've updated the examples.
> Updated "Getting the service" for Umbraco 8

- Reference/Management/Services/LocalizationService/Retrieving-languages.md
There is another Markdown file for Umbraco 7, and this has `versionFrom: 8.0.0` - so I've updated the link to the API docs and removed `ApplicationContext.` from the Razor example.
> Updated Retrieving-languages.md examples to work for Umbraoc 8

- Tutorials/Creating-Basic-Site/Articles-Parent-and-Article-Items/index.md
Fixing the issue with the Truncate Method. It prints out the <p> tags to the frontend view when using the Rich Text Box Editor. It is not supposed to do that. It has now been fixed so the tutorial is up to date with the latest releases.
> Fixing the issue with latest release for tutorial Article Item

- Reference/Routing/custom-controllers.md
Added note about ContentFinderByUrlAndTemplate  being disabled by default and linking to IContentFinder documention on how to re-add it in.
This is to address the docs due to https://github.com/umbraco/Umbraco-CMS/issues/8650 and @marcemarc 's response.
> Added note about ContentFinderByUrlAndTemplate

- Reference/Searching/Examine/Quick-Start/index.md
Hi,
Noticed while working today that there is an issue with the code sample https://our.umbraco.com/Documentation/Reference/Searching/Examine/quick-start/#search-children-of-a-specific-node 
While searching for children of specific node there needs to be an `And()` before the `Field()` can be used
Poornima
> Examine - Fixed a issue with code sample

- Implementation/Services/index.md
Line 424...
IPublishedContentCache contentCache = umbracoContextReference.UmbracoContext.Content;
... currently gives and error:
CS0246 The type or namespace name 'IPublishedContentCache' could not be found (are you missing a using directive or an assembly reference?)
> Update reference for SiteService example

- Implementation/Services/Circular-Dependencies/index.md
- Implementation/Services/index.md
This is a gotcha when injecting `IUmbracoContextFactory` into a service which is registered as part of an `IUserComposer` as per the example on this page.  I have found that there are situations, particularly when interacting with third party extension code (e.g. Umbraco Packages), the provided example will fail with a boot error 'Recursive dependency detected: ServiceType:Umbraco.Web.IUmbracoContextFactory'.  
The tip provided fixes this issue, whereas other techniques (such as applying the ComposeBefore/After attribute) have no effect.  I feel like there are many other situations where this could crop up and therefore would be a worthwhile addition to this page.
Ref: forum discussion: https://our.umbraco.com/packages/backoffice-extensions/contentment/contentment-feedback/102944-boot-fail …
> Add tip for injecting a Lazy version of IUmbracoContextFactory

- Reference/UmbracoVolatile.md
Added a document about Umbraco Volatile Error, currently it shouldn't be available in the menu since it's not finished yet, however we need somewhere to link to from the error tooltip.
> Add Umbraco Volatile docs

- Umbraco-Cloud/Getting-Started/Migrate-Existing-Site/index.md
There are currently some wording around "again" and "double-check", when the users are asked to do an echo > deploy command. That is weird, since this is the first time the user is introduced with this.
> Removing repetitive wording around generating meta data

- Add-ons/UmbracoForms/Developer/Forms-in-the-Database/index.md
- Umbraco-Cloud/Deployment/Umbraco-Forms-on-Cloud/index.md
New article on forms definitions being moved to the database.
Also includes steps on how to enabled this, for older versions.
> Forms definitions moved to the database

- Add-ons/UmbracoForms/Developer/Custom-Markup/index.md
- Add-ons/UmbracoForms/Developer/Extending/Adding-a-Fieldtype.md
- Add-ons/UmbracoForms/Developer/Prepping-Frontend/index.md
Made corrections to the validation description to accommodate that we now that a different validation framework default with Umbraco Forms. But jQuery is still an option if you include it manually.
Notice this feature is not released yet, so we need to wait to merge this in until that happens.
> Umbraco forms validation update

- Extending/Section-Trees/trees.md
- Getting-Started/Code/Subscribing-To-Events/index.md
- Getting-Started/Code/Umbraco-Services/index.md
- Implementation/Composing/index.md
- Implementation/Custom-Routing/index.md
- Implementation/Services/index.md
- Reference/Cache/examples/tags.md
- Reference/Events/ContentService-Events.md
- Reference/Events/EditorModel-Events/index.md
- Reference/Events/MediaService-Events.md
- Reference/Events/MemberService-Events/index.md
- Reference/Management/Services/RelationService/index.md
- Reference/Routing/Request-Pipeline/inbound-pipeline.md
- Reference/Scheduling/index.md
- Reference/Searching/Examine/examine-events.md
- Tutorials/Porting-Packages-V8/index.md
See issue: https://github.com/umbraco/UmbracoDocs/issues/2690
This PR updates examples that subscribe to static events in a component, to also include an example of unsubscribing
> Update Examples that show subscribing to a Static Event in a component to show unsubscribing from the event in Terminate()

- Umbraco-Cloud/Set-Up/Manage-Hostnames/index.md
Removed the mention that you can add up to 15 hostnames to a cloud plan. This is now dependent on the cloud plan you have purchased.
> Remove 15 hostnames mention

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Nested-Content/index.md
Hi,
I dont know whether this is useful, but I wanted to use the document type name as the template and figured out that it can be done by using `{{alias}}` as the template. Hence raising a PR.
Poornima
> Added note for including document type name in the nested content template

- Umbraco-Heartcore/Getting-Started-Cloud/Preview/index.md
Noticed the code sample for the typescript/javascript example wasn't highlighted on [this page](https://our.umbraco.com/documentation/Umbraco-Heartcore/Getting-Started-Cloud/Preview/) as our apparently doesn't support typescript as a language. I changed the language to javascript instead as there's no typescript specific code anyway.
> Change javascript example code language

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Block-List-Editor/index.md
When using custom edit views with inline editing the `block.edit()` command does nothing, so it should be stated that custom views are incompatible with inline editing.
When you add an image to a block editor element type you only get back the UDI. It's not obvious how to display the image, so I've linked to a forum message explaining this.
> More detail about creating custom backoffice views

- Reference/Searching/Examine/Quick-Start/index.md
- Reference/Searching/Examine/examine-events.md
Hi,
Working with indexing on v8 further today and I noticed the docs can be improved by adding a sample on how we can search the index by descendants. The `ParentId()` only does immediate children.
Poornima
> Docs on how to add the path of a node as a searchable field into the index

- Umbraco-Cloud/Deployment/Deploying-Deletions/index.md
Fixed up a few errors. There's some mention of a "database entry referencing a document type" .. the database *entry* is actually what the document type *is*.
Also made it a bit clearer what the consequence of automatically deploying a delete is, to ensure it is clear why we do not want to do this.
Fixed up the description of what to do to completely remove a document type from a project.
> Deploying deletes

- .github/valeStyle/Terms.yml
Just copied the Vale rules into a different repo and noticed this App Plugins rule a bunch of places. The idea to capitalize it is good, but this ruleset is meant more for wrong terms or spaces, hyphens, etc. 
The rule has this line: `ignorecase: true`, which means this rule will always trigger and will never be "correct".
If you want a seperate rule to check for correct casing of terms I can add that, just let me know 🙂
> Remove broken styleguide rule

- Contribute/File-Naming-Conventions/index.md
Fixed broken link pointing to YAML metadata (probably due to folder migration?)
> Fix broken link pointing to YAML metadata

- Reference/Searching/Examine/Quick-Start/index.md
.Url is obsolete and we should now use .Url() extension. Just updating the documentation to reflect this.
> Removing obsolete extension

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Block-List-Editor/index.md
to the backoffice view
with example to display an image from a media picker
> Update the Block List documentation to show how to add an angularJS controller

- Umbraco-Cloud/Troubleshooting/Deployments/Connection-Forcibly/index.md
- Umbraco-Cloud/Troubleshooting/Deployments/index.md
This is a pretty common, but still undocumented error that Umbraco Cloud users will see if they're running on a .net version prior to 4.6. This can hopefully help some people resolve this :-)
> Adding page about resolving the "connection forcibly closed" error

- Umbraco-Heartcore/index.md
Noticed we were missing a link to the GraphQL documentation from the Heartcore landing page.
> Add GraphQL docs link to Heartcore index page

- Getting-Started/Backoffice/Variants/index.md
The documentation for variants covers culture and hostnames in the video but not in the notes. I have added that.
> Added notes about culture and hostnames to variants 

- Reference/Angular/Services/eventsService/index.md
The existing documentation only explained how to listen for events from a controller.
I've now added an example for how to listen for events on a more global level - eg. if you need to listen for an event during the entire lifetime of the application, and not just during the lifetime of a component.
> Updated examples for eventsService

- Reference/Angular/Directives/index.md
- Reference/Angular/Directives/umbProperty/Index.md
The [Backoffice UI API Documentation](https://our.umbraco.com/apidocs/v8/ui/#/api/umbraco.directives.directive:umbProperty) documentation contain a page for the `umbProperty` directive, but doesn't really describe anything more than that.
This PR introduces a new page about the `umbProperty` directive. I'd like to improve this page even further going forward, but I think it can serve as a starting point for now 😉
> Added documentation for umbProperty directive

- Reference/Angular/Services/editorService/Index.md
- Reference/Angular/Services/index.md
- Reference/Angular/index.md
Started on this a while back, so while most of the functions aren't described, here is documentation for the `contentPicker` and `documentTypeEditor` functions.
> Added documentation for editorService

- Umbraco-Heartcore/API-Documentation/GraphQL/Filtering-and-Ordering/index.md
- Umbraco-Heartcore/API-Documentation/GraphQL/index.md
- Umbraco-Heartcore/index.md
Added an article describing how to use GraphQL filtering, ordering and paging.
I've also moved the "API Documentation" links on the landing page to the top of the page, since when you are on our you are most likely looking for documentation and it wasn't easy to spot some of the pages, given they are not visible in the navigation and only accessible from the child pages.
**NOTE** this is targeting https://github.com/umbraco/UmbracoDocs/pull/2817
> Heartcore GraphQL filtering, ordering and paging

- Getting-Started/Setup/Server-Setup/permissions.md
There are currently two sets of permissions, https://github.com/umbraco/UmbracoDocs/blob/main/Getting-Started/Setup/Server-Setup/permissions-v7.md and this one which has the v7 folders removed.
> Change meta Umbraco v of the permissions

- Umbraco-Heartcore/Getting-Started-Cloud/Creating-a-Heartcore-project/index.md
Line 186 - However, once you've checked this permission setting on one Document Type, it will be the **only one** that can be used to create content at the root.
That is not correct as far, as I know. You can have several different doc types that can be used as root content. Please, remove that line unless I somehow misunderstood what it means @sofietoft
> Fixed a few typos and changed the sentence structure.

- Getting-Started/Setup/Server-Setup/azure-web-apps-v7.md
This link didn't work as it tried to find this v7 headline on the v8 document. This change should do it 🙂
> Fix deeplink

- Umbraco-Heartcore/API-Documentation/GraphQL/Property-Editors/index.md
Sees there's the Editor Alias of the Numeric field is wrong. It should be `Umbraco.Integer` and not `Umbraco.Numeric`.
https://our.umbraco.com/documentation/getting-started/backoffice/property-editors/built-in-property-editors/Numeric/
> Update wrong Editor Alias for Umbraco.Integer

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Block-List-Editor/index.md
At the moment the documentation of the block list editor shows examples of how the render the block list editor, but not how to extract content data as `IEnumerable<IPublishedElement>` like in Nested Content, when using block list editor to hold some data:
https://our.umbraco.com/documentation/getting-started/backoffice/property-editors/built-in-property-editors/Block-List-Editor/
> Add more examples of how to extract block list content data

- Implementation/Services/index.md
- Reference/Using-Ioc/index.md
I recently used `Lifetime.Request`, assuming that this is would create a new instance per web-request.  I remember looking at the docs and having to make a guess, and went with `Lifetime.Request` because it sounded the most similar to "web request".  It turned out I actually should have used `Lifetime.Scope`.
This is because the terminology is based on Lightinject (which uses "Request" and "Scope" lifetimes), which is confusing in the context of a web application - this was [highlighted and clarified with Lightinject](https://github.com/seesharper/LightInject/issues/494) by @Shazwazza last year.  It looks like other people have also made the same mistake as me judging by [a forum post I came across](https://our.umbraco.com/forum/umbraco-8/98389-iusercomposer-with-lifetimerequest-works-as-l …
> Added detail to how different "Lifetimes" work

- Umbraco-Heartcore/API-Documentation/GraphQL/Schema-Generation/index.md
Small update that adds the new preview argument to the schema generation docs
> Add preview argument to Heartcore GraphQL schema generation

- Umbraco-Cloud/Set-Up/Media/Connect-to-Azure-Storage-Explorer/index.md
- Umbraco-Cloud/Set-Up/Media/index.md
All Cloud sites are having their Media libraries migrated to Azure Blob Storage.
I've updated the Media article for the Umbraco Cloud docs, to reflect those changes.
> Media updates on cloud

- Umbraco-Cloud/Set-Up/Manage-Hostnames/Rewrites-on-Cloud/index.md
- Umbraco-Cloud/Set-Up/Media/index.md
After migration to Azure Blob Storage, some customers have seen issues with trailing slashes causing their media not to show. When adding this into our section about trailing slashes, we can make sure that the best practices is followed.
> Add trailing slash rewrite rule to the "Rewrites on Cloud" article

- Umbraco-Cloud/Set-Up/Manage-Hostnames/Rewrites-on-Cloud/index.md
With the current version, if you have a content node called eg. "Mediacenter" it is not gonna work.
With this correction all urls with a ".something" will be negated.
> Changing trailing slash redirect to a better approach

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Block-List-Editor/index.md
The documentation doesn't currently pull it all together as well as Niels Lyngsø's blog article. As that article has links back to the three relevant documentation sections I'm proposing that his article should be referenced here. I'd read the docs but couldn't see what the advantage was over Nested Content until I read his article which brought it all together. I hope you agree? :)
> To add a link to a subject overview article

- Umbraco-Heartcore/Client-Libraries/Dot-Net-Console/index.md
- Umbraco-Heartcore/Versions-and-updates/index.md
- Umbraco-Heartcore/index.md
I fixed a few broken links and made some changes to avoid 301's when pointing to Umbraco.com pages about Heartcore.
> Broken links in the Heartcore section

- Umbraco-Cloud/Set-Up/Config-Transforms/index.md
- Umbraco-Cloud/Set-Up/Manage-Hostnames/index.md
- Umbraco-Cloud/Troubleshooting/FAQ/index.md
- Umbraco-Cloud/Upgrades/index.md
I fixed a few broken links in the Cloud section.
Please double-check the link in _Umbraco-Cloud/Troubleshooting/FAQ/index.md_ pointing to the Github Courier Data Resolvers repo. I'm not 100 % sure I found the perfect replacement, but I couldn't find anything matching the broken path.
> Broken links in Cloud section

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Image-Cropper/index-vpre8.7.md
- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Image-Cropper/index.md
Umbraco 8.7.0 saw the addition of Current.ImageUrlGenerator and GetCropUrl was updated to use this.  I've updated the docs to include this.
I've also updated the `html` code snippets with` <img src="@(...)" />` were the calls to GetCropUrl included strings this is because in some views the strings were causing compilation errors.
This is a PR for https://github.com/umbraco/UmbracoDocs/issues/2929
> Updated GetCropUrl for 8.7.0 +

- Getting-Started/Setup/Server-Setup/Load-Balancing/azure-web-apps.md
Keeps coming up in the forum that it's not clear now in 8.4+ in these docs whether the setting is applied just to Primary, or to Replica servers or to both
> Confirm where to apply the Maindom.Lock setting

- Getting-Started/Setup/Server-Setup/Load-Balancing/flexible-v7.md
The v7 version of the flexible LB docs link to advanced v8 features instead of advanced v7. It would be nice to link on to the same major 😊
> Link to same major version

- Umbraco-Cloud/Set-Up/Manage-Hostnames/index.md
Adding a few more clarifying details to the "how to setup hostnames"-page.
1. How to enroll your hostname in a Cloudflare to Cloudflare setup.
2. How to configure CAA-records so Umbraco Cloud can issue certificates for the added hostname.
> Adding details about Cloudflare to Cloudflare and CAA.

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Block-List-Editor/index.md
Update this documentation with a few more advanced examples for label expression without adding a custom view and using filters.
At the moment we have some specific Nested Content filters `ncNodeName` and `ncRichText` filters
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/common/filters/nestedcontent.filter.js#L65-L69
but these also works in Block List editor. Maybe we should added these as global filters in https://github.com/umbraco/Umbraco-CMS/tree/v8/contrib/src/Umbraco.Web.UI.Client/src/common/filters (or as block specific filters).
We could probably register these as new filter names, while keeping these with the existing names for backward compatibility.
If Nested Content sometime is removed, we will probably also remove the `nc` specific …
> Add a few examples using Angular filters in label expression

- Implementation/Unit-Testing/index.md
Turns out the local mocked instance of ICultureDictionary is unused in this test, since the actual test uses the base.CultureDictionary. Probably a result of previous refactoring.
> Removed unused instance of ICultureDictionary

- Umbraco-Cloud/Set-Up/Media/index.md
I had a customer today who thought the documentation was misleading, because he did not get any Media files when he cloned down the project locally, as the documentation stated he would.
I was told by my colleagues that you need to do a Content Restore first, which makes sense, but maybe not that obvious for a new user of Umbraco Cloud.
Therefore I suggest we add this (or rephrase it however you like) so users are aware that they need to do this.
> Remind users about content restore on Media Files

- Umbraco-Cloud/Deployment/Deploy-Settings/index.md
I've added them a little closer together as these two subjects are very much the same.
However, I haven't merged them into one (yet) because I can see that having them seperate, but close/grouped, is good for two reasons:
1. If a user just needs to know about modifying the Timeout, we can link to that heading/section
2. If a user has timeout issues, then it has its seperate sections as of what you can do about it.
The scenario might be a bit too vague, but I am open to suggestions 😄
> Timeouts more grouped

- Implementation/Unit-Testing/index.md
* Added test sample for ContentModel predefined property .Url.
* Added test sample for Apicontroller that returns Json instead of just Enumerable.
* Added test sample for UmbracoContentQuery ContentAtRoot.
> More test samples

- Reference/Config/fileSystemProviders/index-v7.md
This addition explains and exemplifies how to use MediaFileSystem to get the contents of a file in a stream using v7.
> How to get file stream from MediaFileSystem in v7

- Reference/Events/ContentService-Events.md
Further to this issue:
https://github.com/umbraco/Umbraco-CMS/issues/5410
It seems events with variants can be fired not how you might first expect them to work, but if you think about it, it makes sense - action of the issue is to document the things you can do with variants in events, and this PR tries to provide this information
> Add information about handling events with variants in play

- Add-ons/The-Licensing-model/index.md
I'd missed the `xml` part of the language file in my previous PR, so the config file isn't showing on the front end:
https://our.umbraco.com/documentation/add-ons/The-Licensing-model/ 
I think this fixes it 🤔
> Updates code language to xml

- Reference/Management/Services/MemberGroupService/Index.md
The code example was referencing the `IMemberService` when it should be `IMemberGroupService`.
Thanks
> Fix typo in Members Group Service code example

- Umbraco-Cloud/Security/index.md
The first variation is relevant when you have a reverse proxy like Cloudflare in front of the website, which will be the common approach on Cloud going forward. The second variation is the standard way of using rewrite rules for restricting access to the backoffice based on the IP of the visitor. This will be relevant to old Cloud sites and anything running outside of Cloud.
> Updated the Backoffice IP filtering examples with two variations

- Getting-Started/Setup/Upgrading/version-specific.md
removed the version upgrade for 8.12.0 since it is no longer needed as we managed to upgrade the HtmlSanitizer package to the latest major.
> Removed version upgrade for 8.12.0

- Umbraco-Cloud/Set-Up/Project-settings/index.md
I see people getting confused as to why they cannot enable or disable Basic Auth on their Live environment when they are on a Starter Plan. I tried to add a little clarification as to what it means when you are on a Starter Plan and what Basic Auth can do 😄
> Updated Public Access note

- Reference/Scheduling/index.md
The text doesn't match the example code above it, and it also doesn't make sense that you'd set `IsAsync=false` to make something async.
> false should be true

- Umbraco-Cloud/Troubleshooting/Deployments/Changes-Not-Being-Applied/index.md
What was once whole, is now separated for readability.
> Reformatted error msg on deployment config transforms issue

- Reference/Events/EditorModel-Events/index.md
Adding a basic example of how `SendingMemberModel` can be using to set default member group for a specific member type.
I have suggested in this feature request to be able to set a `MemberGroup` property https://github.com/umbraco/Umbraco-CMS/issues/10032 but for now this works 👍
> Add example using SendingMemberModel

- Umbraco-Cloud/Set-Up/Manage-Hostnames/Rewrites-on-Cloud/index.md
After we switched to Cloudflare the rewrite rule to hide the default umbraco.io url will have to use {HTTP_X_Forwarded_For} rather than {HTTP_HOST} to not cause a redirect loop, effectively making the website unavailable.
> Updating the Hiding the Default umbraco.io Url rewrite rule

- Extending/Property-Editors/value-converters.md
Removing incorrect reference for Umbraco Helper as Value<T> is a method of IPublishContent.
> There's no GetPropertyValue<T> in v8 anymore, it's Value<T>

- Umbraco-Cloud/Set-Up/Manage-Hostnames/Rewrites-on-Cloud/index.md
Due to the recent changes to Cloudflare, a redirect that was working before is not working anymore. This PR inserts a warning box to not use this rewrite whilst we are working on finding an appropriate way of creating this rewrite in the Cloudflare setup.
> Inserting a warning and reverting earlier change to rewrites section

- Add-ons/UmbracoForms/Developer/Configuration/index.md
This was added in dealing with some feedback from the forms 8.7 RC.
Please can it be reviewed and then merged in on 6th April?  If it goes earlier doesn't really do any harm though, as I've flagged that it's only available from 8.7,
> Added documentation for Forms configuration key MaxNumberOfColumnsInFormGroup

- Reference/Config/webconfig/index.md
With https://github.com/umbraco/Umbraco-CMS/pull/9744 a new app setting to be able to set the SQL write lock timeout was introduced. This PR inputs a short mentioning of this appsetting into the documentation 😅
> Inserting SqlWriteLockTimeOut into app settings section

- Extending/Health-Check/index.md
Look at the second code snippet on this page: https://our.umbraco.com/documentation/Extending/Health-Check/
The csharp code snippet is not formatted properly an I think it is because the second row of the content of the robots.txt file does not have any indentation which confuses the opening/closing csharp block.
> Updated indentation to avoid breaking csharp code formatting.

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/File-Upload/index.md
The documentation here doesn't seem to be correct: https://our.umbraco.com/Documentation/Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/File-Upload/
The extension exists as a method here:
https://github.com/umbraco/Umbraco-CMS/blob/d428a4543f33bb7094cf7db5f6b6fdc2d1de3063/src/Umbraco.Web/PublishedCache/PublishedElementPropertyBase.cs#L39
ModelsBuilder  return the value as a `string` property in File Upload and the `HasValue()` isn't an string extension method.
> Update documentation for HasValue()

- Add-ons/UmbracoForms/Developer/Extending/Adding-a-Type.md
There was a bug in Umbraco Forms that caused one of the code snippets in this article to not work properly.
This has now been fixed and will be released in Forms v8.7.
Related: 
Forms PR: https://github.com/umbraco/Forms/pull/447
Forms Issue: https://github.com/umbraco/Umbraco.Forms.Issues/issues/433
Docs Issue: https://github.com/umbraco/UmbracoDocs/issues/1739
> Removed warning about bug that has been resolved

- Extending/Property-Editors/package-manifest.md
I have updated the docs to include dashboards and sections since both are root elements and can be registered using a package.manifest file.
> Updating the Package Manifest to include Dashboards and Sections

- Add-ons/Umbraco-Deploy/Extending/index.md
- Add-ons/Umbraco-Deploy/index.md
I've added this as had a small update to make sure we record as part of 4.1.1, but realised we didn't really have a home for it.
It's worth having available for anyone looking to extend Deploy with their own data or custom property types.  Some of this I've adapted from internal documentation, some from code samples I've written for development and testing tasks.
> Added page on how to extend Deploy for custom data and property editors

- UmbracoNetCoreUpdates.md
I tried to follow the documentation for creating a new Package project and associating it with a Test Site, but I kept hitting an error.
Turns out the example had a lowercase `-p` option, but the `dotnet new umbraco --help` says that it's uppercase `-P`. Which then worked for me.
I've updated the documentation to correct the casing of the `-P` option.
I hope this correct? _(I'm very very new to any .NET Core stuff - not really sure what I'm doing, LOL!)_
> UmbracoNetCoreUpdates.md - Package development CLI example

- Extending/Health-Check/Guides/index.md
Noticed a broken link on https://our.umbraco.com/documentation/Extending/Health-Check/Guides/ so thought I'd fix :)
Thanks,
Carole
> Fixing a broken link in docs

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Member-Picker/index.md
This PR updates the example for member picker setting the correct udi value and fixes https://github.com/umbraco/UmbracoDocs/issues/3141
> Set correct udi value in member picker example

- Reference/Config/umbracoSettings/index.md
The usage of umbracoUseDirectoryUrls has been removed in v8 - but not from the docs :)
> Remove mentions of umbracoUseDirectoryUrls

- Extending/Dashboards/index-v9.md
- Extending/Section-Trees/trees-v9.md
Hello,
I noticed a few of the articles suggest we update files in the /config folder, but in v9 we don't have that as standard. It looks like those needed in: https://our.umbraco.com/documentation/Extending/Section-Trees/trees are inside /umbraco/config instead, and this works when running through the tutorial. So I have updated these in this PR. However...
I noticed this article: https://our.umbraco.com/documentation/Extending/Health-Check/index-v9 says _"Don't add the translations to ~/Umbraco/Config/Lang files, the correct location is ~/Config/Lang/*-*.user.xml"_, so maybe this should just be /config after all? If so I think we should mention that it won't exist as default anymore and folks will need to add it.
Feedback appreciated :)
Thanks,
Carole
> Updating config folder

- Extending/Section-Trees/trees-v9.md
- Reference/Events/ContentService-Events-v9.md
- Reference/Events/ContentTypeService-Events-v9.md
- Reference/Events/DataTypeService-Events-v9.md
- Reference/Events/EditorModel-Events/Customizing-the-links-box-v9.md
- Reference/Events/EditorModel-Events/index-v9.md
- Reference/Events/FileService-Events-v9.md
- Reference/Events/LocalizationService-Events-v9.md
- Reference/Events/MediaService-Events-v9.md
- Reference/Events/MediaTypeService-Events-v9.md
- Reference/Events/MemberService-Events/index-v9.md
- Reference/Events/MemberTypeService-Events-v9.md
- Reference/Events/determining-new-entity-v9.md
- Reference/Events/index-v9.md
This migrates the Events docs and sub-pages: https://our.umbraco.com/documentation/Reference/Events/
I've also updated the events mentioned in the trees docs to notifications instead.
While I was migrating this I also noted that the Events section in the MemberService page on the v8 docs (https://our.umbraco.com/documentation/Reference/Events/MemberService-Events/) is wrong, it looks like a copy-paste job gone bad, for instance, the "DeletingVersions" event doesn't exist, and the description column also mentions "Id: Gets the id of the IContent object being deleted.", which of course doesn't make sense, it's the same for a lot of the other events as well.
I also think it would make sense to add an "extending notifications" doc about creating and publishing your own custom notifications, …
> Migrate events docs to notifications

- Umbraco-Cloud/Set-Up/External-Services/index.md
When we migrate projects to the new infrastructure, the outgoing IPs will change. Hence, we need to have the new IPs documented to use as reference.
> Add outgoing IPs for new Cloud Infrastructure

- Add-ons/UmbracoForms/Developer/Configuration/index-v9.md
- Add-ons/UmbracoForms/Developer/Extending/Adding-a-Exporttype-v9.md
- Add-ons/UmbracoForms/Developer/Extending/Adding-a-Fieldtype-v9.md
- Add-ons/UmbracoForms/Developer/Extending/Adding-a-Type-v9.md
- Add-ons/UmbracoForms/Developer/Extending/Adding-a-Workflowtype-v9.md
- Add-ons/UmbracoForms/Developer/Extending/Adding-an-Event-Handler-v9.md
- Add-ons/UmbracoForms/Developer/Forms-in-the-Database/index.md
- Add-ons/UmbracoForms/Developer/IFileSystem/index.md
I think this covers everything that has changed in V9.  The main things are:
- Developer documentation for extending via creating custom field types, workflow types etc.  All the code samples needed some amends, so I've created "v9" versions of all of these.
- Configuration is quite different in .NET Core even though most of the settings have carried over, so I've created a V9 version of this.
Otherwise have read through and made a few other small amends, where something isn't available in V9 or is just subtly different to not justify a new version specific page.
Given the UI hasn't changed, I don't expect the editor documentation to need updating.
> Documentation updates for Forms V9.

- Reference/Routing/Request-Pipeline/index.md
I saw in the comments field of this [sheet ](https://docs.google.com/spreadsheets/d/1YyARbCbLKhqR12cfbATxyCEZ6fYYxwBXeOw-jNUyWXc/edit#gid=0)that this article was not yet verified against Umbraco 8. I think this article also fits Umbraco 8, so I removed the needsV8Update tag. Maybe the image could use an update 😉. In addition, the link to Stephan's slides is somewhat outdated.
> Verified against umbraco 8

- Fundamentals/Setup/Server-Setup/azure-web-apps-v9.md
Updated the azure web app docs for v9..
Note that most is copied from v8. The actually changes are mainly
- The configuration values are updated to v9-style
- Removed the note about 8.6+ as this is v9 docs
- Removed example with `HttpRuntime.AppDomainAppId` as this is not a thing anymore.
> Updated Azure web apps to v9

- Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Nested-Content/index-v7.md
Added an example on rendering nested content elements based on partial views. A guy was asking on the community slack and I was a bit surprised we didn't show any examples that supports multiple different elements, so here is one 🙂
> add nc example

- Fundamentals/Code/Creating-Forms/index-v9.md
This migrates the "Creating Forms" to v9, I've primarily just updated the code examples to make them work on V9. Pretty much the only thing I changed in regards to the text is recommending creating an empty class instead of a controller template since we don't use any of the functionality from the controller template.
> Migrate creating forms to v9

- Reference/Management/Models/DataType-v6.md
- Reference/Management/Models/DataType.md
- Reference/Management/Models/index.md
Update data type (definition) for v8
- Create a v6 version
- Rename DataTypeDefinition to DataType
- Update link in index.md
- Remove needsV8Update labels
- Update constructor and properties section
> Update data type definition for v8

- UmbracoNetCoreUpdates.md
The installer does not create a solution, it creates a project. 
Therefor it should not be called MyCustomUmbraco**Solution**, but instead MyCustomUmbraco**Project**.
> Change MyCustomUmbracoSolution to MyCustomUmbracoProject

- Fundamentals/Setup/Server-Setup/index-v9.md
- Fundamentals/Setup/Server-Setup/permissions-v9.md
- Fundamentals/Setup/index-v9.md
Updated the https://our.umbraco.com/documentation/Fundamentals/Setup/Server-Setup/ and https://our.umbraco.com/documentation/Fundamentals/Setup/Server-Setup/permissions to v9 versions.
As always most text is reused from v8
> Updated permissions to match v9 + fixes index files

- Fundamentals/Setup/Install/install-umbraco-with-templates.md
Updated the command to use with beta 4
and added a note about NuGet feed conflicts and how to specify the specific pre releases feed.
> Update instructions for installing .net core beta 4

- Reference/Routing/custom-controllers-v9.md
Remove call to the SetDefaultRenderController extension method since it doesn't exists anymore. 
See [PR ](https://github.com/umbraco/Umbraco-CMS/pull/10614/files) to the CMS and the [PR ](https://github.com/umbraco/UmbracoDocs/pull/3323)to the docs.
> Remove SetDefaultRenderController

- Extending/Health-Check/index.md
I copied the custom 'SEO' health check sample code into my project from https://our.umbraco.com/documentation/Extending/Health-Check/ (8.0.0). 
To compile, the class needed to inherit from `HealthCheck` not  `HealthCheck.HealthCheck`.
This was in a v8.14 project.
> Fix to custom health check code

- Umbraco-Heartcore/API-Documentation/index.md
Added a note about a required header if the Content Delivery API is set to protected.
> Cleared up some confusion around this feature.

- Reference/Management/Models/Content-v6.md
- Reference/Management/Models/Content.md
- Reference/Management/Models/ContentType-v6.md
- Reference/Management/Models/ContentType.md
The version numbers are duplicated in the content [model article](https://our.umbraco.com/documentation/Reference/Management/Models/). Perhaps adding a meta.Title will solve this issue.
> Add meta.Title

- Add-ons/Umbraco-Deploy/Deploy-Settings/index-v9.md
- Add-ons/Umbraco-Deploy/Deploy-Settings/index.md
This setting was references as being an "undocumented feature" in [an issue](https://github.com/umbraco/Umbraco.Deploy.Issues/issues/5) I've been looking into, and doesn't seem to be any reason why it shouldn't be documented, so I think that's just an oversight.
Hence this PR to document it for V4 and V9.
> Added documentation on the Deploy configuration option ignoreBrokenDependencies

- Reference/Templating/Modelsbuilder/configuration-v9.md
The default PublishedModels namespace is missing "common", it's changed for v9.
See example from v9 RC1:
> updating for v9

- Extending/Database/index-v9.md
It came up in the gold partner "learn-a-thon" today that there's a couple of ways with V9 to do what's described in this article.  So here I've documented the second method, and fixed up a few things with the first for code changes that have been introduced since it was first reviewed and created.
@bergmania - just wondering if you have any thoughts about what the "best" method here is, and whether we should be advocating one, or just as I have document both.
> Updated create a database table article for V9

- Reference/Routing/custom-controllers-v9.md
The previously documented way worked great, but it make the backoffice not work at all any more, I tried this in 3 different example sites and finally figured out it was because the notation in this doc was causing some kind of global action filter to be triggered. 
When using the old code and going to `/umbraco` all you would see was just
```
System.InvalidOperationException: No UmbracoRouteValues feature was found in the HttpContext
at Umbraco.Cms.Web.Common.Controllers.UmbracoPageController.get_UmbracoRouteValues()
at Umbraco.Cms.Web.Common.Controllers.RenderController.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker …
```
> Update the way to get querystring variables in the index method

- Reference/V9-Config/ContentSettings/index.md
I've added "~/" to the path examples in the config to align it with how it's done elsewhere in the config documentation like in https://our.umbraco.com/documentation/Reference/V9-Config/GlobalSettings/
> Add tilde pattern to paths in config example

- Reference/V9-Config/filesystemProviders-v9.md
- Reference/V9-Config/index.md
This creates the V9 version of the `fileSystemProviders` section: https://our.umbraco.com/documentation/Reference/Config/fileSystemProviders/
I've updated the code examples, and also somewhat shortened the article, since the information is also available in the [extending filesystems section](https://our.umbraco.com/Documentation/Extending/FileSystemProviders/index-v9), so now we point to that document instead.
> Add filesystem providers to V9 Config section

- Tutorials/Custom-Error-Pages/index-v9.md
I've added a v9 guide on how to add a 404 page. I copy-pasted the current document and filled out the 404 section as I still don't know how to do the rest documented in the current document. I figured some v9 documentation was better than nothing.
> Added v9 guide to add 404 error page

- Umbraco-Cloud/Set-Up/Manage-Hostnames/Rewrites-on-Cloud/index.md
I have added an example of how to redirect umbraco.io to the actual domain when you are on the new infrastructure on Umbraco Cloud
> Added rewrite example for vNext

- Reference/Cache/cache-refresher-v9.md
- Reference/Cache/index-v9.md
- Reference/Cache/updating-cache-v9.md
Added more docs to the Reference/Cache section. 
Most docs are updated from v7 version, but a few changes are made. *
- Removed an example with donut cache that do not make sense for v9 / .NET5+
- Removed the small individual page for ICacheRefresher<T>.
> V9: Added Cache docs, updated from v7.

- Reference/Notifications/Creating-And-Publishing-Notifications.md
- Reference/Notifications/index.md
- Reference/Scheduling/index-v9.md
Migrates the scheduling documentation for running recurring background jobs to V9.
As a part of this I've also created a page about creating and publishing custom notifications, since this was needed for the  HostedService documentation, but it didn't make sense to me for it to live within the HostedService documentations, since it's really about notifiactions.
> V9: Add scheduling documentation

- Reference/Notifications/ContentService-Notifications.md
Umbraco.Cms.Core.Service.Notifications namespace does not exist. The above docs worked when changing the namespace to Umbraco.Cms.Core.Notifications
> Update namespaces in ContentService-Notifications

- Reference/Events/CacheRefresher-Events.md
Added an example of a cache event - the use case described is something I've been working on recently, and found that the cache events are covered in the docs at all, so figured I'd kick it off with an example 🙂
> add example of content cache event

- Extending/Health-Check/Guides/ContentSniffingProtection.md
The titles said "Click Jacking protection" instead of "Content/MIME Sniffing Protection". Titles were identical to https://our.umbraco.com/documentation/Extending/Health-Check/Guides/ClickJackingProtection so looks like a copy/paste error. Happens to the best of us :)
> Copy/paste text mistake on Content Sniffing Protection page

- Extending/Health-Check/Guides/CrossSiteScriptingProtection.md
The titles said "Click Jacking protection" instead of "Content/MIME Sniffing Protection". Titles were identical to https://our.umbraco.com/documentation/Extending/Health-Check/Guides/ClickJackingProtection so looks like a copy/paste error.
> Copy/paste text mistake on Cross-site scripting Protection page

- Reference/Using-Ioc/index-v9.md
This adds a V9 version of the dependency injection documentation: https://our.umbraco.com/documentation/Reference/Using-Ioc/
I've removed some sections like "Accessing LightInject container" since it doesn't make sense, and added some new ones like how to inject services into views, and how you should register dependencies in packages vs your own sites.
I've updated most links, however, two were missing the one for  UmbracoHelper and the one for Examine, I have updated all the code examples though.
> Add dependency injection docs for V9

- Reference/Events/index.md
- Reference/Notifications/ContentService-Notifications.md
- Reference/Notifications/ContentTypeService-Notifications.md
- Reference/Notifications/Creating-And-Publishing-Notifications.md
- Reference/Notifications/EditorModel-Notifications/index.md
- Reference/Notifications/MediaService-Notifications.md
- Reference/Notifications/MediaTypeService-Notifications.md
- Reference/Notifications/MemberTypeService-Notifications.md
- Reference/Notifications/index.md
When working on creating a new blog on comparing v8 events and v9 Notifications, I came across a bunch of small mistakes and typo's across several pages having to do with Notifications.
> Fixed a broad range of typo's in v9 notification pages

- Reference/Angular/Services/editorService/Index.md
Spotted that the meta data for this article is wrong, so here's a PR to rectify that.
This article was originally written for Umbraco 8, and should therefore also apply to Umbraco 9.
Earlier versions of Umbraco 7 also had an `editorService`, but it was deprecated in favor of the `<umb-overlay />` directive in later versions of Umbraco 7. This article was never about any of those two.
> Updated editorService meta data

- Fundamentals/Setup/Requirements/index-v8.md
- Fundamentals/Setup/Requirements/index.md
As discussed on [Twitter](https://twitter.com/callumbwhyte/status/1455522459504029698), the docs around system requirements are a little ambiguous around support for Edge.
Microsoft released Chromium Edge in January 2020 and "Edge Legacy" has been considered obsolete since March 2021: https://support.microsoft.com/en-gb/microsoft-edge/what-is-microsoft-edge-legacy-3e779e55-4c55-08e6-ecc8-2333768c0fb0
Some [recent changes](https://github.com/umbraco/Umbraco-CMS/commit/f43d84787dfaa6b47562a5d2af148c9f17be9563) have meant the backoffice breaks in non-Chromium edge. Perhaps this is a bug and should be fixed anyway...?
This PR aims to clarify that the supported Edge browser is only the Chromium version.
> Clarify Edge browser requirements

- Reference/Routing/Request-Pipeline/IContentFinder-v7.md
Just tested the XPath query on a v7 project, but it doesn't work, because the XPath query isn't correct.
Id is an attribute in XML, so it should be using `@id` instead of `id`.
See example example here: https://our.umbraco.com/forum/developers/xslt/20513-XPath-Expression-for-nodes-starting-at-specific-node#comment-77782
> Fix XPath query in My404ContentFinder

- Reference/Querying/UmbracoHelper/index.md
Accessor should only be used to get access to scoped service in singleton contexts.
> Removed unnecessary usage of IUmbracoHelperAccessor

- Reference/Templating/Modelsbuilder/configuration.md
In the example it says to use the generate models in the SourceCodeAuto mode, which generates the models automatically. It should be SourceCodeManual.
> Changed what mode generate button should be used

- Reference/Notifications/index.md
- Reference/V9-Config/index.md
- Reference/index-v8.md
- Reference/index.md
Making the reference page v9 by default but adding a v8 version and some links to v8 versions where relevant.
> Updating reference docs to v9

- Reference/Routing/custom-routes.md
Added a note about using `IUmbracoContextFactory `instead of `IUmbracoContextAccessor `to get Umbraco Context inside `FindContent `if your controller endpoint is considered a client side request. 
Related to this issue: https://github.com/umbraco/Umbraco-CMS/issues/11692
> Adds note about getting Context in FindContent

- Reference/Templating/Modelsbuilder/configuration.md
Fixed the typo in the namespace of the config var
> Fixed the typo in the namespace of the config var

- Reference/Config/index.md
certainly because the folder is much lower in the menu. We should have created (or moved) files within the config folder. The current solution is all but handy and practical
> Umbraco v9 configuration should be at least mentioned on the /config

- Extending/UI Library/index.md
Meta title and meta description was missing for this page.
This is especially a problem for the title in the browser, which now shows: "UI%20Library":
> Added meta.title and meta.description for UI Library

- Extending/Property-Editors/index.md
Built in Property Editors articles are available for v9 right?
> Remove: "(Currently only available for Umbraco 8)"

- Reference/V9-Config/MaximumUploadSizeSettings/index.md
- Reference/V9-Config/index.md
So this comes from a number of issues raised on the CMS, where you cannot upload a file larger than 28.6MB, so I thought some documentation on how to do so would be appreciated!
This contains a how-to of the 2 most used services with .net core (kestrel & IIS) but also links to documentation on how to change this with apache and nginx 👍
> v9: Maximum Upload Size documentation

- Fundamentals/Code/Debugging/Logging/index-v8.md
- Fundamentals/Code/Debugging/Logging/index-vpre-8.6.0.md
Microsoft deleted the assets.windowsphone.com domain therefore Get it for Windows badge is failing to render. I've just replaced it with a different URL to get the badge
> Microsoft abandoned the development of Windows Phone

- Extending/Section-Trees/tree-actions-v8.md
- Extending/Section-Trees/tree-actions.md
Spurred by [the issue raised following CMS release 9.2 of a clashing permission letter](https://github.com/umbraco/Umbraco.Deploy.Issues/issues/95), this PR updates the documentation to ensure we've published the currently used permission letters by HQ products.
> Updated list of tree action and permission letters used in CMS and Deploy

- Extending/Property-Editors/package-manifest-vpre9.2.md
- Extending/Property-Editors/package-manifest.md
Adds a new small section in the package manifest document, detailing the new properties added as part of the new telemetry added in 9.2.
> Add information about package telemetry properties

- Tutorials/Creating-a-Custom-Dashboard/index.md
Wouldn't it be nicer to always write an alias with a lowercase letter? This is also common in other places, such as doctypes, etc. In addition, it prevents inconsistent use within language files.
> Rename alias of  WelcomeDashboard to welcomeDashboard

- Reference/Templating/Mvc/views.md
The `Url` property has been obsolete for a while in v8 and in v9 I believe it has been removed and instead `Url()` extension method should be used.
> Update to use Url extension method

- Umbraco-Cloud/Set-Up/Media/index-v7.md
- Umbraco-Cloud/Set-Up/Media/index.md
Noticed that we were still showing a blob migration warning on the Setup/Media pages, even thoug the migrations have been done for quite some time now 🙈
> Remove blob migration warning

- Implementation/Unit-Testing/index.md
I updated the v8 example of an UmbracoApiController unit test to a v9 example.
> Updated v8 example of UmbracoApiController test to v9

- Reference/Cache/updating-cache-v8.md
Moved the link out of the codeblock as it gets wrongly interpreted (as seen in screenshot)
> Moved link from codeblock to normal text

- Reference/V9-Config/index.md
This adds the missing section about using UserSecrets for storing configuration settings.
Also fixed a couple of typos and wordings.
Fixes #3775
> Add docs for UserSettings config

- Umbraco-Cloud/Deployment/Local-to-Cloud/index.md
Just a quick PR to fix typos in the metadata and add a link to Git for Windows (instead of referencing Git Bash) in the Local to Cloud article.
> Update Local to Cloud

- Tutorials/Custom-Error-Pages/index.md
I believe that the custom boot failed error page is available for v9 as well. Hence updating the docs
> Custom boot failed error page

- Reference/Security/Serverside-sanitizing/index-v8.md
- Reference/Security/Serverside-sanitizing/index.md
In 9.3 and 8.18 we've added a new interface `IHtmlSanitizer` people can implement themselves to easily allow for serverside sanitization of the rich text editor content. This adds documentation describing how to use the new interface.
I've intentionally left the specific implementation up to people themselves since we shouldn't really be opinionated about what library people should use to sanitize HTML since they all how their own flavours of issues with strict dependencies.
> Add documentation for using IHtmlSanitizer

- Fundamentals/Design/Rendering-Content/index-v8.md
Noticed that the code sample as lower case m rather than upper case M. 
Was using the samples and noticed it didn't recognise `model` but `Model` worked fine.
> Changing model to Model within code snippet

- Reference/Notifications/EditorModel-Notifications/index.md
The name of the constructor name was different than the class name.
> Fix Constructor name

- Tutorials/Custom-Error-Pages/index.md
updated the generic error page section, as it wasn't updated for v9
> generic error page section update

- Add-ons/Umbraco-Deploy/Installing-Deploy/Install-Configure/index.md
I realised that this had been missed off the V9 version of this page, and is necessary for Umbraco Deploy on-premises (i,e, when not installed on Cloud).
Came up in [this support request](https://umbraco.slack.com/archives/C0968J7PU/p1645807938426169) for background.
> Added missing detail about configuration for Umbraco Deploy on-premises

- Add-ons/Umbraco-Deploy/Installing-Deploy/Install-Configure/index.md
Following on from [this PR](https://github.com/umbraco/UmbracoDocs/pull/3815), now merged, there's one more piece of information we have realised was missing from the configuration details for Umbraco Deploy On-Premises.
> Further update to umbraco deploy on-premises config.

- Reference/V9-Config/ContentSettings/index-v9.1.0.md
- Reference/V9-Config/ContentSettings/index.md
From Umbraco v9.4.0 two new config settings can be set as part of the Content Settings - `DisableDeleteWhenReferenced` and `DisableUnpublishWhenReferenced` - following from [this PR](https://github.com/umbraco/Umbraco-CMS/pull/12047).
> Update Content settings to include the disable actions when referenced settings

- Reference/Routing/custom-routes.md
Changes sections formatted as code inside a note to be formatted as bold. The rendering of the note looks wierd, and I suspect it's the code formatting inside the note that is the issue. I also added to the note, that you can't implement IVirtualPageController when your request is a client-side request.
What I am trying to fix:
> Note formatting

- Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Grid-Layout/Grid-Editors-v7.md
- Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Grid-Layout/Grid-Editors.md
This file doesn't exist by default any more and you need to add in order to do any customizations
> Describe how to create a `grid.editors.config.js` in v9

- Reference/Routing/custom-routes.md
After trying to follow this example, I discovered that `IUmbracoContextAccessor` doesn't let you reference `UmbracoContext`, so you either have to use `_umbracoContextAccessor.GetRequiredUmbracoContext();` or `_umbracoContextAccessor.TryGetUmbracoContext()`
> UmbracoContextAccessor doesn't contain a reference to UmbracoContext

- Reference/V9-Config/index.md
https://our.umbraco.com/documentation/Reference/V9-Config/RichTextEditorSettings/ Based on this forum post, the config explain was missing, i only found the page in the docs GIT, but let´s embress that page
> Update v9-config index.md, for ref to RTE

- Reference/Scheduling/index.md
I have changed the namespace to MySite. This will make it clear that it is custom code you will need to add to your site. I have choosen MySite since it is used already: https://our.umbraco.com/Documentation/Reference/Notifications/MemberService-Notifications/
I have renamed the extension method AddCustomHostedServices. This is to avoid confusion with Umbraco.Extensions.UmbracoBuilderExtensions.AddHostedServices
> Rename in Scheduling documentation

- Fundamentals/Setup/Server-Setup/azure-web-apps.md
Ran into this issue today and spent a while scratching my head, so I think it's definitely worth mentioning.
One thing I haven't included was that I inadvertently ran into this issue using Azure Devops (see my comments on the issue) but this feels overly specific so I haven't included this in the documentation.
Here's the relevant issue: https://github.com/umbraco/Umbraco-CMS/issues/12043
> Added a note about read-only file systems

- Extending/Property-Editors/package-manifest.md
We had missing info about a property available in our package.manifest
https://github.com/umbraco/Umbraco-CMS/pull/10691
> Updates package.manifest example with missing info about bundleOptions

- Reference/Scheduling/index-v8.md
This updates the documentation section on scheduling by adding a reference to the Services and Helpers article explaining how and when to use `UmbracoContextFactory` as discussed in issue #3682.
> Added reference to Services and Helpers

- Umbraco-Cloud/Set-Up/External-Services/index.md
It has now been confirmed by Microsoft that port 25 will continue to be blocked in our static outbound ip setup.
> Update external services with port 25 specifics

- Add-ons/Umbraco-Deploy/Deploy-Settings/index-v8.md
- Add-ons/Umbraco-Deploy/Deploy-Settings/index.md
- Add-ons/Umbraco-Deploy/Extending/index-v8.md
- Add-ons/Umbraco-Deploy/Extending/index.md
I'm not sure exactly when this will be needed yet, but earliest would be 5th April for the release candidate - which is when we should update the docs.
> Docs updates for upcoming 4.6.0/9.4.0 release of Umbraco Deploy.

- Reference/V9-Config/MaximumUploadSizeSettings/index.md
Adds note to the IIS method, notifying the reader that it's the method to be used on sites hosted on Umbraco Cloud.
> Note about Cloud

- Reference/V9-Config/InstallDefaultDataSettings/index.md
- Reference/V9-Config/index.md
This updates the documentation section on configuration for some additional settings introduced by [this PR](https://github.com/umbraco/Umbraco-CMS/pull/12122), and expected in 9.5 (expected in six weeks time).
> Added details on the configuration options available for install of Umbraco default data.

- Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Eye-Dropper-Color-Picker/index.md
In v9 we updated the value type of Eye Dropper Color Picker to return a `string` instead of a generic `object`, which is also the default generated value type using in ModelsBuilder if no value converter is found.
https://github.com/umbraco/Umbraco-CMS/pull/10853
> Eye Dropper Color Picker value type in v9

- Extending/Language-Files/index.md
Small, un-indenting fix for the code samples to reinstate the syntax-highlighting.
> Fix syntax highlighting in Localization samples 

- Reference/V9-Config/SecuritySettings/index.md
Documentation mismatch causes confusion for developers, I can attest!
So does : https://our.umbraco.com/forum/using-umbraco-and-getting-started/108929-keepuserloggedin-v9#comment-338152
> Updates property name to match appsettings-schema

- Reference/Querying/MemberShipHelper/index.md
When visiting this article right now, it looks like it should be valid for Umbraco 9 as well.
However, in the YAML tags is says `versionRemoved: 9.0.0`.
I've added a note to the article, to make it clear that this article is not valid for v9 or above.
Also added a `versionTo` tag, to make it a little clearer.
> Added a note in an attempt to avoid confusion

- Fundamentals/Setup/Upgrading/version-specific.md
In RC2 of v10 the intellisense for the appsettings file has been re-introduced, but requires a small change for existing sites.
I've updated the upgrade docs to show how you re-enable the intellisense :)
> V10: Update the upgrade page to show how to re-enable appsettings intellisense in v10

- Add-ons/Umbraco-Deploy/Installing-Deploy/CICD-Pipeline/ci-cd-azure-dev-ops.md
This just updates the versioning on a documentation page for Deploy, that only applies to V8.  We'll need to create a V9 version.
> Update version on deploy ci/cd doc

- Extending/Content-Apps/index.md
Adding a couple of `@using` statements that was missing from the C# sample - this also applies to the latest version of 9.
There is one difference between v10 and v9 when testing this article.
For v10, VS suggests adding a `?` to the ContentApp method in the C# sample:
```
public ContentApp? GetContentAppFor(object source, IEnumerable<IReadOnlyUserGroup> userGroups)
{
```
It seems to be related to the nullable references.
When adding the same to the v9 code, it still works, only gives a warning.
> Verify Content Apps article for v10

- Reference/Security/Two-factor-authentication/index.md
The only difference between v10 and v9 in `UmbracoUserAppAuthenticator.cs` code:
```
public string? QrCodeSetupImageUrl { get; set; }
public string? Secret { get; set; }
```
> Updated 2FA article for v10

- Extending/Property-Editors/Tracking/index.md
There is one difference between v10 and v9 when testing this article.
For v10, VS suggests adding a ? in the C# sample:
```
public bool IsForEditor(IDataEditor? dataEditor) => dataEditor?.Alias == Constants.PropertyEditors.Aliases.Label;
public IEnumerable<UmbracoEntityReference> GetReferences(object? value)
```
> Verified Tracking article for v10

- Reference/Security/backoffice-user-manager.md
The page is still valid for v9 and since 9.5 it make sense to change `true` to `false ` in the example.
> Updated backoffice user manager docs

- Reference/Routing/Authorized/index.md
Opdated this page to v10. The only changes between v9 and v10 is the nullable reference types, so I still thing it is better to share the page for both v9 and v10, compared to copy paste every thing.
> Updated Reference Routing Authorized to v10

- Reference/Routing/Request-Pipeline/outbound-pipeline.md
I reused the page as 99% is identical between v9 and v10.  Mainly nullable reference types. Also removed a code block that did not bring any value.
> Updated Reference>Routing>Request Pipeline> Outbound pipeline to v10

- Fundamentals/Setup/Upgrading/version-specific.md
Removed this statement:
using Umbraco.Cms.Web.Common.Hosting
After testing the upgrade from 9 -> 10  I discovered that this using statement wasn't being used at all.
> Removing using statement from code example

- Implementation/Nullable-Reference-Types/index.md
Created a new article for nullable reference types.
Not sure if putting it in the Implementation tap is the right place to add the article.
Please let me know if it should be moved somewhere else.
> v10: Created new article for Nullable reference types

- Umbraco-Cloud/Set-Up/Working-With-Visual-Studio/index.md
Documentation updated to provide information on [this issue](https://github.com/umbraco/Umbraco.Deploy.Issues/issues/124), caused when renaming the local project folder on a Cloud project.
> Added details of renaming git hook when renaming the project folder for a Cloud project.

- Extending/Database/index.md
Ntext is deprecated in favor of nvarchar(max)
[quote from the microsoft docs](https://docs.microsoft.com/en-us/sql/t-sql/data-types/ntext-text-and-image-transact-sql?view=sql-server-ver16)
> The ntext, text, and image data types will be removed in a future version of SQL Server. Avoid using these data types in new development work, and plan to modify applications that currently use them. Use [nvarchar(max)](https://docs.microsoft.com/en-us/sql/t-sql/data-types/nchar-and-nvarchar-transact-sql?view=sql-server-ver16), [varchar(max)](https://docs.microsoft.com/en-us/sql/t-sql/data-types/char-and-varchar-transact-sql?view=sql-server-ver16), and [varbinary(max)](https://docs.microsoft.com/en-us/sql/t-sql/data-types/binary-and-varbinary-transact-sql?view=sql-server-ver16) instead.
> Do not use NText anymore, nvarchar(max)

- Reference/Searching/Examine/index.md
Examine has an unintended breaking change for indexing special characters.
Updated docs to make people aware.
> Add note about Examine 1.2.1 breaking change

- Umbraco-Cloud/Upgrades/Migrating-from-9-to-10/index.md
When I build I get the message that Umbraco.Cloud.StorageProviders.AzureBlob version 5.0.0 doesn't exist, and it will use 10.0.0 instead.
> Update blob version number in Cloud 9 to 10 guide

- Extending/Backoffice-Tours/index.md
- Extending/Language-Files/index.md
Updated the Language Files article.
Updated the Backoffice Tours articles
Other related articles:
[Backoffice - Login](https://our.umbraco.com/documentation/Fundamentals/Backoffice/Login/)
[Custom Error Pages](https://our.umbraco.com/documentation/Tutorials/Custom-Error-Pages/#errors-with-booting-a-project)
> v10: Update articles with references to embedded resources

- Reference/Templating/Mvc/partial-views.md
for v9 and 10 and moved the note a bit down to reflect that it is only the three code examples that has not been verified yet.
> Updated the partial views with the new method signature

- Extending/Embedded-Media-Provider/index.md
Fix url to apidocs in the **[Embedded Media Provider](https://our.umbraco.com/documentation/Extending/Embedded-Media-Provider/)**  article.
> Fix url to apidocs

- Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/File-Upload/index.md
- Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Media-Picker-3/index.md
I've made a few different things in this PR:
- Verified and updated the C# code sample for the Media Picker. Replaced the existing with the one from the legacy Media Picker article, as that worked for this Media picker as well. Not sure why the other sample was added to the Media Picker article - but I might be missing something.
- Noted that we're not going to update the C# sample in the File Upload article as we want people to be using the Media Picker for uploading media and files to their projects instead.
> Media Picker should be used instead of File Upload

- Extending/Section-Trees/trees.md
* Missing usings
* Added a reference section to make clear that a reference is needed to Umbraco.Cms.Web.BackOffice to implement MenuRenderingNotification
> Missing usings and added Reference section

- Reference/Scheduling/index.md
Update the code sample. Pass in an instance of `ILogger` in to the base constructor as suggested in https://github.com/umbraco/UmbracoDocs/issues/3883.  Added a note instead of creating a specific file targeting versions before 9.4 as @sofietoft suggested here: https://github.com/umbraco/UmbracoDocs/issues/3883#issuecomment-1081739309
Fixes: https://github.com/umbraco/UmbracoDocs/issues/3883
> Update scheduling article

- Umbraco-Cloud/Security/index.md
The ARRAffinity cookie has been removed for all Cloud projects created after the 25th of February 2022. 
The old projects still have the ARRAffinity cookie enabled.
> ARRAffinity cookie update

- Extending/Backoffice-Tours/index.md
Made some small changes to the section about tours files. This applies for Umbraco 9 later versions.
At the bottom of the article, we have a section called [How to Filter/Disable Tours from being shown](https://our.umbraco.com/documentation/Extending/Backoffice-Tours/#how-to-filterdisable-tours-from-being-shown). 
The code meant to filter out tours based on the file name does not seem to work. It keeps showing the backoffice tour even though I am filtering by the file name used.
Lines 233-234:
```
builder.TourFilters()
.AddFilterByFile("custom-tours.json");
```
The rest of the filters work fine.
> Backoffice tours updates

- Add-ons/UmbracoForms/Developer/Extending/Adding-an-Event-Handler.md
The method `GetPostFieldValue(Form form, HttpContext context, string key)` need `HttpContext` passed in as second parameter.
Furthermore there is no `e` at use of `GetPostField()` method - it takes `Form` as first parameter.
Not sure how the docs should be handled regarding .NET5 vs .NET6.
In Umbraco 10 / Umbraco Forms 10 `GetPostField()` returns a possible nullable `Field`:
```
using Microsoft.AspNetCore.Http;
using Umbraco.Cms.Core.Events;
using Umbraco.Forms.Core.Models;
using Umbraco.Forms.Core.Services.Notifications;
namespace MyProject.Core.Notifications
{
/// <summary>
/// Catch form submissions before being saved and perform custom validation.
/// </summary>
public class FormValidateNotificationHandler : INotificationHandler<FormValidateNotification>
{
public void …
```
> Add missing HttpContext passed into GetPostFieldValue method

- Extending/Property-Editors/Declaring-your-property-editor-v8.md
Most C# is different. Also fixed a few bugs in the v8 version. The `ddd` class was not mentioned and changed "Get get" to "To get"...
> Added v9-v10 version of Declaring-your-property-editor.

- Fundamentals/Setup/Requirements/index.md
- Umbraco-Cloud/Upgrades/Upgrading-from-9-to-10/index.md
The system requirements for Umbraco 10 currently list Visual Studio 2019.
However, VS2019 does not include support for C# 10 and any of the modern C# features being used in Umbraco including:
- Global usings
- File scoped namespaces
Some of these features are used within the Umbraco templates by default, meaning you can't built your solution in VS2019.
Confirmation of this can be found in the .NET 6 launch blog post: https://devblogs.microsoft.com/dotnet/announcing-net-6/#support
This PR bumps the minimum recommended Visual Studio version to VS2022.
> V10 system requirements require VS2022 for .NET 6 support

- Implementation/Unit-Testing/index.md
@sofietoft Turns out nothing new in v10 breaking these examples, everything works just as it did in v9.
So just needed to update the **versionTo** header.
Cheers!
> Verified Unit Testing docs for v10

- Reference/Configuration/HealthChecks/index.md
I came across this when looking to re-use this setting pattern for a feature in Umbraco Forms, and realised that it had been described incorrectly.
@nikolajlauridsen - would you mind double-checking that you agree with my change please? Thanks.
> Corrected description of health check settings first run time.

- Reference/Security/Authenticate-with-Active-Directory/index.md
Callbackpath cannot be the same as the default /umbraco backoffice route.
> Updating Callbackpath

- Add-ons/Umbraco-Deploy/Deploy-Settings/index-v8.md
- Add-ons/Umbraco-Deploy/Deploy-Settings/index.md
This adds details of a currently undocumented setting that allows Umbraco Deploy to be used 
There's a couple of issues being fixed in the next patch release that makes this available, so should be held until they are out (likely 16/8/2022).
> Documented Umbraco Deploy's BackOfficeOnly setting.

- Add-ons/UmbracoForms/Developer/Magic-Strings/index.md
Making a note that Record.Id is only accessible on workflows trigged "on approve". 
This update was made after raising an issue - https://github.com/umbraco/Umbraco.Forms.Issues/issues/835
> Update to Magic String information for record.id

- Add-ons/UmbracoCourier/index.md
- Add-ons/index.md
Since the official support for Umbraco Courier has ended, removing the section from the Add-Ons landing page.
> Removed Umbraco Courier section from the Add-Ons landing page

- Add-ons/UmbracoForms/Editor/Attaching-Workflows/Workflow-Types/index-v7.md
- Add-ons/UmbracoForms/Editor/Attaching-Workflows/Workflow-Types/index.md
These details were provided to help with a support request and are likely useful to have in the documentation for people to find or be pointed to in future.
> Details and code sample for using Forms send to URL workflow.

- Reference/Searching/Examine/index.md
I think after the revamp of the Examine documentation for v10, we can safely remove the note about it only being tested on v8 💪
> Remove note about documentation only being tested in v8

- Reference/Management/Services/MediaService/Index.md
Unlike v8, we no longer can use the example with HttpPostedFileBase in v9. The statement is misleading so have updated that
> No example of HttpPostedFileBase

- Extending/Backoffice-Search/index.md
- using `parentID` was not working, so this has been changed to `nodeType`
- added warning about integers not being searchable this way
> Update backoffice search documentation

- Reference/Searching/Examine/Indexing/index-v8.md
- Reference/Searching/Examine/Indexing/index.md
This is still a draft because a lot of this section cannot actually be completed before an Examine bug has been fixed.
When the bug has been fixed this should be ready for an internal D-team review 💪 
- Revamped the custom indexing section for v9 & 10
- This now used the `ConfiguredNamedOptions` pattern instead of the `UmbracoIndexConfig` pattern
> v9 & v10: Examine custom indexing

- Tutorials/Creating-a-Custom-Dashboard/index.md
By following and to some extend understanding the instructions on this brilliant tutorial I managed to create a friendly welcome screen for my editors. The dashboard includes the suggested activity log which is a nice feature.
However, if editors save or publish a page several times, it will appear on the "pick up where you left off" list several times. Ideally, a node would only appear on the list once, regardless of multiple saves or publishes.
The activity log function seems to attempt to take care of this, but for some reason it does not, at least not in my case. 
So being a Angular JS rookie I tried to rewrite the loop to better understand what is going on. And this code actually works. Maybe other users could benefit from this.
> update activity log function

- Reference/Configuration/GlobalSettings/index.md
- Reference/Security/Security-hardening/index-v9.md
- Reference/Security/Security-hardening/index.md
This PR removes all documentation of `UmbracoPath` being configurable, as the feature is broken for V10+ and will not be fixed. 
Changing `UmbracoPath` is a security-by-obscurity pattern. A much better option is using IP restrictions as documented in the "Security hardening" article. Said article has also been rewritten in this PR to reflect `UmbracoPath` no longer being configurable, as well as removing a few remnants from earlier versions.
See also https://github.com/umbraco/Umbraco-CMS/pull/13032
> UmbracoPath is no longer configurable

- Reference/Configuration/MaximumUploadSizeSettings/index.md
I found this typo when Googling for some docs, so thought I would correct it!
> Correct typo in MaximumUploadSizeSettings meta title

- .github/styles/UmbracoDocs/Acronyms.yml
- Fundamentals/Setup/Server-Setup/Load-Balancing/flexible-advanced.md
- Fundamentals/Setup/Server-Setup/permissions-v10.md
- Umbraco-Cloud/Troubleshooting/troubleshooting-frontend.md
- Umbraco-Cloud/Upgrades/Migrating-from-8-to-10/index.md
- Umbraco-Cloud/Upgrades/Minor-Upgrades/index.md
- Umbraco-Heartcore/API-Documentation/index.md
- Umbraco-Heartcore/Client-Libraries/Dot-Net-Core/MVC-Sample/index.md
- Umbraco-Heartcore/Getting-Started-Cloud/Webhooks/index.md
- Umbraco-Heartcore/Tutorials/Creating-A-Custom-Grid-Editor/index.md
All acronyms should be defined before continuous use in an article.
This means that when an acronym is used in an article, the first use case needs to be accompanied by a definition.
Examples have been added to the PR.
Also, a long list of excluded acronyms have been added to the rule.
This is in order to accommodate the API docs, markup languages and other commonly used acronyms like `IIS` and `CMS`.
> Added rule that catches whether an acronym has been defined

- Fundamentals/Setup/Server-Setup/Load-Balancing/azure-web-apps.md
AppDomain does not exist in netcore so have replaced it with "Host"
This description needed updating to match the MainDomLock setting
> Update Azure Load Balancing Maindom description 

- Umbraco-Cloud/Set-Up/Working-Locally/index.md
I know this is a minor thing, but I just thought that newcomers to Visual Studio and Umbraco might not find it obvious that the Class Library we add here is the ".Core" 😁
Any feedback is appreciated 😀
> Clarifying name of Class Library

- Add-ons/Umbraco-Deploy/Extending/index-v8.md
- Add-ons/Umbraco-Deploy/Extending/index.md
- Add-ons/UmbracoForms/Developer/index.md
This fixes a couple of layout and detail issues in this page, as well as adds a note about obsolete methods introduced in 4.7/9.5/10.1.
> Fixed a couple of layout and detail issues in Deploy's extending for custom entities documentation.

- Extending/Macro-Parameter-Editors/index-v8.md
Just a small edit to fix a broken link that I found when reading the documentation for Macros. 
The link was pointing to a now removed page for V8, I've change the link to point to the main Property Editors page.
> Macro Parameter Editors has a broken link

- Getting-Started/Where-can-I-get-help/index.md
The previous version implied contacting directly to the Team but the link was for the Docs issue tracker.  I thought it would be better when consistent with the CMS issue tracker.
> Readability on Where can I get help.

- Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-Grid-Editor/index.md
Unlike block list, the default rendering for block grid utilizes built-in views within the `Umbraco.Cms.StaticAssets` class library to construct the rendered grid output. 
Some have reported this as being strange and bad for DX and discoverability. 
Unfortunately, due to limitations on package formats we cannot move the files to a more easily discovered location, so this PR adds additional notes to the block grid documentation about where to find these built-in views, in case one wants to change them (or simply want to figure out what's going on).
> Clarify how block grid output is constructed by built-in views

- Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-Grid-Editor/index.md
'wether' is a misspelling of 'whether'
'neglect' didn't make sense in this context - to neglect to do something is a less deliberate action than Umbraco absolutely refusing to move a block to an incompatible area
> Update block grid docs

- .github/styles/UmbracoDocs/Acronyms.yml
More people will know the acronyms that the definitions here, as both are programming languages.
> Add AJAX and XSLT to the acronym exception lists

- Implementation/Rest-Api/index.md
The current Rest Api page only redirects to the official Umbraco Heartcore product page. I thought it would be a useful addition to add a follow-through to the Heartcore Api Documentation too, as some may end up on this page, looking for information on Heartcore instead! 🙂
> Follow-Through from Rest API to Heartcore

- Reference/Security/External-login-providers/index.md
When people are reading the documentation about external login providers it can help them to show a working example which they can download and run without any configuration.
> Added link to Umbraco OpenID Connect example package.

- Reference/Configuration-for-Umbraco-7-and-8/nucache-settings.md
- Reference/Configuration/NuCacheSettings/index-v8.6.md
- Reference/Configuration/NuCacheSettings/index.md
We mention how to set ignorelocaldb for V8 in load balancing docs but now we have a specific NuCache settings page for V9+ makes sense to do a V8 version here?
Fixes #4456
> Add V8 version of Nucache settings

- Reference/Searching/Examine/Indexing/index-v8.md
Notied that there is no mention of ValueSetBuilder and IndexPopulator in V* docs. So added a link to the v9 example with update to the V8 composer on how to register the implementations
> Updated Examine docs for V8

- Umbraco-Cloud/Set-Up/Project-settings/index.md
As it is now possible to add basic auth on environments on cloud again, i have added it to our docs again.
There will still be made some changes to it as described in the following PR: 
- https://github.com/umbraco/UmbracoDocs/pull/4176#issuecomment-1278878795
> Added basic auth back to project settings

- Umbraco-Cloud/Databases/Backups/index.md
This is an amend to the documentation, with thanks to Seb for his help. It outlines the steps required to restore a bacpac file from an Umbraco Cloud backup to a local SQL Server instance
> Instructions for restoring a bacpac file

- .github/styles/UmbracoDocs/Names.yml
- Add-ons/Umbraco-Deploy/Installing-Deploy/CICD-Pipeline/ci-cd-azure-dev-ops-v8.md
- Extending/Health-Check/index-v8.md
- Extending/Health-Check/index.md
- Fundamentals/Code/Debugging/Logging/index.md
- Fundamentals/Code/Source-Control/index-v9.md
- Fundamentals/Setup/Upgrading/version-specific.md
- Implementation/Custom-Routing/signalR.md
- Reference/Configuration-for-Umbraco-7-and-8/dashboard/index-v7.md
- Reference/Configuration/ConnectionStringsSettings/index-v9.md
- Reference/Configuration/ConnectionStringsSettings/index.md
- Reference/Configuration/ContentSettings/index-v9.0.0.md
- Reference/Configuration/ContentSettings/index-v9.1.0.md
- Reference/Configuration/UnattendedSettings/index.md
- Reference/Management/Models/index.md
- Reference/Management/Services/index.md
- Reference/Management/index.md
- Reference/Routing/Request-Pipeline/published-content-request-preparation.md
- Reference/Routing/Umbraco-API-Controllers/index.md
- Reference/Security/Auto-linking/index.md
- Reference/Security/Security-hardening/index-v9.md
- Reference/Security/index-v7.md
- Reference/Using-Ioc/index.md
- Umbraco-Heartcore/API-Documentation/Redirect/index.md
- Fixed some casing warnings for `Umbraco` and `.NET`
- Added a regex rule for `js` and `[jJ]ava[sS]cript`
- This fixes the warnings showing where lower case `js` is used correctly with a `.` before it, for example `Node.js`
- Added a regex rule for `[aA]ngular[jJ][sS]` to fix casing warnings
@sofietoft Let me know what you think about the regex/if it's not helpful!
> Casing fixes + add regex for name rules

- Extending/Section-Trees/Trees/index-v8.md
- Extending/Section-Trees/Trees/index.md
Noticed that Section Trees uses a mixture of _italics_ and `code` to mention code.  I have made it uniform
> Improve readability of section trees

- Tutorials/Custom-Error-Pages/index.md
The format of the configuration examples on the "Custom Error Page" docs is a bit out of whack... I've fixed it!
> Fix custom error page config formatting

- Reference/Configuration/Serilog/index.md
The provided config sample was out-of-date. It doesn't match what you get in Umbraco 10.3 and it doesn't match the description in the second paragraph after the "Specifying minimum log level" heading.
> Update config sample

- Extending/Key-Vault/index.md
CreateHostBuilder updated to v10 (it's currently the v9 version) and the Constants.Azure.AzureKeyVaultEndpoint doesn't exist so it should be a string in the sample.
> Fix the KeyVault code sample

- Fundamentals/Data/Content-Version-Cleanup/index.md
Had a question on the forum asking what happens after 90 days as existing wording sort of hinted the document would be deleted... I thought restructuring it like this might make it clearer that Published content is never deleted? The settings are a bit of a mouthful, so probably only so much we can do!
> Update wording of explanation of default Content Version Cleanup

- Extending/Health-Check/Guides/StrictTransportSecurityHeader.md
While looking at https://github.com/umbraco/Umbraco-CMS/pull/13166 I noticed that this guide does not use the recommended approach to enabling HSTS in ASP.NET Core.
I've updated the guide to use the recommended extension method built into ASP.NET Core.
> Update HSTS health check guide based on ASP.NET docs

- Reference/Common-Pitfalls/index-v11.md
- Reference/Common-Pitfalls/index-v9.md
- Reference/Common-Pitfalls/index.md
Removes the reference to the `UmbracoApplicationMainDomAcquiredNotification` in the common pitfalls document, since this notification no longer exists in V11 😄 
I'm still a bit shaky about the whole multiple versions thing, but I've copied the old one and named it `index-v9.md` even though it covers both v9 and v10 and then made index.md be the v11 one. Feel free to change this if I've done it wrong 😄
> V11: Remove reference to UmbracoApplicationMainDomAcquiredNotification in common pitfalls

- Reference/Configuration/RequestHandlerSettings/index.md
We added an extra setting in v9 to the `RequestHandlerSettings`, in this PR: https://github.com/umbraco/Umbraco-CMS/pull/11386
This PR adds that setting to the docs aswell 👍
> Add EnableDefaultCharReplacements to settings

- Add-ons/UmbracoForms/Editor/Attaching-Workflows/index.md
- Reference/Notifications/SendingAllowedChildrenNotification/index.md
During [DF22](https://df22.nl/) @dawoe did a talk of the unknown features of Umbraco. One of the subjecs was `SendingAllowedChildrenNotification`
I think it would be nice if we can add an example to the docs
> Add sending allowed children notification article

- Add-ons/Umbraco-Deploy/Extending/index.md
- Add-ons/Umbraco-Deploy/Upgrades/version-specific.md
- Add-ons/UmbracoForms/Installation/Version-Specific.md
This adds the documentation about Forms and Deploy 11, mostly just adding the breaking changes for reference.
Now the first release candidates are out, these can be reviewed and published at any time.
> Upgrade notes for Forms/Deploy 11

- Reference/Response-Caching/index.md
- Reference/index.md
- Tutorials/Cache-Static-Assets/index.md
- Tutorials/index.md
The current tutorial name of "Cache static assets" is not accurate. This tutorial does not cache anything it allows the setting of a response header that is used to determine how long a file should be cached for by the browser or a proxy server.
This PR updates the title for static assets cache control tutorial, updates code samples from Samples project, and swaps from IComposer to Startup.cs registration
> Update and rename/move static asset cache tutorial to "Reference/Response Caching"

- Reference/Notifications/EditorModel-Notifications/index.md
This functionality has been present in the codebase for some time now, but I hadn't gotten around to adding the documentation for it.
> Added SendingChildrenNotification to list of editormodel notifications

- Fundamentals/Data/Data-Types/default-data-types.md
Some updates to using stylesheets with the RTE.
Also removed this part:
"The editor also supports TinyMCE plugins which can be controlled in the configuration file located at `/config/tinyMce.config`."
It should instead be updated and added to the RTE articles in the Backoffice/Property-Editors section.
> Updated "Default Data Types" article  in relation to the RTE

- Extending/Health-Check/Guides/DebugCompilationMode.md
- Extending/Health-Check/Guides/FixedApplicationUrl.md
- Extending/Health-Check/Guides/HttpsConfiguration.md
- Extending/Health-Check/Guides/NotificationEmail.md
- Extending/Health-Check/Guides/SMTP.md
Noticed a typo when reading the health checks. 
Included a niche readability fix for developers who happen to be called Jason 😉
> Fix typo, capitalize JSON

- Add-ons/UmbracoForms/Developer/Configuration/index-v7.md
- Add-ons/UmbracoForms/Developer/Configuration/index.md
- Add-ons/UmbracoForms/Developer/Security/index.md
This was reported via [this functional issue](https://github.com/umbraco/Umbraco.Forms.Issues/issues/907), that looked to be due to an incorrect value in the documentation.
> Fixes incorrect reference to Forms configuration key.

- Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-Grid-Editor/index.md
The docs have a bad case of casing going on 😄 this will cause issues for Linux users.
The correctly cased full path is: `/Views/Partials/blockgrid/Components/`
> Fix casing for block grid components path

- Add-ons/UmbracoForms/Developer/Magic-Strings/index.md
This PR contains updates made for Forms 10.2 following the RC release.  Ideally it would be reviewed and released early on November 8th.
Includes:
- Added details of magic strings in HTML tags.
> Forms 10.2 post RC docs updates

- Fundamentals/Setup/Requirements/index-v11.md
Updated
- .NET version to **7.0**
- Link to Microsoft documentation (line 56)
Are there any updated requirements in terms of local development or SQL?
> Update Requirements article for Umbraco 11

- Reference/Configuration/ConnectionStringsSettings/index.md
We have discussed this on the D-team and we will no longer be recommending shared cache mode, therefore the documentation that mentions shared cache for Sqlite needs to be changed to private cache, if there's anywhere else this is mentioned please let me know 🤔
> Update documentation to use private cache instead of shared

- Extending/Macro-Parameter-Editors/index.md
We had deployed an update to our site that included custom macro parameter editors, but the editor wasn't loading the AngularJS controller at runtime. After much head scratching, we found this post: https://our.umbraco.com/forum/umbraco-9/107740-umbraco-9-cant-register-controller-for-a-custom-dashboard-that-works-locally-but-fails-when-deploy which described the issue and the solution. I figured it would be valuable to include a note about this on this documentation page for others.
> Add section on runtime minification

- Reference/Routing/Custom-Controllers/index.md
It was hard to find any documented way to use an async Index()-method but this approach works. I think that official docs should have an example for people looking to use a async implementation in the controller. 
Without the sync Index() with the [NoAction]-attribute the call would be ambiguous between the async version on the ProductPageController and the sync Index()-method on RenderController.
As far as I can tell this is the best approach at the moment.
> Example of how to create async RenderController

- Umbraco-Heartcore/Client-Libraries/Dot-Net-Core/Content-Management-Sample/index.md
- Umbraco-Heartcore/Client-Libraries/Dot-Net-Core/index.md
This PR provides documentation on how to use the `ContentManagementService` to manage content and media. It has been created to solve customer issues regarding File Upload and Image Cropper upload requiring raw property values for the specific property editor.
> Added Content Management Api documentation for the Heartcore client library

- umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/rich-text-editor/configuration.md
Currently, there are no references in the documentation about how to configure the RTE through the appSettings. This PR adds an overview showing how to get started, complete with an example for a given use case.
> Add an intro to the RTE appSettings config

- Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Image-Cropper/index-v8.md
Adding crops directly into templates can cause media usage to increase.
Each of those crop URLs will result in a different image, but those will only be generated/processed once when the URL is requested and any consecutive requests will then get it from the cache... Deleting files from the cache will reduce the overall size, but if those crop URLs are requested again (meaning they are actively used in the website), they will need to be processed and cached again, requiring additional CPU power to do so without actually resulting in a reduced cache size.
Basically, the cache size can't be smaller than all actively used crops. So if you have an image of 1MB that's rendered in 7 crop sizes (widths 800 to 2200 from the example), you might end up using around 7MB of cache storage. Smaller …
> Adding crops directly into templates

- umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/block-editor/block-grid-editor.md
The current docs are somewhat weirdly referencing ModelsBuilder typed without actually putting them to use.
This PR updates the docs so we separate and clarify the difference between default and strongly typed views - the latter being ModelsBuilder powered views.
> Update block grid editor partial views docs

- umbraco-cms/fundamentals/setup/install/README.md
Updated fundamentals/setup/install/README.md to use new install command. It looks like since .NET 7, the install flag has changed:
> Updated Fundamentals Setup Install readme to use new install command

- umbraco-cms/fundamentals/design/rendering-content.md
> Readability improvements - Fundamentals design rendering-content

- umbraco-forms/README.md
The purchase and sign up link on https://docs.umbraco.com/umbraco-forms/umbraco-forms are broken. I am not sure if you want to continue to redirect the sign up to a documentation page or if it should go to the trial flow - I chose the latter :)
> Broken Forms links

- umbraco-cms/reference/templating/macros/README.md
The image path on page https://docs.umbraco.com/umbraco-cms/reference/templating/macros is broken
> Fixed broken image Reference/Templating/Macros

- umbraco-heartcore/api-documentation/graphql/schema-generation.md
Mentioned that a document type that is inherited from is being generated as an interface
> Heartcore: Parent document types generates interfaces in GraphQL

- umbraco-cms/reference/routing/request-pipeline/published-content-request-preparation.md
It seems this part was from the old documentation https://our.umbraco.com/Documentation/Reference/Routing/Request-Pipeline/published-content-request-preparation#findpublishedcontentandtemplate as one now subscribe to a notification.
https://docs.umbraco.com/umbraco-cms/implementation/custom-routing#routingrequestnotification
https://docs.umbraco.com/umbraco-cms/reference/routing/request-pipeline/published-content-request-preparation#redirects
Besides that I couldn't make the redirect in the example to work:
https://github.com/umbraco/Umbraco-CMS/issues/13542
> Update example for `PublishedRequestHandler`

- umbraco-deploy/deploy-settings.md
I suspect that the duplicate description meta-tag is causing the article to not being searchable.
> Remove duplicate meta description

- Add-ons/UmbracoForms/Developer/Configuration/index.md
This came up in a support request where we realised there was a misalignment between the key used in the code and in the docs, for Forms 8.
> Fixed incorrect configuration key.

- umbraco-cms/reference/templating/modelsbuilder/README.md
Links that use uppercase don't work. Github urls are case-sensitive.
> fixed links

- umbraco-cms/tutorials/creating-an-xml-site-map.md
This might just be in Rider, but I suspect not.  If the RenderSiteMapUrlEntry(siteHomePage) is inline then there is an error. If not, it runs ok.
> Prevents error "cannot convert from 'void' to 'object?'"

- umbraco-cms/reference/searching/examine/quick-start.md
Removed an S from the Service(s) class name as it should have been Service.
> Fixing a typo in the code example
