- Extending/Database/index.md
Adding to docs for custom database tables explaining why it is important to not reuse schema classes.
Adding details on handling data in custom database tables.
> Updating docs for custom database tables.

- .github/valeStyle/Hyperbolic.yml
Removed also the link as it is not resolving
> Improve vale: add more condescending words

- Reference/Security/auto-linking.md
- Reference/Security/backoffice-user-manager.md
- Reference/Security/external-login-providers.md
- Reference/Security/index.md
Looks great! Added a few tiny tweaks.
> Review external login provider docs

- Reference/Management/Services/UserService/Update-user-information-v7.md
> Duplicate word removal "a a"

- Reference/Events/EditorModel-Events/index-v7.md
> Duplicate word removal

- Reference/Events/EditorModel-Events/index.md
> Duplicated word removal

- Reference/Security/Security-settings/index.md
- Reference/Security/auto-linking-v7.3.0.md
- Reference/Security/auto-linking.md
- Reference/Security/backoffice-user-manager-v7.3.0.md
- Reference/Security/backoffice-user-manager.md
- Reference/Security/external-login-providers.md
- Reference/Security/index-v7.md
- Reference/Security/index.md
With 8.9 there's a bunch of new functionality that I've documented. This functionality is also listed here https://github.com/umbraco/Umbraco-CMS/pull/8623#issue-466447539
I think i've got the versioning of these things ok, but please adjust as you see fit.
> Adds documentation for new external login provider functionality and cleans up a bit of the existing docs

- Reference/Security/Security-hardening/index.md
- Umbraco-Heartcore/Client-Libraries/Dot-Net-Core/MVC-Sample/index.md
Added a link to https://www.youtube.com/watch?v=yTB-tXi3Ldg under https://our.umbraco.com/documentation/Umbraco-Heartcore/Client-Libraries/Dot-Net-Core/MVC-Sample/
> Add video link to net MVC sample

- Contribute/index.md
Grammatical fixes to Contribute to the Umbraco Documentation https://our.umbraco.com/documentation/Contribute/
> Contribute to the Umbraco Documentation

- Getting-Started/Backoffice/Sections/index.md
A few grammatical mistakes fixed on the following page: https://our.umbraco.com/documentation/getting-started/backoffice/Sections/
> Fixed Grammatical mistakes on Getting Started Sections page

- Tutorials/Creating-Basic-Site/Document-Types/index.md
Grammatical and highlighting to Document Types page https://our.umbraco.com/documentation/Tutorials/Creating-Basic-Site/Document-Types/
> Proposed Improvements for Document Types page

- Reference/Events/EditorModel-Events/index-v7.md
- Umbraco-Heartcore/API-Documentation/GraphQL/Filtering-and-Ordering/index.md
- Umbraco-Heartcore/API-Documentation/GraphQL/Property-Editors/index.md
- Umbraco-Heartcore/API-Documentation/GraphQL/Schema-Generation/index.md
- Umbraco-Heartcore/API-Documentation/GraphQL/index.md
- Umbraco-Heartcore/index.md
Added information on how the filter and order by GraphQL types are generated.
**NOTE**: This is not released yet.
> Add GraphQL schema generation docs for filters and orderby

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Content-Picker/index.md
Belongs to https://github.com/umbraco/UmbracoDocs/issues/1528 
Add ModelsBuilder example
> Update Content Picker

- Umbraco-Heartcore/Getting-Started-Cloud/Deployment-workflow/index.md
- Fixed some typos.
- Changed some sentence structure.
- Added a minor clarification.
> Read desc for more details.

- Umbraco-Heartcore/Getting-Started-Cloud/The-Cloud-Portal/index.md
- Fixed typos.
- Changes sentence structure.
- Removed the part about 5EUR per new team member, as I believe that this was never a thing for Heartcore.
> Read desc for details.

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Label.md
Add ModelsBuilder example.
Belongs to:
https://github.com/umbraco/UmbracoDocs/issues/1528
> Update Label Property Editor

- Reference/Config/tinyMceConfig/index.md
I've added some more information about how to setup the Code Sample option within TinyMCE as I found I needed to do a bit more than what the tutorial outlined.
> Updating instructions for TinyMCE Code Sample

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Block-List-Editor/index.md
MediaLink doesn't exist on the object.  it should be mediaLink (lower m).
> Fix media link case

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Media-Picker/index.md
> Update Media Picker Property Editor

- Umbraco-Cloud/Getting-Started/The-Umbraco-Cloud-Portal/index.md
Please, check if the link to the DB guide is working, as I'm not sure if I wrote it correctly.
> Added a section about the env error log

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Multinode-Treepicker/index.md
> Update Multinode treepicker property editor

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/RadioButton-List/index.md
Delete hardcoded string form modelsbuilder example. 
Belongs to:
https://github.com/umbraco/UmbracoDocs/issues/1528
> Update Radio Button List Property Editor

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Numeric/index.md
> Update Numeric Property Editor

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/CheckBox-List/index.md
> Update Checkbxlist Property Editor

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/DropDown/index.md
> Update Dropdown Property Editor

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Member-Picker/index.md
> Update Member Picker Property Editor

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Textarea/index.md
> Update textarea property editor

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Textbox/index.md
> Update textbox property editor

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/User-Picker/index.md
Add null check
Add ModelsBuilder example 
> Update user picker property editor

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Rich-Text-Editor/index.md
> Update Rich Text Property Editor

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Multiple-Textbox/index.md
> Update Repeatable Textstrings

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Block-List-Editor/index.md
Added a missing bracket and semicolon in the basic controller example
> Added missing bracket and semicolon

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/File-Upload/index.md
> Update file upload property editor

- Reference/Querying/IPublishedContent/Properties/index.md
Updated documentation to match PRs
https://github.com/umbraco/Umbraco-CMS/pull/7544
&
https://github.com/umbraco/Umbraco-CMS/pull/7550
Once those 2 PRs are merged this should be merged
> Update IPublishedContent properties docs to reflect coming obsolete methods

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Email-Address/index.md
> Update email address property editor

- Extending/Packages/UmbPack/index.md
This will be an upcoming feature in Umbpack v0.9.6 from https://github.com/umbraco/UmbPack/pull/38
Would appreciate a review but **don't merge!** If it's approved I can just merge and deploy myself when we release the new version 🙂
> Add info on property replacement

- Extending/Packages/UmbPack/index.md
And also added information around the {name} and {version} templating
> UmbPack: Updated the version to match the recent release

- Umbraco-Heartcore/API-Documentation/GraphQL/Filtering-and-Ordering/index.md
- Umbraco-Heartcore/API-Documentation/GraphQL/index.md
- Umbraco-Heartcore/Getting-Started-Cloud/Preview/index.md
> Add info about fetching draft content with GraphQL

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Date-Time/index.md
> Update DateTime Property Editor

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/User-Picker/index.md
> Update UserPicker PropertyEditor

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Nested-Content/index.md
To help out with https://github.com/umbraco/UmbracoDocs/issues/2714 , I added a sample on how to create nested content using ContentService in v8
> Added sample on how to create nested content programmatically

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/True-False/index.md
> Update true/false property editor

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Multi-Url-Picker/index.md
Update .Url to .Url() as .Url is now depreciated.
Update versionFrom to match the pre version index
> Update Multi Url Picker Page with Url() 

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Multi-Url-Picker/index-vpre8.8.md
Creating new pre 8.9 version to then allow for update to 8.9 documentation for .URL()
> Create Multi Url Picker page for pre8.8 

- Extending/Content-Apps/index.md
Hi,
I  have added a tip on how to control the colour of the content app icon.
Poornima
> Add a tip on how to control the colour of the content app icon

- Extending/Packages/package-types.md
A package can also contain content so I have added this to the list of options.
> Added content as an option for package

- Extending/Property-Editors/Build-a-Block-Editor.md
To link documentation together with an overview
> An addition to PR #2908

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/RadioButton-List/index.md
Add or change value programmatically
> Update RadioButton List

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Member-Group-Picker/index.md
> Update Member Group Picker

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Rich-Text-Editor/index.md
> Add value to RTE

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Media-Picker/index.md
> Update Media Picker

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/DropDown/index.md
> Dropdown Property Editor

- Umbraco-Uno/Creating-Content/Extending-Uno/index.md
- Umbraco-Uno/Uno-pedia/Content-Types/Global-Content/index.md
- Umbraco-Uno/Uno-pedia/Content-Types/Site-Start/index.md
- Umbraco-Uno/Widgets/Instagram/index.md
I've updated some broken links in the Uno documentation.
Primarily the /Widgets/ section.
> Uno broken links

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Block-List-Editor/index.md
...on how to create block list content dynamically (without settings model).
Made to help out with https://github.com/umbraco/UmbracoDocs/issues/2714
> Blocklist editor - added a code sample

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Multi-Url-Picker/index.md
> Update Multi Url Picker

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Decimal/index.md
> Uddate decimal property editor

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Color-Picker/index.md
> Update Color Picker

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Markdown-Editor/index.md
> Update markdown editor

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Multinode-Treepicker/index.md
> Multinode Treepicker

- Add-ons/UmbracoForms/Developer/Forms-in-the-Database/index.md
Based on a Twitter question: https://twitter.com/FranscdeJong/status/1339163614331146243
> Add info on migrating forms files

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/True-False/index.md
> Udate True/False

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Image-Cropper/index.md
> Update Image Cropper

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/File-Upload/index.md
> Update File Upload

- Umbraco-Cloud/Frequently-Asked-Questions/index.md
Minor update to highlight how to enroll a hostname for a domain that is within a Cloudflare account.
I will probably add a short section to the Set-up/Hostname section as well. But wanted to update this FAQ entry first where we already mention Cloudflare (for when you as a customer have your domain in your own Cloudflare account).
> Updated FAQ entry about Cloudflare to Cloudflare with Umbraco Cloud

- Getting-Started/Setup/Upgrading/migrating-to-v8.md
How to workaround the migration script errors with migrating directly to V8 from V7.
> Add information about how to migrate to 8.6+

- Reference/Routing/Request-Pipeline/IContentFinder.md
the sample had unused code, so I removed the unnecesary line
> removed unused line

- Reference/Cache/applicationcache-v7.md
- Reference/Cache/applicationcache.md
Belongs to: https://github.com/umbraco/UmbracoDocs/issues/1874
> Update ApplicationCache for v8

- Umbraco-Cloud/Set-Up/External-Services/index.md
Renamed whitelist to allowlist for improved inclusivity
> Updating whitelist to allowlist

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Block-List-Editor/index.md
To preserve functionality and ensure a consistent look/feel:
* Div has been changed to Button
* Class has been added to preserve drag-to-reorder/sort
* ng-click has been updated to current default
* Comment below code added to explain importance of the class
> Update custom backoffice html view

- Tutorials/Creating-a-Property-Editor/index.md
Belongs to https://github.com/umbraco/UmbracoDocs/issues/2972
> Add property editor with c#

- Tutorials/Creating-Basic-Site/Adding-Language-Variants.md
- Tutorials/Creating-Basic-Site/Creating-Your-First-Template-and-Content-Node/index.md
- Tutorials/Creating-Basic-Site/Document-Types/index.md
Corrected:
-incorrect info about doctype permissions
-changed **varying by culture** to **vary by culture**
-added a link to the site template later in the steps in case someone missed it on the overview page
> Corrected some  mistakes in Creating basic site tutorial

- Reference/Searching/Examine/Quick-Start/index-v7.md
Resubmitting the PR as my previous PR ran in to issues on my Fork! 
Hopefully this link works this time round :)
> Fixing Examining Examine link

- Getting-Started/Setup/Install/Unattended-Install.md
Hi @sofietoft one for you & the docs team to consider adding
> Add in configuration table for unattended install

- Umbraco-Cloud/Getting-Started/Migrate-Existing-Site/index.md
> Upgrade migration guide to reflect Umbraco ID updates

- Tutorials/Creating-a-Custom-Dashboard/index.md
> Dashboard Tutorial: Update JS samples to define supported entity types

- Tutorials/Creating-a-Property-Editor/part-2.md
Add config to a property editor using c#
Belongs to https://github.com/umbraco/UmbracoDocs/issues/2972
> Add configuration

- Implementation/Unit-Testing/index.md
As promised @sofietoft here is the link to the project in a note on the Unit Testing section. I took the chance I got and added a link to my blogpost about the project as well, hope thats ok with you. I saw that PhoWorks had done the same on https://our.umbraco.com/documentation/getting-started/setup/upgrading/migrating-to-v8#known-issues so I just went with it. If it doesn't feel ok with you I can remove it.
Have a great weekend!
> Added link to Github project and blog.

- Reference/Config/fileSystemProviders/index.md
This addition explains and exemplifies how to use IMediaFileSystem to get the contents of a file in a stream.
> How to get file stream from IMediaFileSystem

- UmbracoNetCoreUpdates.md
- Should not be merged before the alpha3 is released
> Update UmbracoNetCoreUpdates.md to match alpha3

- Umbraco-Cloud/Set-Up/Manage-Hostnames/Move-away-from-Latch/index.md
> Updates spelling of Cloudflare

- Add-ons/The-Licensing-model/index.md
Adds a technique to install the Umbraco license into a directory other than ./bin
> Adds alternative license location documentation

- Extending/Backoffice-Search/index.md
Updates code as requested in #3025
> Updates Backoffice Search to IEnumerable samples

- Extending/Dashboards/index.md
Use constant for Writer User Group
> Use constant

- Umbraco-Cloud/Set-Up/Manage-Hostnames/index.md
Adding an example of a wildcard CAA record for clarification
> Updated with wildcard example

- Reference/Config/Serilog/index.md
Added example of extending a property with an environment variable.
> Update index.md to add example of extending a property with an environment variable.

- Getting-Started/Setup/Upgrading/migrating-to-v8.md
It is a bit too easy to miss the note about the upgrade flow for Cloud sites is different. Moving this up - and putting it into a note, will help make it more visible.
> Moving note about upgrading Cloud sites higher

- Umbraco-Heartcore/API-Documentation/GraphQL/index.md
> Removing section about querystring parameter in Heartcore GraphQL

- Reference/Management/Services/MediaService/Index.md
Explained why we need to include the Umbraco.Core, and suggested different approached to creating folders programmatically
> A few corrections regarding Media Service

- Umbraco-Heartcore/Getting-Started-Cloud/API-Browser/index.md
Just my suggestion on a more clear of formulating the text 😃
> Typo fix and formatting suggestion

- Getting-Started/Setup/Upgrading/general.md
Related to: https://github.com/umbraco/Umbraco-CMS/pull/9531 
Also included a "Table of contents" to the General Upgrades article.
> Document how to upgrade projects unattended

- Reference/Security/Security-hardening/index.md
Added for better highlighting of "note" 😄
> Markdown improvement

- Umbraco-Cloud/Set-Up/Config-Transforms/index.md
- Umbraco-Cloud/Troubleshooting/Deployments/Changes-Not-Being-Applied/index.md
- Umbraco-Cloud/Troubleshooting/Deployments/index.md
A new guide for troubleshooting cases where the deployment goes through seemingly OK, but nothing is extracted.
To do with config transforms.
> Tutorial for troubleshooting changes not being applied on deployments

- Extending/Property-Editors/Build-a-Block-Editor.md
Some minor adjustments regarding the Block List editor content/settings data.
> Update Block List editor content/settings

- UmbracoNetCoreUpdates.md
Prepared the docs for the upcoming alpha4. 
Should not be merged before we release :)
> Prepared the docs for the upcoming alpha4

- Reference/Events/EditorModel-Events/index.md
Oh I should have added this as well @sofietoft @marcemarc 🙈🤦‍♂️
> Add csharp code formatting

- Add-ons/Umbraco-Deploy/Deployment-Workflow/Content-Transfer/index.md
- Add-ons/Umbraco-Deploy/Deployment-Workflow/Restoring-Content/index.md
- Add-ons/Umbraco-Deploy/Deployment-Workflow/index.md
Added small videos with Andy about Deploy on prem
> Deploy on prem videos

- UmbracoNetCoreUpdates.md
> Fixed wrong version number

- Getting-Started/Data/Users/index.md
Added important when you create your own custom, user groups. You will need remember to set a start node for the user group.
> Updated the user group section

- Add-ons/UmbracoForms/Developer/Healthchecks/index.md
- Add-ons/UmbracoForms/Developer/Healthchecks/scripts/8.7.0-apply-keys-and-indexes-forms-in-db.md
- Add-ons/UmbracoForms/Developer/Healthchecks/scripts/8.7.0-apply-keys-and-indexes-forms-in-db_revert.md
- Add-ons/UmbracoForms/Developer/Healthchecks/scripts/8.7.0-apply-keys-and-indexes.md
- Add-ons/UmbracoForms/Developer/Healthchecks/scripts/8.7.0-apply-keys-and-indexes_revert.md
Linking directly to the SQL files resulted in 404 errors.
I've changed the files to Markdown instead.
> Change sql files to markdown and updated links

- Add-ons/UmbracoForms/Developer/Healthchecks/index.md
- Add-ons/UmbracoForms/Developer/Healthchecks/scripts/8.7.0-apply-keys-and-ind-forms-in-db.md
- Add-ons/UmbracoForms/Developer/Healthchecks/scripts/8.7.0-apply-keys-and-ind-forms-in-db_revert.md
- Add-ons/UmbracoForms/Developer/Healthchecks/scripts/8.7.0-apply-keys-and-ind.md
- Add-ons/UmbracoForms/Developer/Healthchecks/scripts/8.7.0-apply-keys-and-ind_revert.md
Also added meta title to each of the files.,
> Updated file names and links

- Extending/Content-Apps/index.md
Updated "Limiting according to type" section
> Updated ContentTypes info

- Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Grid-Layout/Grid-Editors.md
Explain how to use Custom Macro's in the Grid Editor with an example.
> Add Sample Macro in Grid Editor

- Add-ons/The-Licensing-model/index.md
- Add-ons/Umbraco-Deploy/Installing-Deploy/Existing-site/index.md
- Add-ons/Umbraco-Deploy/Installing-Deploy/New-site/index.md
- Add-ons/index.md
- Umbraco-Cloud/Deployment/Deploy-Settings/index.md
- Umbraco8FAQ.md
Minor fixes to the deploy docs, where i have added a missing setting and a new license description as well as a small change to the deploy settings section for cloud
> Deploy patch

- Implementation/Unit-Testing/index.md
Here we go again. 😉
More test examples for the Unit Testing documentation.
For more info: https://adolfi.dev/blog/testing-iurlsegmentprovider/
Cheers! ❤️
> Added test example for UrlSegmentProvider.

- Implementation/Unit-Testing/index.md
Sorry, my bad. Correcting my PR from yesterday.
Been working with xUnit for so long now that I forgot you need to use [SetUp] in NUnit.
Cheers.
> Replace constructor with SetUp in test sample

- Getting-Started/Design/Stylesheets-Javascript/index.md
see https://github.com/umbraco/UmbracoDocs/issues/3076
> Add a couple of notes around gotchas with the Client Dependency Framework

- Reference/Config/webconfig/index.md
Add AllowContentDashboardAccessToAllUsers
Belongs to https://github.com/umbraco/UmbracoDocs/issues/3136
> AllowContentDashboardAccessToAllUsers

- UmbracoNetCoreUpdates.md
`-ce` = Invalid input switch
should be  `--UseSqlCe `
> Incorrect code in CE example

- Getting-Started/Setup/Install/install-umbraco-with-templates.md
Trying to play with the beta and I couldn't install - found out it's because you need to add a custom nuget source.
> Add missing step for beta in install steps

- Umbraco-Cloud/Set-Up/Manage-Hostnames/Rewrites-on-Cloud/index.md
I suggest removing this warning, because my latest testing has shown that the rewrite actually also works on Cloudflare.
> Removing warning about rewrite not working on Cloudflare

- Add-ons/UmbracoForms/Developer/Configuration/index.md
Currently planning a patch release for Forms on Tuesday 11th May, for which there's a minor update to configuration.
> Added reference of additional configuration element introduced in Forms 8.7.2

- UmbracoNetCoreUpdates.md
Updated with info about beta002
> Updated to beta002

- Extending/Content-Apps/index.md
Noticed the title and description were wrong on this article 😊
> Update wrong meta title and description

- Tutorials/Creating-Basic-Site/Articles-Parent-and-Article-Items/index.md
The article was mentioning "Article Main" when it should be "Articles Main" .
> Update  Articles-Parent-and-Article-Items/index.md

- Add-ons/Umbraco-Deploy/Installing-Deploy/Existing-site/index.md
Just a small addition referencing an additional package required for installation if using certain property editors for content.
> Added details of UmbracoDeploy.Contrib to Umbraco Deploy installation documentation.

- UmbracoNetCoreUpdates.md
According to dotnet new umbraco --help, it has to be a lowercase p
> Change -P to -p

- Extending/Content-Apps/index-v9.md
> Update Content App Article

- Extending/Section-Trees/trees-v9.md
* Adding full code snippet including usings.
* Explaining we also need a constructor when we mention the methods we need to implement as part of inheriting TreeController.
* Changing the legacy "developer" setting reference as it may confuse folks.
> Sections docs updates based on learn-a thon

- UmbracoNetCoreUpdates.md
Updated to have info about beta003
> Updated .NET Core info doc to have info about beta003

- Reference/Querying/IPublishedContent/Collections/index-v9.md
- Reference/Querying/IPublishedContent/index-v9.md
-ContentType replaced DocumentTypeAlias
-GetProperty replaced GetPropertyValue
> Ipub Content Collections. Updated for v9.

- Fundamentals/Data/Scheduled-Publishing/index.md
1. Added verified-against: 9.0.0 metadata.
2. Fixed some UI changes
> Fix article

- Fundamentals/Backoffice/Content-Templates/index.md
1. Added verified-against: 9.0.0 metadata
2. Updated steps for clarity
> Updated article for V9

- Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Media-Picker/index.md
> Broken link

- Umbraco-Cloud/Set-Up/Working-With-Visual-Studio/index.md
Came across this issue the other day.
> Added information about ModelsBuilder VSIX and Umbraco Id

- Tutorials/Editors-Manual/Getting-Started-With-Umbraco/Creating-Saving-and-Publishing-Content/index.md
- Tutorials/Editors-Manual/Getting-Started-With-Umbraco/Editing-Existing-Content/index.md
- Tutorials/Editors-Manual/Getting-Started-With-Umbraco/Finding-Content/index.md
- Tutorials/Editors-Manual/Getting-Started-With-Umbraco/Umbraco-Interface/index.md
- Tutorials/Editors-Manual/Getting-Started-With-Umbraco/index.md
- Tutorials/Editors-Manual/Media-Management/index.md
- Tutorials/Editors-Manual/Tips-and-Tricks/Audit-Trail/index.md
- Tutorials/Editors-Manual/Tips-and-Tricks/index.md
- Tutorials/Editors-Manual/Version-Management/Comparing-Versions/index.md
- Tutorials/Editors-Manual/Version-Management/Rollback-to-a-Previous-Versions/index.md
- Tutorials/Editors-Manual/Version-Management/index.md
- Tutorials/Editors-Manual/index.md
1. Added section intros
2. Fixed formatting issues
> Editors manual

- Fundamentals/Setup/Upgrading/general-v9.md
- Fundamentals/Setup/Upgrading/index-v9.md
- Fundamentals/Setup/Upgrading/version-specific.md
- Fundamentals/Setup/index-v9.md
- Added run-an-unattended-upgrade
-  Version specific upgrades 8 to 9
> Updated Fundamentals/Setup/Upgrading to v9

- Fundamentals/Code/Umbraco-Services/index-v9.md
- Reference/Management/Services/AuditService/index-v9.md
- Reference/Management/Services/ConsentService/index-v9.md
- Reference/Management/Services/ContentService/index-v9.md
- Reference/Management/Services/ContentTypeService/Retrieving-content-type-containers-v9.md
- Reference/Management/Services/ContentTypeService/Retrieving-content-types-v9.md
- Reference/Management/Services/ContentTypeService/index-v9.md
- Reference/Management/Services/DataTypeService/index-v9.md
- Reference/Management/Services/EntityService/index-v9.md
- Reference/Management/Services/FileService/index-v9.md
- Reference/Management/Services/LocalizationService/Retrieving-languages-v9.md
- Reference/Management/Services/LocalizationService/index-v9.md
- Reference/Management/Services/MacroService/index-v9.md
- Reference/Management/Services/MediaService/index-v9.md
- Reference/Management/Services/MemberGroupService/index-v9.md
- Reference/Management/Services/MemberService/index-v9.md
- Reference/Management/Services/MemberTypeService/index-v9.md
- index-v9.md 
- Changed code snippets and wording 
- Some of the links at the bottom of index-v9.md are not changed as the articles have not been migrated + Umbraco TV videos are about v7
</br>
Articles under services available:
* AuditService
- removed **Services property** as it uses `Services` property which we no longer use
- removed **Static accessor** section as it was using `Current` which we don't have any more
* ConsentService
* ContentService
* ContentTypeService
* ApplicationTreeService
- removed - was dealing with tree registrations in the ~/Config/trees.config file (not working with such file anymore)
* DataTypeService
- removed **Services property** as it uses `Services` property which we no longer use
- removed **Static accessor** section as it was using `Current` which we …
> Update UmbracoServices to v9

- Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Media-Picker-3/index.md
Adding Add content programmatically
Referenced by Marc
https://our.umbraco.com/forum/using-umbraco-and-getting-started/106296-problem-with-assigning-value-to-media-picker-3-programmatically#comment-331306
> Update on Media-Picker-3/index.md

- Reference/Management/Models/ContentType-v6.md
- Reference/Management/Models/ContentType.md
Update [ContentType article](https://our.umbraco.com/documentation/Reference/Management/Models/ContentType) for v8
> Update reference management models contenttype for v8

- Reference/Management/Models/Content-v6.md
- Reference/Management/Models/Content.md
Belongs to: https://github.com/umbraco/UmbracoDocs/issues/3263
> Update content model article for v8

- UmbracoNetCoreUpdates.md
Prepared for beta4 to go out tuesday
> Prepared for beta4 to go out tuesday

- Reference/Management/Models/Language.md
- Reference/Management/Models/index.md
> Reference management models language

- Reference/Querying/IPublishedContent/IsHelpers/index-v9.md
and updated v8 one about specific config based on the issue:
https://github.com/umbraco/Umbraco-CMS/issues/10391
(template methods)
> v9 article for IsHelpers

- Fundamentals/Backoffice/Login/index-v9.md
1. Created v9 version
2. Updated file names and paths.
> Backoffice-Login

- Reference/Management/Models/MediaType-v6.md
- Reference/Management/Models/MediaType.md
> Reference management models media type v8

- Reference/Management/Models/RelationType-v6.md
- Reference/Management/Models/RelationType.md
> Reference management models relation type v8

- Fundamentals/Setup/Server-Setup/Load-Balancing/azure-web-apps-v9.md
- Fundamentals/Setup/Server-Setup/Load-Balancing/file-system-replication-v9.md
- Fundamentals/Setup/Server-Setup/Load-Balancing/files-replicated.md
- Fundamentals/Setup/Server-Setup/Load-Balancing/files-shared.md
- Fundamentals/Setup/Server-Setup/Load-Balancing/flexible-advanced-v9.md
- Fundamentals/Setup/Server-Setup/Load-Balancing/flexible.md
- Fundamentals/Setup/Server-Setup/Load-Balancing/index-v9.md
- Fundamentals/Setup/Server-Setup/Load-Balancing/logging.md
- Fundamentals/Setup/Upgrading/general-v9.md
Added docs for v9 regarding load-balancing...
Note that most text is reused. But especially the area around Data Protection is hard to give one recommendation about. Instead, I pointed to Microsoft's documentation, as there are so many different ways to set this up. And this is required for all ASP.NET Core load-balanced environments. This is not specific for Umbraco,
> Added v9 docs for load balancing.

- Reference/Routing/custom-controllers-v9.md
Update docs based on the change here https://github.com/umbraco/Umbraco-CMS/pull/10614
> Update docs based for V9 to set RenderController as IOptions

- Reference/Management/Models/DataType.md
> Update DataType Constructor

- Fundamentals/Setup/Install/install-umbraco-with-templates.md
Removing beta note as it's now RC, updating the help output to be accurate to what is returned, updating mysql command to match one in RC release blog post
> Updating install by CLI guide based on RC

- Extending/Backoffice-Tours/index.md
Added a mention to the configuration which globally enables / disables the tour functionality
> Added a mention to the tours configuration setting

- Reference/Management/Models/RelationType-v9.md
> Management models relation type v9

- Reference/Management/Models/Template-v9.md
> Reference management models template

- Reference/Management/Models/MediaType-v9.md
> Reference management models media type v9

- Reference/Management/Models/Language-v9.md
> Reference management models language v9

- Reference/Management/Models/DictionaryItem-v9.md
> Reference management models dictionary item

- Reference/Management/Models/ContentType-v9.md
> Reference management models content type v9

- Reference/Management/Models/Content-v9.md
> Reference management models content v9

- Reference/Management/Models/DataType-v9.md
Belongs to https://github.com/umbraco/UmbracoDocs/issues/3145
> Reference management models data type v9

- Umbraco-Cloud/Upgrades/Migrating-To-New-Infrastructure/index.md
It causes miscommunication...
either change it to what I wrote or change the date because people are getting confused and I don't blame them
> please, update this

- Reference/Management/Models/ContentType-v9.md
- Reference/Management/Models/Language.md
- Reference/Management/Models/Template.md
- Reference/Management/Models/index.md
Fix some small issues in the Model articles.
> Reference management models content small issues

- Reference/Management/Models/Relation-v9.md
- Reference/Management/Models/Relation.md
> Reference management models relation

- Tutorials/Starter-kit/Index.md
- Tutorials/Starter-kit/Lessons/1-Customise-the-Starter-Kit/index.md
- Tutorials/Starter-kit/Lessons/2-Add-a-Blog-Post-Publication-Date/part-2.md
- Tutorials/Starter-kit/Lessons/2-Add-a-Blog-Post-Publication-Date/part-3.md
- Tutorials/Starter-kit/Lessons/3-Add-Open-Graph/index.md
- Tutorials/Starter-kit/Lessons/3-Add-Open-Graph/step-1.md
- Tutorials/Starter-kit/Lessons/3-Add-Open-Graph/step-2.md
- Tutorials/Starter-kit/Lessons/3-Add-Open-Graph/step-3-v9.md
- Tutorials/Starter-kit/Lessons/3-Add-Open-Graph/step-4-v9.md
- Tutorials/Starter-kit/Lessons/3-Add-Open-Graph/summary.md
- Tutorials/Starter-kit/Lessons/index.md
1. Updated steps for v9
2. Added versionTo metadata
> Updated Starter Kit Tutorial

- Reference/Management/Models/Relation.md
- Reference/Management/Models/index.md
- v8 version of the relation model. 
- update link in index file
Belongs to https://github.com/umbraco/UmbracoDocs/issues/3370
> Reference management models relation v8

- Implementation/Data-Persistence/index-v7.md
- Implementation/Data-Persistence/index.md
Verify article against Umbraco 8.
> Implementation data persistence

- Add-ons/UmbracoForms/Developer/Rendering-Scripts/index-v9.md
- Add-ons/UmbracoForms/Developer/Themes/index-v9.md
> Forms Themes

- UmbracoNetCoreUpdates.md
> Added Changes between rc 1 and rc 2

- Reference/V9-Config/index.md
Fixed type in "Intellisense" and added "to" in the sentence "having **to** configure..."
> Fix a type and add a word

- Reference/Cache/Examples/tags.md
Belongs to #3190 
Rename TagService to CacheTagService
> Rename TagService to CacheTagService

- Reference/Mapping/index-v9.md
Update UmbracoMapper article to v9
Belongs to: https://github.com/umbraco/UmbracoDocs/issues/3145
> Reference umbraco mapper

- Reference/Querying/MemberShipHelper/index-v7.md
- Reference/Querying/MemberShipHelper/index.md
Belongs to https://github.com/umbraco/UmbracoDocs/issues/2673
Verify article against Umbraco 8.
> Update reference querying member ship helper v8 2673

- Tutorials/Creating-Basic-Site/CSS-And-Images/index-v7.md
- Tutorials/Creating-Basic-Site/Creating-Your-First-Template-and-Content-Node/index-v7.md
- Tutorials/Creating-Basic-Site/index-v7.md
Belongs to https://github.com/umbraco/UmbracoDocs/issues/3377
> Update some broken links

- Reference/Cache/applicationcache-v9.md
- Reference/Cache/applicationcache.md
Belongs to https://github.com/umbraco/UmbracoDocs/issues/3145
> Reference cache applicationcache v9

- Extending/Section-Trees/sections.md
Added the schema snippet, which will enable intellisense in case people copy / paste the example from the docs.
> Update package.manifest sample

- Extending/Dashboards/index.md
I might be late to the party but recently noticed that there is a schema that can be referenced in the package.manifest files in order to provide us with some intellisense so I have updated the package.manifest samples to use it hoping it will benefit people who read the documentation 🤞🏻 😃
> Update package.manifest samples

- Reference/V9-Config/RequestHandlerSettings/index.md
As @jemayn suggested on #3397 the issue reported could be due to invalid JSON. This PR uses the valid JSON sample provided by @jemayn on the issue, which will most likely fix it 👍🏻
> Update Code sample with valid JSON

- UmbracoNetCoreUpdates.md
Added recent blog posts and videos to NETCore/Umbraco 9 updates
> Hemraker update umbraconetcoreupdates

- Implementation/Composing/index-v9.md
- Implementation/Services/Circular-Dependencies/index.md
- Implementation/Services/index-v9.md
- Implementation/index-v9.md
Updated Implementation/Services + /Implementation/Composing to v9.
Mainly code examples that had to change
> Updated Implementation/Services + /Implementation/Composing to v9

- UmbracoNetCoreUpdates.md
A  wee wording update and broken link due to it now being RC, not beta
> Beta to RC wording updates

- Add-ons/Umbraco-Deploy/index.md
As it contained nothing, fixing issue #3439
> Removing the FAQ section for deploy

- Reference/Management/Models/Media-v9.md
Belongs to #3145 
Updated the parameter names in the constructors from contentType to mediaType, see also [PR ](https://github.com/umbraco/Umbraco-CMS/pull/10689)the CMS.
> Reference management models media v9

- Umbraco-Cloud/Deployment/Deploy-Settings/index.md
> Fixing link to media

- Fundamentals/Setup/Upgrading/general.md
> Change version number

- Reference/Cache/index.md
> Update reference cache index v8

- Reference/Cache/index.md
- Reference/Cache/updating-cache-v7.md
- Reference/Cache/updating-cache.md
> Update updating cache

- Reference/Security/Setup-Umbraco-for-a-Fips-Server/index-v7.md
- Reference/Security/Setup-Umbraco-for-a-Fips-Server/index-v9.md
- Reference/Security/Setup-Umbraco-for-a-Fips-Server/index.md
Update the link in the Setup Umbraco for FIP page(s)
> Update link to microsoft fips article.

- Fundamentals/Backoffice/Infinite-editing/index.md
> Spelling error

- Fundamentals/Backoffice/LogViewer/index-v8.md
- Fundamentals/Backoffice/LogViewer/index.md
- Reference/V9-Config/Serilog/index.md
Updated the logviewer information to v9
> Updated the logviewer information to v9

- Fundamentals/Setup/index-v7.md
- Fundamentals/index-v8.md
- Fundamentals/index.md
Updated the landing page for fundamentals
> Fundamentals landing page patch

- Add-ons/UmbracoForms/Editor/Creating-a-Form/Fieldtypes/Recaptcha2/index.md
- Add-ons/UmbracoForms/Editor/Creating-a-Form/Fieldtypes/Recaptcha3/index.md
> Added field type to the rechapta for forms examples

- Add-ons/UmbracoForms/Developer/Extending/Adding-a-Fieldtype.md
- Add-ons/UmbracoForms/Developer/Extending/Adding-a-Workflowtype.md
The docs currently don't show how to compose custom Umbraco Forms fieldtypes or workflows
> Add FieldType/Workflow registration for v9

- Extending/Dashboards/index.md
This file is now verified against V9, code samples updated
> Updating Dashboard section

- Fundamentals/Data/index.md
I find it easier to absorb the edited paragraph if its listed as bullet points, rather than a wall of text.
> Reduce wall of text to bullet points, Fundamentals/Data

- Fundamentals/Code/Creating-Forms/index.md
File name doesn't match the controller name in the docs.
> Update to Create Forms tutorial

- Add-ons/Umbraco-Deploy/Deploy-Settings/index-v8.md
- Add-ons/Umbraco-Deploy/Deploy-Settings/index.md
- Add-ons/Umbraco-Deploy/Deployment-Workflow/Restoring-Content/index.md
- Add-ons/UmbracoForms/Editor/Attaching-Workflows/Workflow-Types/index-v7.md
- Add-ons/UmbracoForms/Editor/Attaching-Workflows/Workflow-Types/index.md
- Add-ons/UmbracoForms/Editor/Creating-a-Form/Conditional-Logic/index.md
- Add-ons/UmbracoForms/Editor/Viewing-and-Exporting-Entries/index.md
This PR contains the docs updates necessary to go with the next minor releases of Forms and Deploy (for V8 and V9).
Dates for release aren't confirmed yet but am aiming for Tuesday 2nd November for release candidates, at which point it makes sense to have the docs available.  Hope that sounds OK, and thanks.
> Added updates for functionality due in Forms 8.9/9.1 and Deploy 4.4/9.1.

- Reference/Templating/Macros/index-v9.md
> Templating/Macros. Adjusted for v9. Modified code samples

- Implementation/Integration-Testing/index.md
- Implementation/index.md
As a note, this will only be possible from 9.1.0 rc and forwards
- Added Integration-Testing
- Added Integration Testing with NotificationHandlers
- Added Integration Testing with a Schema
> Integration-Testing

- Implementation/Unit-Testing/index-v8.md
- Implementation/Unit-Testing/index.md
I've created a v9 version for the Unit Testing Documentation. I includes examples for testing: 
- RenderController, 
- SurfaceController
- ContentModel.
It's a start and all I could find the time for at the moment. In the future I'll add examples for UmbracoApiControllers, ViewComponents, Members and UmbracoHelper testing, but as I mentioned this is what I got at the moment.
Hopefully this could be a good starting point..
Cheers!
> V9 version of Unit Testing Documentation

- Reference/Events/MemberService-Events/index.md
Fixes https://github.com/umbraco/UmbracoDocs/issues/3622
> Fix broken links

- Add-ons/Umbraco-Deploy/Extending/index.md
- Add-ons/UmbracoForms/Developer/Extending/index.md
Just a small update adding some missing detail on extending Umbraco Deploy in V9.
> Added detail on registering custom udis

- Reference/Routing/Request-Pipeline/IContentFinder-v8.md
Some code improvements for NotFoundHandlers
> Some improvements for contentfinder v8

- Implementation/Default-Routing/Controller-Selection/index.md
Fixes [#3628](https://github.com/umbraco/UmbracoDocs/issues/3628)
> Change the Default Controller

- Extending/Dashboards/index.md
Use constant for WriterGroup 😄
> Use constant for WriterGroup

- Reference/Management/Services/MediaService/Index.md
> Fix small typo

- Reference/Routing/Request-Pipeline/IContentFinder.md
> Similar change as in the V8 doc - Added HTTP check

- Reference/Routing/Request-Pipeline/IContentFinder.md
In line with this comment https://github.com/umbraco/UmbracoDocs/pull/3638#pullrequestreview-811068459 use the startup class instead of a I(User)Composer.
> use Startup.cs to SetContentLastChanceFinder

- Reference/Management/Services/ServerRegistrationService/Index-v8.md
- Reference/Management/Services/ServerRegistrationService/Index.md
Update server registration service for v9
> Update server registration service v9

- Reference/Debugging/index.md
> IUserComposer - IComposer

- Reference/Routing/Request-Pipeline/outbound-pipeline.md
> Use IComposer in outbound-pipeline article

- README.md
Is it OK to link to this project from here?
> Mention preview app

- Implementation/Composing/index.md
Just missing a ';' from the end of line 46.
> Update to Composing page

- Reference/Cache/index-v7.md
- Reference/Cache/index-v8.md
Add warning to v7 and v8 article as well to be more consistent
> Add warning to chache article

- Extending/FileSystemProviders/Azure-Blob-Storage/index-v8.md
> Add xml to code block

- Reference/V9-Config/ContentSettings/index.md
Fixes broken link to global settings config in Notifications section.
> Fixes broken link to global settings config

- Fundamentals/Setup/Install/install-umbraco-with-templates.md
No idea if it's really a desirable addition, but I think a lot of people want to add a .sln file. I've added a note explaining how to do that.
> Rename solution to project and add note how to create a .sln file

- Reference/V9-Config/GlobalSettings/index.md
To show an example of a Friendly Name and reference the relevant RFC
> Enhanced the description of an SMTP From address

- Fundamentals/Setup/Server-Setup/iis/index.md
Updated ASP.NET Core 5.0 Runtime link
> Updated link

- Extending/Health-Check/Guides/ClickJackingProtection.md
- Extending/Health-Check/Guides/ContentSniffingProtection.md
- Extending/Health-Check/Guides/CrossSiteScriptingProtection.md
- Extending/Health-Check/Guides/ExcessiveHeaders.md
- Extending/Health-Check/Guides/StrictTransportSecurityHeader.md
The code samples on these pages look slightly different, probably because of the different notation?
> Update code block language 

- Reference/Angular/index-v7.md
Fixes https://github.com/umbraco/UmbracoDocs/issues/3706
> Change Angular to AngularJS

- Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Image-Cropper/index.md
> Fixed typo in Image Cropper documentation 

- Extending/Content-Apps/index-vpre9.2.md
In line with comment: https://github.com/umbraco/UmbracoDocs/pull/3638#pullrequestreview-811068459 I've created a PR: https://github.com/umbraco/Umbraco-CMS/pull/11691#issue-1062228629. In v9.2.0 we can register content apps in the `startup.cs` class.
> Register a content app in the startup class

- Fundamentals/Setup/Server-Setup/Load-Balancing/azure-web-apps.md
The names are different in this one to the linked doc so updating them to make them consistent
> Update Load Balancing Lucene Directory Factories Docs

- Fundamentals/Setup/Server-Setup/Load-Balancing/index.md
> Update Load Balancing config to reflect v9 UmbracoApplicationUrl setting

- Fundamentals/Setup/Server-Setup/Load-Balancing/file-system-replication-v8.md
- Fundamentals/Setup/Server-Setup/Load-Balancing/file-system-replication.md
Fixes: https://github.com/umbraco/UmbracoDocs/issues/3681
**v9:**
**v8**
> File system replication update tip

- Reference/Language-Variation/index-v8.md
- Reference/Language-Variation/index.md
Create a v9 version for the  Language-Variation article.
> Reference language variation v9

- UmbracoNetCoreUpdates.md
When having a workshop yesterday at UmbracoDK Festival I could not install Umbraco v9 although I followed all the steps. Magician Sebastiaan helped me out and I wanted to make sure that his magic solution was included in the documentation as well
> Added an extra optionale step to the installation process

- Add-ons/UmbracoForms/Developer/Extending/Adding-a-Workflowtype.md
Fixes: https://github.com/umbraco/UmbracoDocs/issues/3674
> Update workflow type

- Reference/Management/Services/ContentTypeService/index-v8.md
Fixes: https://github.com/umbraco/UmbracoDocs/issues/3721
> Fix broken link

- Add-ons/UmbracoForms/Editor/Creating-a-Form/Fieldtypes/Recaptcha3/index.md
Article is about ReCaptcha 3 but this was still referencing ReCaptcha 2
> [AMEND] Typo for ReCaptcha Version

- Reference/Templating/Modelsbuilder/index-v8.5.md
Fixes: https://github.com/umbraco/UmbracoDocs/issues/3729
> Update link in 8.5 article

- Fundamentals/Setup/Requirements/index.md
* Docker is not a requirement to run Umbraco
* Added the minimal server requirement (IIS 8 requires at least Windows server 2012 R2)
> Update hosting requirements

- Reference/Security/auto-linking/index-vpre-9.3.0.md
- Reference/Security/auto-linking/index.md
- Reference/Security/external-login-providers/index-vpre-9.3.0.md
- Reference/Security/external-login-providers/index.md
- Reference/Security/index-vpre-9.3.0.md
- Reference/Security/index.md
- Reference/Security/two-factor-authentication/index.md
Added docs to external logins and 2FA for members.
> V9.3 External logins and 2FA for members

- Contribute/File-Naming-Conventions/index.md
- Contribute/How-to-add-a-new-version/index.md
- Contribute/Issues/index.md
- Contribute/Markdown-Conventions/index.md
Small grammar and punctuation fixes. Redundant words removed, a few words and phrases replaced with better while retaining the original meaning, some standardization.
> Various small grammar, punctuation and readability changes.

- Reference/Routing/Request-Pipeline/inbound-pipeline-v8.md
- Reference/Routing/routing-properties-v8.md
There was no page for V8, so redirecting to base of the page
> Fix routing properties link

- Umbraco-Uno/Getting-Started/index.md
- Umbraco-Uno/Uno-pedia/index.md
> Fixing some broken links

- Add-ons/UmbracoForms/Developer/Extending/Adding-a-Fieldtype-v7.md
- Add-ons/UmbracoForms/Developer/Extending/Adding-a-Type-v7.md
- Add-ons/UmbracoForms/Developer/Extending/Adding-a-Type-v8.md
- Add-ons/UmbracoForms/Developer/Extending/Adding-a-Type.md
Just a tiny cleanup to improve readability
> Increased readability

- Reference/Templating/Modelsbuilder/configuration.md
Add recommendation to change Mode to 'Nothing' for staging and production. 
Fixes: https://github.com/umbraco/UmbracoDocs/issues
> Update ModelsBuilder Configuration article

- Umbraco-Cloud/Set-Up/Application-Insights/index-v7.md
Belongs to: https://github.com/umbraco/UmbracoDocs/issues/3748
> Add a v9 version of Application Insights

- Add-ons/Umbraco-Deploy/Deploy-Settings/index-v8.md
- Add-ons/Umbraco-Deploy/Deploy-Settings/index.md
WIP PR for documentation updates related to the next minor release of Umbraco Deploy, which will be 4.5.0 and 9.3.0.
> Added docs for member transfer operations using Umbraco Deploy.

- Reference/Security/use-https-v8.md
- Reference/Security/use-https.md
There was a double quote in the YAML description, stopping it from being parsed
> Use Https documentation had mucked up YAML

- Extending/Dashboards/index.md
Add using `Umbraco.Cms.Core;` and simplify code a bit.
> Update Dashboard: Simplify code

- Extending/FileSystemProviders/Azure-Blob-Storage/index.md
- Fixed some grammar readability issues
- Added help about creating the `/media` folder in the container for existing media files - this confused me so will be helpful
> Update Azure Blob Storage readme

- Reference/Config/umbracoSettings/index.md
Added info about the `hideBackofficeLogo` setting
> Updated settings for 8.18

- Reference/Querying/IPublishedContent/index-v8.1.md
Fixes: https://github.com/umbraco/UmbracoDocs/issues/3817
> Fix Broken link: Changes IsHelper to IsHelpers

- Tutorials/Creating-a-Property-Editor/index.md
Fixes: https://github.com/umbraco/UmbracoDocs/issues/3803
> Update code block

- Fundamentals/Setup/Upgrading/version-specific.md
The issue is marked as solved on the tracker :)
> Removed the warning

- Reference/Routing/IISRewriteRules/index.md
Some changes to the article based on feedback from customers and internally at Umbraco HQ
> Url Rewrites in V9 update

- Reference/V9-Config/ContentSettings/index-v9.0.0.md
Added info about the `HideBackOfficeLogo` setting
> Updated settings introduced in 9.4

- Extending/Backoffice-UI-API-Documentation/index-v8.md
- Extending/Backoffice-UI-API-Documentation/index.md
- Reference/Angular/index.md
Fixes: https://github.com/umbraco/UmbracoDocs/issues/2956
> Link to 'UI Examples' package

- Fundamentals/Code/Creating-Forms/index.md
This commit changes the way form fields are rendered to a partial view. I "think" this is the way to do it now 😄
> Updated creating forms fundamentals

- Reference/Angular/Directives/umbProperty/Index-v8.md
- Reference/Angular/Directives/umbProperty/Index.md
> Fix links to propertyeditors folder

- Extending/Section-Trees/sections-vpre9.2.md
- Extending/Section-Trees/sections.md
See also this [PR](https://github.com/umbraco/Umbraco-CMS/pull/11691) and this [comment](https://github.com/umbraco/UmbracoDocs/pull/3638#pullrequestreview-811068459).
> Update extending section trees sections

- Umbraco-Cloud/Getting-Started/Migrate-Existing-Site/index.md
We have removed the content node limits so I have made this PR
> Updated this article due to content node limits

- Reference/Cache/index.md
Update broken link in chache article
> Update broken link

- Add-ons/UmbracoForms/Developer/Extending/Adding-an-Event-Handler-v8.md
Fixes:  https://github.com/umbraco/UmbracoDocs/issues/3868
> using System.Linq

- Fundamentals/Setup/Install/visual-studio.md
Added some information about using VS 2022 and the dotnet new templates
> Updated article with info about using VS 2022

- Umbraco-Cloud/Set-Up/SMTP-settings/index.md
Adds Rapidmail, a 100% GDPR compliant service based in the EU. 
No affiliation, just this it's a good service to mention, since Umbraco is used a lot in the EU, and I don't really know any alternatives to it. 
I have tested the SMTP side of things out on Umbraco Cloud, and it works as expected.
> Adds another e-mail service

- Fundamentals/Setup/Install/Unattended-Install.md
> Mention InstallMissingDatabase setting on Unattended-Install page

- Extending/Key-Vault/index.md
Fixes: https://github.com/umbraco/UmbracoDocs/issues/3825
> Add Azure Key Vault Article

- Add-ons/UmbracoForms/Editor/Creating-a-Form/Fieldtypes/Recaptcha2/index.md
Saw some people getting confused with why these settings weren't working so I've added the `"Umbraco"` wrapper to make it clear.
> Make it clear where in the appSettings the Forms settings go

- Add-ons/UmbracoForms/Developer/Configuration/index-v7.md
- Add-ons/UmbracoForms/Developer/Configuration/index.md
- Add-ons/UmbracoForms/Developer/Custom-Markup/index.md
- Add-ons/UmbracoForms/Developer/Security/index.md
I'm not sure exactly when this will be needed yet, but earliest would be 5th April for the release candidate - which is when we should update the docs.
> Docs updates for upcoming 8.12.0/9.4.0 release of Umbraco Forms.

- Fundamentals/Code/Subscribing-To-Events/index.md
- Reference/Config/umbracoSettings/index.md
- Reference/V9-Config/umbracoSettings/index.md
https://github.com/umbraco/UmbracoDocs/issues/3912
https://github.com/umbraco/UmbracoDocs/issues/3904
> Added contentVersionCleanupPolicyGlobalSettings and fixed typos, grammar, and lint issues

- Reference/Config/index.md
https://github.com/umbraco/UmbracoDocs/issues/3905
Fixed lint formatting issues
> Added umbraco.config/NuCache info

- Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Multi-Url-Picker/index.md
@using Umbraco.Web.Models > @using Umbraco.Cms.Core.Models
> Umbraco 9 - Using case updated to correct model

- Tutorials/Creating-a-Property-Editor/index.md
Not needed for a basic property editor.
> Update index.md for Creating-A-Property-Editor

- Add-ons/UmbracoForms/Developer/Extending/Adding-a-Type.md
Subtle difference to link to V9 forms rather than V8
> Link to V8 Forms nuget

- Add-ons/UmbracoForms/Developer/index.md
Typo Custoimize -> Customize
Not sure why line 66 is marked as a change. I didn't touch it. Probably EOF, but I did this in the browser.
> Typo Customize -> Custoimize

- Add-ons/UmbracoForms/Developer/Working-With-Data/index-v8.md
This is a small update coming from an escalated support request I had, which was solved using an interface that we hadn't documented.  So wanted to make sure we have a public reference to it.
It can be published at any time.
> Added details on working with single records from form submissions.

- Implementation/Services/index.md
In this PR: https://github.com/umbraco/Umbraco-CMS/pull/12088 I've now added the functionality to configure routes to be handled as serverside requests. With this PR it should now be documented how to do so 🎉 
This is only possible after the `9.5` release, so i might need help to set it up, so that this section can only be seen after that 😆
> Add documentation about serverside request handling options

- Fundamentals/Setup/Upgrading/version-specific.md
Added docs for v9 to v10 upgrade
> Added docs for v9 to v10 upgrade

- Add-ons/UmbracoForms/Developer/Prepping-Frontend/index-v7.md
- Add-ons/UmbracoForms/Developer/Prepping-Frontend/index.md
- Add-ons/UmbracoForms/Editor/Creating-a-Form/Conditional-Logic/index.md
1. Added Conditions for Dates section in Conditional Logic article. 
2. Noticed "Preparing your Frontend" article in https://our.umbraco.com/documentation/Add-ons/UmbracoForms/Developer/ still links to version 7 of the article. Changed it to v9.
> Conditions for Date field

- Fundamentals/Design/Stylesheets-Javascript/index.md
I think this edit makes it clear that SmidgeHelper needs some help in knowing whether to bundle or not.
> SmidgeHelper ignores Umbraco:CMS:Hosting:Debug

- Fundamentals/Setup/Upgrading/version-specific.md
I have updated the docs for upgrading from 9 to 10 and made the different steps clearer.
> V9 to v10 upgrade patch

- Getting-Started/Developing-websites-with-Umbraco/index.md
https://github.com/umbraco/UmbracoDocs/issues/3976
> Removed Uno reference

- Add-ons/Umbraco-Deploy/Installing-Deploy/Install-Configure/index.md
- Add-ons/Umbraco-Deploy/Upgrades/index-v9.md
- Add-ons/Umbraco-Deploy/Upgrades/index.md
- Add-ons/Umbraco-Deploy/Upgrades/version-specific.md
- Add-ons/UmbracoForms/Developer/Themes/index.md
- Add-ons/UmbracoForms/Installation/Version-Specific.md
- Add-ons/UmbracoForms/Installation/index.md
This update provides information on the changes for Forms and Deploy for V10.
> Documented breaking changes for Forms and Deploy 10.

- .github/workflows/Vale-Linter.yml
- _vale.ini
Adds in the GitHub Action for the Vale Linter
https://github.com/errata-ai/vale-action
> Add in the Official Vale Linter GitHub Action

- Fundamentals/Setup/Requirements/index-v10.md
Bump .Net requirements from net5.0 -> net6.0
The existing article can be modified slightly to fit both 9 and 10 however it doesn't look quite right in the same way that a code example change would.
> Update system requirements for 10.x

- Fundamentals/Setup/Install/Unattended-Install-v10.md
Removed references to SQL CE
Added example connection string for SQLite.
> Update untattended-install documentation for 10.x

- Add-ons/Umbraco-Deploy/Installing-Deploy/CICD-Pipeline/ci-cd-azure-dev-ops-v8.md
- Add-ons/Umbraco-Deploy/Installing-Deploy/CICD-Pipeline/ci-cd-azure-dev-ops.md
- Add-ons/Umbraco-Deploy/Installing-Deploy/CICD-Pipeline/index-v8.md
This adds an Umbraco 9+ version of the CI/CD pipeline for Umbraco Deploy.  In can be reviewed, merged and published whenever is convenient.
> Added AzureDevOps example for Umbraco 9.

- Tutorials/Add-Google-Authentication/index.md
Updated the tutorial for Google authentication with a code example for v10
> Added Umbraco 10 specific code example for article

- Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Label.md
> v10: Verify "Label" article

- Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Member-Picker/index.md
* Added using statements to code snippets.
> v10: Member Picker

- Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Member-Group-Picker/index.md
* Added using-statements to samples where missing.
> v10: Verify "Member Group Picker" article

- Fundamentals/Data/Members/index.md
Added versionTo tag as well as removed reference to Umbraco tv and added link to youtube
> Updated article for v10

- Fundamentals/Code/Creating-Forms/index.md
Added a few comments about how it might be necessary to create the /Models and /Controllers folders manually.
> v10: Verified "Create Form (MVC)"

- Fundamentals/Data/Users/index.md
No changes. Fixed some formatting.
> v10: Verify Users article

- Fundamentals/Data/Content-Version-Cleanup/index.md
Clean up some grammar and language.
Tried to make it a little clearer how this feature works.
> v10: Content Version Cleanup

- Fundamentals/Setup/Upgrading/umbraco10-breaking-changes.md
- Reference/Configuration/GlobalSettings/index-v10.md
> v10: Add global settings docs etc

- Reference/Routing/custom-routes.md
Update custom route docs to include more succinct information about utilising custom routes and routes that are considered client side requests since 9.5 was released that fixes some previously noted bugs
Profile: https://our.umbraco.com/members/id:294245/
> Updated custom-route docs post 9.5 Release

- Reference/Searching/Examine/Indexing/index.md
- Reference/Searching/Examine/Quick-Start/index.md
- Reference/Searching/Examine/examine-events.md
- Reference/Searching/Examine/examine-management.md
- Reference/Searching/Examine/examine-manager.md
- Reference/Searching/Examine/index.md
- Reference/Searching/Examine/overview-explanation.md
- Reference/Searching/Examine/pdf-index.md
- Reference/Searching/Examine/terminology.md
- Reference/Searching/index.md
Added notes to each article, referencing the Examine and Lucene documentation.
> v10: Examine

- Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/User-Picker/index.md
The samples didn't work for v9 either, so I updated the article to cover both.
> v10: Verified User Picker article for v10

- Umbraco-Cloud/Upgrades/Product-Dependencies/index.md
Removed V7 and courier and added v10
> Cleaned up product dependencies on cloud

- Extending/Key-Vault/index-v10.md
- Extending/Key-Vault/index.md
Belongs to: https://github.com/umbraco/UmbracoDocs/issues/4039
> Update KeyVault article for v10

- Umbraco-Cloud/Set-Up/Working-Locally/index.md
Removed the part about saying umbraco 9 and made it more general.
> Removed the Umbraco 9 reference

- Add-ons/UmbracoForms/Installation/Version-Specific.md
Can be reviewed and published as soon ready as it applies also to the release candidates that are already out.
> Added upgrade note for Forms 10.

- Add-ons/Umbraco-Deploy/Deploy-Settings/index.md
- Add-ons/Umbraco-Deploy/Upgrades/version-specific.md
This is some additional detail on a configuration option that will be available in Umbraco Deploy for Cloud 10.0.0.
> Documented prefer local db configuration

- Fundamentals/Setup/Upgrading/version-specific.md
- Umbraco-Cloud/Upgrades/Migrating-from-9-to-10/index.md
Also added a table of contents to the Cloud upgrade guide, and moved the video tutorial up in the article.
> Added link between CMS and Cloud upgrade guides for v10

- Add-ons/Umbraco-Deploy/Installing-Deploy/CICD-Pipeline/ci-cd-azure-dev-ops.md
- Extending/Section-Trees/Searchable-Trees/index-v10.md
Updated the C# code sample starting on line 73.
> Updating SearchableTrees for v10

- Reference/Templating/Mvc/partial-views-v8.md
- Reference/Templating/Mvc/partial-views.md
Need help verifying Caching section.
> Updated Partial Views article for v9/v10

- Reference/Routing/Request-Pipeline/IContentFinder.md
Fixes: https://github.com/umbraco/UmbracoDocs/issues/4111
return `Task<bool>` instead of `bool`.
> Update IContentFinder code samples

- Tutorials/Creating-a-Property-Editor/part-2.md
Is necessary to update the if statement so that it works even if the config is created using c# code. 
Fixes: https://github.com/umbraco/UmbracoDocs/issues/4118
> Update if statement

- Fundamentals/Setup/Install/visual-studio.md
> Added reference to Umbraco's dotnet new templates in the Abbreviated version

- Umbraco-Cloud/Upgrades/Migrating-from-8-to-9/index.md
as it is no longer possible to create umbraco 9 project on Umbraco Cloud, and instead they need to go from 8 to 10 instead
> Updated the article from v9 to v10

- Umbraco-Cloud/Upgrades/Upgrading-from-9-to-10/index.md
A few updated after following the Umbraco 9 -> 10 guide on an existing Umbraco Cloud project.
> Info about packages to update

- Fundamentals/Setup/Server-Setup/azure-web-apps-v9.md
Updated Azure recommendations to use the new FileSystemMainDomLock (from 9.4+)
> Updated Azure recommendations to use the new FileSystemMainDomLock 

- Fundamentals/Setup/Upgrading/version-specific.md
I tried to follow the Upgrade steps 1 to 8 verbatim but step 8 doesn't actually work until after the old files have been deleted.
I've updated the steps to include the Program.cs change and file deletion to make it clear these are a necessary part of the process. 
Also, I'm pretty sure that the whole `/umbraco/config` directory can go.
> v9 - v10 Upgrade step improvements

- Contribute/Style-Guide/index.md
https://github.com/umbraco/UmbracoDocs/issues/4066
> Fixed broken links in the Contribute article

- Add-ons/Umbraco-Deploy/Troubleshooting/index.md
Removed duplicate content and added link to the cloud article.
> Cleanup duplicate schema mismatch article.

- Reference/Security/Cookies/index.md
Added info as per https://umbraco.slack.com/archives/C02JJQU9B/p1655981011967159?thread_ts=1655971280.012539&cid=C02JJQU9B
> Added info on `UMB_SESSION` cookie

- Extending/Database/index-v8.md
- Extending/Database/index.md
- Fundamentals/Setup/Requirements/index-v7.md
- Fundamentals/Setup/Requirements/index-v8.md
- Fundamentals/Setup/Requirements/index-v9.md
- Fundamentals/Setup/Requirements/index.md
> Added Database-level Roles section

- Fundamentals/Code/Debugging/Logging/index.md
Fixes #3954
I've added the Note as mentioned in the Issue. Do we have a code snippet that can be added as well?
> Added IProfilingLogger Note

- Add-ons/UmbracoForms/Installation/Version-Specific.md
- Fundamentals/Setup/Upgrading/version-specific.md
This adds a couple of points around upgrades that came up in community discussions.
> Clarified upgrade requirements for Forms 10

- Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/File-Upload/index.md
@sofietoft 
As mentioned [here](https://github.com/umbraco/UmbracoDocs/pull/4156)  I've created a pull request to update this document as well.
Thanks
> Updated signature of SetValue overload method

- Reference/Searching/Examine/Quick-Start/index-v8.md
- Reference/Searching/Examine/Quick-Start/index.md
Fixes: https://github.com/umbraco/UmbracoDocs/issues/3634
> Update examine quick start for v9 plus

- Add-ons/UmbracoForms/Installation/Version-Specific.md
- Fundamentals/Setup/Upgrading/version-specific.md
I've created this with some further information on the Forms upgrade, following the discussion in [this PR](https://github.com/umbraco/UmbracoDocs/pull/4182#issuecomment-1175303686).
> Further clarification and detail on Forms 10 upgrade from previous versions.

- Umbraco-Cloud/Upgrades/Upgrading-from-9-to-10/index.md
As mentioned in PR #4182 by @bjarnef added link to UmbracoForms.
> Added link to UmbracoForms

- Umbraco-Heartcore/Tutorials/Creating-A-Custom-Grid-Editor/index.md
Noticed that notes didn't show correctly on https://our.umbraco.com/documentation/Umbraco-Heartcore/Tutorials/Creating-A-Custom-Grid-Editor/
> Fix note syntax

- Extending/Packages/Creating-a-Package/index.md
- Extending/Packages/UmbPack/index.md
- Added more details about package migrations to the "Creating a package" article.
- Updated version numbers on the UmbPack article.
- Added note to UmbPack article about how to use NuGet instead.
> Minor updates to the Packages docs

- Reference/Querying/UmbracoContext/index.md
Not sure if I put in in the right folder. What do you think?
> Add missing documentation about the UmbracoContext

- Add-ons/UmbracoForms/Developer/Extending/Adding-a-Fieldtype.md
> Added detail of FieldTypeViewName property when creating custom field types.

- Fundamentals/Setup/Install/iis.md
Added additional instructions as described in #4203.
> Added instructions on how to set proper permissions on the NuGet cache folder

- Extending/Backoffice-Tours/index.md
"want to user to click" -> "want the user to click"
> tiny typo fix

- Umbraco-Cloud/Databases/Backups/index.md
As it is not working no longer
> Removed powershell backup script

- Fundamentals/Setup/Install/install-umbraco-with-templates.md
-all doesn't work, --list does
> -all changed to --list

- Umbraco-Cloud/Upgrades/Manual-Upgrades/Manual-Upgrade-Deploy-v8.md
- Umbraco-Cloud/Upgrades/Manual-Upgrades/index.md
Hopefully this will make the v9 version show up as well as it was not showing up
> Renamed the manual upgrade deploy folders, so it matches versions

- Umbraco-Heartcore/Client-Libraries/Dot-Net-Core/MVC-Sample/index.md
Updated Heartcore MVC Sample to reflect the changes in <https://github.com/umbraco/Umbraco.Headless.Client.Net/pull/50#issue-1302122023>
> Updated Heartcore MVC Sample

- Add-ons/UmbracoForms/Developer/Extending/Adding-a-Fieldtype.md
A bit documentation about how to access settings, prevalues etc. in preview of custom field types.
> Add documentation about accessing settings in field preview

- Implementation/Custom-Routing/index.md
Updated the documentation on where the `SetContentLastChanceFinder` is located, which might confuse people who have the right usings but the method is not compiling
> Update custom routing

- Umbraco-Cloud/Upgrades/Minor-Upgrades/index.md
Also i am a bit unsure about the Database upgrade failing part, not sure how i can test it without a new update available, and whether it is still relevant.
Might need input from the cloud team.
> Minor grammar changes

- Umbraco-Cloud/Troubleshooting/Deployments/Changes-Not-Being-Applied/index.md
Some minor changes and verified for v10
> Updated changes not being applied article

- Tutorials/Creating-a-Custom-Dashboard/index.md
Created PR as per discussion in [slack](https://umbraco.slack.com/archives/CT8TJCNN9/p1658218988261509)
> Updated text for v9 and above

- Umbraco-Cloud/Set-Up/Project-settings/index.md
removed superfluous MyAwesomeProject folder 
please see: #4240
> removed superfluous MyAwesomeProject folder

- Umbraco-Cloud/Set-Up/Users-On-Cloud/index.md
All project on the new infra should be on UmbracoID therefore the note is not necessary any more
> Minor changes and removed the note about the version

- Umbraco-Cloud/Set-Up/Project-settings/index.md
- removed the renaming content and moved it to working locally 
- added a link to the working locally article
> updated the project settings article

- Umbraco-Heartcore/API-Documentation/Redirect/index.md
- Umbraco-Heartcore/API-Documentation/index.md
Added a proposal of how the Redirect documentation could look like.
Is there anything i forgot to mention?
> Added redirect docs

- Umbraco-Cloud/Databases/Local-Database/index-v7.md
- Umbraco-Cloud/Databases/Local-Database/index.md
> Updated the article to reflect that we use SQLite now

- Umbraco-Cloud/Databases/Cloud-Database/index.md
Not fully completed yet, as we need to clarify the LocalDB part.
> Updated the cloud db article with grammar fixes

- Reference/Configuration/RequestHandlerSettings/index.md
Fixes syntax highlight issue in the code block.
> Updated language settings for code block

- Reference/Templating/Mvc/partial-views.md
Update the existing docs, to match Umbraco 9+10
> Updated MVC > Partial Views (And Caching) to v9+v10

- Umbraco-Heartcore/API-Documentation/Redirect/index.md
Noticed the endpoint description was wrong so I've updated with the correct description.
> Update redirect url endpoint description

- Add-ons/UmbracoForms/Installation/Version-Specific.md
- Add-ons/UmbracoForms/Installation/index.md
> Added notes from release blog post for changes to be aware of in Forms 8.13, 9.5, 10.1.

- Add-ons/UmbracoForms/Installation/Install/index.md
- Add-ons/UmbracoForms/Installation/index.md
- Added video tutorial
- Changed the title from extending to installing
- Removed the part where it was mentioning Umbraco 7.2 as i don't believe that is relevant anymore.
> Small changes to the extending forms section

- Reference/Routing/Surface-Controllers/index.md
> Fixes Issue# 3242

- Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/index.md
All built in property editors are verified against Umbraco 10.
> Change 'versionTo' from 9 to 10

- Fundamentals/Setup/Upgrading/migrating-to-v8.md
... including two possible work-arounds.
> Add back note on migrating issue

- Umbraco-Cloud/Set-Up/SMTP-settings/index.md
As per slack conversation: https://umbraco.slack.com/archives/C03GN8R44/p1660640211801949?thread_ts=1660312464.709569&cid=C03GN8R44 added 2 more configuration settings and linked to the global settings article.
> Updated SMTP settings article with additional configuration

- Extending/FileSystemProviders/Azure-Blob-Storage/index-v9.md
Version 1.1.1 is the correct version of Umbraco.StorageProviders.AzureBlob for v9 of Umbraco
Spent a while on this when tracking down a build failure hope this helps
> Umbraco.StorageProviders.AzureBlob version 9 info 

- Extending/Property-Editors/Property-Value-Converters/index.md
Proposed clarifications for property cache level as requested in https://github.com/umbraco/UmbracoDocs/issues/3335
> Update docs for property cache level

- Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Media-Picker-3/index-v9.md
- New `index-v9.md` file for Umbraco 9
- Updated `index.md` based on notes from @kjac 🎉
> Added v10 version of Media Picker 3 article

- Add-ons/UmbracoForms/Editor/Creating-a-Form/Fieldtypes/Recaptcha3/index.md
updated the appsettings.json to be more clear where to add the ReCaptcha settings (in the "umbraco" group)
> where in appsettings to add recaptcha

- Tutorials/Creating-and-distributing-a-package/index.md
- Added Notes referring to v9 and above article
- Fixed markdown errors.
> Added Note and fixed markdown errors

- Umbraco-Cloud/Set-Up/Config-Transforms/index.md
Some xdt magic that don't work no more on v10. Not sure when it changed but I updated the snippet and tested it on Cloud.
> Updated the code snippet for config transforms

- Reference/Configuration/index.md
I removed a deprecated link for UmbracoSettings
> Remove deprecated link

- Reference/Searching/Examine/Quick-Start/index.md
> Fix up formatting for the Examine quick start

- Umbraco-Cloud/Frequently-Asked-Questions/index.md
- Umbraco-Cloud/Getting-Started/Baselines/index.md
> Updated articles to reflect that we now have to regions available.

- Umbraco-Cloud/Set-Up/Usage/index.md
measured against the plan usage limits. against instead of againt
> Fixing typo

- Reference/Security/index.md
"how to can harden" - deleted can
> Fixing sentence

- Fundamentals/Code/Subscribing-To-Events/index.md
> Updated Note

- Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Nested-Content/index.md
data-type => Data Type
data type => Data Type
document-type => Document Type
document type => Document Type
> Small fixes

- Fundamentals/Setup/Install/installing-nightly-builds.md
"There are three steps to this" - added "do" so the sentence becomes "There are three steps to do this."
> Added a word

- Contribute/Style-Guide/index.md
What may be 'easy' for you, might not be easy another user reading the article. > What may be 'easy' for you, might not be easy for another user reading the article.
> added "for"

- Add-ons/Umbraco-Deploy/Installing-Deploy/Install-Configure/index.md
We spotted this error today where the docs and code don't match up, hence this PR to resolve.
It can be published as soon as it is reviewed and approved.
> Fixed incorrect configuration key

- Tutorials/Creating-a-Custom-Dashboard/index.md
Old sentence: "Next we will create a HTML file inside this folder called 'WelcomeDashboard.html' the html file will contain a fragment of a html document and so does not need <html><head><body> entities."
New sentence: "Next, we will create a HTML file inside this folder called 'WelcomeDashboard.html'. The html file will contain a fragment of a html document and does not need &lt;html&gt;&lt;head&gt;&lt;body&gt; entities."
> Added comma, dot and deleted "so"

- Add-ons/UmbracoForms/Developer/Email-Templates/index.md
Related to https://github.com/umbraco/Umbraco.Forms.Issues/issues/866
> Fix typo in CheckBoxList field type

- Fundamentals/Setup/Server-Setup/Load-Balancing/azure-web-apps-v9.md
To align with the recommendation https://our.umbraco.com/Documentation/Fundamentals/Setup/Server-Setup/azure-web-apps#recommended-configuration I updated the `MainDomLock` for 9.4+
> Updated docs since 9.4 to recommend using FileSystemMainDomLock

- Reference/Configuration/SecuritySettings/index.md
Added details about the `AllowEditInvariantFromNonDefault` security setting added in 10.2.
> v10.2: New AllowEditInvariantFromNonDefault setting

- Extending/Property-Editors/Package-Manifest/index.md
- Tutorials/Creating-a-Property-Editor/index.md
This should not be merged before I've cleared up the difference between the `supportsReadOnly` setting and the `isReadOnly` setting.
> Add note about the supportsReadOnly mode config

- Reference/Querying/IPublishedContentQuery/index.md
- Reference/Querying/index.md
- Changed code examples from being directly in view to being in a service
> Update IPublishedContentQuery to use proper standards

- Add-ons/index.md
Learn more about the licensing model we use for our licensed products, Umbraco Courier and Umbraco Forms. => Learn more about the licensing model we use for our licensed product Umbraco Forms.
Deleted: "s, Umbraco Courier and"
> Deleted stuffs :o

- Add-ons/UmbracoForms/Developer/Extending/Adding-a-Type.md
Adding a note about additional NuGet package.
> Update to 'Adding a type to the provider model'

- Reference/Searching/Examine/pdfindex-multisearcher-v8.md
- Reference/Searching/Examine/pdfindex-multisearcher.md
This will have to pass an internal review from the D-team before being merged in 👍 
- Updated nuget command to use `dotnet add package`
- Updated composer to directly add the multisearcher
> Update multisearcher documentation

- Umbraco-Heartcore/API-Documentation/Redirect/index.md
> Added an 's' to Acces

- Add-ons/UmbracoForms/Developer/Extending/Adding-a-Prevaluesourcetype.md
Reassuring people about what ValidateSettings are and hopefully linking correctly to the page on which that is explained...
> Adding the new Caption to the PreValue example

- Reference/Routing/Umbraco-API-Controllers/index.md
> Fixes Issue 4361

- Add-ons/Umbraco-Deploy/Deployment-Workflow/Deploying-Deletions/index.md
- Fundamentals/Setup/Server-Setup/Load-Balancing/azure-web-apps-v8.md
- Reference/Searching/Examine/examine-events.md
- Tutorials/Creating-a-Custom-Dashboard/index.md
Minor changes made during our Styleguide Workshop in the HDTV team.
> Cleanup some vale warnings

- Reference/Configuration/RichTextEditorSettings/index.md
added an example of adding custom formats to the dropdown.
> add custom formats dropdown example

- Tutorials/Cache-Static-Assets/index.md
- Tutorials/index.md
Related to issue/discussion in https://github.com/umbraco/Umbraco-CMS/issues/12666
Example of caching static assets in Umbraco 9.3.0+ with suggestions from @ronaldbarendse
> Add tutorial for caching of static assets

- Umbraco-Cloud/Set-Up/Manage-Hostnames/ca-record-migration.md
- Umbraco-Cloud/Set-Up/Manage-Hostnames/index.md
Updated the docs to reflect that CA for new hostnames has been changed.
> New certificate authority documentation

- Implementation/Services/index-v8.md
- Implementation/Services/index.md
The docs for using UmbracoContext via the `UmbracoContextFactory` in C# include a code sample that recommends creating a new UmbracoContext for each item in a collection.
This is okay and will work fine, but definitely won't be as efficient as it should be (especially for larger collections).
This PR changes this code sample to first create an UmbracoContext (once), then loop over the items in the collection.
> Avoid using EnsureUmbracoContext in a loop

- Implementation/Custom-Routing/index.md
- Implementation/Custom-Routing/signalR.md
> Fixes Issue 4391

- Add-ons/UmbracoForms/Developer/Extending/Adding-a-Fieldtype.md
https://github.com/umbraco/UmbracoDocs/issues/4405
> Fixes Issue 4405

- .github/styles/UmbracoDocs/Brands.yml
- .github/styles/UmbracoDocs/Names.yml
- .github/styles/UmbracoDocs/Terms.yml
- .github/styles/UmbracoDocs/UmbracoTerms.yml
I've updated
- Terms.yaml
I've added
- Brands.yaml to ensure correct capitalization of brand names
- Names.yaml to ensure the current capitalization of markup languages
- UmbracoTerms.yaml to ensure correct spelling and capitalization of Umbraco specific terms and names
> Adding more rules and extending existing ones

- CONTRIBUTING.md
- Contribute/Style-Guide/index.md
- Contribute/index.md
I've added the new rules to the Styleguide contribution article.
Also cleaned up the article a bit.
> Update Styleguide article in Contribution section

- Extending/Health-Check/Guides/CrossSiteScriptingProtection.md
Reverts umbraco/UmbracoDocs#4421
The removal of the Health Check was reverted, so doing the same to this one.
> Revert "Delete CrossSiteScriptingProtection.md"

- Add-ons/Umbraco-Plumber/Licensing/index.md
Adding a section to Licensing to let people know how to aquire a plumber license.
> Licensing update for Plumber

- Umbraco-Cloud/Upgrades/index.md
"prior and the *the* status page will be updated"
> the instead of that

- Add-ons/Umbraco-Deploy/Extending/index.md
https://airtable.com/appAelapv34OT1avk/tbliWYWb9SC0z4k3I/viwIrOG4IpVmsxFOD/recswaAMH7OcWl4vf?blocks=hide
I couldn't shorten a couple of sentences so they are still throwing a warning message.
> Fixed quite some vale and markdown issues

- Extending/Property-Editors/Package-Manifest/index.md
@eshanrnh Sorry for the deplay on this one. 
fixes: https://github.com/umbraco/UmbracoDocs/issues/4339
> Explain imanifest filters

- .github/styles/UmbracoDocs/Acronyms.yml
- .github/styles/UmbracoDocs/Brands.yml
- .github/styles/UmbracoDocs/Names.yml
- Add-ons/Umbraco-Deploy/Installing-Deploy/CICD-Pipeline/ci-cd-azure-dev-ops-v8.md
- Extending/Section-Trees/Trees/index-v7.md
- Extending/Section-Trees/Trees/index-v8.md
- Extending/Section-Trees/Trees/index.md
- Fundamentals/Design/Stylesheets-Javascript/index-v7.md
- Fundamentals/Design/Stylesheets-Javascript/index.md
- Implementation/Custom-Routing/signalR.md
- Reference/Configuration-for-Umbraco-7-and-8/webconfig/index-v7.md
- Reference/Configuration-for-Umbraco-7-and-8/webconfig/index.md
- Reference/Routing/Surface-Controllers/index.md
- Tutorials/Creating-a-Custom-Dashboard/index-v7.md
- Umbraco-Cloud/Release-Notes/2022-05-23-ReleaseNotes.md
- Umbraco-Heartcore/Backoffice/Grid-Editors/index.md
- Umbraco-Heartcore/Getting-Started-Cloud/Using-The-Forms-API/index.md
Small fix for "javascript" casing and "azure" casing :)
> Add" javascript -> JavaScript" rule and "azure -> Azure" rule

- Reference/Management/Services/MediaService/Index.md
Following https://github.com/umbraco/UmbracoDocs/issues/4440 I have made a few updates to the Media Service doc and updated the code samples from the Samples Project.
> Various updates to the MediaService doc

- Fundamentals/Backoffice/Content-Templates/index.md
- Fundamentals/Backoffice/Infinite-editing/index.md
> Readability improvements, update Content Templates and  Infinite Editing 

- Fundamentals/Data/Defining-content/index-v8.md
- Fundamentals/Data/Defining-content/index.md
- Tutorials/Creating-Basic-Site/Document-Types/index.md
Belongs to: https://airtable.com/appAelapv34OT1avk/tbliWYWb9SC0z4k3I/viwIrOG4IpVmsxFOD/rec271bnT4V5SZj7F?blocks=hide
> Added note for property alias casing

- .github/styles/UmbracoDocs/Acronyms.yml
- Fundamentals/Backoffice/Login/index.md
Update Fundamentals -- Login to improve readability. 
Belongs to:
https://github.com/umbraco/UmbracoDocs/issues/4416
> Update Fundamentals -- Login -- index.md

- Fundamentals/Setup/Upgrading/umbraco11-breaking-changes.md
Added docs about breaking changes between 10 and 11
> Added docs about breaking changes between 10 and 11

- Reference/Templating/Mvc/ViewComponents.md
Docs Sample repo
https://github.com/umbraco/Umbraco.Docs.Samples/pull/11
> Amended view components sample

- Reference/Configuration/filesystemProviders.md
Fixed the docs based on feedback from a custom in intercom
> Fixed the docs

- Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Multi-Url-Picker/index.md
li tag not needed when not looping through links (max == 1)
> cleaned up code, removed li tag

- Fundamentals/Backoffice/Sections/index.md
Belongs to https://github.com/umbraco/UmbracoDocs/issues/4416
> Readability improvements - Fundamentals Backoffice Sections

- Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-Grid-Editor/index.md
* Updated note to reflect the new release version
* Cleaned up from formatting
> Block Grid release is moved to Umbraco 11

- Tutorials/Custom-Error-Pages/index-v8.md
- Tutorials/Custom-Error-Pages/index.md
Making some small updates to the Custom Errors tutorial pages using VALE. 
First time using VALE so I hope this is OK. They are small changes and before I work on any other pages, I'll wait for feedback on this PR. :)
> [AMEND] VALE updates to Custom Errors tutorials

- Fundamentals/Backoffice/Variants/index.md
Belongs to https://github.com/umbraco/UmbracoDocs/issues/4416
> Readability improvements - Fundamentals Backoffice Variants

- Tutorials/Add-Google-Authentication/index.md
Making changed to the Google Authentication Tutorial. Following VALE suggestions on how to make the tutorial friendlier.
> Making Google Authentication Tutorial Friendlier

- Reference/Security/Authenticate-with-Active-Directory/index.md
Is it a good idea to explain that the TokenEndpoint and AuthorizationEndpoint must also be configured if it is a Single Tenant configuration?
> Add TokenEndPoint and AuthorizationEndpoint explanation

- Tutorials/Connecting-Umbraco-Forms-and-Zapier/index.md
- There are a couple of sentences I just couldn't find a way to get in to the 25 word limit. I think if they were shortened at all they would lose their meaning.
> Make Zapier Tutorial more friendly

- Fundamentals/Setup/Install/index.md
> Improve readability --> Fundamentals Setup Install

- Reference/Notifications/Creating-And-Publishing-Notifications/index-v11.md
- Reference/Notifications/Creating-And-Publishing-Notifications/index.md
Adds a new v11 document and fixed the code example to work with v11.
I also noticed that the V10 version is wrong (missing logger, and not properly using ICoreScopeProvider) so I've update the V10 version as well to fix this 😄
> V11: Fix publishing notifications

- .github/styles/UmbracoDocs/Acronyms.yml
- Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Image-Cropper/index.md
No changes to the code samples are needed.
> Fixed vale on the ImageCropper article

- Tutorials/Creating-a-Custom-Dashboard/index.md
- the 7 issues remaining are .html and .css extensions. I looked to see if there was a way to add a new rule to exclude extensions but couldn't find any info in the VALE documentation.
> Update Create a Custom Dashboard

- Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-Grid-Editor/index.md
- Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-List-Editor/index-v8.md
- Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-List-Editor/index.md
- Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/label-property-configuration.md
- Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Nested-Content/index-v7.md
- Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Nested-Content/index-v8.md
- Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Nested-Content/index.md
As suggested by HQ staffers after I published this blog post https://joe.gl/ombek/blog/umbraco-angularjs-filter-cheat-sheet/
> Provide details about block editor label syntax

- Extending/Database/index-v10.md
- Extending/Database/index-v11.md
- Extending/Database/index.md
While verifying this works for v11, I stumbled upon a few things in the code examples that could be updated 👍
> Update "Extending/Database" code examples for v11

- Add-ons/UmbracoForms/Editor/Attaching-Workflows/Workflow-Types/index.md
To be merged in on **Oct 27**.
> Added Video Link

- Development-Guidelines/Coding-Standards/index.md
- Development-Guidelines/Coding-Standards/jquery-guidelines.md
- Development-Guidelines/Coding-Standards/js-guidelines.md
- Development-Guidelines/Coding-Standards/naming-conventions.md
- Development-Guidelines/building-angular-project.md
- Development-Guidelines/index.md
- Getting-Started/Developing-websites-with-Umbraco/Customizing-Umbraco-sites/index.md
- Getting-Started/Developing-websites-with-Umbraco/Extending-the-Umbraco-Backoffice/index.md
- Getting-Started/Developing-websites-with-Umbraco/index.md
- Getting-Started/Editing-websites-with-Umbraco/index.md
- Getting-Started/Where-can-I-get-help/index.md
- Getting-Started/index.md
Updates files in Development-Guidelines and Getting-Started folders.
> Readability Improvements base on style guide

- Implementation/Controllers/index-v7.md
- Implementation/Controllers/index.md
- Implementation/Custom-Routing/index-v7.md
- Implementation/Custom-Routing/index-v8.md
- Implementation/Custom-Routing/signalR.md
- Implementation/Data-Persistence/index-v7.md
Improves readability in the Implementation folder.
> Reability improvements based on the style guide

- Add-ons/The-Licensing-model/index.md
https://umbraco.slack.com/archives/C016ZRZ9MJP/p1666625778492389
> Added a note based on a question.

- Fundamentals/Data/Adding-Tabs/index.md
Belongs to:  https://github.com/umbraco/UmbracoDocs/issues/4416
> Improve readability --> Fundamentals  Data Adding-Tabs

- Add-ons/Umbraco-Deploy/Installing-Deploy/CICD-Pipeline/ci-cd-azure-dev-ops-v8.md
- Extending/Health-Check/Guides/HttpsConfiguration.md
- Extending/index-v8.md
- Fundamentals/Data/Creating-Media/default-media-types.md
- Fundamentals/Setup/Install/install-umbraco-with-vs-code.md
- Implementation/Unit-Testing/index-v8.md
- Reference/Configuration/WebRoutingSettings/index.md
- Reference/Events/CacheRefresher-Events.md
- Reference/Management/Services/ConsentService/Index-v7.md
- Reference/Management/Services/ConsentService/Index-v8.md
- Reference/Management/Services/ConsentService/Index.md
- Reference/Routing/Custom-Routes/index.md
- Reference/Templating/Modelsbuilder/Builder-Modes-v7.md
- Tutorials/Editors-Manual/Working-with-Content/Rich-Text-Editor/index-v7.md
- Umbraco-Cloud/Set-Up/Config-Transforms/index-v7.md
A collection of changes to fix some docs based on the recommended formatting :)
> Docs: make friendly

- umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/block-editor/README.md
- umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/block-editor/block-grid-editor.md
- umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/block-editor/block-list-editor.md
- umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/block-editor/build-custom-view-for-blocks.md
- umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/block-editor/label-property-configuration.md
- umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/checkBox-list.md
- umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/color-picker.md
- umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/content-picker.md
- umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/dropdown/README.md
- umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/dropdown/old-dropdown-list-multiple-publish-keys.md
- umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/dropdown/old-dropdown-list-multiple.md
- umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/dropdown/old-dropdown-list-publishing-keys.md
- umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/dropdown/old-dropdown-list.md
- umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/grid-layout/README.md
- umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/grid-layout/add-value-programmatically.md
- umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/grid-layout/build-your-own-editor.md
- umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/grid-layout/configuring-the-grid-layout-datatype.md
- umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/grid-layout/grid-editors.md
- umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/grid-layout/grid-layout-best-practices.md
- umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/grid-layout/render-grid-in-template.md
- umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/grid-layout/settings-and-styles.md
- umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/grid-layout/what-are-grid-layouts.md
- umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/rich-text-editor/README.md
- umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/rich-text-editor/configuration.md
- umbraco-cms/fundamentals/backoffice/property-editors/built-in-property-editors/rich-text-editor/rte-styles.md
Fixed some markdown errors as well.
> Cleanup cms/fundamentals/backoffice/property-editors article Part 1

- Fundamentals/Data/Content-Version-Cleanup/index.md
> Improve readability - Fundamentals Data Content-Version-Cleanup

- Reference/Querying/IPublishedContent/Properties/index.md
> Update .Url heading to match code sample

- Add-ons/Umbraco-Deploy/Extending/index.md
This came up in a support request where we found this particular type of "connector" for Umbraco Deploy didn't have a public example available.  So I've added one in this PR.
> Added docs on grid cell value connectors.

- Fundamentals/Data/Data-Types/index.md
> Improve readability - Fundamentals Data Data-Types

- Umbraco-Cloud/Getting-Started/Migrate-Existing-Site/index-v8.md
Removed the migrating video from the docs as it is very out-dated
> Removed deprecated video from docs

- Fundamentals/Code/Creating-Forms/index.md
> Improve readability - Fundamentals Code Creating-Forms

- Extending/Property-Editors/Package-Manifest/index.md
Reference script instead of html view
> Reference script instead of html view

- Fundamentals/index.md
> Improve readability - Fundamentals 

- Fundamentals/Backoffice/Property-Editors/index.md
> Improve readability - Fundamentals Backoffice Property Editors 

- umbraco-forms/installation/manualupgrade.md
> Verified for v11

- Fundamentals/Code/Subscribing-To-Events/index.md
> Improve readability - Fundamentals Code Subscribing to Events

- Fundamentals/Backoffice/LogViewer/index.md
> Improve readability - Fundamentals Backoffice LogViewer

- Umbraco-Cloud/Upgrades/Migrating-from-8-to-10/index.md
- Umbraco-Cloud/Upgrades/Upgrading-from-9-to-10/index.md
Added sections for adding and upgrading `global.json` in the following sections
- Migrating from 8 - 10
- Upgrading from 9-10
> Upgrade globaljson

- Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-Grid-Editor/index.md
- Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/build-custom-view-for-blocks.md
A few additions and changes to the Block Grid Editor documentation.
TODO:
[] Would be nice with a screenshot/gif for the new part about Scaling
> Changes and improvements for the Block Grid Editor documentation

- Add-ons/Umbraco-Deploy/Deploy-Settings/index-v8.md
- Add-ons/Umbraco-Deploy/Deploy-Settings/index.md
This is due in a patch release expected on 15th November.  So it can be reviewed but shouldn't be published before then.
> Documented Deploy's SourceDeployBatchSize setting.

- Fundamentals/Code/Debugging/index.md
> Improve readability - Fundamentals Code Debugging

- Extending/Dashboards/index.md
And clarify creation rather than modification. Also highlight that other languages are available!
> Correct user language file path

- Tutorials/Members-Registration-And-Logins/index.md
https://github.com/umbraco/Umbraco.Docs.Samples/pull/16
> Making sure the code sample matches with the Samples repo

- Reference/Configuration/ContentSettings/index-10.0.0.md
- Reference/Configuration/ContentSettings/index.md
With https://github.com/umbraco/Umbraco-CMS merged, we will have 2 new settings in the ContentSettings 👍 
I have made a note for the v10 docs, that from 10.4 an onwards you can use the new settings.
I have also created v11 docs and removed mention of the old settings, and replaced them with the new ones 😁
> Update contentsettings documentation

- umbraco-cms/reference/configuration/contentsettings.md
Update content settings article based on #4641
> Update content settings article

- Fundamentals/Setup/Server-Setup/index.md
> Improve readability - Fundamentals Setup Server-Setup

- Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Nested-Content/index-v8.md
error thrown if item doesn't exist so added null check
> added null checker for single item mode

- Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Nested-Content/index.md
Missed one from the previous merge!
> Another Nested Content nullchecker for V9/10 docs

- Add-ons/Umbraco-Deploy/Upgrades/version-specific.md
This PR will be updated with further documentation for Deploy 11, reflecting changes made after the first release candidate (so currently pending). I'll mark is as draft and create a full PR when it's ready for review and publish.
> Further documentation updates for Deploy 11

- umbraco-cloud/getting-started/README.md
- umbraco-cms/README.md
- umbraco-deploy/README.md
- umbraco-deploy/get-started-with-deploy.md
- umbraco-forms/README.md
- umbraco-heartcore/umbraco-heartcore/README.md
> Update landing pages

- Add-ons/UmbracoForms/Developer/AjaxForms/index.md
- Add-ons/UmbracoForms/Developer/Configuration/index.md
This documents a couple of configuration options that are available from this upcoming release, due to be available on Tuesday 29th November.
If it's possible to review and publish for the morning of that day please, that would be ideal, and thanks if so.
> Docs updates for Forms 10.2.1

- Fundamentals/Design/Partial-View-Macro-Files/index.md
> Improve readability - Fundamentals Design Partial-View-Macro-Files

- Add-ons/UmbracoForms/Installation/Version-Specific.md
This PR will be updated with further documentation for Forms 11, reflecting changes made after the first release candidate (so currently pending).  I'll mark is as draft and create a full PR when it's ready for review and publish.
> Further documentation updates for Forms 11

- Umbraco-Cloud/Upgrades/Minor-Upgrades/index.md
- Created Change Requests for both 10 and 11 branch in GitBook
> Updated video link

- umbraco-cloud/set-up/project-settings/secrets-management.md
Added an explanation on how to overwrite keys in appSettings.json using secrets.
> Updated secret management page

- umbraco-cms/fundamentals/code/subscribing-to-notifications.md
> Improve readability - Fundamentals Code Subscribing-To-Notifications

- umbraco-cms/fundamentals/code/umbraco-services.md
> Readability improvements - Fundamentals code Umbraco-Services

- umbraco-cms/fundamentals/data/defining-content.md
> Readability improvements - Fundamentals data defining-content

- Fundamentals/Setup/Install/index.md
- Fundamentals/Setup/Install/install-umbraco-with-nuget-v7.md
- Fundamentals/Setup/Install/install-umbraco-with-nuget.md
- Fundamentals/Setup/Install/install-umbraco-with-vs-code.md
- Fundamentals/Setup/Requirements/index.md
- Fundamentals/Setup/Upgrading/general.md
- Fundamentals/Setup/Upgrading/version-specific.md
Add links to the new platform from upgrading and installation articles.
> Add direct links to the migated docs

- umbraco-cms/fundamentals/setup/upgrading/version-specific/README.md
I bet we'll see problems judging from this chat
> Add upgrade guidance for v10 to v11

- umbraco-cms/implementation/integration-testing.md
Migrating this PR: https://github.com/umbraco/UmbracoDocs/pull/4503
> adding v10 specific information for integration testing (migrated)

- umbraco-cloud/set-up/project-settings/manage-cdn-caching.md
Migrated this PR: https://github.com/umbraco/UmbracoDocs/pull/4615/
> Making it more clear what kind of hostname (migrated)

- umbraco-cms/reference/templating/mvc/viewcomponents.md
Added missing closing tag from the view component documentation
> Add missing closing tag

- umbraco-cloud/upgrades/major-upgrades.md
Changed some of the titles from a h3 to a h2.
> Fixed headings in the major upgrades article.

- umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/grid-layout/README.md
Suggest marking Grid Layout and Nested Content as obsolete and directing users to replacement Block Grid and Block List respectively.
> Indicate that Grid Layout is obsolete

- umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/nested-content.md
Suggest marking Nested Content as obsolete and directing users to replacement Block List.
> Indicate that Nested Content is obsolete

- umbraco-heartcore/client-libraries/dot-net-core/mvc-samples.md
Changed "Umbraco" to "Heartcore"
> Appsettings not correct format

- umbraco-cms/fundamentals/setup/requirements.md
Just spotted this while making a question for the Community Quiz :)
> Fixing spelling mistake of minimum

- umbraco-cms/fundamentals/data/scheduled-publishing.md
> Readability improvements - Fundamentals data scheduled - publishing

- umbraco-cms/fundamentals/backoffice/login.md
Updated the greeting in the login article with the correct information.
> Updated  the login article 

- umbraco-cms/fundamentals/data/users.md
> Readability improvements - Fundamentals data users

- umbraco-cms/tutorials/custom-error-page.md
I have copied from a former PR, because there are merge conflicts (cause by the new structure?)
Hopefully this helps you😊
I close the _old_ PR
> add error 500 handling example

- umbraco-cms/reference/notifications/editormodel-notifications/customizing-the-links-box.md
Updating https://github.com/umbraco/UmbracoDocs/pull/4293 for the migrated docs.
@dampee , @kjac - please have a look and let me know if I did it correctly based on the comments 🙏
> Use hardcoded language (migrated)

- umbraco-cms/reference/routing/surface-controllers/README.md
Adds documentation for how to use `Async` action name suffixes.
Originates from https://github.com/umbraco/Umbraco-CMS/issues/12191
> Document asynchronous surface controller actions

- umbraco-cms/reference/security/authenticate-with-active-directory.md
- umbraco-cms/reference/security/auto-linking.md
- umbraco-cms/reference/security/external-login-providers.md
- umbraco-cms/tutorials/add-google-authentication.md
Resolved some vale warnings in articles related to "backOfficeAuthenticationBuilder" and "OnAutoLinking".
Also made sure that the meta description is properly formatted in those articles.
> Updates to fix search issues

- SUMMARY.md
- umbraco-cloud/upgrades/major-upgrades.md
- umbraco-cloud/upgrades/migrate-from-umbraco-10-to-11.md
Created an article for how you can migrate a project from Umbraco 10 to 11
> how to migrate a project from umbraco 10 to 11 on cloud

- umbraco-cloud/upgrades/major-upgrades.md
and linked to the migration guide
> changed the note

- umbraco-cms/fundamentals/setup/server-setup/iis.md
Updated .NET references to the latest version.
Also made some minor changes to the structure.
Related to: https://github.com/umbraco/UmbracoDocs/issues/4811
> IIS Hosting - Server Setup

- umbraco-cloud/upgrades/major-upgrades.md
- adding an image where to find the repository and wwwroot in Kudu 
- adding more information on step 6 about staging as well. 
- it is also not necessary to do the changes locally if you have removed the mentioned files on stage and live on step 5 and 6
> Elaborating on some steps

- umbraco-11/filtering-using-linq.md
Hi there 👋 
I'm back ith a couple of updates to the **Filtering using Linq** section, to make the extensions as self-explanatory as possible (I hope - open to critique, of course 😁)
> Elaborate Linq extensions

- umbraco-forms/developer/ajaxforms.md
- umbraco-forms/developer/configuration/README.md
- umbraco-forms/developer/extending/adding-a-workflowtype.md
- umbraco-forms/developer/themes.md
This PR contains the docs updates to go along with the next set of Forms patch releases: 8.13.5, 9.5.5, 10.2.2 and 11.0.1.
We'll look to make these available on Jan 17, please can they be reviewed prior to then, and then published live on the morning of that date.  Thanks.
> Updates for Forms patch releases (8.13.5, 9.5.5, 10.2.2 and 11.0.1)

- Add-ons/UmbracoForms/Developer/Configuration/index.md
This should be published alongside [this PR](https://github.com/umbraco/UmbracoDocs/pull/4782), so we can also update one piece of information for Forms 8.
> Added additional config value available in Forms 8.13.5

- umbraco-cms/extending/section-trees/trees/README.md
Wouldn't it be nicer to check if the user is an admin using the extension?
> Use extension method

- umbraco-cloud/upgrades/major-upgrades.md
It is now recommended to upgrade from Umbraco 10 to Umbraco 11.
> Removed upgrade warning

- umbraco-cms/tutorials/creating-a-basic-website/creating-master-template-part-2.md
Ref: 404 => https://umbraco.com/apps/umbraco-forms/
> Wrong URL to Umbraco forms purchase page

- umbraco-cms/reference/security/authenticate-with-active-directory.md
Added a note to the Azure AD article based on comments in this Issue: https://github.com/umbraco/Umbraco-CMS/issues/13100
> Note to Azure AD article

- umbraco-cms/reference/searching/examine/indexing.md
> Update Examine/Indexing article - replaces PR #4625

- umbraco-forms/developer/extending/adding-a-fieldtype.md
Fixes the model being wrong in the partial view example.
> Fixes wrong model in example

- umbraco-cms/reference/configuration/datatypes.md
Use Data Type instead of data type
> Readability improvements - datatypes.md

- umbraco-cms/reference/management/services/redirecturlservice.md
> Readability improvements redirect url serivce

- umbraco-cms/reference/configuration/tourssettings.md
> Readability improvement - toursettings.md

- umbraco-cms/extending/language-files.md
I think this is obvious a duplication.
> Remove duplicated description

- umbraco-cloud/getting-started/baselines/README.md
Added the UK region as baselines are not available here
> Added the UK region

- SUMMARY.md
- umbraco-cms/extending/packages/accessibility.md
Hello
This documentation was originally written for the Umbraco Packages team but following a review with @LottePitcher, @KevinJump , @dawoe and so on that the pull request should be moved to Umbraco docs.
I am fully expecting feedback on the PR. The goal wasn't to replace what is available on the internet and from others but to provide some basic information on testing and the benefits of using the Umbraco UI.
> Added notes for creating accessible packages

- .github/styles/UmbracoDocs/Acronyms.yml
- umbraco-cms/reference/searching/examine/pdfindex-multisearcher.md
- umbraco-cms/reference/security/README.md
> More readability improvements

- Fundamentals/index.md
Pr to remove the blank area and add line (attached screenshots)
> Fix Fundamentals design

- umbraco-cms/reference/templating/modelsbuilder/configuration.md
> Readability improvements - modelsbuilder - configuration.md

- umbraco-cms/reference/routing/custom-controllers.md
Was alerted to this on the Discord: https://discord.com/channels/869656431308189746/882984315884040192/1072807329583611945
> Add missing description

- umbraco-cms/reference/templating/modelsbuilder/coolthingswithmodels.md
> Readability improvements cool things with models

- umbraco-cloud/set-up/project-settings/dedicated-resources.md
Added a small section that answers some of the questions from support about the dedicated resources.
> Added Q&A section to dedicated resources

- umbraco-cms/extending/section-trees/trees/README.md
> Small fixes for tree article

- umbraco-cms/extending/backoffice-search.md
> Readability improvements - Update backoffice-search.md

- umbraco-cms/extending/key-vault.md
> Readability improvements - umbraco-cms/extending/key-vault.md

- 10/umbraco-cms/extending/packages/language-files-for-packages.md
- 11/umbraco-cms/extending/packages/language-files-for-packages.md
> Readability improvements language files for packages

- 10/umbraco-cms/extending/packages/README.md
- 11/umbraco-cms/extending/packages/README.md
> Readability improvements extending packages

- 11/umbraco-cms/reference/configuration/runtimesettings.md
> Fix spelling error

- 10/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/block-editor/block-grid-editor.md
- 11/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/block-editor/block-grid-editor.md
"Remake" of this PR: https://github.com/umbraco/UmbracoDocs/pull/4918
> Removes duplicate Scaling Blocks section

- umbraco-cloud/set-up/project-settings/manage-hostnames/rewrites-on-cloud.md
Adds www redirect rule example as well as a warning hint mentioning the  `".*azurewebsites.net*"` pattern requirement
> Enriches the rewrite documentation.

- 10/umbraco-cms/extending/backoffice-search.md
> Readability improvements - backoffice-search.md

- 10/umbraco-cms/extending/property-editors/property-actions.md
- 11/umbraco-cms/extending/property-editors/property-actions.md
> Readability improvements - property actions

- 11/umbraco-cms/extending/language-files.md
> Add Ukranian to list of backoffice languages for 11.2

- 11/umbraco-cms/reference/configuration/requesthandlersettings.md
This PR adds changes from #4893 to the new docs structure.
> Add changes from #4893

- Extending/FileSystemProviders/Azure-Blob-Storage/index.md
This PR adds the changes from #4700 to the legacy-docs.
> Add changes from #4700

- 10/umbraco-cms/extending/embedded-media-providers.md
Still some issues in this article, but I think we can ignore those 😄
> Readability improvements - embedded-media-providers

- generic/the-licensing-model.md
.. as discussed in the previous sprint planning meeting.
> Removed old image/gif and fixed markdown errors..

- 10/umbraco-cms/implementation/default-routing/inbound-pipeline.md
- 11/umbraco-cms/implementation/default-routing/inbound-pipeline.md
> Readability improvements inbound pipeline

- 10/umbraco-cms/implementation/nullable-reference-types.md
- 11/umbraco-cms/implementation/nullable-reference-types.md
> Readability improvements nullable reference types

- 11/umbraco-cms/extending/health-check/guides/clickjackingprotection.md
> readability improvements - clickjackingprotection

- 10/umbraco-cms/extending/property-editors/build-a-block-editor.md
- 10/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/block-editor/block-grid-editor.md
- 10/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/checkbox-list.md
- 10/umbraco-forms/SUMMARY.md
- 10/umbraco-forms/developer/extending/adding-a-exporttype.md
- 10/umbraco-forms/developer/extending/adding-an-event-handler.md
- 11/umbraco-cms/extending/property-editors/build-a-block-editor.md
- 11/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/block-editor/block-grid-editor.md
- 11/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/checkbox-list.md
- 11/umbraco-forms/SUMMARY.md
- 11/umbraco-forms/developer/extending/adding-a-exporttype.md
- 11/umbraco-forms/developer/extending/adding-an-event-handler.md
- SUMMARY.md
- generic/contribute/how-to-add-a-new-version.md
Hey there 👋 - this is just me stumblin' upon something and then digging through to fix it wherever I can.
I've made smaller commits so it's possible to cherry-pick some of them, if necessary.
> Fixes minor typos

- 10/umbraco-forms/developer/localization.md
- 11/umbraco-forms/developer/localization.md
> Updated details on localization for Forms.

- 11/umbraco-cms/extending/health-check/guides/fixedapplicationurl.md
> readability improvements - fixedapplicationurl

- 11/umbraco-cms/extending/health-check/guides/contentsniffingprotection.md
> readability improvements - contentsniffingprotection

- umbraco-cloud/getting-started/migrate-existing-site/README.md
As there are still plenty of people working on v8 who might want to migrate to cloud, I believe it's still worth to have these merge steps included, as they are not identical to the steps on v9+.
Here's just an idea on how to include it.
> Proposing change to include legacy version(s)

- 10/umbraco-cms/extending/health-check/guides/fixedapplicationurl.md
> readability improvements - fixedapplicationurl 

- 10/umbraco-cms/extending/health-check/guides/clickjackingprotection.md
In addition to: https://github.com/umbraco/UmbracoDocs/pull/5000
> readability improvements - clickjackingprotection - v10

- 10/umbraco-cms/extending/health-check/guides/contentsniffingprotection.md
In addition to https://github.com/umbraco/UmbracoDocs/pull/5005
> readability improvements - contentsniffingprotection v10

- 11/umbraco-cms/extending/health-check/guides/folderandfilepermissions.md
> readability improvements - folderandfilepermissions

- 10/umbraco-forms/installation/version-specific.md
- 10/umbraco-forms/release-notes.md
- 11/umbraco-forms/installation/version-specific.md
- 11/umbraco-forms/release-notes.md
I have left these as is as they are still not released 11.1.0-rc001 and 10.3.0-rc001
> Restructured Forms RNs

- 10/umbraco-deploy/release-notes.md
- 11/umbraco-deploy/release-notes.md
To include the updates for the patch release going out on 21st March.
These will also be added in the old location on our, where people will be directed to to view for now.
> Updated Deploy release notes.

- 10/umbraco-forms/release-notes.md
- 11/umbraco-forms/release-notes.md
These are related to a release going out on March 21st, but I've got them on our.umbraco.com too so they can go live whenever you prefer.
> Adds release notes for Forms 10.3.0 and 11.1.0.

- 10/umbraco-cms/extending/key-vault.md
> readability improvements - KeyVault

- 11/umbraco-cms/SUMMARY.md
- 11/umbraco-cms/fundamentals/setup/upgrading/version-specific/upgrade-from-8-to-latest.md
Basically took the one we have for Cloud, added it to the CMS docs and took out all the Cloud specifics.
To do (after review):
> Added a "Upgrade 8 to latest" guide to CMS docs.

- 10/umbraco-cms/reference/configuration/securitysettings.md
- 11/umbraco-cms/reference/configuration/securitysettings.md
Based on this PR: https://github.com/umbraco/Umbraco-CMS/pull/13808 
(also fixed some long sentences in other parts of the article)
To do (post review)
> Added new Security configs to the docs

- 10/umbraco-cms/reference/configuration/contentsettings.md
- 11/umbraco-cms/reference/configuration/contentsettings.md
Pending 11.3 and 10.5 release - **RC Release: March 23th**
This adds documentation of new setting introduced in https://github.com/umbraco/Umbraco-CMS/pull/13900
> Added documentation of new AllowedMediaHosts setting

- 11/umbraco-forms/developer/contentapps.md
> readability improvements - contentapps
