umbraco-11/is-helpers.md
Just stumbled upon this teeny-tiny typo in `.isDescendantOrSelf()`
=> Fix typo in CheatSheet

umbraco-cms/extending/health-check/guides/smtp.md
Value for port is an integer not a string, per appsettings-schema.json 😄
=> Update port reference in SMTP settings

umbraco-cms/reference/configuration/maximumuploadsizesettings.md
I was confused to why Cloud needs a web.config to set a max upload size, so I asked in Discord.
https://discordapp.com/channels/869656431308189746/882984067312787466/1064481265279049818
=> Clarify max upload size settings for Cloud users

.gitbook.yaml, SUMMARY.md
Removed the migration to v11 article from the summary file, so it won't be displayed in the docs as the issue preventing the upgrade should be fixed now.
Gonna keep the article for a while just in case it somehow might be needed again.
=> removed the migration article from the summary

umbraco-cms/tutorials/creating-a-custom-dashboard.md
In the creating custom dashboard tutorial, the HTML example was titled with the XML-file. This PR fixes that.
=> Fix title in dashboard tutorial

umbraco-forms/developer/extending/adding-a-exporttype.md
I'll create this as a draft for now, as this will contain updates associated with a currently unscheduled patch release.
Includes:
- Fix to "add export type" sample code (that to fully work requires a fix due in this patch (see [issue 949](https://github.com/umbraco/Umbraco.Forms.Issues/issues/949) and [PR 707](https://github.com/umbraco/Forms/pull/707)).
=> Updates for Forms patch releases (10.2.3 and 11.0.2)

Add-ons/UmbracoForms/Developer/Healthchecks/scripts/Apply-keys.md, Add-ons/UmbracoForms/Developer/Healthchecks/scripts/Forms-in-the-database-apply-keys.md, Fundamentals/Code/Source-Control/index-v7.md, Fundamentals/Setup/Server-Setup/Load-Balancing/files-replicated.md, Fundamentals/Setup/Server-Setup/Load-Balancing/files-shared.md, Fundamentals/Setup/Server-Setup/Load-Balancing/flexible.md
For the https://our.umbraco.com/Documentation/Fundamentals/Code/Source-Control/index-v7, I've removed the `needsV8Update: "true"` tag since we have a v8 article for it.
=> Fixed auto-gen links

10/umbraco-cms/extending/property-editors/declaring-your-property-editor.md, 11/umbraco-cms/extending/property-editors/declaring-your-property-editor.md
=> Readability improvements - declaring your property editor

10/umbraco-cms/reference/routing/iisrewriterules.md, 11/umbraco-cms/reference/routing/iisrewriterules.md
We need to enrich the www redirect rule to contain ".*azurewebsites.net*" pattern, otherwise we will have issues deploying as the rule will redirect to www.{stie}.azurewebsites.net which will break the deployment process.
Fixing this in the site extension is a no-go, as we don't want to hijack the customer's rewrite rules.
DISCUSSION:
Do we want to include a warning hint mentioning this? 🤔  
I've added it, but can be removed or updated if it does not make sense.
=> Update rewrite rules docs

10/umbraco-cms/reference/querying/imembermanager.md, 11/umbraco-cms/reference/querying/imembermanager.md
Adding a missing namespace to allow for IMemberManager to work correctly.
If using Rider or Visual Studio this using may automatically appear but not always. Useful to have it in the docs just in case it doesn't appear automatically via intellisense.
=> Update to IMemberManager

umbraco-cloud/product-upgrades/manual-upgrades/manual-upgrade-deploy.md
A lot of people are still on v8, and although we no longer support it I still believe it's good to have included how you can upgrade your project manually, as the steps are not the same compared to v9+
Here, I have made a little dropdown to include them, its not intrusive, however still available info for those that need it.
Not sure about the wording on the "Summary" though.
=> Include legacy versions for upgrading

10/umbraco-forms/developer/extending/adding-a-workflowtype.md, 11/umbraco-forms/developer/extending/adding-a-workflowtype.md
This adds some information about a method parameter that wasn't otherwise documented, and aligns the 10 and 11 versions.
=> Updated details about retrieving record values in workflow execution.

10/umbraco-cms/extending/language-files.md, 11/umbraco-cms/extending/language-files.md
The documentation now states that language files are only used by backoffice.
However, these files are used by member identity which in turn is also used by an Umbraco website.
=> Update language-files to document usage by member identity errors in website

10/umbraco-cms/reference/searching/examine/indexing.md, 11/umbraco-cms/reference/searching/examine/indexing.md
Our Umbraco docs used to cover the Examine events `TransformingIndexValues` with the view to allowing developers to customise the External index. This has been dropped because we're not seeking to document Examine, but it leaves developers a little unsure how to achieve customisation of indexes.
I've sort a minimal update to avoid this confusion by adding a link to the Examine events documentation, where they are briefly mentioned.
=> Added a link to Examine events

10/umbraco-cms/extending/backoffice-ui-api-documentation.md, 10/umbraco-cms/extending/ui-library.md, 11/umbraco-cms/extending/backoffice-ui-api-documentation.md, 11/umbraco-cms/extending/ui-library.md
I've created a link to the new Umbraco Backoffice site from the article about the Backoffice UI API docs in the CMS docs.
=> Link to Umbraco backoffice site from CMS

umbraco-cloud/set-up/project-settings/public-access.md
Removed the following line: 
"By default, we add Basic Authentication to all trials and non-live environments."
This is not correct I checked with Søren and v9+ projects and all trials don't have the Basic Authentication enabled by default. The Public access option will be enabled on all the trials at some point in the next sprints.
=> Remove a line from the article

10/umbraco-cms/reference/configuration/imagingsettings.md, 11/umbraco-cms/reference/configuration/imagingsettings.md
This adds some context and example code on how to add your custom ImageSharp command parsing logic without overriding the build-in maximum width/height validation.
=> Add OnParseCommandsAsync example

11/umbraco-cms/reference/notifications/README.md
Fixed incorrect link, "MemberService Notifications" now correctly links to the _MemberService Notifications_ page instead of the _MemberTypeService Notifications_ page.
=> Fix incorrect link on the Notifications page

11/umbraco-cms/reference/configuration/serilog.md
* Change case of Serilog to be consistent with the rest of the document.
* Fix typo of log level.
=> Capitalise Serilog and fix typo

10/umbraco-deploy/release-notes.md, 11/umbraco-deploy/release-notes.md
These are the release notes for the next Deploy minor, aiming to go out on April 11th.
If it's possible to have these reviewed and published one week before please, that would be perfect.
I'll create another PR with the docs update for the release, as those should be published after the release notes (on the day of the release itself).
=> Release notes for Deploy 4.8/9.6/10.2/11.1

11/umbraco-cms/reference/management/services/contentservice/create-content-programmatically.md
I've updated the sample to set the localized language and provided a reference to retrieve multilingual languages.
Further updated the sample to reflect "Catalogue"/"Product" instead of "People"/"Person"
Let me know if anything else needs to be added.
=> Add culture to the "Creating content programmatically" article

marketplace-and-integrations/integrations/algolia.md
Current PR contains updates to Algolia documentation based on the latest 1.3.0 release. 
Updates included:
- Corrected Umbraco version
- Details on record object structure
- Details on `CacheRefresher Notifications`
=> Algolia docs update for version 1.3.0

10/umbraco-forms/release-notes.md, 11/umbraco-forms/release-notes.md
This release is due on 18th April, but can be reviewed and go live at any time.
=> Added notes for Forms 10.3.2 and 11.1.2 releases.

.github/styles/UmbracoDocs/UmbracoTerms.yml
Vale should only warn when `umbraco` is not used in a URL - changes here add a regular expression to only match `umbraco` when it is NOT preceded by a `.` or `/` character.
=> Ignore Umbraco case when used in a URL

11/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/grid-layout/README.md
This is just a thought, based on a forum question I saw...
A lot of people are migrating V7->V10 at the moment and wondering about the wonderful new block grid editor, they can see the current grid layout is considered 'legacy', but it still works... so it's not clear on the consequences of continuing to use it. 'I think' (but I don't know where this has been officially said, maybe it hasn't been and this is just word on the street) that in V13, there won't be a Grid Layout property editor... which would make sense with the new backoffice.... so if that is the roadmap for obsoletion, and we are pretty sure it's going to happen, then having that info somewhere, (Maybe it's in a blog post?) perhaps here... will help people decide on whether they should or should not migrate to the Block …
=> Hint when property editor will be removed in the future

11/umbraco-cms/fundamentals/setup/upgrading/version-specific/README.md
If you are upgrading from V7/V8/V9 and have used the UmbracoPath property to rename your /Umbraco backoffice path, then it's super useful to know this isn't possible in V10, and in that context, people might see this is a 'breaking change' - but I understand there may be strict rules about what can be put in the 'breaking changes' section here - and technically the property is 'still there' on the Global settings, the only change is people can't use it for its purpose! - even though it might not be deemed a 'breaking change' - anyway I ask if you would consider listing it here as I do think it will help people prepare for the migration/upgrade to V10 if they can see that this change has been made.
The discussion of the removal is on this issue: …
=> Alert people to the drop in support for UmbracoPath configuration in V10

10/umbraco-cms/reference/querying/ipublishedcontent/properties.md, 11/umbraco-cms/reference/querying/ipublishedcontent/properties.md
In the Fallback section all the examples have the first parameter of PublishedValueFallback  but dont explain what it is or how to access it.
Hopefully this adds the extra bit of information for people.
I do wonder if we also need to highlight its optional, as there is a "friendly" overload.
=> Add clarifty on what PublishedValueFallback is

10/umbraco-forms/developer/extending/adding-a-fieldtype.md, 11/umbraco-forms/developer/extending/adding-a-fieldtype.md
The current docs reference the deprecated `ValidateField` method within the `Umbraco.Forms.Core.FieldType` class. As a result, if you use the documentation the validate function doesn't actually get called (it does when you match the new Validate signature).
I'm not sure which version of Forms introduced the new signature, but since you can't change Forms version in the docs I wondered if this PR could do with some wording to the effect of "Forms v10.3.0 and under so this...... otherwise do this"?
=> Forms - Update the Validate signature

marketplace-and-integrations/integrations/algolia.md
Current PR contains updates to the Algolia documentation after adding the additional `Search API Key` as detailed [here](https://github.com/umbraco/Umbraco.Cms.Integrations/pull/98).
=> Update Algolia API keys docs

11/umbraco-cms/fundamentals/setup/server-setup/load-balancing/README.md, umbraco-cloud/frequently-asked-questions.md
Does what it says on the tin. The link currently points to the file system replication docs.
=> Fix link to Azure Web Apps in Load Balancing docs

10/umbraco-forms/editor/attaching-workflows/workflow-types.md, 11/umbraco-forms/editor/attaching-workflows/workflow-types.md
This came up in a support issue from where I realised we were missing some detail of the fallback behaviour here.  Can be reviewed and published at any time.
=> Fixed details on fallback behaviour to find sender email address in workflows.

Add-ons/Umbraco-Deploy/Deploy-Settings/index.md
Backports https://github.com/umbraco/UmbracoDocs/pull/5164 for the legacy documentation.
Can also go live at any time.
=> Added note about removing any existing serialized schema files when switching an entity to be deployed as content (legacy docs).

10/umbraco-deploy/deploy-settings.md, 11/umbraco-deploy/deploy-settings.md
Came up in a support issue and having followed the recommendation added here would have avoided the problem.
// @ronaldbarendse
=> Added note about removing any existing serialized schema files when switching an entity to be deployed as content.

12/umbraco-cms/content-delivery-api.md
- The section about "Feature Capabilities" is removed for now as it will be added to another article later on;
- Updates related to:
- Delivery API is disabled by default even on fresh install;
- Clarifying that it is necessary to build the Delivery API content index manually when enabling the Delivery API; 
- Media can also be expanded;
- Listing the built-in selectors, filters and sorts;
- Not Found response can be returned from the Query endpoint;
- Adding "Query parameter" section to explain what options are supported by default by our endpoints.
=> Content Delivery API article updates

10/umbraco-cms/extending/embedded-media-providers.md, 11/umbraco-cms/extending/embedded-media-providers.md
Fixes https://github.com/umbraco/UmbracoDocs/issues/5150
- Updates both v10 & v11 articles to no longer reference obsolete `EmbedProviderBase`
- Also no longer reference IUserComposer, instead refer to `IComposer`
=> Update v10 & v11 articles to not use Obsolete EmbedProviderBase

Add-ons/Umbraco-Deploy/Deploy-Settings/index.md
Backports information from https://github.com/umbraco/UmbracoDocs/pull/5176
Can be reviewed and go live any time on or after May 23rd.
=> Release documentation for Deploy 4.8.1

10/umbraco-cms/reference/searching/examine/indexing.md
Add missing line: 
```
builder.Services.ConfigureOptions<ConfigureProductIndexOptions>();
```
Fixes: https://github.com/umbraco/UmbracoDocs/issues/5067
=> Add missing line in examinecomposer code sample 

11/umbraco-cms/extending/filesystemproviders/azure-blob-storage.md
With v11.0.0 of the Umbraco.StorageProviders, the ImageSharp cache was split out into a separate package, which means it now needs to be installed and added to the startup file separately.
I have therefore updated the documentation to include instructions for the new way of enabling the ImageSharp Azure Blob storage cache using the `Umbraco.StorageProviders.AzureBlob.ImageSharp` package.
Updates were based on the instructions found here: https://github.com/umbraco/Umbraco.StorageProviders#umbracostorageprovidersazureblobimagesharp
=> Add instructions for enabling Azure Blob Storage ImageSharp cache

10/umbraco-forms/developer/configuration/README.md, 11/umbraco-forms/developer/configuration/README.md
This fixes an incorrect configuration key as raised in support issue https://github.com/umbraco/Umbraco.Forms.Issues/issues/1025.
=> Fixed incorrect forms configuration key name

10/umbraco-deploy/release-notes.md, 11/umbraco-deploy/release-notes.md
This adds the release notes for Deploy 9.6.1, 10.2.2 and 11.1.2 that went out on Tuesday, so can be published at any time.
=> Added release notes for Deploy 9.6.1, 10.2.2 and 11.1.2

11/umbraco-cms/reference/configuration/webroutingsettings.md
It mentions on https://docs.umbraco.com/umbraco-cms/reference/configuration#reading-configuration-in-code how to read configuration in code, but it only shows the GlobalSettings config which doesn't contain everything.
I've added an example to show how to get options under the WebRoutingSettings.
=> Add example of using web routing settings in code

11/umbraco-cms/reference/routing/request-pipeline/icontentfinder.md
PR for #4671. Updates the 404 content finder explanation text which did not match the code example.
=> Update icontentfinder.md to reflect 404 code example

12/umbraco-cms/README.md, 12/umbraco-cms/SUMMARY.md, 12/umbraco-cms/reference/api-versioning-and-openapi.md, 12/umbraco-cms/reference/dive-into-the-code.md
As V12 ships with Swagger and applies both OpenAPI and API versioning configuration in a global scope, we need to document how site implementers can work around these global configurations to achieve an API versioning and/or OpenAPI (Swagger) setup that fits their liking.
We're assigning a D-team dev to review the code samples of this new article ASAP.
Umbraco CMS v12.
As soon as possible. This applies to the 12 RC, and although we're not explicitly asking for people to test it, the information might still be useful for people performing early upgrades.
At the latest, this should be included in the docs when v12 ships on June 29th.
=> Added docs for API versioning and OpenAPI

12/umbraco-commerce/getting-started/installation.md
Umbraco Commerce doesn't support azurewebsites.net or umbraco.io as dev domains OOTB, these now need to be requested.
=> Remove license comment for azurewebsites.net or umbraco.io

11/umbraco-cms/reference/notifications/README.md
Under the `Other notifications` section further down the page, the links to the ContentTypeService Notifications and MediaTypeService Notifications have been updated to their respective pages.
These links were formerly directed to the ContentService Notifications and the MediaService Notifications, respectively
I see this appears to be under the 11 folder, but I can go back and see if the others would need updates too.  Please let me know and I'd be happy to help.
None
=> Update notifications README.md

10/umbraco-cms/reference/notifications/README.md
Under the `Other notifications` section further down the page, the links to the ContentTypeService Notifications and MediaTypeService Notifications have been updated to their respective pages.
These links were formerly directed to the ContentService Notifications and the MediaService Notifications, respectively
_This is the follow-up of pull request #5250 for v10.  I reviewed the other pull requests, I saw that it would make sense to duplicate this update for v10._
This is the v10 version of the update. 
None
=> Update notifications README.md (v10)

12/umbraco-cms/reference/configuration/debugsettings.md
The comma was invalid.
Correction of JSON syntax.
Not relevant.
Not relevant.
=> Fix syntax formatting of JSON snippet

12/umbraco-commerce/key-concepts/pipelines.md
The pipeline examples show 2 extension methods but the were missing the ‘this’ keyword prefix
=> Update pipeline examples to include ’this’

10/umbraco-cms/extending/backoffice-search.md, 11/umbraco-cms/extending/backoffice-search.md, 11/umbraco-cms/tutorials/starter-kit/lessons/4-help-and-community.md, 12/umbraco-cms/extending/backoffice-search.md, 12/umbraco-cms/tutorials/starter-kit/lessons/4-help-and-community.md, contribs.md, umbraco-cloud/frequently-asked-questions.md, umbraco-heartcore/tutorials/querying-with-graphql.md
Updated some links to our.umbraco.com/documentation to their https://docs.umbraco.com/ counterpart, similar to #5338 from yesterday.
I searched the repo for `our.umbraco.com/documentation`, and updated any references I found, except those referencing earlier versions of Umbraco in section like "see our legacy documentation here..."
* [ ✅ ] Updated outdated content
v10, v11, v12
N/A
=> Updates our umbraco to docs umbraco

10/umbraco-cms/reference/configuration/runtimeminificationsettings.md, 11/umbraco-cms/reference/configuration/runtimeminificationsettings.md, 12/umbraco-cms/reference/configuration/runtimeminificationsettings.md
The runtime minification configuration has some undocumented constraints. Hopefully the PR changes make those constraints abundantly clear, otherwise this PR should not be accepted 😄 
I have updated the docs for v10, v11 and v12.
Cross-linking the origin for future reference: https://github.com/umbraco/Umbraco-CMS/issues/14608
v10+
Not relevant.
=> Document "Timestamp" constraint for minification

12/umbraco-cms/reference/content-delivery-api/README.md
I have added a section about how to handle deeply nested JSON, if this is produced by the Delivery API as a consequence of deeply nested content structures.
My editor seems to have performed some clean-up of trailing white-spaces throughout the article. I guess this is based on the `.editorconfig` of this repo... might as well include those changes now rather than later 😄 
Cross-linking the origin for future reference: https://github.com/umbraco/Umbraco-CMS/issues/14610
v12
Not relevant.
=> Delivery API: Add section about deeply nested JSON

11/umbraco-cms/reference/searching/examine/indexing.md
The order that you do things in your ExamineComposer seems crucial...
basically, it seems you can't add the ConfigureOptions for the ProductIndex, before you have added the ProductIndex!
If we move that line to after the adding of the index then the 'Validator' rule in the example ConfigureOptions is applied.
If it's before we get the default Options (maybe calling AddExamineLuceneIndex resets the options?)
=> Fix CustomIndex sample

10/umbraco-workflow/installing-workflow.md, 10/umbraco-workflow/release-notes.md, 11/umbraco-workflow/installing-workflow.md, 11/umbraco-workflow/release-notes.md, 12/umbraco-workflow/release-notes.md
Adds release notes for Workflow 10.3, 11.3, and 12.1. These are the same for all three versions, with the exception of the licensing UI update in 10.3 and 11.3.
Between RC (22 August) and release (5 September) I'll come back through with a proper documentation update as there are changes/additions to some settings.
22 August would be great, but not essential - notes are covered in the RC blog post.
=> Workflow release notes for 10.3, 11.3, 12.1

umbraco-heartcore/api-documentation/graphql/filtering-and-ordering.md, umbraco-heartcore/api-documentation/graphql/property-editors.md
Deleted an outdated note about Schema not being generated for multinode treepickers in GraphQL.
and fixed a typo.
Heartcore
=> Multinode Treepickers do generate schema in GraphQL

10/umbraco-commerce/key-concepts/ui-config-files.md, 12/umbraco-commerce/key-concepts/ui-config-files.md
Updated docs to use the correct `.json` file extension for UI Config files, and not the old `.js` extension that was used in Vendr
=> In Umbraco Commerce UI Config files use the `.json` file extension

11/umbraco-cms/reference/configuration/contentsettings.md, 12/umbraco-cms/reference/configuration/contentsettings.md
We added a new Content Setting in V11/v12 called ShowDomainWarnings, by default this is true, but can be set to false to turn off the warnings if they become annoying.
umbraco/Umbraco-CMS#13954
V11 and V12
can be now
This is the warning in orange that the setting refers to:
=> Document existence of 'ShowDomainWarnings' setting

10/umbraco-forms/release-notes.md, 11/umbraco-forms/release-notes.md, 12/umbraco-forms/release-notes.md
Made note about introduced configuration option for the Forms headless API more prominent in the release notes.  I heard about someone getting caught out by this so wanted to flag it so it's a bit clearer when scanning the release notes.
Forms 10.4 and 11.2
=> Made note about introduced configuration option for the Forms headless API more prominent in the release notes.

10/umbraco-cms/reference/configuration/webroutingsettings.md, 11/umbraco-cms/reference/configuration/webroutingsettings.md, 12/umbraco-cms/reference/configuration/webroutingsettings.md
In Umbraco 7 and 8 we had the following:
```
<web.routing
trySkipIisCustomErrors="true"
internalRedirectPreservesTemplate="false" disableAlternativeTemplates="false" validateAlternativeTemplates="false" disableFindContentByIdPath="false"
umbracoApplicationUrl="">
</web.routing>
```
where the comment says:
```
@umbracoApplicationUrl
The url of the Umbraco application. By default, Umbraco will figure it out from the first request.
Configure it here if you need anything specific. Needs to be a complete url with scheme and umbraco
path, eg http://mysite.com/umbraco. NOT just "mysite.com" or "mysite.com/umbraco" or "http://mysite.com".
```
However @nul800sebastiaan pointed out it isn't required as the BackOffice path on no longer configurable in Umbraco 9+ …
=> Add note about Umbraco application URL

12/umbraco-cms/reference/content-delivery-api/README.md
- Adding documentation for "Get multiple items by ids content endpoint" - V12.2 features a new `/content/item` endpoint.
- Removing extra spacing for query params examples.
V12.2
Ideally on September 7 when the V12.2 RC is out.
=> Adding new `/item` endpoint documentation (for 12.2)

12/umbraco-cms/reference/content-delivery-api/README.md
Moved the Swagger section from "Limitations" to the "Endpoints" part of the article. The Swagger docs are no longer limited, they should be treated as a feature 😄 
V12
Not relevant. As soon as possible, but absolutely no rush 😆
=> Swagger is no longer a limitation in the Delivery API - it's a feature

10/umbraco-cms/SUMMARY.md, 10/umbraco-cms/reference/configuration/README.md, 10/umbraco-cms/reference/configuration/indexingsettings.md, 11/umbraco-cms/SUMMARY.md, 11/umbraco-cms/reference/configuration/README.md, 11/umbraco-cms/reference/configuration/indexingsettings.md, 12/umbraco-cms/SUMMARY.md, 12/umbraco-cms/reference/configuration/README.md, 12/umbraco-cms/reference/configuration/indexingsettings.md
[V10.7.0](https://our.umbraco.com/download/releases/1070) / [V11.5.0](https://our.umbraco.com/download/releases/1150) / [V12.1.0](https://our.umbraco.com/download/releases/1210) introduced a new settings section for controlling content indexing. Seems we missed the docs 🙈 so here they are.
10.7, 11.5 & 12.1
This is not urgent. Whenever there is time 😄
=> Add docs for indexing settings

12/umbraco-cms/reference/configuration/typefindersettings.md
Added the new AdditionalAssemblyExclusionEntries that is introduced in Umbraco 10.7, 11.5 and 12.2 to the  TypeFinderSettings
Umbraco 10.7, 11.5 and 12.2
When Umbraco 10.7, 11.5 and 12.2 is released
=> Add AdditionalAssemblyExclusionEntries to TypeFinderSettings

10/umbraco-cms/fundamentals/backoffice/content-templates.md, 11/umbraco-cms/fundamentals/backoffice/content-templates.md, 12/umbraco-cms/fundamentals/backoffice/content-templates.md
Updated content template as per CMS PR: https://github.com/umbraco/Umbraco-CMS/pull/14454 where from 12.2.0 it is possible to create content templates from settings section only for "Document types" and "Document Types with Templates"
added a warning note on method 2 guide where it shows how to create content templates from settings section that "it is possible to create content templates from settings section only for "Document types" and "Document Types with Templates"" for v12
And as extra for other versions as well, I also added the video https://www.youtube.com/watch?v=tz7dRStOo2Y to the docs.
I have also tested the docs and checked the video and they are still working for v10 and above 👍 
CMS
before 21 September 2023 when v12.2.0 is out 
_When …
=> updated content template as per CMS PR #14454

new-backoffice/tutorials/creating-a-custom-dashboard.md
=> Uddate: Creating a custom dashboard - the new backoffice

new-backoffice/tutorials/creating-a-custom-dashboard.md, new-backoffice/tutorials/creating-a-custom-dashboard/adding-functionality-to-the-dashboard.md, new-backoffice/tutorials/creating-a-custom-dashboard/adding-localization-to-the-dashboard.md, new-backoffice/tutorials/creating-a-custom-dashboard/extending-the-dashboard-using-umbraco-ui-library.md
The multi-part dashboard tutorial for the new backoffice has a few glitches and errors. While these are somewhat simple to fix, they do pose an unnecessary barrier to get started.
While I was there, I also opted to use "part" instead of "session" when referring to the different parts of the tutorial, and cleaned up a few wordings.
V14
Not relevant 😄
=> New backoffice: Fix a few glitches in the dashboard tutorial

10/umbraco-workflow/release-notes.md, 11/umbraco-workflow/release-notes.md, 12/umbraco-workflow/release-notes.md
Adds release notes for the latest patch releases of Workflow. Wondering too if it's really necessary (or useful) for later versions to include release notes for all previous versions (ie v12 release notes include v11 and v10), given almost all changes are the same across all three versions?
Workflow 10.3.1, 11.3.1 and 12.1.1
=> Release notes for Workflow 10.3.1, 11.3.1 and 12.1.1

new-backoffice/SUMMARY.md, new-backoffice/fundamentals/backoffice/document-blueprints.md
Rename content template to document blueprint. Will need to update images when new backoffice imagery is available.
Updated the content template page to be document blueprint and copied into the new backoffice docs area. This is a copy of the 12 cms documentation at this time.
When new backoffice is available, the content templates were renamed to document blueprints to have a consistent name within the CMS. See https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/893
With the new backoffice release and inclusion of PR https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/893
=> create document blueprint docs

10/umbraco-cms/extending/language-files.md, 11/umbraco-cms/extending/language-files.md, 12/umbraco-cms/extending/language-files.md
I've clarified the introduction of the language file page. I noticed that some had a tough time finding the correct syntax and explanation on how to get and create the files. I hope that by first giving a short explanation and clearly describing the `key` and `area` elements it will be easier to pickup.
=> Added clarification of text for Language translations

10/umbraco-commerce/getting-started/licensing-model.md, 12/umbraco-commerce/getting-started/licensing-model.md
This adds some extra docs about when and how to configure a `UmbracoApplicationUrl` in relation to licensing of Umbraco Commerce.
I've seen a few people having issues within licensing that this should resolve so I think it's worth documenting.
=> Add docs about `UmbracoApplicationUrl` in relation to licensing

umbraco-cloud/deployment/deployment-webhook.md
The previous email address being used referenced a real-world TLD that was in use. 
This replaces that TLD with the reserved example domain, example.com
=> Remove unrelated real-world domain from docs

12/umbraco-cms/reference/api-documentation.md
The [**API Documentation**](https://docs.umbraco.com/umbraco-cms/reference/api-documentation) page is part of the Umbraco 12 documentation, but I noticed that it's still linking to the Umbraco 11 API docs.
Since the API docs also exists for Umbraco 12, I've updated the links to point to these instead.
Umbraco 12
Somewhere between right now and some time next year 🙄
=> Updated API docs links to Umbraco 12

10/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/block-editor/README.md
Updated documentation to reflect Block Grid was introduced to v10 in 10.4. Current documentation suggests only the Block List Block Editor is available in v10.
See the following links about the introduction of Block Grid into v10:
- https://umbraco.com/blog/umbraco-103-release-candidate/
- https://our.umbraco.com/download/releases/1040
Documentation of v10.
It is not time-critical, but it is important to maintain v10 documentation as this version has LTS.
=> Block Grid Editor is available from v10.4

10/umbraco-commerce/getting-started/licensing-model.md, 10/umbraco-workflow/licensing.md, 11/umbraco-workflow/licensing.md, 12/umbraco-commerce/getting-started/licensing-model.md, 12/umbraco-deploy/the-licensing-model.md
Following the addition of [this extra](https://github.com/umbraco/UmbracoDocs/pull/5417/) detail for licensing Umbraco Commerce, I've added similar for Workflow and Deploy.
@nathanwoulfe - can you review the changes for Workflow please?  I took out the part about setting the server role, as that won't be necessary with the latest version of the `Umbraco.Licenses` component.
Workflow 10, 11, 12 and Deploy 12
=> Added details of configuring the Umbraco application URL for licensing Workflow and Deploy.

10/umbraco-cms/fundamentals/setup/requirements.md, 11/umbraco-cms/fundamentals/setup/requirements.md, 12/umbraco-cms/fundamentals/setup/requirements.md
Pull request for fixing #5488
I added SQL Snippets example on [Database Account Roles section](https://docs.umbraco.com/umbraco-cms/fundamentals/setup/requirements#database-account-roles) of Umbraco CMS Requirements blog. I have used info note for adding the example. And, I have added it to all versions of Umbraco blog so that the blog is consistent.
Umbraco CMS Docs ❤( v10,v11,v12)
=> Add SQL snippets example on Database Account Roles

12/umbraco-cms/extending/property-editors/full-examples-value-converters.md, 12/umbraco-cms/extending/property-editors/property-value-converters.md, 12/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/multinode-treepicker.md, 12/umbraco-cms/reference/configuration/contentsettings.md, 12/umbraco-cms/reference/configuration/index-10.0.0.md, 12/umbraco-cms/reference/querying/umbracohelper.md, 12/umbraco-cms/reference/routing/authorized.md, 12/umbraco-cms/tutorials/custom-error-page.md
Added a warning note where XPath is mentioned in the CMS v12 documentation as per issue [#5394 
](https://github.com/umbraco/UmbracoDocs/issues/5394)
CMS v12
anytime
anytime
=> adding information about xpath being obsolete in v12

10/umbraco-commerce/getting-started/licensing-model.md, 10/umbraco-workflow/licensing.md, 11/umbraco-workflow/licensing.md, 12/umbraco-commerce/getting-started/licensing-model.md, 12/umbraco-workflow/licensing.md
Updated licensing docs with details of configuring an Umbraco application URL on Umbraco Cloud.  This is to clarify the situation and present options for the issue described in https://github.com/umbraco/Umbraco.Commerce.Issues/issues/440
Workflow and Commerce
Can go live at any time.  Please can you wait for an approval from one or both of @mattbrailsford or @nathanwoulfe though.
=> Updated licensing docs with details of configuring an Umbraco application URL on Umbraco Cloud.

12/umbraco-cms/SUMMARY.md, 12/umbraco-cms/reference/content-delivery-api/README.md, 12/umbraco-cms/reference/content-delivery-api/protected-content-in-the-delivery-api.md
Added docs for the upcoming "protected content" feature in the Delivery API. The feature is slated for V12.3.
⚠️ Do NOT merge this in until V12.3RC is out ⚠️ 
V12.3
V12.3RC is out on October 19, so it would be nice for this to go out then too.
=> Add documentation for protected content in the Delivery API

12/umbraco-cms/reference/configuration/securitysettings.md
- Adding documentation about a new configuration setting that will be introduced with v12.3;
CMS v12.3
Between 19th Oct and 2nd Nov 🙂 - 12.3RC is out on 19th Oct and the final release is out on 2nd Nov. So, it is fine to merge it in this period (at latest on 2nd Nov).
---
> **Note**
> In v13.0.0 we will change the default value of `Umbraco:CMS:Security:AllowConcurrentLogins` from `true` to `false` - related to https://github.com/umbraco/Umbraco-CMS/pull/14989. So after we merge this PR we need to make sure that the following changes are made and available for 1st Nov:
Indicate that the default value of `AllowConcurrentLogins` is changed to `false`:
```json
"MemberDefaultLockoutTimeInMinutes": 43200,
"AllowConcurrentLogins": false
```
And remove the hint and keep the description:
```md …
```
=> Adding new AllowConcurrentLogins setting (for 12.3)

10/umbraco-deploy/SUMMARY.md, 10/umbraco-deploy/handling-cache-refresher-notifications.md
Added details of handling cache refresher notifications for operations after Umbraco items are deployed.
Improving the documentation in this area was raised as an issue here: https://github.com/umbraco/Umbraco.Deploy.Issues/issues/183
I had something like this previously [published in a personal blog post](https://www.andybutland.dev/2022/11/handling-umbraco-events-after-deploy.html), but I think it makes sense to have in the documentation.
Deploy 10+
Can be reviewed and published at any time, but please wait for an approval from @ronaldbarendse first.
Once it is approved, the content should be copied to the 11 and 12 folders for Deploy.
=> Added details of handling cache refresher notifications for operations after Umbraco items are deployed.

umbraco-cloud/set-up/project-settings/umbraco-cicd/UmbracoCloudApi.md
The URL in the code snippet for https://docs.umbraco.com/umbraco-cloud/set-up/project-settings/umbraco-cicd/umbracocloudapi#get-deployment-diff is incorrect.
* [x ] Typo/grammar fix
Umbraco Cloud
As long as it counts as a hacktoberfest contribution 😄
=> Wrong url and path in Get Deployment diff in UmbracoCloudApi.md

12/umbraco-ui-builder/getting-started/licensing-model.md
The link was pointing to the Commerce page instead of UI Builder.
Update the link to point to the correct page
=> Update link to point to UI Builder page

10/umbraco-deploy/release-notes.md, 11/umbraco-deploy/release-notes.md, 12/umbraco-deploy/release-notes.md, 13/umbraco-deploy/release-notes.md
Added release notes for Deploy 10.2.7, 11.1.7, 12.0.5.
Deploy 10.2.7, 11.1.7, 12.0.5.
Today or tomorrow if possible please so we can link to them from the status page.
=> Added release notes for Deploy 10.2.7, 11.1.7, 12.0.5.

10/umbraco-forms/release-notes.md, 11/umbraco-forms/release-notes.md, 12/umbraco-forms/release-notes.md, 13/umbraco-forms/release-notes.md
Added release notes for Forms 8.13.12, 10.5.2, 11.2.1, 12.1.2.
Forms 8.13.12, 10.5.2, 11.2.1, 12.1.2.
Today or tomorrow if possible please so we can link to them from the status page.
=> Added release notes for Forms 8.13.12, 10.5.2, 11.2.1, 12.1.2.

13/umbraco-deploy/SUMMARY.md, 13/umbraco-deploy/deploy-settings.md, 13/umbraco-deploy/release-notes.md, 13/umbraco-deploy/upgrades/version-specific.md
Added details of webhook support and further breaking changes in expected in Deploy 13-rc3.
Still to do:
Deploy 13.0.0-rc3
Can be published any time from tomorrow (28th November).
=> Added details of webhook support and further breaking changes in expected in Deploy 13-rc3.

13/umbraco-cms/SUMMARY.md, 13/umbraco-cms/reference/content-delivery-api/output-caching.md
The Delivery API supports output caching from V13 RC3 (hopefully RC3, at least). These are the accompanying docs 😄 
V13 RC3
When V13 RC3 is released. Date to follow - we will update this PR when we know more.
=> Add docs for output caching in the Delivery API

10/umbraco-cms/reference/searching/examine/indexing.md, 11/umbraco-cms/reference/searching/examine/indexing.md, 12/umbraco-cms/reference/searching/examine/indexing.md
On https://docs.umbraco.com/umbraco-cms/reference/searching/examine/indexing#creating-your-own-index (v12), most of the C# examples were using block-scoped namespaces, but with a semicolon like they wanted to also use file-scoped namespaces. I've changed them all to file-scoped.
I also fixed the usings in ExamineComposer.cs.
Umbraco 12.
=> Fix file-scoped namespaces and usings in ExamineComposer

10/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/color-picker.md, 11/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/color-picker.md, 12/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/color-picker.md
In Color Picker docs I'd suggest adding an explicit comment specifying that "Color" is a user-created property on the model.
Other editor examples use naming such as "myColorPicker" (example - [Toggle](https://docs.umbraco.com/umbraco-cms/v/10.latest-lts/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/true-false) uses "myCheckBox") to imply that the property was created by the user. This naming schema might also be more appropriate to use.
In my opinion the problem with just having Model.Color is that "Color" is quite generic, so it might not be obvious that there's the prerequisite steps of creating the property called "Color".
10-12
N/A, just a suggestion
=> Color Picker - add explicit comment defining "Color" property

13/umbraco-cms/fundamentals/setup/upgrading/version-specific/README.md
In the Umbraco 13 documentation, there is still mention of the release candidate. I think this can now be changed to Umbraco 13? I also removed an item from the list because it is not a breaking change when upgrading from v12 to 13 (only from Umbraco 13 rc1 to 13 rc2). Maybe the list needs further adjustments?
https://docs.umbraco.com/umbraco-cms/fundamentals/setup/upgrading/version-specific#umbraco-13
See also comments in https://github.com/umbraco/Umbraco-CMS/pull/15113#issuecomment-1862681128
Umbraco CMS
=> Remove non breaking change

10/umbraco-deploy/deploy-settings.md, 10/umbraco-deploy/release-notes.md, 11/umbraco-deploy/release-notes.md, 12/umbraco-deploy/deploy-settings.md, 12/umbraco-deploy/release-notes.md, 13/umbraco-deploy/deploy-settings.md, 13/umbraco-deploy/release-notes.md
Added release notes for Deploy 4.9.2, 10.3.2, 12.1.2, 13.0.2.
Note that I've also copied over the essential changes from https://github.com/umbraco/UmbracoDocs/pull/5732, which contains release notes for the previous patch and isn't yet published as there are some unresolved comments.
Please can you merge this one first, and then what's remaining in the PR from Ronald can be picked up with him when he's back next week?
Note that for now at least I've continued with the existing pattern of copying release notes to all versions.
Deploy 4.9.2, 10.3.2, 12.1.2, 13.0.2.
Can go live at any time, ideally today or tomorrow please.
=> Added release notes for Deploy 4.9.2, 10.3.2, 12.1.2, 13.0.2.

Add-ons/Umbraco-Deploy/Deploy-Settings/index.md
Added details of Deploy settings included in recent versions of Deploy 4 (for Umbraco 8).  This is for the legacy documentation hosted [at this page](https://our.umbraco.com/documentation/Add-ons/Umbraco-Deploy/Deploy-Settings/) on our.umbraco.com (the more recent versions have already been updated on docs.umbraco.com).
Deploy 4
=> Added details of Deploy settings included in recent versions of Deploy 4 (for Umbraco 8).

10/umbraco-cms/reference/management/models/contenttype.md, 12/umbraco-cms/reference/management/models/contenttype.md, 13/umbraco-cms/reference/management/models/contenttype.md
=> Update content type

10/umbraco-cms/reference/management/models/relationtype.md, 12/umbraco-cms/reference/management/models/relationtype.md, 13/umbraco-cms/reference/management/models/relationtype.md
Update relation type:
Umbraco CMS version 10, 12 & 13
=> Update relation type

umbraco-cloud/set-up/project-settings/umbraco-cicd/samplecicdpipeline/github-actions.md
There was an awkwardly phrased sentence with a few incorrect bits. I've adjusted it with some minor edits. I also removed a trailing space from that same sentence.
The diff preview I can see now also shows a change on a later line (line 237), but I'm not sure why. Maybe the online editor modified a line break character or something.
=> docs (Typo) address grammar issues in github-actions.md

10/umbraco-cms/reference/notifications/determining-new-entity.md, 12/umbraco-cms/reference/notifications/determining-new-entity.md, 13/umbraco-cms/reference/notifications/determining-new-entity.md
Update determining new entity:
=> Update determining new entity

10/umbraco-deploy/release-notes.md, 10/umbraco-forms/developer/configuration/README.md, 10/umbraco-forms/developer/rendering-scripts.md, 10/umbraco-forms/release-notes.md, 12/umbraco-forms/developer/configuration/README.md, 12/umbraco-forms/developer/rendering-scripts.md, 12/umbraco-forms/release-notes.md, 13/umbraco-deploy/release-notes.md, 13/umbraco-forms/developer/configuration/README.md, 13/umbraco-forms/developer/rendering-scripts.md, 13/umbraco-forms/release-notes.md
Added release notes and updates to documentation for Forms 8.13.13, 10.5.3, 12.2.2, 13.0.1.
Forms 8.13.13, 10.5.3, 12.2.2, 13.0.1.
Please could this be pushed live by or on Thursday, so I can link it from the status page? Thanks.
=> Added release notes and updates to documentation for Forms 8.13.13, 10.5.3, 12.2.2, 13.0.1.

10/umbraco-cms/extending/content-apps.md, 12/umbraco-cms/extending/content-apps.md, 13/umbraco-cms/extending/content-apps.md
Update content app (remove Program.cs or Startup.cs examples). I only removed the `Program.cs`/`Startup.cs` example and did not add any new explanation because there is already an example with an `IComposer` in this article.
Belongs to: 
https://github.com/umbraco/UmbracoDocs/issues/5709 
Replaces: 
https://github.com/umbraco/UmbracoDocs/pull/5735 
Umbraco 10, 11, 12 & 13
=> Update content app (remove Program.cs or Startup.cs examples)

13/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/rich-text-editor/configuration.md
CustomConfig link in rich text editor configuration has invalid link. 
Updated hhttps to https protocol in the link
=> Updated URL typo error in configuration.md

10/umbraco-cms/fundamentals/data/dictionary-items.md, 12/umbraco-cms/fundamentals/data/dictionary-items.md, 13/umbraco-cms/fundamentals/data/dictionary-items.md
Update dictionary items:
Umbraco CMS v10, 12 & 13.
=> Update dictionary items

10/umbraco-commerce/key-concepts/order-calculation-state.md, 12/umbraco-commerce/key-concepts/order-calculation-state.md, 13/umbraco-commerce/key-concepts/order-calculation-state.md
Update order calculation state:
Umracom Commerce
=> Update order calculation state

10/umbraco-cms/reference/angular/directives/umbloadindicator.md, 12/umbraco-cms/reference/angular/directives/umbloadindicator.md, 13/umbraco-cms/reference/angular/directives/umbloadindicator.md
=> Update umb load indicator 

12/umbraco-forms/developer/custom-markup.md
Instructions for creating custom fieldtypes in a custom form are missing the `Fieldtypes` directory in the path. 
Tested on Umbraco 12.12.3 with Form 12.2.1.
No rush.
=> Custom fieldtype path incorrect in custom-markup.md

10/umbraco-cms/extending/property-editors/package-manifest.md, 10/umbraco-cms/tutorials/creating-a-property-editor/README.md, 10/umbraco-cms/tutorials/creating-a-property-editor/part-2.md, 10/umbraco-cms/tutorials/creating-a-property-editor/part-3.md, 10/umbraco-cms/tutorials/creating-a-property-editor/part-4.md, 12/umbraco-cms/extending/property-editors/package-manifest.md, 12/umbraco-cms/tutorials/creating-a-property-editor/README.md, 12/umbraco-cms/tutorials/creating-a-property-editor/part-2.md, 12/umbraco-cms/tutorials/creating-a-property-editor/part-3.md, 12/umbraco-cms/tutorials/creating-a-property-editor/part-4.md, 13/umbraco-cms/extending/property-editors/package-manifest.md, 13/umbraco-cms/tutorials/creating-a-property-editor/README.md, 13/umbraco-cms/tutorials/creating-a-property-editor/part-2.md, 13/umbraco-cms/tutorials/creating-a-property-editor/part-3.md, 13/umbraco-cms/tutorials/creating-a-property-editor/part-4.md
Update package manifest and property editor docs as they were outdated from v8:
- https://docs.umbraco.com/umbraco-cms/extending/property-editors/package-manifest 
- https://docs.umbraco.com/umbraco-cms/tutorials/creating-a-property-editor - also tested until step 2. There might be some code that is obsolete in step 3 and 4 but with v14 where angular is not used anymore these tutorial might need to be revisited and re-tested
CMS 10, 12, 13
anytime
=> Update package manifest and property editor docs

10/umbraco-deploy/troubleshooting.md, 12/umbraco-deploy/troubleshooting.md, 13/umbraco-deploy/troubleshooting.md
Updated Deploy's troubleshooting page to include reference to the import/export feature.
Umbraco Deploy.
=> Updated Deploy's troubleshooting page to include reference to the import/export feature.

umbraco-cloud/set-up/project-settings/manage-hostnames/README.md
Add new set of static IPs as A & AAAA records for Umbraco Cloud Websites. Move former records to the former section.
Add new set of static IPs as A & AAAA records for Umbraco Cloud Websites. Move former records to the former section. The new set of static IPs are static as long as we use Cloudflare. With the previous IPs we've risked "clawbacks" from previous providers.
Previous IPs used by customers will continue working but still carry the risk of eventual clawback with a short deadline. We don't have such risk with the new IPs.
Umbraco Cloud
The merge needs to be timed. We need to merge this after we've enabled the new static IPs.
=> Static IPs change on Umbraco Cloud

13/umbraco-cms/reference/content-delivery-api/README.md
The "getting started" part of to the [Delivery API docs](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#getting-started) is currently written for V12. We shouldn't mention V12 specifically, but rather state that versions below V12 (V11 and below) need to take an extra step by code to enable the API.
Also - the instructions to perform said step by code is written for the minimal hosting model. But this hosting model was introduced in V13, so any projects applicable for the extra code step will most likely not be using the minimal hosting model. Thus I have rewritten the instructions to be specific for V12 and below (without the minimal hosting model, i.e. using `Startup.cs`).
Not relevant 😄 
No deadline. As soon as possible, I guess 😛
=> Fix Delivery API "getting started" + configuration sample

umbraco-cloud/set-up/project-settings/manage-hostnames/README.md
The suggestions to not use A records was because they weren't static. Now that they are static we can simplify the docs and let the customers use their preferred record sets.
Umbraco Cloud
n/a
=> Simplify DNS records section

10/umbraco-commerce/installation/licensing-model.md, 10/umbraco-ui-builder/installation/licensing-model.md, 10/umbraco-workflow/installation/licensing.md, 12/umbraco-commerce/installation/licensing-model.md, 12/umbraco-deploy/installation/the-licensing-model.md, 12/umbraco-ui-builder/installation/licensing-model.md, 12/umbraco-workflow/installation/licensing.md, 13/umbraco-commerce/installation/the-licensing-model.md, 13/umbraco-deploy/installation/the-licensing-model.md, 13/umbraco-ui-builder/installation/licensing-model.md, 13/umbraco-workflow/installation/licensing.md
Added details of how to license commercial products in an environment without an outgoing Internet connection.
Umbraco.Licenses (used by Deploy, Commerce, Workflow and UIBuilder) 10.1, 12.1 and 13.1
=> Added details of how to license commercial products in an environment without an outgoing Internet connection.

10/umbraco-commerce/release-notes.md, 12/umbraco-commerce/release-notes.md, 13/umbraco-commerce/release-notes/README.md
Umbraco Commerce release notes
10.0.6, 12.1.5 and 13.0.1
ASAP
=> Update patch release notes for Umbraco Commerce

12/umbraco-forms/developer/extending/adding-a-fieldtype.md, 13/umbraco-forms/developer/extending/adding-a-fieldtype.md
Removed some unnecessary quotes
=> Removed stray quotes

umbraco-heartcore/api-documentation/graphql/property-editors.md, umbraco-heartcore/api-documentation/graphql/schema-generation.md
Added block grid to the list of property editors and GraphQL schema examples.
Heartcore
On or after February 12th
=> Heartcore: Add block grid property editor & schema

10/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/email-address.md, 12/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/email-address.md, 13/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/email-address.md
v13
whenever
---
The example was sending the 'value' of ModelEmail instead of the alias of the field...
... there is also a counterargument to say that HasValue shouldn't be being used here at all, in either with and without Modelsbuilder...
that instead we should be promoting
```
@if (!string.IsNullOrWhiteSpace(Model.Value<string>("email")))
```
and
```
@if (!string.IsNullOrWhiteSpace(Model.Email))
```
because HasValue isn't necessarily considering PropertyValueConverters...
=> Update Modelsbuilder HasValue check

10/umbraco-deploy/release-notes.md, 10/umbraco-forms/release-notes.md, 12/umbraco-deploy/release-notes.md, 12/umbraco-forms/release-notes.md, 13/umbraco-deploy/getting-started/deploy-settings.md, 13/umbraco-deploy/release-notes.md, 13/umbraco-forms/release-notes.md
Added release notes for Forms 8.13.14, 10.5.4, 12.2.3 and 13.0.2 and Deploy 4.9.4, 10.3.4, 12.1.4 and 13.0.4
Forms 8.13.14, 10.5.4, 12.2.3 and 13.0.2 and Deploy 4.9.4, 10.3.4, 12.1.4 and 13.0.4
By Thursday this week if possible please (doesn't matter if earlier).
=> Release notes for Forms 8.13.14, 10.5.4, 12.2.3 and 13.0.2 and Deploy 4.9.4, 10.3.4, 12.1.4 and 13.0.4

10/umbraco-cms/reference/security/custom-password-check.md, 12/umbraco-cms/reference/security/custom-password-check.md, 13/umbraco-cms/reference/security/custom-password-check.md
=> Uddate custom password check

10/umbraco-forms/developer/extending/customize-default-workflows.md, 12/umbraco-forms/developer/extending/customize-default-workflows.md, 13/umbraco-forms/developer/extending/customize-default-workflows.md
`TestWorkflow` needs to be `LogMessageWorkflow` as the constructur is `LogMessageWorkflow` and match `T` in `ILogger<T>`
=> Fix LogMessageWorkflow class name

10/umbraco-commerce/release-notes.md, 12/umbraco-commerce/release-notes.md, 13/umbraco-commerce/release-notes/README.md
Release notes for Umbraco Commerce 10.0.7, 12.1.6, 13.0.2 and 13.1.0-rc3
Umbraco Commerce 10.0.7, 12.1.6, 13.0.2 and 13.1.0-rc3
ASAP
=> Release notes for Umbraco Commerce 10.0.7, 12.1.6, 13.0.2 and 13.1.0-rc3

13/umbraco-cms/reference/configuration/connectionstringssettings.md
This fixes a malformed tag linking to external documentation - ttps:// -> https://
Located on the Connection String Settings part of the documentation site -> https://docs.umbraco.com/umbraco-cms/reference/configuration/connectionstringssettings
N/A
N/A
=> fixes broken link in Connection String Settings documentation

10/umbraco-cms/reference/security/external-login-providers.md, 12/umbraco-cms/reference/security/external-login-providers.md, 13/umbraco-cms/reference/security/external-login-providers.md
Added reference to the community package Umbraco.Community.AzureSSO
=> Added reference to Umbraco.Community.AzureSSO

13/umbraco-commerce/release-notes/README.md, commerce-add-ons/packages/checkout/release-notes.md, commerce-add-ons/packages/deploy/release-notes.md, commerce-add-ons/shipping-providers/dhl/release-notes.md, commerce-add-ons/shipping-providers/easypost/release-notes.md, commerce-add-ons/shipping-providers/shipmondo/release-notes.md
Updated release notes for Umbraco.Commerce 13.1.0 release
Umbraco.Commerce 13.1.0 
ASAP
=> Updated release notes for Umbraco.Commerce 13.1.0 release

13/umbraco-commerce/reference/shipping/README.md, 13/umbraco-commerce/reference/shipping/realtime-rate-shipping.md, commerce-add-ons/shipping-providers/dhl/README.md, commerce-add-ons/shipping-providers/easypost/README.md, commerce-add-ons/shipping-providers/shipmondo/README.md
Fixing some broken links, and added a missing docs page for Realtime Shipping Rate setup
v13
ASAP
=> Umbraco Commerce Docs Updates

13/umbraco-forms/release-notes.md
=> Fix typo in webhooks

10/umbraco-cms/reference/routing/request-pipeline/inbound-pipeline.md, 12/umbraco-cms/reference/routing/request-pipeline/inbound-pipeline.md, 13/umbraco-cms/reference/routing/request-pipeline/inbound-pipeline.md
=> Update inbound pipeline

13/umbraco-cms/reference/content-delivery-api/README.md, 13/umbraco-cms/reference/routing/custom-middleware.md
Based on Issue #5877 I have re-added lost commit changes from PR #5626 and rest of commits from https://github.com/umbraco/UmbracoDocs/commits/main/13/umbraco-cms/reference/content-delivery-api/README.md 
cms v13
anytime
=> re-added lost commit changes from PR #5626

12/umbraco-cms/reference/searching/examine/README.md, 13/umbraco-cms/reference/searching/examine/README.md
Update examine readme:
Umbraco CMS v12 & 13
=> Update examine readme

13/umbraco-forms/release-notes.md
Added release notes for Forms 13.1.0
Forms 13.1.0
Any time before 19th March.
=> Added release notes for Forms 13.1.0

13/umbraco-cms/tutorials/getting-started-with-entity-framework-core.md
Updated documentation to prevent it recommending the use of an obsolete method.
Removed reference to `AddUmbracoEFCoreContext` for V13 as this now marked `[Obsolete("Use AddUmbracoDbContext<T>(this IServiceCollection services, Action<DbContextOptionsBuilder>? optionsAction = null) instead.")]` in the latest release but the documentation doesn't reflect.
V13
N/A
=> Updated use of obsolete method

13/umbraco-cms/fundamentals/backoffice/README.md
Updated `/umbraco-cms/fundamentals/backoffice` to use the screenshot of the new login screen, rather than the screenshot of the old one, it now uses the same screenshot as found on the `/umbraco-cms/fundamentals/backoffice/login` page.
Umbraco CMS v13
=> Update the Backoffice page to use the screenshot of the new login screen

10/umbraco-deploy/release-notes.md, 12/umbraco-deploy/release-notes.md, 13/umbraco-deploy/getting-started/deploy-settings.md, 13/umbraco-deploy/release-notes.md, 13/umbraco-forms/release-notes.md
Added release notes for Deploy 4.10.0, 10.4.0, 12.2.0 and 13.1.0
Deploy 4.10.0, 10.4.0, 12.2.0 and 13.1.0
Ideally on Tuesday 19th March if possible please.  If not, as soon as is feasible afterwards.
=> Release notes for Deploy 4.10.0, 10.4.0, 12.2.0 and 13.1.0

10/umbraco-ui-builder/release-notes.md, 12/umbraco-ui-builder/release-notes.md, 13/umbraco-ui-builder/collections/the-basics.md, 13/umbraco-ui-builder/release-notes.md
- `Umbraco.UIBuilder` release notes.
- Small docs update
`Umbraco.UIBuilder` versions 10, 12 and 13.
Coming days.
=> Update UIBuilder release notes and docs

10/umbraco-forms/developer/extending/adding-a-fieldtype.md, 12/umbraco-forms/developer/extending/adding-a-fieldtype.md, 13/umbraco-forms/developer/extending/adding-a-fieldtype.md
=> Clarified text on virtual folder

13/umbraco-commerce/key-concepts/umbraco-commerce-builder.md
Related to https://github.com/umbraco/Umbraco.Commerce.Issues/issues/475 
It is important the composer which extends `IUmbracoCommerceBuilder` run before `UmbracoCommerceComposer` to work.
while this work, it seems to fail with `InsertBefore<TTask>()` or `InsertAfter<TTask>()` used in the composer:
https://docs.umbraco.com/umbraco-commerce/key-concepts/pipelines
https://github.com/umbraco/Umbraco.Commerce.Issues/issues/475#issuecomment-2003367330
=> Notice about register `IUmbracoCommerceBuilder` extensions using composer

13/umbraco-cms/reference/content-delivery-api/README.md
I think this is how you do it in v13 and project.cs, but copied it from the latest branch of the core repo
=> In v13 there is no startup.cs file

13/umbraco-forms/release-notes.md
Added release notes for Forms 13.1.1.
Forms 13.1.1.
Ideally tomorrow, but any time before or after you can manage is fine.  It's a very small update for a patch release.
=> Release notes for Forms 13.1.1

10/umbraco-forms/developer/extending/adding-an-event-handler.md, 12/umbraco-forms/developer/extending/adding-an-event-handler.md, 13/umbraco-forms/developer/extending/adding-an-event-handler.md
Update event handler:
Umbraco Forms
=> Update event handler

10/umbraco-commerce/release-notes.md, 12/umbraco-commerce/release-notes.md, 13/umbraco-commerce/release-notes/README.md
Release notes for Umbraco Commerce v10.0.9, 12.1.8 and 13.1.2
Umbraco Commerce v10.0.9, 12.1.8 and 13.1.2
ASAP
=> Umbraco Commerce patch relase notes

13/umbraco-forms/installation/the-licensing-model.md
Added details of how to get a Forms license that will work in FIPS-compliant environments.
Documents a solution we've come up with from a customer case.
Forms 13+.
=> Added details of how to get a Forms license that will work in FIPS-compliant environments.

10/umbraco-forms/developer/field-types.md, 12/umbraco-forms/developer/field-types.md, 13/umbraco-forms/developer/field-types.md
Update field types: 
Umbraco Forms
=> Update field types

umbraco-cloud/security.md
Documenting that Umbraco Cloud supports HTTP2 and HTTP3 protocols.
Umbraco Cloud
The statement about HTTP3 working will be true after 3rd of April.
=> document http2 and http3 protocol support

13/umbraco-cms/reference/security/external-login-providers.md
Looks like maybe a bad merge left duplicate tags in there?
Currently looks like this on the page:
https://docs.umbraco.com/umbraco-cms/reference/security/external-login-providers#auto-linking-on-member-authentication
This PR should remove the additional tags.
=> Fix bad formatting

13/umbraco-cms/extending/content-apps.md
I've updated the documentation for content apps, correcting errors caused by the existing C# code examples and ensuring that it reflects the latest standards and practices.
I also reviewed the C# code examples for versions 10 and 12, confirming their accuracy and reliability. These versions were found to be in good standing without the need for corrections.
* [ x] Other
13
=> Fix issue content-apps documentation v13

10/umbraco-commerce/release-notes.md, 12/umbraco-commerce/release-notes.md, 13/umbraco-commerce/release-notes/README.md
Umbraco Commerce release notes
10.0.10, 12.1.9, 13.1.3
ASAP
=> Umbraco Commerce release notes

10/umbraco-forms/developer/field-types.md, 12/umbraco-forms/developer/field-types.md, 13/umbraco-forms/developer/field-types.md
Updated the field types article for Umbraco Forms with the correct information for Umbraco projects running v10+.
Fixes issue #6000 
10
12
13
N/A
N/A
=> Updated Field types article with correct information for v10+ for forms

14/umbraco-cms/extending-backoffice/extension-types/sections-and-trees/README.md
I think and hope that I fixed some broken links on this page: https://docs.umbraco.com/umbraco-cms/v/14.latest-beta/extending-backoffice/extension-types/sections-and-trees
The lacked the `.md` extension so the links ended up as 404s to Github. 
I'm not 100% sure, looked at other articles, is this correct? Should links point to the markdown files with the `.md` extension at the end?
=> Fix broken links for sections and tree

14/umbraco-cms/SUMMARY.md, 14/umbraco-cms/extending-backoffice/routes.md
Added initial docs (needs review) for routes, I'm sure that there are more to this but figured that this is good start.
Umbraco v14 new backoffice
=> Initial docs for Bellissima Routes

10/umbraco-cms/tutorials/creating-a-property-editor/part-4.md, 12/umbraco-cms/tutorials/creating-a-property-editor/part-4.md, 13/umbraco-cms/tutorials/creating-a-property-editor/part-4.md
We have gotten some feedback from various people, about part 4 of the Creating a Property Editor guide not working and having wrong information.
This PR is created to mitigate that.
Updated the code as it was using `IScopeProvider` which is marked as obsolete, and it is recommended to use `Umbraco.Cms.Infrastructure.Scoping.IScopeProvider` instead.
The example was also using `[PluginControllerMetadata("My")]` which is also wrong and should be `[PluginController("My")]`
10
12
N/A
N/A
=> Updated creating a  property editor part 4

14/umbraco-cms/extending-backoffice/extension-types/property-editors/property-editor-ui.md, 14/umbraco-cms/tutorials/creating-a-property-editor/README.md, 14/umbraco-cms/tutorials/creating-a-property-editor/adding-configuration-to-a-property-editor.md, 14/umbraco-cms/tutorials/creating-a-property-editor/integrating-services-with-a-property-editor.md
Updated guide to use the new UmbPropertyValueChangeEvent-class over magic string.
=> Use UmbPropertyValueChangeEvent over magic string

10/umbraco-cms/extending/macro-parameter-editors.md, 12/umbraco-cms/extending/macro-parameter-editors.md, 13/umbraco-cms/extending/macro-parameter-editors.md
Update macro parameter editors:
=> Update macro parameter editors

13/umbraco-deploy/deployment-workflow/import-export.md
I added additional info to the current note about Deploy not touching the maximum upload size
Discovered in a recent case using import/export, we encountered a 500mb limit on the file size for importing on Umbraco Cloud.
This is imposed by Cloudflare.
I have only added it on v13 docs, but I suggest getting it added on the other versions.
Deploy
=> Deploy Import file size limit on Umbraco Cloud

13/umbraco-cms/implementation/custom-routing/signalR.md
The docs said you have you have to put terminating middleware in the postpipeline, that's not correct. It needs to be in the endpoints.
It was found here https://github.com/umbraco/Umbraco-CMS/issues/16114, and have not always been failing before v14, but apparently it fails hard now.
I would guess this is v10+, but at least v13+
ASAP, as the current docs are wrong.
=> Update signalR docs by using the UmbracoPipelineFilter correct

13/umbraco-ui-builder/release-notes.md
Updated release notes for Umbraco UI Builder 13.1.2.
Umbraco UIBuilder 13.1.2
Anytime
=> UI Builder 13.1.2 release notes

12/umbraco-cms/reference/content-delivery-api/README.md, 13/umbraco-cms/reference/content-delivery-api/README.md, 14/umbraco-cms/reference/content-delivery-api/README.md
Update Content Delivery API:
Umbraco CMS v12 & 13
=> Update Content Delivery API

13/umbraco-cms/extending/database.md, 13/umbraco-cms/extending/section-trees/trees/README.md, 13/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/block-editor/block-grid-editor.md, 13/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/image-cropper.md, 13/umbraco-cms/fundamentals/code/debugging/logging.md, 13/umbraco-cms/implementation/controllers.md, 13/umbraco-cms/implementation/unit-testing.md, 13/umbraco-cms/reference/cache/examples/tags.md, 13/umbraco-cms/reference/common-pitfalls.md, 13/umbraco-cms/reference/management/services/relationservice.md, 13/umbraco-cms/reference/mapping.md, 13/umbraco-cms/reference/querying/itagquery.md, 13/umbraco-cms/reference/querying/umbraco-context.md, 13/umbraco-cms/reference/routing/umbraco-api-controllers/README.md, 13/umbraco-cms/reference/routing/umbraco-api-controllers/authorization.md, 13/umbraco-cms/reference/routing/umbraco-api-controllers/routing.md, 13/umbraco-cms/reference/using-ioc.md, 13/umbraco-cms/tutorials/getting-started-with-entity-framework-core.md, 14/umbraco-cms/reference/management/services/create-a-new-user.md, 14/umbraco-cms/reference/querying/imembermanager.md
UmbracoApiController is removed in v14 and replaced with UmbracoManagementApiControllerBase as per CMS PR https://github.com/umbraco/Umbraco-CMS/pull/15863 so I have added a warning note about this on v13 docs.
CMS team has it on their backlog to help update the articles with examples where UmbracoApiController  to be replaced with UmbracoManagementApiControllerBase 👍
=> adding warning note on v13 about removal of UmbracoApiController

14/umbraco-cms/extending-backoffice/customize-backoffice.md
Update customize backoffice:
Umbraco CMS v14
=> Update customize backoffice

13/umbraco-cms/reference/api-versioning-and-openapi.md
This previously said "both are disabled in non-production environments" (a double negative, meaning that they're only enabled in production). Corrected this to say that swagger is disabled in production.
Corrected a typo that incorrectly said swagger is only enabled in production.
CMS 13
N/A
=> Corrected typo - Swagger is enabled in non-production environments.

10/umbraco-deploy/deployment-workflow/import-export.md, 12/umbraco-deploy/deployment-workflow/import-export.md, 13/umbraco-deploy/deployment-workflow/import-export.md
Adding content how to upgrade from umbraco 7 using export and import deploy on-prem and also updated the code formats from dropdowns with the newer ones 
Deploy 10, 12 and 13
anytime
=> Adding content how to upgrade from umbraco 7 using export and import from Umbraco Deploy

marketplace-and-integrations/integrations/algolia.md
Algolia 2.1.5
No deadline, when possible.
=> Update docs for Algolia 2.1.5 changes.

10/umbraco-cms/extending/backoffice-tours.md, 12/umbraco-cms/extending/backoffice-tours.md, 13/umbraco-cms/extending/backoffice-tours.md, 14/umbraco-cms/extending-cms/backoffice-tours.md
Step Object was missing a functional property: skipStepIfVisible. Added for v13 documentation.
Added an undocumented property for the backoffice tours in v13. Not sure what all versions the property is relevant to but this was a start at least ^^
Related to [issue #6038](https://github.com/umbraco/UmbracoDocs/issues/6038#issue-2257591188)
v13 (could be related to more this is just the only one I confirmed 100%)
N/A
=> Added skipStepIfVisible to v13 Tours

10/umbraco-cms/fundamentals/setup/install/running-umbraco-on-linux-macos.md, 12/umbraco-cms/fundamentals/setup/install/running-umbraco-on-linux-macos.md, 13/umbraco-cms/fundamentals/setup/install/running-umbraco-on-linux-macos.md, 14/umbraco-cms/fundamentals/setup/install/running-umbraco-on-linux-macos.md
Updated broken link in Running Umbraco on Linux/macOS article
The link to the tutorial for setting it up with docker was not working anymore.
Instead, I have replaced the article with a new one about setting up Umbraco with docker.
10
12
13
14
ASAP
ASAP
=> Updated broken link in Running Umbraco on Linux/macOS article

14/umbraco-cms/extending-backoffice/extension-registry/entry-point.md
Update entry point:
Umbraco CMS v14
=> Update entry point

10/umbraco-deploy/getting-started/deploy-settings.md, 12/umbraco-deploy/getting-started/deploy-settings.md, 13/umbraco-deploy/getting-started/deploy-settings.md
I noticed some detail on a setting missing on the 13 versioned docs that was on 10 and 12.  So have aligned with this update/
Deploy 13
=> Aligned configuration docs across versions for Deploy

12/umbraco-forms/developer/ajaxforms.md, 13/umbraco-forms/developer/ajaxforms.md
Minor update in querystring with multiple parameters.
=> Update querystring in forms definitions request

14/umbraco-cms/reference/security/two-factor-authentication.md
Update code examples for Two-Factor Authentication.
14.0.0
ASAP
=> V14 RC: Two-Factor Authentication code examples update

13/umbraco-ui-builder/release-notes.md, 13/umbraco-ui-builder/searching/searchable-properties.md
Updated docs and release notes for Umbraco UI Builder 13.1.4.
Umbraco UI Builder 13.1.4
=> Update release notes and docs for Umbraco UI Builder 13.1.4

14/umbraco-cms/SUMMARY.md, 14/umbraco-cms/tutorials/creating-a-backoffice-api/README.md
I have moved the "custom backoffice APIs" article from the Fundamentals section to the Tutorials section, where I think it belongs 😄 (the article is currently [here](https://docs.umbraco.com/umbraco-cms/v/14.latest-rc/fundamentals/backoffice/create-your-own-api)).
I have also updated the code snippets slightly:
1. Added `{% code %}` and `{% endcode %}` tags.
2. Ensured the "full implementation" snippet can compile on its own by including all classes/enims, the required `using` instructions and a namespace for the controller.
Lastly I have prepared for this tutorial to be expanded; we will be adding more advanced stuff later on 😄 
V14
As soon as it can be 😄
=> Moved "custom backoffice APIs" to tutorials + update code snippets

14/umbraco-cms/reference/management-api/README.md
Swagger is disabled in production environments. This page incorrectly says it's disabled for **non**-production environments.
You can confirm this from the existing docs page that discusses the security of the [Content Delivery API](https://docs.umbraco.com/umbraco-cms/reference/api-versioning-and-openapi).
v14
ASAP
=> v14 fix: should be "production" not "non-production"

14/umbraco-cms/README.md, 14/umbraco-cms/fundamentals/backoffice/README.md, 14/umbraco-cms/fundamentals/setup/README.md, 14/umbraco-cms/fundamentals/setup/install/README.md, 14/umbraco-cms/fundamentals/setup/upgrading/README.md, 14/umbraco-cms/fundamentals/setup/upgrading/version-specific/README.md, 14/umbraco-cms/reference/security/README.md, 14/umbraco-deploy/README.md, 14/umbraco-forms/README.md, 14/umbraco-ui-builder/README.md, 14/umbraco-workflow/README.md
update missing v14 content from some articles
v14
asap
=> update missing v14 content from some articles

14/umbraco-cms/tutorials/creating-a-custom-dashboard/README.md, 14/umbraco-cms/tutorials/creating-a-property-editor/README.md, 14/umbraco-cms/tutorials/creating-a-property-editor/adding-configuration-to-a-property-editor.md, 14/umbraco-cms/tutorials/creating-a-property-editor/adding-server-side-validation.md
[This PR](https://github.com/umbraco/Umbraco-CMS/pull/16393) changes how the server performs caching on `umbraco-package.json` files. TL;DR: It is no longer necessary to restart the Umbraco site when changing these files 😄 
I have updated the docs to reflect this cache change.
V14 RC5
After today 😉 RC5 is (hopefully) going out today.
=> Reflect server cache changes for `umbraco-package.json` in docs

14/umbraco-cms/extending/customize-backoffice/development-flow/README.md, 14/umbraco-cms/extending/customize-backoffice/development-flow/vite-package-setup.md, 14/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/block-editor/label-property-configuration.md, 14/umbraco-cms/fundamentals/setup/install/README.md, 14/umbraco-cms/fundamentals/setup/install/installing-nightly-builds.md, 14/umbraco-cms/fundamentals/setup/upgrading/version-specific/README.md, 14/umbraco-cms/reference/management/services/README.md, 14/umbraco-cms/tutorials/creating-your-first-extension.md
update the install to v14 rc 5
cms v14
once release notes are updated as well
=> update to v14 rc5

umbraco-heartcore/SUMMARY.md, umbraco-heartcore/migration-2024.md, umbraco-heartcore/release-notes/core-dependency-upgrade.md
Add some info around what to expect from the mid-year Heartcore migration of older sites.
Heartcore
5th June 2024
=> Add info for mid-year Heartcore migration

14/umbraco-cms/extending/key-vault.md, 14/umbraco-cms/reference/routing/custom-routes.md, 14/umbraco-cms/reference/security/ssl-https.md
From v14 u.UseInstallerEndpoints(); is not longer used in the program.cs file.
This PR removes the mention of this from the documentation.
Fixes #6151 
14
ASAP
=> Removed u.UseInstallerEndpoints();  from the documentation for v14

14/umbraco-forms/developer/ajaxforms.md
Updated path for delivery API in Forms 14.  This was mentioned in the breaking changes but I omitted to update the 14 version of this page with the new path that we've introduced to make clear the difference between the delivery and management APIs.
Forms 14
Any time.
=> Updated path for delivery API in Forms 14

10/umbraco-cms/fundamentals/setup/install/README.md, 12/umbraco-cms/fundamentals/setup/install/README.md, 13/umbraco-cms/fundamentals/setup/install/README.md
The install docs for using the terminal was wrong and would result in installing v14 for versions below.
This PR fixes that.
Fixes #6160
10
12
13
=> updated install docs for versions below v14

14/umbraco-forms/developer/configuration/README.md
It's not intuitive to say to disable this feature, then set it to false, when it by default is set to false.
If they want to enable "DisableRelationTracking" they should set this to true
=> Updating the wording

14/umbraco-cms/fundamentals/data/defining-content/document-type-localization.md
Document Type Localization has changed a lot for V14, so the [current article](https://docs.umbraco.com/umbraco-cms/fundamentals/data/defining-content/document-type-localization) is no longer correct. I have added a warning to it 😄 
V14
Whenever. Not urgent 😄
=> Add warning to Document Type Localization

14/umbraco-forms/.gitbook/assets/umbraco_forms_swagger.json
Fixes the delivery API details documented for Forms 14
At least I think so.  I can't tell locally unfortunately but hopefully you can see this resolves the problems with rendering the Forms delivery API details at https://docs.umbraco.com/umbraco-forms/developer/ajaxforms
Forms 14
Can go live any time.
=> Fixes the delivery API details documented for Forms 14

14/umbraco-forms/release-notes.md
Added release notes for Forms 14.0.2
Forms 14.0.2
As soon as is feasible please but no harm if it goes up at any time.
=> Added release notes for Forms 14.0.2

umbraco-cloud/set-up/project-settings/external-services.md
Static outbound IPs vary per region and are not the same across all regions.
Umbraco Cloud
=> Static outbound IPs vary per region

14/umbraco-cms/implementation/composing.md
In the Composing article, the code samples related to Collections are no longer valid in V14:
- [Example of using Ordered Collections and adding types explicitly](https://docs.umbraco.com/umbraco-cms/implementation/composing#example-of-using-ordered-collections-and-adding-types-explicitly)
- [Example of using Lazy Collections with Type Scanning](https://docs.umbraco.com/umbraco-cms/implementation/composing#example-of-using-lazy-collections-with-type-scanning)
I have rewritten the samples, so:
1. Now they can actually compile 🤦 
2. They no longer reference the `UmbracoAuthorizedApiController`
3. They have been cleaned up a bit.
A little bit of wording surrounding these samples has changed too, but this PR is primarily about the code samples.
V14
When possible.
=> Rewrite the Collections part of the Composing article for V14

14/umbraco-cms/tutorials/creating-a-property-editor/adding-configuration-to-a-property-editor.md
Add reference to the id field in the example umbraco-package.json file.  By providing this we are able to better match up a package's install data available from telemetry in order to order it by this metric on the Umbraco Marketplace.
This should in time be documented properly, as really this is just a passing reference to the file as part of a page focussed mostly on other topics.
Umbraco 14
No urgency.
=> Add reference to the id field in the example umbraco-package.json file.

14/umbraco-cms/tutorials/creating-a-basic-website/setting-the-navigation-menu.md
Corrected typo in [Setting the Navigation Menu](https://docs.umbraco.com/umbraco-cms/tutorials/creating-a-basic-website/setting-the-navigation-menu). Fixes #6158.
Original:
"The \<ul> tag needs to be wrapped inside the \<class> and \<nav> tags"
Fix:
"The \<ul> tag needs to be wrapped inside the \<div class="container"> and \<nav> tags"
=> Corrected typo in "Setting the Navigation Menu"

14/umbraco-cms/extending/language-files/README.md, 14/umbraco-cms/extending/language-files/net-localization.md
The [Language Files & Localization](https://docs.umbraco.com/umbraco-cms/extending/language-files) article has been restructured a bit to emphasize that UI Localization is the "main thing" in V14.
The [.NET Localization article](https://docs.umbraco.com/umbraco-cms/extending/language-files/net-localization) has undergone same changes, and the code sample now actually works 😄 
V14
When possible. Not urgent.
=> Update language/localization docs

marketplace-and-integrations/marketplace/listing-your-package.md
Added details of a new `VersionDependencyMode` option in package owner data for Umbraco Marketplace.
Relates to this PR: https://github.com/umbraco/Umbraco.Marketplace/pull/172
Umbraco Marketplace
Can go live any time from next week.
=> Added details of VersionDependencyMode option in package owner data for Umbraco Marketplace

commerce-add-ons/payment-providers/README.md, commerce-add-ons/payment-providers/install-payment-providers.md, commerce-add-ons/payment-providers/invoicing/README.md
I could't find any documentation about the Zero Payment Provider in Umbraco Commerce.
I wonder if it should be a separate section like "Invoicing" or combine these under the same?
Furthermore more I have removed "Invoicing" from NuGet package list as it is no longer a separate NuGet packages as in Vendr: https://www.nuget.org/packages?q=Umbraco.Commerce.PaymentProviders.Invoicing&includeComputedFrameworks=true&prerel=true&sortby=relevance
=> Add info about Zero Payment Provider

14/umbraco-cms/reference/notifications/editormodel-notifications/README.md
The [EditorModel notifications](https://docs.umbraco.com/umbraco-cms/reference/notifications/editormodel-notifications#notifications) article currently explains that the `Sending***Notification` notifications still exist. They have been explicitly removed in V14, because their functionality is a client-side responsibility moving forward.
This PR adds a warning to the top of the article (and removes the current warning in the middle of the article), to let people know that the entire article is out of date.
V14
Whenever possible. Not super urgent.
=> Updated the warning for the EditorModel notifications article to be more explicit

14/umbraco-cms/extending/backoffice-setup/extension-types/header-apps.md
Update header apps:
Umbraco 14
=> Update header apps

14/umbraco-cms/.gitbook.yaml, 14/umbraco-cms/extending/ui-documentation.md, 14/umbraco-cms/fundamentals/backoffice/property-editors/README.md, 14/umbraco-cms/reference/configuration/README.md, 14/umbraco-cms/reference/routing/umbraco-api-controllers/README.md, 14/umbraco-cms/reference/templating/macros.md
- I've added redirects for all the deleted and renamed articles
- I've added notes to landing pages where some of the redirects lead
- Removed the mention of v9 from the Configuration landing page
- Added back the Macros article to inform users about the removed of the feature
Umbraco CMS
=> Adding redirects for articles removed/renamed with Umbraco 14

.github/styles/UmbracoDocs/Names.yml, 14/umbraco-cms/extending/backoffice-setup/extension-types/header-apps.md
As suggested https://github.com/umbraco/UmbracoDocs/pull/6212#issuecomment-2188161835
Umbraco 14/Generic
=> Update names yml

14/umbraco-cms/.gitbook.yaml, 14/umbraco-cms/SUMMARY.md, 14/umbraco-cms/extending/property-editors/declaring-your-property-editor.md
Tree Actions were renamed Entity Actions.
I've added a redirect in order to present the user with the correct content.
Also removed the "Declaring your property editor" correctly from the SUMMARY file 💪
=> Redirect for renamed Trees/Tree-Actions

12/umbraco-cms/reference/content-delivery-api/protected-content-in-the-delivery-api.md
Current "We have to implement a login page `[as described above]`" part links to a level up https://docs.umbraco.com/umbraco-cms/v/12.latest/reference/content-delivery-api#logging-in-members instead of same page https://docs.umbraco.com/umbraco-cms/v/12.latest/reference/content-delivery-api/protected-content-in-the-delivery-api#logging-in-members
=> Link to section on same page

13/umbraco-cms/reference/webhooks/README.md, 14/umbraco-cms/reference/webhooks/README.md
Update webhook events:
For now, I have only updated the v13 version because I know you are working on all the v14 documentation. Of course, I am willing to update this as well, but could you please let me know when this is possible or allowed?
Umbraco v13
=> Update webhook events

10/umbraco-commerce/release-notes.md, 13/umbraco-commerce/release-notes/README.md
Umbraco Commerce 10.0.12 and 13.1.5 release notes
Umbraco Commerce 10.0.12 and 13.1.5
ASAP
=> Umbraco Commerce 10.0.12 and 13.1.5 release notes

14/umbraco-cms/.gitbook.yaml
The package manifest file was recently moved further up in the tree structure.
This was done via GitBook so the rewrite should work, however, I've received reports that this is not the case after all.
This PR adds the redirect manually.
=> Add redirect for package manifest file

10/umbraco-forms/developer/configuration/README.md, 12/umbraco-forms/developer/configuration/README.md, 12/umbraco-forms/upgrading/version-specific.md, 13/umbraco-forms/developer/configuration/README.md, 14/umbraco-forms/developer/configuration/README.md
Corrected details of default values for IP tracking across Forms versions.
Resolves the confusion leading to https://github.com/umbraco/Umbraco.Forms.Issues/issues/1245.
Forms 12+
=> Corrected details of default values for IP tracking across Forms versions.

10/umbraco-forms/developer/extending/adding-a-fieldtype.md, 12/umbraco-forms/developer/extending/adding-a-fieldtype.md, 13/umbraco-forms/developer/extending/adding-a-fieldtype.md, 14/umbraco-forms/developer/extending/adding-a-fieldtype.md
=> Update  adding a fieldtype

10/umbraco-cms/extending/packages/README.md, 10/umbraco-cms/extending/packages/installing-and-uninstalling-packages.md, 12/umbraco-cms/extending/packages/README.md, 12/umbraco-cms/extending/packages/installing-and-uninstalling-packages.md, 13/umbraco-cms/extending/packages/README.md, 13/umbraco-cms/extending/packages/installing-and-uninstalling-packages.md, 14/umbraco-cms/extending/packages/README.md, 14/umbraco-cms/extending/packages/good-practice-and-defaults.md, 14/umbraco-cms/extending/packages/installing-and-uninstalling-packages.md, 14/umbraco-cms/extending/packages/language-files-for-packages.md
Based on feedback from the DXP team I have updated some of the articles about packages in Umbraco so that they match the latest version.
14
N/A
N/A
=> Updated articles based on feedback from DXP team

10/umbraco-commerce/release-notes.md, 13/umbraco-commerce/release-notes/README.md
Umbraco Commerce 13.1.6 and 10.0.13 release notes
Umbraco Commerce 13.1.6 and 10.0.13 
ASAP
=> Umbraco Commerce 13.1.6 and 10.0.13 release notes

13/umbraco-deploy/release-notes.md, 14/umbraco-deploy/getting-started/deploy-settings.md, 14/umbraco-deploy/release-notes.md
Add release notes for Deploy 13.1.1 and 14.0.2.
Deploy 13.1.1 and 14.0.2.
Thursday July 11th (the patches are already released to NuGet)
=> Add release notes for Deploy 13.1.1 and 14.0.2

14/umbraco-forms/developer/configuration/README.md, 14/umbraco-forms/release-notes.md
Added release notes for Forms 14.1.0-rc2
Forms 14.1.0-rc2
=> Added release notes for Forms 14.1.0-rc2

14/umbraco-forms/developer/localization.md
Update the forms localization article: 
Umbraco Forms v14
=> v14 Update the forms localization article

10/umbraco-deploy/release-notes.md, 12/umbraco-deploy/release-notes.md, 13/umbraco-deploy/release-notes.md, 14/umbraco-deploy/release-notes.md
Release notes for the first RC release of Deploy and Deploy Contrib minors.
Deploy 13.2.0-rc1 and 14.1.0-rc1
Deploy Contrib 4.4.0-rc1, 10.3.0-rc1, 12.2.0-rc1, 13.2.0-rc1 and 14.1.0-rc1
Friday July 19th (the releases have already been published to NuGet)
=> Add Deploy 13.2.0-rc1 and 14.1.0-rc1, Deploy Contrib 4.4.0-rc1, 10.3.0-rc1, 12.2.0-rc1, 13.2.0-rc1 and 14.1.0-rc1 release notes

13/umbraco-forms/release-notes.md, 14/umbraco-forms/release-notes.md
Added release notes for Forms 13.2 and 14.1.
Forms 13.2 and 14.1.
Today or tomorrow if possible please.
=> Added release notes for Forms 13.2 and 14.1.

10/umbraco-cms/tutorials/creating-a-property-editor/part-3.md, 12/umbraco-cms/tutorials/creating-a-property-editor/part-3.md, 13/umbraco-cms/tutorials/creating-a-property-editor/part-3.md
Update creating a property editor:
=> Update creating a property editor

14/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/block-editor/label-property-configuration.md
The labels only work without the spaces. so it should be {=myPropertyAlias} and not {= myPropertyAlias }
removed spaces from the example label.
14.1
at any time
=> Typo in example on label-property-configuration.md

.github/styles/UmbracoDocs/Acronyms.yml, 10/umbraco-cms/extending/health-check/guides/macroerrors.md, 13/umbraco-cms/extending/health-check/README.md, 14/umbraco-cms/reference/umbraco-flavored-markdown.md
There has been some issues with this rule, and this is an attempt to resolve them.
=> Fix Acronym rule for vale

13/umbraco-forms/developer/working-with-data.md, 13/umbraco-forms/release-notes.md, 14/umbraco-forms/developer/working-with-data.md, 14/umbraco-forms/release-notes.md
Added release notes and documentation updates for Forms 13.2.1 and 14.1.1.
Forms 13.2.1 and 14.1.1
Can be reviewed and published at any time, but at least before 6th August if possible please.
=> Added release notes and documentation updates for Forms 13.2.1 and 14.1.1.

14/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/content-picker.md, 14/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/document-picker.md
Add notes to the renamed Content Picker and Document Picker to avoid confusion.
=> Notes on renamed pickers

13/umbraco-workflow/release-notes.md, 14/umbraco-workflow/release-notes.md
Release notes for 13.1.0 and 14.0.2.
Also adds belated note for 14.0.1.
=> Release notes - Workflow August patch

10/umbraco-cms/SUMMARY.md, 10/umbraco-cms/reference/templating/modelsbuilder/README.md, 12/umbraco-cms/SUMMARY.md, 12/umbraco-cms/reference/templating/modelsbuilder/README.md, 13/umbraco-cms/SUMMARY.md, 13/umbraco-cms/reference/templating/modelsbuilder/README.md, 13/umbraco-cms/reference/templating/modelsbuilder/install-the-full-version.md, 14/umbraco-cms/SUMMARY.md, 14/umbraco-cms/reference/templating/modelsbuilder/README.md, 14/umbraco-cms/reference/templating/modelsbuilder/install-the-full-version.md
- Removed reference to an empty article from SUMMARY.md
- Deleted the empty article from v13 and v14. v10 and v12 do not contain the article.
- Changed the link title to match the article title and side nav title.
CMS v10, v12, v13, v14
Anytime
=> Removed reference to an empty article from SUMMARY.md

14/umbraco-cms/extending/health-check/README.md
Update the Health Check article:
Umbraco v14
Thursday, August 22 2024 (release date Umbraco 14.2.0)
=> Update the Health Check article

14/umbraco-cms/reference/routing/umbraco-api-controllers/porting-old-umbraco-apis.md
update broken link for the one linked to the tutorials
cmx v14
anytime
=> Update broken link

14/umbraco-commerce/release-notes/README.md
Umbraco Commerce v14-rc3 release notes
Umbraco Commerce v14-rc3 
asap
=> Umbraco Commerce v14-rc3 release notes

12/umbraco-cms/reference/content-delivery-api/extension-api-for-querying.md, 13/umbraco-cms/reference/content-delivery-api/extension-api-for-querying.md, 14/umbraco-cms/reference/content-delivery-api/extension-api-for-querying.md
Remove invalid backtick in code blocks in extension-api-for-querying.md
Umbraco Docs [ 12 , 13 , 14] - extension-api-for-querying.md
=> Remove invalid backtick in code blocks in extension-api-for-querying.md [Umbraco 12, 13,14 Docs]

14/umbraco-cms/fundamentals/setup/install/unattended-install.md, 14/umbraco-cms/fundamentals/setup/upgrading/version-specific/README.md, 14/umbraco-cms/reference/configuration/connectionstringssettings.md, 14/umbraco-commerce/how-to-guides/configure-sqlite-support.md
While upgrading an Umbraco site using Sqlite from v13 to v14 I kept getting the following error: `System.ArgumentException: The specified invariant name 'Microsoft.Data.SQLite' wasn't found in the list of registered .NET Data Providers.`
I was using the exact values from the docs for `umbracoDbDSN_ProviderName` which made this error very confusing. 
After some source diving and looking at the git history, I found umbraco/Umbraco-CMS#15999 which removed support for the format mentioned in the docs. 
This PR updates the examples for version 14 to use the correct format. It may make sense to update the docs for versions 12 and 13 as well as it seems this format has been deprecated for a while.
It also may be worth updating the Breaking Changes section of the [Version Specific Upgrades …
=> Fix legacy ProviderName in sqlite examples

14/umbraco-commerce/SUMMARY.md, 14/umbraco-commerce/release-notes/README.md, 14/umbraco-commerce/release-notes/v14.0.0.md, commerce-add-ons/packages/checkout/release-notes.md, commerce-add-ons/packages/deploy/release-notes.md, commerce-add-ons/shipping-providers/dhl/release-notes.md, commerce-add-ons/shipping-providers/easypost/release-notes.md, commerce-add-ons/shipping-providers/shipmondo/release-notes.md
Umbraco Commerce v14 release notes
Umbraco Commerce v14 
ASAP
=> Umbraco Commerce v14 release notes

10/umbraco-deploy/release-notes.md, 12/umbraco-deploy/release-notes.md, 13/umbraco-deploy/release-notes.md, 14/umbraco-deploy/release-notes.md
Added release notes for Deploy 13.2.0, 14.1.0, 14.1.1 and Deploy Contrib 4.4.0, 10.3.0, 12.2.0, 13.2.0 and 14.1.0.
- Deploy 13.2.0, 14.1.0, 14.1.1.
- Deploy Contrib 4.4.0, 10.3.0, 12.2.0, 13.2.0 and 14.1.0.
These releases are already out, so this can be merged immediately.
=> Add release notes for Deploy 13.2.0, 14.1.0, 14.1.1 and Deploy Contrib 4.4.0, 10.3.0, 12.2.0, 13.2.0 and 14.1.0

marketplace-and-integrations/integrations/zapier-with-umbraco-forms.md, marketplace-and-integrations/integrations/zapier.md
Updated docs for the following integrations:
- Umbraco.Cms.Integrations.Automation.Zapier `2.0.0`
- Umbraco.Forms.Integrations.Automation.Zapier `4.0.0`
- Umbraco.Cms.Integrations.Automation.Zapier `2.0.0`
- Umbraco.Forms.Integrations.Automation.Zapier `4.0.0`
Anytime
=> Update docs for Zapier integrations

14/umbraco-cms/reference/common-pitfalls.md
An attempt to clean up the Common Pitfalls article.
I've made it comply with out styleguide.
=> Use vale linter on Common pitfalls article

14/umbraco-cms/customizing/extending-overview/extension-types/bundle.md
Corrected the JSON syntax in the example code for the [bundle](https://docs.umbraco.com/umbraco-cms/customizing/extending-overview/extension-types/bundle) example to follow JSON standards.
=> Corrected JSON syntax

14/umbraco-cms/reference/security/external-login-providers.md
Additional configuration is required for using External Login Providers on Cloud.
I added this information in a note.
=> Add section about external login providers on Cloud

10/umbraco-forms/release-notes.md, 13/umbraco-forms/developer/configuration/README.md, 13/umbraco-forms/developer/themes.md, 13/umbraco-forms/release-notes.md, 14/umbraco-forms/developer/configuration/README.md, 14/umbraco-forms/developer/themes.md, 14/umbraco-forms/release-notes.md
Added release notes and documentation updates for Forms 10.5.7, 13.2.2 and 14.1.2
Forms 10.5.7, 13.2.2 and 14.1.2
Can be reviewed and published at any time, ideally by the morning of Thursday 12th September.  Thanks.
=> Release notes and documentation updates for Forms 10.5.7, 13.2.2 and 14.1.2

10/umbraco-workflow/getting-started/configuration.md, 10/umbraco-workflow/release-notes.md, 13/umbraco-workflow/getting-started/configuration.md, 13/umbraco-workflow/release-notes.md
Release notes for 10.4, 13.2
Planning releases for 12 September.
=> Release notes - Workflow 10.4.0, 13.2.0

14/umbraco-cms/README.md, 14/umbraco-cms/customizing/extend-and-customize-editing-experience.md, 14/umbraco-cms/reference/routing/README.md, 14/umbraco-cms/reference/searching/README.md, 14/umbraco-cms/reference/security/README.md, 14/umbraco-cms/tutorials/editors-manual/README.md, umbraco-cloud/README.md, umbraco-cloud/deployment/README.md, umbraco-cloud/set-up/working-locally.md
Added links to training course details from relevant docs artices
v14
Anytime
=> Promoting training course

14/umbraco-forms/upgrading/version-specific/migration-ids.md
Updated migration IDs for Forms 10+.
Please note I modified the layout to use markdown rather than HTML (as it's much easier to edit in a text file).  I've included migrations from 10+, which seems reasonable given Forms 8 is out of support.
You will want to tidy up and remove the WIP note if you are happy with it.  And probably copy into the 10 and 13 folders, removing the migrations that are for versions subsequent to the one you copy into.
Forms 10+
Any time.
=> Updated migration IDs for Forms 10+

10/umbraco-deploy/release-notes.md, 13/umbraco-deploy/release-notes.md, 14/umbraco-deploy/release-notes.md
Added release notes for Deploy patch versions 13.2.1 and 14.1.2,
Deploy 13.2.1 and 14.1.2
The patches are already released, so this can get merged right away!
=> Add Deploy 13.2.1 and 14.1.2 release notes

14/umbraco-cms/extending/database.md
I added a line in the introduction to specify and link to NPoco.
This documentation worked really well for me, however I wished that it had specified that we're using NPoco. In earlier Umbraco days, it used to be PetaPoco, of which NPoco is based on. Coming back to Umbraco several years later, I was a bit confused until I figured out that PetaPoco had been swapped out.
I think it's also important to mention NPoco explicitly and link to it, as developers are likely going to need to go to NPoco's own documentation to learn how it works and how to use it. At first glance, I feel like it could be misunderstood that the database access facilities are provided by Umbraco itself, instead of by an outside project/dependency.
* [ X] New content
v14
N/A
=> Specifying that Umbraco includes NPoco

.github/styles/UmbracoDocs/Acronyms.yml
Add JPG & JPEG to the list of acronyms since PNG is also on the list.
=> Add JPG & JPEG to the list of acronyms

14/umbraco-cms/customizing/property-editors/composition/property-editor-ui.md
In the example it references the incorrect `propertyEditorSchema`, it should be `propertyEditorSchemaAlias`
In the example for [Property Editor UI](https://docs.umbraco.com/umbraco-cms/customizing/property-editors/composition/property-editor-ui) the property to select the schema is incorrect. It is currently `propertyEditorSchema`, it should be `propertyEditorSchemaAlias`.
=> Correct schema name in PropertyEditor example

13/umbraco-forms/release-notes.md, 14/umbraco-forms/release-notes.md
Added release notes for Forms 13.2.4 and 14.1.4
Forms 13.2.4 and 14.1.4
Can go live at any time, but ideally before or on Thursday morning.
=> Added release notes for Forms 13.2.4 and 14.1.4

10/umbraco-cms/reference/cache/updating-cache.md, 12/umbraco-cms/reference/cache/updating-cache.md, 13/umbraco-cms/reference/cache/updating-cache.md, 14/umbraco-cms/reference/cache/updating-cache.md, 15/umbraco-cms/reference/cache/updating-cache.md
Update updating cache:
Umbraco CMS 10,12,13,14 & 15
=> Update updating cache

14/umbraco-cms/reference/security/external-login-providers.md
Add a solution for fixing error "OpenIdConnectProtocol requires the jwt token to have an 'iss' claim" when using Azure AD for user logging into BackOffice. (Fixing for the issue https://github.com/umbraco/Umbraco-CMS/issues/16565)
I added a note in case of error when using Azure AD for login, it may be necessary to update the Microsoft.IdentityModel.Protocols.OpenIdConnect package to the latest version.
v14
=> Update external login provider to fix issue 16565

14/umbraco-cms/SUMMARY.md, 14/umbraco-cms/extending/health-check/guides/README.md, 14/umbraco-cms/extending/health-check/guides/contentsecuritypolicy.md, 14/umbraco-cms/extending/health-check/guides/crosssitescriptingprotection.md, 15/umbraco-cms/SUMMARY.md, 15/umbraco-cms/extending/health-check/guides/README.md, 15/umbraco-cms/extending/health-check/guides/contentsecuritypolicy.md, 15/umbraco-cms/extending/health-check/guides/crosssitescriptingprotection.md
Add CSP health check article
Fixes: https://github.com/umbraco/UmbracoDocs/issues/6336
Umbraco > 14.3 
Thursday, October 3 2024 (release Umbraco 14.3)
=> Add CSP health check article

umbraco-heartcore/.gitbook.yaml, umbraco-heartcore/SUMMARY.md, umbraco-heartcore/api-documentation/README.md, umbraco-heartcore/api-documentation/content-delivery/redirect.md, umbraco-heartcore/api-documentation/redirect.md, umbraco-heartcore/release-notes/2024-02-releasenotes.md, umbraco-heartcore/release-notes/2024-04-releasenotes.md, umbraco-heartcore/release-notes/2024-08-releasenotes.md, umbraco-heartcore/release-notes/2024-09-releasenotes.md
Heartcore release notes & updated API docs for September.
Also moved the redirect API to underneath the content delivery API - It's not really a seperate API on its own and the docs should reflect that.
Heartcore
N/A
=> add september heartcore release notes. update redirect api with new endpoint

13/umbraco-ums/security-and-privacy/gdpr/how-to-become-gdpr-compliant-using-cookiebot.md, 14/umbraco-forms/developer/rendering-forms.md, 14/umbraco-forms/developer/themes.md
I've updated the "Render Forms" article by removing the macro section.
I've updated the "Themes article" by linking to the "Rendering Forms" article instead of the example using Macros.
Forms - 14
=> Remove mentions of Macros to render Umbraco Forms

10/umbraco-deploy/deployment-workflow/content-transfer.md, 13/umbraco-cms/fundamentals/data/defining-content/README.md, 13/umbraco-cms/fundamentals/data/defining-content/default-document-types.md, 13/umbraco-deploy/deployment-workflow/content-transfer.md, 13/umbraco-deploy/troubleshooting.md, 13/umbraco-forms/editor/creating-a-form/conditional-logic.md, 13/umbraco-forms/editor/creating-a-form/form-settings.md, 14/umbraco-cms/fundamentals/data/defining-content/README.md, 15/umbraco-cms/fundamentals/data/defining-content/README.md, umbraco-cloud/product-upgrades/manual-upgrades/manual-cms-upgrade.md, umbraco-cloud/product-upgrades/manual-upgrades/manual-upgrade-deploy.md
Before we unpublish the documentation for Umbraco 12 and move the directory for the version out of the main branch, some image references needed to be cleaned up.
=> Remove references to images in v12 directory

10/umbraco-commerce/upgrading/migrate-from-vendr-to-umbraco-commerce/README.md, 13/umbraco-commerce/upgrading/migrate-from-vendr-to-umbraco-commerce/README.md, 14/umbraco-commerce/upgrading/migrate-from-vendr-to-umbraco-commerce/README.md, 15/umbraco-commerce/upgrading/migrate-from-vendr-to-umbraco-commerce/README.md
When you're migrating from Vendr to Umbraco Commerce, you need to be using the latest version of Vendr.
A note about this has been added to all versions of the Commerce docs.
Fixed #6478
=> Adding note about migrating from latest Vendr version

14/umbraco-cms/extending/database.md, 15/umbraco-cms/extending/database.md
This PR belongs to: https://github.com/umbraco/UmbracoDocs/issues/6466.  Change `UmbracoApiController` to a default `Controller` and also added route attributes as suggested in the [Porting old Umbraco API Controllers article](https://docs.umbraco.com/umbraco-cms/reference/routing/umbraco-api-controllers/porting-old-umbraco-apis). Happy hacktoberfest! 🎃 
UmbracoApiController
=> Porting old Umbraco API Controller [Extending > Database]

13/umbraco-forms/release-notes.md, 14/umbraco-forms/release-notes.md
Added release notes for Forms 13.2.5 and 14.1.5
Forms 13.2.5 and 14.1.5
At any time but ideally on or before Thursday morning please.
=> Added release notes for Forms 13.2.5 and 14.1.5

10/umbraco-workflow/release-notes.md, 13/umbraco-workflow/release-notes.md, 14/umbraco-workflow/release-notes.md
Release notes for Workflow patches
Workflow 10.4.1, 13.2.1, 14.0.3
Patches due to release October 3
=> Release notes for Workflow 10.4.1, 13.2.1, 14.0.3

14/umbraco-cms/customizing/extending-overview/custom-extension-type/custom-extension-type.md, 14/umbraco-cms/customizing/extending-overview/extension-conditions/extension-conditions.md, 14/umbraco-cms/customizing/extending-overview/extension-kind/extension-kind.md, 14/umbraco-cms/customizing/extending-overview/extension-registry/extension-manifest.md, 14/umbraco-cms/customizing/extending-overview/extension-registry/extension-registry.md, 14/umbraco-cms/customizing/extending-overview/extension-types/condition.md
Notice this is only correct for v.15
Update and additional articles to the topic of Extension Manifests and sub topics.
Writting your own extension type is changed slitghly in v.15 — this lead me to update a write a bit more about Extension Manifest.
And then related topics of Conditions and Kinds have been updated with additional articles from an overview perspective. But notice the structural challenge of both kinds and conditions begin an extension type of them self but also a Extension Manifest Feature. The point to understand here is that its a Core feature, which can be extended with additional opportunities. hence the two perspectives.
Please see changes to get a better overview of this PR.
=> V15: Updated and additional articles to Extension Manifests and sub topics

13/umbraco-ums/developers/headless/headless-example.md, 13/umbraco-ums/marketers-and-editors/personalization/cockpit-insights.md, 13/umbraco-ums/marketers-and-editors/personalization/creating-a-segment.md, 13/umbraco-ums/marketers-and-editors/profiling/profile-detail.md, 13/umbraco-ums/security-and-privacy/gdpr/how-to-become-gdpr-compliant-using-cookiebot.md, 13/umbraco-ums/security-and-privacy/how-it-works.md
=> cleanup articles

14/umbraco-cms/reference/language-variation.md, 14/umbraco-cms/reference/security/custom-password-check.md
Added the missing descriptions for articles as mentioned in #6465 
I added the description for the following articles
- Language Variation
- Replacing the basic username/password check
=> Add article descriptions

14/umbraco-cms/reference/common-pitfalls.md, 15/umbraco-cms/reference/common-pitfalls.md
=> Porting old Umbraco API Controller [Common Pitfalls: Static references to scoped references]

umbraco-cloud/frequently-asked-questions.md
Update cloud faq article: styleguide, missing region (australian) + .net versions support -> linked to eol for easier future maintaintence + SQL ce is removed since v9 so left just SQL instead 
- noticed as well that many questions are similar to the ones from https://umbraco.com/products/umbraco-cloud/faq/ so am not sure if an idea could be to remove questions that are on docs and just put a link to .com to read more about them there?💡
- 
cloud
anytime
=> Update cloud faq article

15/umbraco-forms/developer/configuration/README.md, 15/umbraco-forms/release-notes.md, 15/umbraco-forms/upgrading/version-specific/README.md
Made addition to Forms 15.0.0-rc1 release notes.
Forms 15.0.0-rc1
By Tuesday if possible please.
=> Addition to Forms 15.0.0-rc1 release notes.

10/umbraco-cms/fundamentals/code/debugging/logging.md, 13/umbraco-cms/fundamentals/code/debugging/logging.md, 14/umbraco-cms/fundamentals/code/debugging/logging.md, 15/umbraco-cms/fundamentals/code/debugging/logging.md
=> Porting old Umbraco API Controller [Debugging > Logging]

14/umbraco-cms/fundamentals/data/defining-content/default-document-types.md, 15/umbraco-cms/fundamentals/data/defining-content/default-document-types.md
- move around the sections to match that of the top-most screenshot
- describe compositions in more detail detailing how you need to create the document types first (unlike v13 where there was a "Composition" option)
- fixed Vale issues
Fixes https://github.com/umbraco/Umbraco-CMS/issues/17173
14 & 15
ASAP
=> docs: describe default document types in more detail

14/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/image-cropper.md, 15/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/image-cropper.md
=> Porting old Umbraco API Controller [Image Cropper]

13/umbraco-commerce/SUMMARY.md, 13/umbraco-commerce/how-to-guides/add-item, 13/umbraco-commerce/how-to-guides/add-item.md
Original article for adding an item to a cart when using Umbraco Commerce
How to add an item to the Umbraco Commerce cart
Umbraco 13
ASAP
=> Create add-item article

14/umbraco-cms/reference/mapping.md, 15/umbraco-cms/reference/mapping.md
=> Porting old Umbraco API Controller [Mapping]

15/umbraco-workflow/release-notes.md
Removes v14 info from v15 release notes, leaving entry for 15-rc1 only.
Workflow 15.0.0-rc1
=> Workflow 15 release notes

10/umbraco-cms/reference/cache/examples/tags.md, 13/umbraco-cms/reference/cache/examples/tags.md, 14/umbraco-cms/reference/cache/examples/tags.md, 15/umbraco-cms/reference/cache/examples/tags.md
=> Porting old Umbraco API Controller [Cache > Tags]

15/umbraco-cms/reference/cache/examples/tags.md, 15/umbraco-cms/reference/management/using-services/contenttypeservice.md
Updated docs to be correct with the new annoucement for v15
https://github.com/umbraco/Announcements/issues/15
And this PR, which will go out before v15 release: https://github.com/umbraco/Umbraco-CMS/pull/17223
Umbraco 15
Just when reviewed
=> Updated docs to use GetMany vs GetAll

14/umbraco-cms/reference/routing/request-pipeline/icontentfinder.md, 15/umbraco-cms/reference/routing/request-pipeline/icontentfinder.md
Removed duplicate code.
Added a note about the obsolete `GetAll()` method on the `_domainService`.
15.0.0
=> Removed duplicate code and add note for obsolete method

14/umbraco-cms/customizing/extending-overview/extension-types/menu.md, 15/umbraco-cms/customizing/extending-overview/extension-types/menu.md
I added extra examples + explanation to the menu docs for V14 and v15
V14, V15
=> Menu: Added extra examples + explanation

14/umbraco-cms/implementation/unit-testing.md, 15/umbraco-cms/implementation/unit-testing.md
=> Porting old Umbraco API Controller [Unit Testing]

14/umbraco-forms/developer/extending/setting-types.md, 15/umbraco-forms/developer/extending/setting-types.md
Updated details of setting types used in Forms.
Forms 14+
=> Updated details of setting types used in Forms

14/umbraco-cms/reference/management-api/README.md
Added a note with the client_id, that you need to leave the client_secret empty for non-production environments as it's easy to miss the hint below the screen shot that lets you know that you need to leave the client_secret empty.
=> Clarifying management API authentication

10/umbraco-cms/reference/querying/itagquery.md, 13/umbraco-cms/reference/querying/itagquery.md, 14/umbraco-cms/reference/querying/itagquery.md, 15/umbraco-cms/reference/querying/itagquery.md
=> Porting old Umbraco API Controller [Querying > ITagQuery]

13/umbraco-deploy/deployment-workflow/import-export-v7.md, 13/umbraco-deploy/deployment-workflow/import-with-migrations.md, 14/umbraco-deploy/deployment-workflow/import-export-v7.md, 14/umbraco-deploy/deployment-workflow/import-with-migrations.md
Deploy Contrib 13.3 and 14.2 added legacy property type migrators (besides the artifact migrators, see PR https://github.com/umbraco/Umbraco.Deploy.Contrib/pull/71), which requires extra setup code to correctly migrate all values from version 7. I've currently only amended the documented composer with the required code and an inline comment, as I don't think we need to add a separate mention about this...
While preparing my talk for DF24, I also noticed we currently don't have any documentation about the import and migration flow, including the notifications that are published. I've added a new paragraph/section to list out all steps involved in this operation.
Finally, I've added notes about providing custom grid editor configurations when migrating the legacy Grid editor to the Block …
=> Document Deploy legacy property type migrators, import and migration flow and clarify grid editor configuration

14/umbraco-deploy/release-notes.md, 15/umbraco-deploy/release-notes.md, 15/umbraco-deploy/upgrades/version-specific.md, 15/umbraco-forms/release-notes.md
Deploy, Deploy Contrib and Forms Deploy 15.0.0-rc1 release notes
Deploy, Deploy Contrib and Forms Deploy
As soon as possible, as all versions are already released to NuGet.
=> Add Deploy, Deploy Contrib and Forms Deploy 15.0.0-rc1 release notes

umbraco-heartcore/getting-started/preview.md
The Preview API is available on Standard Plan and above
The documentation said that the Preview API is available on Professional Plans.
I changed it to Standard, as the Preview API is also available there now.
=> Plan requirement change

10/umbraco-forms/developer/working-with-data.md, 13/umbraco-forms/developer/working-with-data.md, 14/umbraco-forms/developer/working-with-data.md, 15/umbraco-forms/developer/working-with-data.md
Updated outdated documentation on working with Forms record data.
Forms 10, 13 and 14
=> Update outdated documentation on working with Forms record data.

13/umbraco-commerce/release-notes/README.md, 14/umbraco-commerce/release-notes/README.md
Updated release notes for `Umbraco.Commerce`.
Umbraco.Commerce 13.1.8/14.1.3
Whenever possible
=> Update Umbraco Commerce docs

13/umbraco-engage/developers/analytics/client-side-events-and-additional-javascript-files/README.md, 13/umbraco-engage/developers/analytics/client-side-events-and-additional-javascript-files/additional-measurements-with-the-analytics-scripts.md, 13/umbraco-engage/developers/analytics/client-side-events-and-additional-javascript-files/bridging-library-for-google-analytics.md, 13/umbraco-engage/developers/analytics/client-side-events-and-additional-javascript-files/bridging-library-for-google-tag-manager.md, 13/umbraco-engage/developers/analytics/client-side-events-and-additional-javascript-files/google-analytics-blocker-detection.md, 13/umbraco-engage/developers/analytics/location.md, 13/umbraco-engage/developers/introduction/dataflow-pipeline/data-collection.md, 13/umbraco-engage/developers/introduction/the-umbraco-engage-cookie/module-permissions.md, 13/umbraco-engage/upgrading/migrate-from-umarketingsuite.md
Hi @sofietoft,
Hereby a couple of changes that I've noticed were incorrect for the Assets path, and some code styling changes.
I've noticed some other pages also aren't formatting code correctly, but hopefully Tom or someone else has the time for that 😊
=> Asset path changes

14/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/block-editor/block-grid-editor.md, 15/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/block-editor/block-grid-editor.md
=> Porting old Umbraco API Controller [Block Grid Editor]

13/umbraco-workflow/getting-started/configuration.md, 13/umbraco-workflow/release-notes.md, 13/umbraco-workflow/workflow-section/workflow-settings.md, 14/umbraco-workflow/getting-started/configuration.md, 14/umbraco-workflow/release-notes.md
Release notes for 13.3.0, 14.1.0
Feature docs for scheduled content lock
Umbraco Workflow 13.3.0 and 14.1.0
Releases scheduled for 23 October
=> Workflow release notes - 13.3.0, 14.1.0

14/umbraco-cms/tutorials/getting-started-with-entity-framework-core.md, 15/umbraco-cms/tutorials/getting-started-with-entity-framework-core.md
=> Porting old Umbraco API Controller [Getting started with Entity Framework (EF) Core]

13/umbraco-commerce/release-notes/README.md, 14/umbraco-commerce/release-notes/README.md
Umbraco Commerce v13.1.9 and v14.1.4 release notes
Umbraco Commerce v13.1.9 and v14.1.4 
ASAP
=> Umbraco Commerce v13.1.9 and v14.1.4 release notes

13/umbraco-forms/release-notes.md, 14/umbraco-forms/release-notes.md
Minor tweaks to release notes for Forms 13.3 and 14.1 that I only noticed when reading after publication.
Forms 13.3 and 14.2
Any time is fine.
=> Minor tweaks to release notes for Forms 13.3 and 14.1

15/umbraco-deploy/release-notes.md, 15/umbraco-forms/release-notes.md
Add Deploy, Deploy Contrib and Forms Deploy 15.0.0-rc2 release notes.
Deploy 15.0.0-rc2
Deploy Contrib 15.0.0-rc2
Forms Deploy 15.0.0-rc2
These versions are already available on NuGet, so this can get merged right away.
=> Add Deploy, Deploy Contrib and Forms Deploy 15.0.0-rc2 release notes

13/umbraco-commerce/release-notes/README.md, 14/umbraco-commerce/release-notes/README.md, commerce-add-ons/packages/deploy/release-notes.md
Umbraco Commerce 13.1.11 & 14.1.6 and Umbraco Commerce Deploy 13.1.2 & 14.1.1 release notes
Umbraco Commerce 13.1.11 & 14.1.6
Umbraco Commerce Deploy 13.1.2 & 14.1.1
ASAP
=> Umbraco Commerce 13.1.11 & 14.1.6 and Umbraco Commerce Deploy 13.1.2 & 14.1.1 release notes

14/umbraco-cms/SUMMARY.md, 14/umbraco-cms/fundamentals/setup/install/install-umbraco-with-templates.md, 14/umbraco-cms/fundamentals/setup/install/running-umbraco-on-docker-locally.md, 15/umbraco-cms/SUMMARY.md, 15/umbraco-cms/fundamentals/setup/install/install-umbraco-with-templates.md, 15/umbraco-cms/fundamentals/setup/install/running-umbraco-on-docker-locally.md, 15/umbraco-cms/release-candidate-guide.md
Updated the help output in the  `install-umbraco-with-templates.md` to include the new options, I also added an article about how you can run Umbraco locally with Docker using Docker Compose.  Note that this is only relevant for 14.3 and up, but I still added it to the V14 section as well.
CMS v14 and v15
=> Add docker documentation for V14 and V15

14/umbraco-cms/customizing/extending-overview/extension-types/section-view.md, 15/umbraco-cms/customizing/extending-overview/extension-types/section-view.md, 15/umbraco-cms/customizing/section-trees/sections/section-view.md
I updated the already existing example which wasn't up to date with the current version of the ManifestSectionView.
I also added a typescript example of how to define the manifest + added a lit component example as reference to the linked element in the manifest.
V14, v15
=> Sectionview: fixed existing example + added extra examples

umbraco-heartcore/compare-with-umbraco-cms.md
Fix some misinformation re: special property aliases in Heartcore
Heartcore
N/A
=> fix: correct special property alias misinformation

14/umbraco-cms/reference/notifications/contentservice-notifications.md
I fixed a misspelling on the "Suppress()" method used in the scopes example. I also corrected the same misspelling several times in the surrounding description(s).
=> Fixed misspelled method in example and description

14/umbraco-cms/reference/management/using-services/relationservice.md, 15/umbraco-cms/reference/management/using-services/relationservice.md
=> Porting old Umbraco API Controller [Relation Service] 

14/umbraco-cms/reference/configuration/globalsettings.md
Every time I end up at the **Global Settings** page, I feel like each section on the page misses a bit of context. You can see the description about a given option, but you can't see the actual key unless you scroll back up to the top of the page. Also if you enter the page searching for a specific key, you can only find it in the big JSON example.
With this commit, I've added an extra line for each option stating the name of the associated key, and for most of the options, also specified a default value. I feel that this improving the descriptions for the various options. And keep scrolling frantically up and down to minimum.
There are a few options where I'm unsure about what to enter, so I've skipped these. Some of them I've skipped adding the key entirely, why others I've skipped the …
=> Added key and default value information to most sections

14/umbraco-cms/tutorials/custom-error-page.md
The "Implement Custom Error Pages" tutorial instructs users to create a doc type with the name "404."
`3. Name the Document Type 404.`
This is an invalid name, and the CMS will not allow the user to create/save the new doc type.
I reworked the existing content to instruct users to name the doc type "404 Page" and manually set the alias to "404Page."
This should tighten up the tutorial and add a little clarity with what the CMS does/doesn't allow.
v14
N/A
=> 404 Page Tutorial Fix

umbraco-cloud/troubleshooting/deployments/schema-mismatches.md
Removing mention of "macros" 
cloud
anytime
=> Removing mention of "macros" 

14/umbraco-forms/developer/extending/adding-a-fieldtype.md
Since Localization is moved to the front-end in Umbraco 14, adding a reference to that article (based on customer issue/suggestion).  ​
Added a reference link for ease
v14
Anytime
=> Added a reference link to the Localization article

13/umbraco-cms/reference/configuration/contentsettings.md, 14/umbraco-cms/reference/configuration/contentsettings.md
Removed v9 references and only retained default value to avoid confusion.
CMS v13 and v14
Anytime
=> Defined default value of ContentCleanupPolicy for v13+

14/umbraco-cms/tutorials/add-microsoft-entra-id-authentication.md
As per issue #6586, updated the note to specify that the conflict with Entra ID only applies to backoffice logins, not member logins. Added a line about the upcoming feature (WIP) which might remove this limitation. 
CMS v14.
Anytime
=> Reworded warning for clarity

15/umbraco-cms/fundamentals/setup/upgrading/version-specific/README.md
The notes for 15 and 14 had been merged together.
This PR separates them again.
15
=> Split up 15 and 14 section

13/umbraco-cms/reference/templating/modelsbuilder/understand-and-extend.md
I corrected the usage of the Models Builder `GetModelPropertyType` and `GetModelContentType` methods to include the `publishedSnapshotAccessor` parameter which has been required for a few Umbraco versions now.
v9-v13 (<v8 and v14 untested)
N/A
=> Correct usage of GetModelPropertyType and GetModelContentType methods

13/umbraco-cms/fundamentals/setup/server-setup/azure-web-apps.md, 14/umbraco-cms/fundamentals/setup/server-setup/azure-web-apps.md
Added note about `ASPNETCORE_ENVIRONMENT`, which doesn't seem to be added by default.
https://our.umbraco.com/forum/using-umbraco-and-getting-started/108432-appsettingsjson-transform#comment-336800
https://stackoverflow.com/a/38761777
https://stackoverflow.com/a/34622196
=> Add `ASPNETCORE_ENVIRONMENT` variable

13/umbraco-commerce/release-notes/README.md, 14/umbraco-commerce/release-notes/README.md
Umbraco Commerce 13.1.3 & 14.1.8 release notes
Umbraco Commerce 13.1.3 & 14.1.8 
ASAP
=> Umbraco Commerce 13.1.3 & 14.1.8 release notes

14/umbraco-cms/reference/routing/custom-routes.md
Added a note about client-side requests, to highlight it in the article.
CMS
=> Add note about client side requests

14/umbraco-commerce/SUMMARY.md, 14/umbraco-commerce/reference/telemetry/README.md, 14/umbraco-commerce/release-notes/README.md
Release notes for Umbraco Commerce 14.2.0
Umbraco Commerce 14.2.0
=> Umbraco Commerce 14.2.0 Release Notes

15/umbraco-cms/SUMMARY.md, 15/umbraco-cms/fundamentals/setup/upgrading/version-specific/README.md, 15/umbraco-cms/fundamentals/setup/upgrading/version-specific/migrate-content-to-umbraco-15.md
Added docs for the V15 content migration (for Block Level Variance) including tips on how to optimize or entirely opt out of the migration.
V15
Whenever possible
=> Added docs for V15 content migration

14/umbraco-workflow/release-notes.md, 15/umbraco-workflow/release-notes.md
Final release notes for Workflow 15, along with bonus 14.1.2 patch release
Workflow 15.0.0, 14.1.2
=> Workflow release notes - 15, 14.1.2

umbraco-cloud/set-up/project-settings/umbraco-cicd/KnownLimitationsAndConsiderations.md
Update the "limitation" about making schema changes only in the leftmost environment.
Changed to limitation to a consideration and included a link to the deployment workflow article.
Fixes: #6663
=> Make workflow consideration more clear

14/umbraco-cms/reference/content-delivery-api/README.md, 15/umbraco-cms/reference/content-delivery-api/README.md
Updates the "Enable the Content Delivery API" section on the docs to reflect the template changes in  14.3.0
CMS 14 & 15
=> Update enabling delivery api

15/umbraco-cms/reference/security/external-login-providers.md
The sample code is using an old namespace so will not compile
=> Sample code is using v13 namespace and doesn't compile

15/umbraco-cms/fundamentals/code/debugging/logging.md
=> Update loggin article v15

15/umbraco-cms/reference/umbraco-flavored-markdown.md
Updated [UFM documentation](https://docs.umbraco.com/umbraco-cms/reference/umbraco-flavored-markdown) with the latest amends to support Umbraco 15.
In brief...
- Changes to the UFM prefixes (from a "marker" to an "alias)
- More detail on each available UFM component
- Documents UFM filters + details the available filters
- Guide to developing a custom UFM filter
Umbraco CMS 15.0.0
As soon as possible _(not urgent)_
=> UFM updates for v15

13/umbraco-forms/release-notes.md, 14/umbraco-forms/release-notes.md, 15/umbraco-forms/release-notes.md
Added release notes for Forms 13.3.1, 14.2.1 and 15.0.1
Forms 13.3.1, 14.2.1 and 15.0.1
Towards the end of the day or early tomorrow if possible please (it's just release notes for an upcoming patch release).  I may amend it up until early afternoon as will be doing some testing, and if I uncover anything may need to add.  Thanks.
=> Added release notes for Forms 13.3.1, 14.2.1 and 15.0.1

15/umbraco-cms/reference/umbraco-flavored-markdown.md
A code sample for the UFM component example, using implements means I needed to do more than what I needed to do.
Looked at the source code of the existing UFM-Components and they use the `extends` approach instead so we only need to implement the `render` method
=> Change code example from Implements to Extends

15/umbraco-cms/fundamentals/code/umbraco-services.md, 15/umbraco-cms/fundamentals/design/templates/basic-razor-syntax.md, 15/umbraco-cms/reference/querying/ipublishedcontent/README.md, 15/umbraco-cms/reference/querying/umbracohelper.md, 15/umbraco-cms/reference/routing/custom-routes.md, 15/umbraco-cms/reference/templating/mvc/querying.md, 15/umbraco-cms/tutorials/creating-an-xml-site-map.md
Updated selected articles referencing `IPublishedContent.Children` and `IPublishedContent.Parent` to use the extension methods (`IPublishedContent.Children()` and `IPublishedContent.Parent()`) instead as the properties are obsoleted and will be removed in Umbraco 16.
15.0
No
=> V15 CMS: Updating `IPublishedContent.Children` and `IPublishedContent.Parent` property references to extension methods

10/umbraco-deploy/getting-started/deploy-settings.md, 13/umbraco-deploy/getting-started/deploy-settings.md, 14/umbraco-deploy/getting-started/deploy-settings.md, 15/umbraco-deploy/getting-started/deploy-settings.md
This adds explicit anchors to the Deploy settings, which are externally linked to from the Deploy management dashboard (shown below the Settings section):
We've updated the URLs in each (supported) Deploy major to include the version in the documentation links, so e.g. `https://docs.umbraco.com/umbraco-deploy/15.latest/getting-started/deploy-settings#excludedentitytypes` is used (which now redirects to the current version without the `15.latest`, but once v16 is released, will keep linking to the documentation for that version).
Deploy 10, 13, 14 and 15.
These anchors are already linked to from current Deploy releases, so this can be merged as soon as possible.
=> Add anchors to Deploy settings (used by management dashboard)

14/umbraco-cms/fundamentals/data/defining-content/default-document-types.md, 15/umbraco-cms/fundamentals/data/defining-content/default-document-types.md
=> Updated Default Document Types article

10/umbraco-deploy/getting-started/deploy-settings.md, 10/umbraco-deploy/release-notes.md, 13/umbraco-deploy/deployment-workflow/import-on-startup.md, 13/umbraco-deploy/getting-started/deploy-settings.md, 13/umbraco-deploy/release-notes.md, 14/umbraco-deploy/deployment-workflow/import-on-startup.md, 14/umbraco-deploy/getting-started/deploy-settings.md, 14/umbraco-deploy/release-notes.md, 15/umbraco-deploy/deployment-workflow/import-on-startup.md, 15/umbraco-deploy/getting-started/deploy-settings.md, 15/umbraco-deploy/release-notes.md
Add Deploy 10.4.1, 13.3.1, 14.2.1 and 15.0.1 release notes, fix setting heading levels and `PhysicalDirectoryArtifactImportOnStartupProvider` example code.
Deploy 10.4.1, 13.3.1, 14.2.1 and 15.0.1
These versions will be released today 😄
=> Add Deploy 10.4.1, 13.3.1, 14.2.1 and 15.0.1 release notes

10/umbraco-cms/reference/routing/iisrewriterules.md, 13/umbraco-cms/reference/routing/iisrewriterules.md, 14/umbraco-cms/reference/routing/iisrewriterules.md, 15/umbraco-cms/reference/routing/iisrewriterules.md, umbraco-cloud/set-up/project-settings/manage-hostnames/rewrites-on-cloud.md
For now, I have added the info only to v15. If it is good to go, I'll add it to the other versions as well.
CMS v15
Anytime
=> Added an example to IIS rewrites article

13/umbraco-commerce/release-notes/README.md
Replaced 13.1.3 with 13.1.13 in the Release History (title and GitHub link).
Umbraco Commerce 13.1.13
=> Minor typo fix for Release 13.1.13

15/umbraco-forms/developer/extending/adding-a-fieldtype.md
Updates a code sample for localization to reflect the change in location of a type for Umbraco 15.
Forms 15
Any time.
=> Fixes code sample for Umbraco 15

14/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/date-time.md, 15/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/date-time.md
The offset setting is no longer available in the Date Time property - this is from 14+.
14 + 15
=> Update Date Time property editor article

umbraco-cloud/set-up/project-settings/manage-security.md
Added a paragraph about WAF and link to the WAF section
=> Update manage-security.md to include WAF paragraph and link to the WAF section in the docs

15/umbraco-commerce/getting-started/the-licensing-model.md
Try again :-) 
In v14 and v15 Umbraco Commerce has updated the JSON structure of the location of the licence key
'Products' has been added to the structure
Although this has been updated in the docs
Just above is a handy cut and paste key for the structure
However, 'Products:' has not been added to this key to match the new structure...
=> Update Key in licence docs for v15

10/umbraco-workflow/installation/licensing.md, 13/umbraco-workflow/installation/licensing.md, 14/umbraco-workflow/installation/licensing.md, 15/umbraco-workflow/installation/licensing.md
Updates licensing information to list the differences between the free and licensed versions. This was previously available on dotcom in a large, hard-to-read table. I understand the product pages are in line for rework, but for now at least, this PR ensures we highlight the differences between the two Workflow versions.
Workflow 10, 13, 14, 15
=> Adds content to explain free vs licensed Workflow features

14/umbraco-cms/SUMMARY.md, 14/umbraco-cms/customizing/extending-overview/extension-types/entity-create-option-action.md, 15/umbraco-cms/SUMMARY.md
This PR adds documentation for a new Backoffice Extension type in v 15.
v15
=> Feature: New Backoffice Extension Type: Entity Create Option Action

.github/styles/UmbracoDocs/Acronyms.yml, 13/umbraco-cms/reference/configuration/requesthandlersettings.md, 15/umbraco-cms/reference/configuration/requesthandlersettings.md
Added docs for the new configuration option that ensures ASCII conversion of file names for Media items (introduced in [this PR](https://github.com/umbraco/Umbraco-CMS/pull/17580)),
V15.1 & V13.6
It's not at all urgent. Sometime after both of the above versions have been released 😄 
At this moment there is no release date for V13.6. V15.1 is due December 12 - I don't expect V13.6 to be out before that, so... no rush 👍
=> Document the "Convert file names to ASCII" config

13/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/media-picker-3.md, 14/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/media-picker-3.md, 15/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/media-picker-3.md
=> Update mediapicker article with an example

15/umbraco-ui-builder/installation/licensing-model.md
Add 'Products' to the key
In v14/v15 Umbraco have added 'Products' to the structure of the JSON for adding licences to the products, the docs have been updated with the new JSON but not the handy cut and paste configuration key
we did umbraco commerce, yesterday, this is UI builder, but likely they are all affected...
=> Update UI Builder Licence Key Key

10/umbraco-cms/reference/notifications/contentservice-notifications.md, 10/umbraco-cms/reference/notifications/mediaservice-notifications.md, 10/umbraco-cms/reference/notifications/memberservice-notifications.md, 13/umbraco-cms/reference/notifications/contentservice-notifications.md, 13/umbraco-cms/reference/notifications/mediaservice-notifications.md, 13/umbraco-cms/reference/notifications/memberservice-notifications.md, 14/umbraco-cms/reference/notifications/mediaservice-notifications.md, 14/umbraco-cms/reference/notifications/memberservice-notifications.md, 15/umbraco-cms/reference/notifications/mediaservice-notifications.md, 15/umbraco-cms/reference/notifications/memberservice-notifications.md
I corrected the spelling of the "Suppress" method from "Supress". The code has the correct spelling but the docs are wrong.
N/A
=> Correct typo of Suppress as "Supress"

14/umbraco-workflow/release-notes.md, 15/umbraco-workflow/release-notes.md
Release notes for Workflow 14.1.3 and 15.0.1
Workflow 14.1.3 and 15.0.1
=> Release notes for Workflow 14.1.3 and 15.0.1

13/umbraco-forms/developer/themes.md, 14/umbraco-forms/developer/themes.md, 15/umbraco-forms/developer/themes.md, 15/umbraco-forms/upgrading/version-specific.md
Added details on removing built-in email templates
Forms 13+
Any time.
=> Added details on removing built-in email templates

15/umbraco-cms/reference/content-delivery-api/media-delivery-api.md
Based on some feedback, I've added some additional information to the Take parameter for the Media delivery API article.
CMS
=> More info on the take parameter

10/umbraco-commerce/installation/licensing-model.md, 10/umbraco-ui-builder/installation/licensing-model.md, 13/umbraco-commerce/installation/the-licensing-model.md, 13/umbraco-deploy/installation/install-configure.md, 13/umbraco-deploy/installation/the-licensing-model.md, 13/umbraco-engage/installation/licensing.md, 13/umbraco-ui-builder/installation/licensing-model.md, 14/umbraco-commerce/getting-started/the-licensing-model.md, 14/umbraco-deploy/installation/install-configure.md, 14/umbraco-deploy/installation/the-licensing-model.md, 14/umbraco-ui-builder/installation/licensing-model.md, 15/umbraco-commerce/getting-started/the-licensing-model.md, 15/umbraco-deploy/installation/install-configure.md, 15/umbraco-deploy/installation/the-licensing-model.md, 15/umbraco-ui-builder/installation/licensing-model.md
Described option for using underscores in product keys when configuring product licenses with environment variables.
Commerce, UI Builder, Engage and Deploy (on-premise)
Any time.
=> Described option for using underscores in product keys when configuring product licenses with environment variables.

10/umbraco-cms/fundamentals/backoffice/logviewer.md, 13/umbraco-cms/fundamentals/backoffice/logviewer.md, 14/umbraco-cms/fundamentals/backoffice/logviewer.md, 15/umbraco-cms/fundamentals/backoffice/logviewer.md
I added timestamp filtering the the AzureTableLogEntity to prevent memory issues.
I encountered a lot of memory issues when using the original version from the documentation. I think I relied on it a bit too blindly! I wanted to share my experience to help prevent others from running into the same problems 😄
10, 13, 14, 15
=> Added timestamp filtering the the AzureTableLogEntity

marketplace-and-integrations/packages/authorized-services.md
Update of authorized services package details based on 10.1 and 15.1 releases.  This includes changes to the response type received from authorized service requests, describing how the response is now wrapped in a object that makes available additional information about the response, derived from the headers.
Also tidied up some details around configuration notes and versions.
Umbraco.AuthorizedServices 10.1 and 15.1
Anytime from today.
=> Update of authorized services package details based on 10.1 and 15.1 releases

13/umbraco-forms/release-notes.md, 15/umbraco-forms/developer/extending/adding-a-fieldtype.md, 15/umbraco-forms/release-notes.md
Release notes for Forms 13.4.0-rc2 and 15.1.0-rc2
Forms 13.4.0-rc2 and 15.1.0-rc2
Today
=> Release notes for Forms 13.4.0-rc2 and 15.1.0-rc2

14/umbraco-cms/tutorials/creating-a-backoffice-api/README.md
For Umbraco 14+ I think the following should be replaced
Umbraco.Cms.Web.BackOffice.Controllers.ManagementApiControllerBase =>
Umbraco.Cms.Api.Management.Controllers.ManagementApiControllerBase
See above
14
=> Fix for https://github.com/umbraco/UmbracoDocs/issues/6728

13/umbraco-forms/release-notes.md, 15/umbraco-forms/release-notes.md
Added release notes for Forms 13.4-rc3 and 15.1-rc3.
Forms 13.4-rc3 and 15.1-rc3
Today
=> Added release notes for Forms 13.4-rc3 and 15.1-rc3

commerce-add-ons/payment-providers/mollie/how-to-guides/testing-mollie-webhooks-locally.md
=> Updated webhook docs for clarity

15/umbraco-cms/fundamentals/backoffice/sections.md
=> Fix links in sections article

15/umbraco-cms/customizing/extending-overview/extension-types/bundle.md
Update the [bundle artice](https://docs.umbraco.com/umbraco-cms/customizing/extending-overview/extension-types/bundle) since `ManifestTypes` deprecaded in v15 and `UmbExtensionManifest` should be used instead.  See also #6767
=> Update Bundle article

15/umbraco-cms/customizing/development-flow/vite-package-setup.md, 15/umbraco-cms/customizing/extending-overview/extension-registry/extension-manifest.md, 15/umbraco-cms/customizing/foundation/contexts/README.md, 15/umbraco-cms/customizing/foundation/routes.md, 15/umbraco-cms/customizing/foundation/working-with-data/context-api.md, 15/umbraco-cms/customizing/property-editors/README.md, 15/umbraco-cms/customizing/property-editors/build-a-block-editor.md
Fix links for `umbraco-package.md` that were not updated when the section "Customize the backoffice" was renamed to "Customizing". I searched through all documents in V15 but did not find other references to the renamed section. In fact, I fixed it so that the links are linking more relative to the document without mentioning the name of the section.
15
ASAP
=> V15: Fix links for "customize-the-backoffice" -> "customize"

14/umbraco-cms/customizing/extending-overview/extension-types/localization.md, 15/umbraco-cms/customizing/extending-overview/extension-types/localization.md
Use the correct property `localizations` (and not `translations`). Credits to #6635 & @PerplexDaniel for discovering this on V14 - this PR brings the same fix to V15.
15
ASAP
=> V15: Localization property `translations` does not exist

13/umbraco-engage/SUMMARY.md, 13/umbraco-engage/release-notes.md, 13/umbraco-engage/upgrading/upgrade-umbraco-engage.md, 13/umbraco-engage/upgrading/version-specific-upgrade-notes.md
Added placeholder articles for:
- Release notes
- Version Specific upgrades
Added new article:
- Upgrade Umbraco Engage
Engage version 13.
=> Engage: Add more articles related to Upgrades

14/umbraco-cms/fundamentals/data/defining-content/README.md, 15/umbraco-cms/fundamentals/data/defining-content/README.md
Fixes Issue #6743 
v14 and v15
Anytime
=> Updated syntax for collapsible descriptions

umbraco-cloud/set-up/project-settings/umbraco-cicd/Troubleshooting.md
Troubleshooting for the .umbraco 
Cloud / CICD / Troubleshooting
=> CICD troubleshooting dotUmbraco-file

13/umbraco-forms/release-notes.md, 15/umbraco-forms/release-notes.md
Add Forms 13.4.0 and 15.1.0 release notes. I've also removed the bold formatting in the version headers, because these are already rendered in bold...
Forms 13.4.0
Forms 15.1.0
This can be merged right away (the releases are already on NuGet).
=> Add Forms 13.4.0 and 15.1.0 release notes

13/umbraco-ui-builder/release-notes.md, 14/umbraco-ui-builder/release-notes.md, 15/umbraco-ui-builder/release-notes.md
Updated release notes.
Umbraco.UIBuilder versions 13.1.7/14.0.2/15.0.2
=> Updated release notes for Umbraco.UIBuilder versions 13.1.7/14.0.2/15.0.2

10/umbraco-forms/installation/install.md, 13/umbraco-forms/installation/install.md, 14/umbraco-forms/installation/install.md, 15/umbraco-forms/installation/install.md
When installing Umbraco Forms on my Umbraco 13 installation, I made the mistake of installing the latest version of umbraco forms when running `dotnet add package Umbraco.Forms`
As a result, Umbraco Forms was not loading in my backoffice. After searching on [Discord](https://discord.com/channels/869656431308189746/1326916296796934297) and [GitHub](https://github.com/umbraco/Umbraco.Forms.Issues/issues/1188#issuecomment-2003832548), I discovered that the issue was due to version incompatibility. I felt sharing this would help others as well.
Please let me know if the note can be improved or changed.
Added a note about ensuring that the version of Umbraco Forms is compatible with the version of Umbraco being used.
Umbraco 10, 13, 14, 15
=> add note about ensuring Umbraco Forms version compatibility

14/umbraco-commerce/key-concepts/shipping-providers.md, 15/umbraco-commerce/key-concepts/shipping-providers.md
Applied only 1 change from PR #6793 to v 14 and v15.
The description tag is removed and the `ApiKey` typo is also fixed for both versions.
Commerce v14 and v15
Anytime
=> Applied PR changes to other versions

15/umbraco-cms/customizing/development-flow/vite-package-setup.md, 15/umbraco-cms/tutorials/creating-a-property-editor/README.md
Fixes Issue #6797 
Also, while testing the article, I had to bump the backoffice version. I added that info in the Vite Package Setup article.
CMS v15
=> Updated import module

umbraco-cloud/set-up/external-login-providers.md
=> Added introduction for External Login Providers article

14/umbraco-cms/customizing/ui-library.md, 15/umbraco-cms/customizing/ui-library.md
=> Update UI library

14/umbraco-cms/customizing/umbraco-package.md, 15/umbraco-cms/customizing/umbraco-package.md
=> Update umbraco package

10/umbraco-cms/reference/configuration/nucachesettings.md, 13/umbraco-cms/reference/configuration/nucachesettings.md, 14/umbraco-cms/reference/configuration/nucachesettings.md, 15/umbraco-cms/reference/configuration/cache-settings.md
Fixes Issue #6734 
v10, v13, v14, v15
Anytime
=> Added documentation for NuCache JSON Serialization Option

14/umbraco-cms/customizing/extending-overview/extension-types/section-view.md, 15/umbraco-cms/customizing/extending-overview/extension-types/sections/section-view.md
=> Update section view

13/umbraco-forms/release-notes.md, 15/umbraco-forms/release-notes.md
Umbraco.Forms.Deploy 13.1.0 and 15.1.0 release notes. I've also updated the heading levels, because the version headers skipped a level... If this causes all versions to be listed in the sidebar (and get a bit unwieldy), we could also add a header below 'Release history' to differentiate between the 'Umbraco.Forms' and 'Umbraco.Forms.Deploy' packages.
Umbraco.Forms.Deploy 13.1.0
Umbraco.Forms.Deploy 15.1.0
These updates were released last week, so this can get merged straight away.
=> Add Umbraco.Forms.Deploy 13.1.0 and 15.1.0 release notes

15/umbraco-cms/reference/configuration/contentsettings.md
Updated [**Content Settings** documentation](https://docs.umbraco.com/umbraco-cms/reference/configuration/contentsettings) to add `BackOfficeLogo` setting, (added in Umbraco CMS 15.2.0).
Umbraco CMS 15.2.0
As soon as possible.
=> Adds `BackOfficeLogo` to the `ContentSettings`

14/umbraco-cms/customizing/workspaces.md
=> Updated article

umbraco-cloud/deployment/content-transfer.md
Value of `AllowMembersDeploymentOperations` should be `Transfer` not `transfer`, otherwise intellisense shows a warning.
=> AllowMembersDeploymentOperations transfer operation

contributing/documentation/style-guide/images.md, contributing/documentation/style-guide/markdown-conventions.md, contributing/documentation/style-guide/structure.md
=> Updated Images style guide article

15/umbraco-cms/reference/querying/udi-identifiers.md
Added a code snippet for retrieving content by udi
CMS v15
=> Updated UDI Identifiers article

umbraco-cloud/.gitbook.yaml
Fix for [this issue](https://github.com/umbraco/Umbraco.Heartcore.Issues/issues/146) reported on the Heartcore tracker, but probably present in all Cloud sites.
Cloud
N/A
=> fix: redirect for old link in Deploy backoffice dashboard

10/umbraco-cms/reference/templating/modelsbuilder/understand-and-extend.md, 13/umbraco-cms/reference/templating/modelsbuilder/understand-and-extend.md, 14/umbraco-cms/reference/templating/modelsbuilder/understand-and-extend.md, 15/umbraco-cms/reference/templating/modelsbuilder/understand-and-extend.md
- Added some text to clarify code samples in Modelsbuilder articles
- Shortened long sentences
- Simplified some texts
CMS v10, 13,14,15
Anytime
=> Added some text to clarify code samples in Modelsbuilder articles

14/umbraco-cms/fundamentals/data/dictionary-items.md
Related to https://github.com/umbraco/UmbracoDocs/pull/6803
=> Removed section regarding Document Types

15/umbraco-cms/reference/configuration/contentsettings.md
Removed reference in the CMS Content Settings page to the `HideBackOfficeLogo` content setting that is now obsolete and not used.
This was raised in https://github.com/umbraco/Umbraco-CMS/issues/18222
Umbraco 15
Any time (I'll self-review).
=> Removed reference to HideBackOfficeLogo content setting that is now obsolete and not used.

13/umbraco-cms/reference/content-delivery-api/protected-content-in-the-delivery-api.md, 15/umbraco-cms/reference/content-delivery-api/protected-content-in-the-delivery-api/README.md
Documentation of new `userinfo` endpoint from Umbraco 13.6+
https://github.com/umbraco/Umbraco-CMS/pull/17719
Also document of this part would be great, e.g. a custom properties from member like `firstName` and `lastName`:
> The implementation is build to be extendable, so custom claims can be added to these claims - and the core claims can be removed, too.
Perhaps it should be mentioned `sub` contains Umbraco member guid key, but not sure if it always guid if integration with external providers.
=> Document `userinfo` endpoint

15/umbraco-commerce/release-notes/README.md
Umbraco Commerce v15.0.1 release notes
Umbraco Commerce v15.0.1
ASAP
=> Umbraco Commerce v15.0.1 release notes

15/umbraco-cms/fundamentals/setup/upgrading/version-specific/migrate-content-to-umbraco-15.md
With https://github.com/umbraco/Umbraco-CMS/pull/17827, parallel content migration for V15 has become optional and opt-in. This documents how to opt in 😄 
15.1.2 or 15.2, whichever comes first
When either of the versions above are released 😛
=> Document opt-in for parallel content migration of block editors

umbraco-heartcore/api-documentation/README.md
Updated Heartcore API documentation to mention that we currently do not support Bearer tokens when using `External Login providers` an Api-key should be used instead.
Heartcore
If it is possible - medio week 6 should be fine.
=> feat: Update documentation on external login providers and bearer tokens

13/umbraco-cms/reference/content-delivery-api/protected-content-in-the-delivery-api.md, 15/umbraco-cms/reference/content-delivery-api/protected-content-in-the-delivery-api/README.md
Added links too.
I wonder if there is a specific syntax to ensure external links open in new tab/window?
=> Add links to `userinfo` and standard claims

13/umbraco-cms/reference/webhooks/README.md
Updated the webhook page where an example of the webhook naming doesnt match the webhook type
* [X ] Typo/grammar fix
v13 LTS
=> Content publish example refrencing content unpublish webhook type

marketplace-and-integrations/integrations/shopify.md
Following the PR https://github.com/umbraco/Umbraco.Cms.Integrations/pull/240 being accepted I updated the documentation
Updated outdated content
Umbraco CMS Shopify Integration
=> Shopify documentation now reflects v1.3.0 settings

13/umbraco-deploy/getting-started/deploy-settings.md, 13/umbraco-deploy/release-notes.md, 14/umbraco-deploy/getting-started/deploy-settings.md, 14/umbraco-deploy/release-notes.md, 14/umbraco-forms/release-notes.md, 15/umbraco-deploy/getting-started/deploy-settings.md, 15/umbraco-deploy/release-notes.md, 15/umbraco-forms/release-notes.md
Deploy 13.4.0, 14.3.0 and 15.1.0 release notes (and their RCs), including new `PostDeploySchemaOperation`, `AllowIgnoreDependenciesOperations` and `ExportUserGroups` settings.
Deploy 13.4.0, 14.3.0 and 15.1.0
The versions are already released, so this can be merged right away.
=> Add Deploy 13.4.0, 14.3.0 and 15.1.0 release notes

umbraco-cloud/getting-started/umbraco-cloud-plans.md
=> Cloud Plan article - Added full form for acronyms

umbraco-cloud/set-up/smtp-settings.md
=> Updated SMTP settings article as per styleguide

14/umbraco-deploy/installation/install-configure.md
Updated the incorrect package name so that it is the correct one.
`Umbraco.Deploy.Forms` have been renamed to `Umbraco.Forms.Deploy`
14
=> Updating incorrect package name for the forms package for deploy for v14

15/umbraco-deploy/installation/install-configure.md
Updated the incorrect package name so that it is the correct one.
Umbraco.Deploy.Forms have been renamed to Umbraco.Forms.Deploy
15
=> Updating incorrect package name for the forms package for deploy v15

10/umbraco-workflow/getting-started/configuration.md, 10/umbraco-workflow/installation/licensing.md, 13/umbraco-engage/developers/analytics/forms.md, 13/umbraco-workflow/installation/licensing.md, 14/umbraco-workflow/getting-started/configuration.md, 14/umbraco-workflow/installation/licensing.md, 15/umbraco-workflow/getting-started/configuration.md, 15/umbraco-workflow/installation/licensing.md, generic/getting-started/developing-websites-with-umbraco/README.md, umbraco-cloud/set-up/project-settings/secrets-management.md
Found some broken links when browsing through the docs and corrected them. Also came across some json which used the incorrect quote symbol and corrected those too 😊.
=> Fix broken links and correct json quotes

13/umbraco-workflow/release-notes.md, 15/umbraco-workflow/release-notes.md
=> Workflow 15.0.3 release notes

10/umbraco-forms/installation/the-licensing-model.md, 13/umbraco-forms/installation/the-licensing-model.md, 14/umbraco-forms/installation/the-licensing-model.md, 15/umbraco-forms/installation/the-licensing-model.md
This adds a paragraph describing how to configure multiple Umbraco Forms license files.
All Forms versions.
🚀
=> Configure multiple Forms license files

15/umbraco-cms/implementation/custom-routing/signalR.md
=> Fixed a typo of Umbraco!

15/umbraco-cms/customizing/extending-overview/extension-types/kind.md
Fixed a small Typo...
TBH, for someone new to what a "Kind" is, this page doesn't really help explain what it is and why we should be using it? At least, I didn't get it the first couple of times I read it :)
Changed:
```extensionRegistry.register(extension);```
to
```extensionRegistry.register(manifest);```
=> Fixed a typo: Changed "extension" to "manifest" 

13/umbraco-cms/reference/configuration/contentsettings.md, 14/umbraco-cms/reference/configuration/contentsettings.md, 15/umbraco-cms/reference/configuration/contentsettings.md
Updated CMS content settings pages to remove old setting keys
CMS 13+
Any time.
=> Updated content settings to remove old setting keys

15/umbraco-cms/fundamentals/setup/server-setup/runtime-modes.md
Keepalive was removed in v14.
Remove reference to removed keepalive task.
14+
=> Remove reference to removed keep-alive task

15/umbraco-ui-builder/upgrading/migrating-from-konstrukt-to-umbraco-ui-builder.md, 15/umbraco-ui-builder/upgrading/upgrade.md, 15/umbraco-ui-builder/upgrading/version-specific.md
Applied styleguide to the upgrade articles.
UI Builder v15
Anytime
=> Updated UI Builder upgrade articles

15/umbraco-ui-builder/areas/context-apps.md, 15/umbraco-ui-builder/areas/dashboards.md, 15/umbraco-ui-builder/areas/folders.md, 15/umbraco-ui-builder/areas/trees.md
=> Updated UI Builder Areas articles

13/umbraco-commerce/release-notes/README.md, 15/umbraco-commerce/release-notes/README.md
Umbraco Commerce 13.2.0 and 15.2.0 release notes
Umbraco Commerce 13.2.0 and 15.2.0
ASAP
=> Umbraco Commerce 13.2.0 and 15.2.0 release notes

15/umbraco-ui-builder/getting-started/configuration.md, 15/umbraco-ui-builder/guides/creating-your-first-integration.md
... as that is the recommended approach.
Also, I updated a few statements here and there.
UI Builder v15
Anytime
=> Added info on usage of Composer... 

13/umbraco-workflow/release-notes.md, 15/umbraco-workflow/release-notes.md
Release notes for Workflow 13.4 and 15.1
=> release notes - 13.4 and 15.1

15/umbraco-ui-builder/searching/overview.md, 15/umbraco-ui-builder/searching/searchable-properties.md
=> Updated UI Builder Searching section

14/umbraco-cms/customizing/umbraco-package.md, 15/umbraco-cms/customizing/umbraco-package.md
Updates the description around `allowTelemetry` and deletes records of the old name `allowPackageTelemetry`.
14 & 15
ASAP
=> docs: correct info on allowTelemetry

13/umbraco-cms/reference/configuration/securitysettings.md, 13/umbraco-forms/developer/configuration/README.md, 14/umbraco-cms/reference/configuration/securitysettings.md, 14/umbraco-forms/developer/configuration/README.md, 15/umbraco-cms/reference/configuration/securitysettings.md, 15/umbraco-forms/developer/configuration/README.md
Made a couple of updates following issues pointed out related to configuration:
1. Removed documentation of a Form's setting that was removed in Forms 13.
2. Adds details of a CMS security setting that wasn't documented in the expected place.
Forms 13+, CMS 13+
Any time.
=> Corrects a couple of configuration documentation errors for CMS and Forms

10/umbraco-cms/reference/routing/request-pipeline/icontentfinder.md, 13/umbraco-cms/reference/routing/request-pipeline/icontentfinder.md, 14/umbraco-cms/reference/routing/request-pipeline/icontentfinder.md, 15/umbraco-cms/reference/routing/request-pipeline/icontentfinder.md
Renaming `AddCustomContentFinders()` to `AddMyCustomContentFinders()` to make it more specific and avoid confusion as mentioned in Issue #6938.
CMS v10, 13, 14, 15
Anytime
=> Updated AddCustomContentFinders() to AddMyCustomContentFinders()

13/umbraco-workflow/release-notes.md, 15/umbraco-workflow/release-notes.md
release notes for workflow 13.4.1 and 15.1.1 patches
=> release notes for workflow 13.4.1 and 15.1.1 patches

10/umbraco-cms/fundamentals/design/rendering-content.md, 13/umbraco-cms/fundamentals/design/rendering-content.md, 14/umbraco-cms/fundamentals/design/rendering-content.md, 15/umbraco-cms/fundamentals/design/rendering-content.md
Fixed reference to typed value when rendering rich text property values which were raised as incorrect in https://github.com/umbraco/Umbraco-CMS/issues/18738
Umbraco 10+
Any time.
=> Fixed reference to typed value when rendering rich text property values

14/umbraco-workflow/getting-started/workflow-workspace-view.md, 15/umbraco-workflow/getting-started/workflow-workspace-view.md
Rename Content App to Workspace view as suggested in https://github.com/umbraco/UmbracoDocs/issues/6576
Umbraco Workflow
=> Umbraco workflow content app to workspace view

13/umbraco-ui-builder/release-notes.md, 15/umbraco-ui-builder/release-notes.md
Release notes for Umbraco UIBuilder versions 13.2.2 and 15.1.1
Umbraco UIBuilder 13.2.2 and 15.1.1
=> Updated release notes for Umbraco.UIBuilder 13.2.2 & 15.1.1

15/umbraco-cms/customizing/foundation/localization.md
The example of the dashboard localization shows this, but its good to show this as an example with the different approaches on how to use/consume the localizations rather than find it in an example that is hard to spot IMO.
15.x
None - whenever you feel like and feel free to improve my copy/grammar 😄
=> Adds in an example to show how you can use the values inside a manifest

15/umbraco-cms/customizing/extending-overview/extension-registry/extension-manifest.md, 15/umbraco-cms/customizing/extending-overview/extension-types/menu.md, 15/umbraco-cms/customizing/extending-overview/extension-types/sections/section-view.md, 15/umbraco-cms/extending/build-on-umbraco-functionality.md, 15/umbraco-cms/extending/embedded-media-providers.md, 15/umbraco-cms/extending/packages/good-practice-and-defaults.md, 15/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/block-editor/block-level-variance.md, 15/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/tags.md, 15/umbraco-cms/fundamentals/backoffice/sections.md, 15/umbraco-cms/fundamentals/backoffice/settings-dashboards.md, 15/umbraco-cms/fundamentals/backoffice/variants.md, 15/umbraco-cms/fundamentals/data/adding-tabs.md, 15/umbraco-cms/fundamentals/data/creating-media/default-media-types.md, 15/umbraco-cms/fundamentals/data/defining-content/default-document-types.md, 15/umbraco-cms/fundamentals/data/defining-content/document-type-localization.md, 15/umbraco-cms/fundamentals/design/templates/razor-cheatsheet.md, 15/umbraco-cms/reference/content-delivery-api/README.md, 15/umbraco-cms/reference/content-delivery-api/protected-content-in-the-delivery-api/README.md, 15/umbraco-cms/reference/management-api/external-access.md, 15/umbraco-cms/reference/management/using-services/contentservice.md, 15/umbraco-cms/reference/scheduling.md, 15/umbraco-cms/reference/templating/macros.md, 15/umbraco-cms/reference/templating/mvc/partial-views.md, 15/umbraco-cms/tutorials/creating-a-basic-website/adding-language-variants.md, 15/umbraco-cms/tutorials/creating-an-xml-site-map.md, 15/umbraco-cms/tutorials/editors-manual/getting-started-with-umbraco/umbraco-interface.md, 15/umbraco-cms/tutorials/multilanguage-setup.md, 15/umbraco-cms/tutorials/starter-kit/lessons/4-help-and-community.md
Used Lychee tool to get a list of broken links in the CMS.
Manually fixed the broken links.
=> Fixing broken links in the CMS

15/umbraco-cms/customizing/extending-overview/extension-types/menu.md, 15/umbraco-cms/customizing/extending-overview/extension-types/modals/custom-modals.md, 15/umbraco-cms/customizing/extending-overview/extension-types/sections/section-view.md, 15/umbraco-cms/customizing/property-editors/composition/property-editor-ui.md, 15/umbraco-cms/tutorials/creating-a-custom-dashboard/README.md, 15/umbraco-cms/tutorials/creating-a-property-editor/README.md, 15/umbraco-cms/tutorials/creating-a-property-editor/adding-configuration-to-a-property-editor.md, 15/umbraco-cms/tutorials/creating-a-property-editor/integrating-context-with-a-property-editor.md, 15/umbraco-forms/developer/extending/adding-a-fieldtype.md
- Corrects usages of `UmbPropertyValueChangeEvent` and converts them into `UmbChangeEvent` with updated code samples
- Updates import paths throughout code examples with known changes in V15
- Updates code examples with updated best practices
- Adds `lineNumbers="true"` and `overflow="wrap"` on large code sections
15
ASAP
=> Change UmbPropertyValueChangeEvent to UmbChangeEvent and updates wrong import paths

10/umbraco-forms/developer/extending/excluding-a-built-in-field.md, 13/umbraco-forms/developer/extending/excluding-a-built-in-field.md, 14/umbraco-forms/developer/extending/excluding-a-built-in-field.md, 15/umbraco-forms/developer/extending/excluding-a-built-in-field.md
Forms v10,13,14, and 15
Anytime
=> Updated using statements as per feedback

15/umbraco-cms/reference/security/serverside-file-validation.md
Correct typo. Change trough to through.
A one letter typo. 
* [Yes] Typo/grammar fix
Umbraco 15 docs
None 
ASAP
=> Update serverside-file-validation.md - correct typo

13/umbraco-commerce/release-notes/README.md, 15/umbraco-commerce/release-notes/README.md
Umbraco Commerce 13.2.1 & 15.2.1 release notes
Umbraco Commerce 13.2.1 & 15.2.1 
ASAP
=> Umbraco Commerce 13.2.1 & 15.2.1 release notes

13/umbraco-workflow/release-notes.md, 15/umbraco-workflow/release-notes.md
=> Workflow release notes - 13.4.2, 15.1.2

umbraco-cloud/set-up/project-settings/manage-hostnames/README.md
=> Added limitations section in Manage Hostnames article

umbraco-cloud/getting-started/environments.md
Update the article to reflect the two new types of environments.
Ensured that the remaining content is up to date.
The image reference will remain broken until #6999 is merged.
=> Update Environments article

commerce-add-ons/packages/deploy/deploying-changes.md
Add docs on Ignoring Settings for Umbraco Commerce Deploy
Umbraco Commerce Deploy
ASAP
=> Add docs on Ignoring Settings for Umbraco Commerce Deploy

15/umbraco-ui-builder/areas/context-apps.md, 15/umbraco-ui-builder/getting-started/user-interface.md, 15/umbraco-ui-builder/miscellaneous/conventions.md, 15/umbraco-ui-builder/miscellaneous/umbraco-aliases.md, 15/umbraco-ui-builder/property-editors/entity-picker.md, 15/umbraco-ui-builder/property-editors/overview.md
=> Updated UI Builder articles

15/umbraco-ui-builder/advanced/encrypted-properties.md, 15/umbraco-ui-builder/advanced/events.md, 15/umbraco-ui-builder/advanced/repositories.md, 15/umbraco-ui-builder/advanced/value-mappers.md, 15/umbraco-ui-builder/advanced/virtual-sub-trees.md
=> Updated UI Builder Advanced section articles

umbraco-cloud/set-up/project-settings/secrets-management.md
I added the `UMBRACO__COMMERCE_` to allowed list of prefixes
Cloud / Secret Management
=> Cloud Secrets - allow Umbraco Commerce paths

10/umbraco-cms/tutorials/custom-error-page.md, 13/umbraco-cms/tutorials/custom-error-page.md, 14/umbraco-cms/tutorials/custom-error-page.md, 15/umbraco-cms/tutorials/custom-error-page.md
Fix to ensure links to 404 and 500 sections are using correct ids. Currently clicking on them does nothing as the wrong ids are being set in the URLs.
Version 10, 13, 14, and 15
=> Updated broken links - 404 and 500 section url ids

umbraco-cloud/frequently-asked-questions.md
=> Update environment references where needed in the FAQ article

umbraco-cloud/deployment/README.md
Also changed the references to metadata to schema instead.
=> Update environment refs in Deployment article

13/umbraco-ui-builder/SUMMARY.md, 13/umbraco-ui-builder/collections/entity-identifier-converters.md, 13/umbraco-ui-builder/release-notes.md, 15/umbraco-ui-builder/SUMMARY.md, 15/umbraco-ui-builder/collections/entity-identifier-converters.md, 15/umbraco-ui-builder/release-notes.md
* Updated release notes for Umbraco UI Builder 13.2.3 and 15.1.2
* Details on `EntityIdentifierTypeConverters`
Umbraco UI Builder 13.2.3 and 15.1.2
When possible.
=> Umbraco UI Builder release notes and details on entity identifier type converters

umbraco-cloud/databases/backups.md
Updated Backups with error codes
Cloud
=> Backups feature errorcodes

15/umbraco-cms/customizing/extending-overview/extension-registry/README.md
Typo and deadlink in the docs.
Deadlink is currently present on the page but is accessible through the left hand side menu.
=> Fix link in Extension Registry

15/umbraco-cms/customizing/extending-overview/extension-registry/replace-exclude-or-unregister.md
Updated the reference when using the `umbExtensionsRegistry` to unregister an extension. The current import doesn't contain a definition for this.
15.3.1
N/A
=> Correct reference to unregister export

13/umbraco-cms/fundamentals/setup/server-setup/runtime-modes.md, 14/umbraco-cms/fundamentals/setup/server-setup/runtime-modes.md, 15/umbraco-cms/fundamentals/setup/server-setup/runtime-modes.md, 16/umbraco-cms/fundamentals/setup/server-setup/runtime-modes.md
Added note on running production mode from source.
This came up from investigating an [issue](https://github.com/umbraco/Umbraco-CMS/issues/19043), finding a [comment on a PR](https://github.com/umbraco/Umbraco-CMS/pull/14656#discussion_r1296900457) about how to resolve it for the customer's situation, and deciding it would be useful in the documentation with an appropriate warning about when it should be used.
CMS 13+
Any time.
=> Added note on running production mode from source

15/umbraco-cms/customizing/extending-overview/README.md
=> Fixing typos.

15/umbraco-cms/customizing/development-flow/vite-package-setup.md, 15/umbraco-cms/tutorials/creating-a-custom-dashboard/README.md, 15/umbraco-cms/tutorials/creating-a-custom-dashboard/extending-the-dashboard-using-umbraco-ui-library.md
Fixed some minor errors I found when going through the custom dashboard tutorials.
15.4.0-rc2
=> Fixed some minor errors in the custom dashboard tutorials

16/umbraco-cms/extending/packages/creating-a-package.md, 16/umbraco-cms/fundamentals/setup/upgrading/version-specific/README.md, 16/umbraco-cms/reference/configuration/loggingsettings.md
Includes the following:
- Version specific upgrade guide breaking changes.
- Details of additional logging settings provided via https://github.com/umbraco/Umbraco-CMS/pull/19074
- Details of asynchronous package migrations provided via https://github.com/umbraco/Umbraco-CMS/pull/17057
Umbraco CMS 16.0.0-rc
We should publish this when the RC is released.  For now, keeping in draft.
=> Updates relating to 16.0.0-rc

15/umbraco-cms/tutorials/creating-a-property-editor/integrating-context-with-a-property-editor.md
The Codeblock seems to have had an extra tab, making it look like it was part of the first defined const - Making it confusing on the eyes :-)
=> Fix code alignment

15/umbraco-commerce/release-notes/README.md
Umbraco Commerce 15.3.2 Release Notes
Umbraco Commerce 15.3.2
ASAP
=> Umbraco Commerce 15.3.2 Release Notes

15/umbraco-commerce/release-notes/README.md
Umbraco Commerce v15.3.3 release notes
Umbraco Commerce v15.3.3 
ASAP
=> Umbraco Commerce v15.3.3 release notes

14/umbraco-cms/extending/packages/language-files-for-packages.md, 15/umbraco-cms/extending/packages/language-files-for-packages.md, 16/umbraco-cms/extending/packages/language-files-for-packages.md
Updated the docs to use `en` for the culture in code samples for package developers as this is the default fallback.
See this for details: https://github.com/umbraco/Umbraco-CMS/issues/19227
Umbraco CMS v14+
=> Updated docs with fallback en

14/umbraco-cms/fundamentals/setup/install/running-umbraco-on-docker-locally.md, 16/umbraco-cms/fundamentals/setup/install/running-umbraco-on-docker-locally.md
Added SQLite changes in Docker article for v14 and v16
CMS v14 and v16
Anytime
=> Added SQLite changes in Docker article for v14 and v16

15/umbraco-cms/tutorials/add-microsoft-entra-id-authentication.md
Updated the warning box to suggest Cloud functionality, instead of a warning against specific tech.
* [ X] Updated outdated content
=> Updating hint box to suggest using External Login Providers on Cloud

15/umbraco-cms/reference/umbraco-flavored-markdown.md
When copy/pasting the displayed code sample my IDE tells me to import "Tokens" so I suggest that it's added to the docs as well :)
=> Add missing import statement for "Tokens"

10/umbraco-cms/tutorials/creating-a-basic-website/css-and-images.md, 13/umbraco-cms/tutorials/creating-a-basic-website/css-and-images.md, 14/umbraco-cms/tutorials/creating-a-basic-website/css-and-images.md, 15/umbraco-cms/tutorials/creating-a-basic-website/css-and-images.md, 16/umbraco-cms/tutorials/creating-a-basic-website/css-and-images.md
Added info about the project folder and how the article works
CMS v10, v13, v14, v15, v16
Anytime
=> Added info about the project folder and how the article works

14/umbraco-cms/customizing/extending-overview/extension-conditions.md, 14/umbraco-cms/customizing/extending-overview/extension-types/condition.md, 15/umbraco-cms/customizing/extending-overview/extension-conditions.md, 15/umbraco-cms/customizing/extending-overview/extension-types/condition.md, 16/umbraco-cms/customizing/extending-overview/extension-conditions.md, 16/umbraco-cms/customizing/extending-overview/extension-types/condition.md
In v14, the Built-in Conditions Types section is in the Extension Conditions article, where it also talks about how to make your own conditions. For v15 and v16, that info was moved into the high-level overview Extension Conditions article, where it was kinda lost. 
For consistency and ease of finding stuff, I moved the info back in the original article, where it makes more sense, and added a link in the high-level overview article.
CMS v14, v15, and v16
Anytime
=> Moved Built-in Conditions Types info and added reference link

13/umbraco-forms/release-notes.md, 15/umbraco-forms/release-notes.md
Added release notes for Forms 13.4.2 and 15.1.2.
Forms 13.4.2 and 15.1.2
These patches are already released.
=> Add Forms 13.4.2 and 15.1.2 release notes

13/umbraco-cms/reference/configuration/imagingsettings.md, 14/umbraco-cms/reference/configuration/imagingsettings.md, 15/umbraco-cms/reference/configuration/imagingsettings.md, 16/umbraco-cms/reference/configuration/imagingsettings.md
Added section about HMACSecretKey to secure image requests. This has been a feature since V12, so it updates all articles since then.
13, 14, 15, 16
ASAP
=> CMS: Adds documentation for HMACSecretKey to Imaging Settings

15/umbraco-cms/customizing/development-flow/typescript-setup.md, 15/umbraco-cms/customizing/development-flow/vite-package-setup.md, 15/umbraco-cms/customizing/extending-overview/extension-types/bundle.md, 16/umbraco-cms/customizing/development-flow/README.md, 16/umbraco-cms/customizing/development-flow/vite-package-setup.md, 16/umbraco-cms/customizing/extending-overview/extension-types/bundle.md
Updated `extension-types` location as per folder in the project
Anytime
=> Updated extension-types location

15/umbraco-ui-builder/release-notes.md
Release notes for Umbraco UI Builder 15.1.5
Umbraco UI Builder 15.1.5
Whenever possible.
=> Umbraco UI Builder release notes for 15.1.5

10/umbraco-cms/fundamentals/design/rendering-media.md, 13/umbraco-cms/fundamentals/design/rendering-media.md, 14/umbraco-cms/fundamentals/design/rendering-media.md, 15/umbraco-cms/fundamentals/design/rendering-media.md, 16/umbraco-cms/fundamentals/design/rendering-media.md
Added more details about videos
CMS v10, v13, v14, and v15
Anytime
=> Added more details about videos

13/umbraco-forms/editor/creating-a-form/form-settings.md, 13/umbraco-forms/release-notes.md, 13/umbraco-forms/tutorials/creating-a-contact-form.md
Fix broken links in Forms 13.
This included removing a reference to a later version (14).
=> Fix broken links in Forms 13

15/umbraco-workflow/getting-started/submitting-changes.md, 15/umbraco-workflow/installation/installing-workflow.md, 15/umbraco-workflow/workflow-section/active-workflows.md, 15/umbraco-workflow/workflow-section/approval-groups.md, 15/umbraco-workflow/workflow-section/content-reviews.md
Fixed broken links in Workflow 15 docs.
=> Fix broken links in Workflow

.github/styles/UmbracoDocs/Acronyms.yml, 15/umbraco-cms/tutorials/custom-error-page.md, 16/umbraco-cms/tutorials/custom-error-page.md
1. Fixed broken links.
2. Moved the comment out of the code as a separate line to enable copy/pasting the json code without errors.
3. Added sample code to show different cultures.
4. Added some context as to when the 500 setup provided in the docs works.
5. Cleaned the _Trigger a 500 error (for testing)_ section.
6. Added a _Handling app startup failures_  section to cover app side of things.
Anytime
=> Feedback on 500 error page

umbraco-cloud/deployment/restoring-content/partial-restore.md, umbraco-cloud/product-upgrades/manual-upgrades/manual-upgrade-deploy.md, umbraco-cloud/release-notes/overview-2024/september-2024.md, umbraco-cloud/set-up/power-tools/generating-uda-files.md, umbraco-cloud/set-up/project-settings/umbraco-cicd/UmbracoCloudApi.md, umbraco-cloud/troubleshooting/deployments/changes-not-being-applied.md
Fixed broken links and images
Umbraco Cloud
Anytime
=> Fixed broken links and images in Umbraco Cloud

13/umbraco-workflow/release-notes.md, 15/umbraco-workflow/release-notes.md
Release notes for 13.4.3 and 15.1.4
=> Workflow release notes - 13.4.3, 15.1.4

15/umbraco-cms/reference/configuration/globalsettings.md, 16/umbraco-cms/reference/configuration/globalsettings.md
I have tried to scan through and add full forms for acronyms or correct the usage of certain terms. Is there something specific that needs to be defined in the article?
NA
Anytime
=> Defined acronyms

16/umbraco-forms/release-notes.md, 16/umbraco-forms/upgrading/version-specific.md
Add Forms 16.0.0-rc1 and 16.0.0-rc2 release notes and update version specific upgrade notes.
n/a
Forms 16
Direct: Forms 16.0.0-rc1 was released May 15th and 16.0.0-rc2 on the 26th.
=> Add Forms 16 RC release notes and update version specific upgrade notes

15/umbraco-forms/installation/the-licensing-model.md
=> Update the-licensing-model.md with restart recommendation

umbraco-cloud/SUMMARY.md, umbraco-cloud/release-notes/overview-2025/2025-06-releasenotes.md, umbraco-cloud/release-notes/overview-2025/overview-2025.md
Updated with release notes for June 2025 for Cloud
=> Updated with release notes for June 2025 for Cloud

14/umbraco-ui-builder/.gitbook.yaml, 15/umbraco-ui-builder/.gitbook.yaml, 16/umbraco-commerce/.gitbook.yaml, 16/umbraco-deploy/.gitbook.yaml, 16/umbraco-forms/.gitbook.yaml, 16/umbraco-ui-builder/.gitbook.yaml, 16/umbraco-workflow/.gitbook.yaml, commerce-add-ons/packages/.gitbook.yaml, commerce-add-ons/payment-providers/.gitbook.yaml, commerce-add-ons/shipping-providers/.gitbook.yaml
The redirects section can't be empty in the .gitbook.yaml files.
This PR removed all empty redirects sections from our docs sites.
=> Fix yaml files

13/umbraco-cms/fundamentals/data/creating-media/default-media-types.md
Additional instructions when adding Media Types after an upgrade
Fixes #7101
13. Applies to 13 and above
=> Resolution to https://github.com/umbraco/UmbracoDocs/issues/7101

16/umbraco-ui-builder/filtering/data-views.md, 16/umbraco-ui-builder/release-notes.md
Umbraco UI Builder 16 release notes
Umbraco UI Builder 16.0.0
=> Umbraco UI Builder 16 release notes and data views docs

16/umbraco-deploy/release-notes.md, 16/umbraco-deploy/upgrades/version-specific.md, 16/umbraco-forms/release-notes.md
Add Deploy 16.0.0-rc3, 16.0.0-rc4, 16.0.0-rc5 and 16.0.0 release notes and update version specific upgrade notes.
n/a
Deploy 16.0.0-rc3
Deploy 16.0.0-rc4
Deploy 16.0.0-rc5
Deploy 16.0.0
🚀 
=> Add Deploy 16 release notes and update version specific upgrade notes

14/umbraco-cms/customizing/development-flow/README.md, 15/umbraco-cms/customizing/development-flow/README.md, 16/umbraco-cms/customizing/development-flow/README.md
Added a Note to check compatible version and updated the command
CMS v14, v15, v16
Anytime
=> Updated Typescript setup section

16/umbraco-forms/developer/configuration/README.md
Small correction for the 'DisableRelationTracking' configuration value within the Umbraco documentation.
=> Update README.md of Umbraco Forms Configuration values

14/umbraco-cms/customizing/foundation/icons.md, 15/umbraco-cms/customizing/foundation/icons.md, 16/umbraco-cms/customizing/foundation/icons.md
Moved path for icon registry to the cms repo because these files have been moved.
CMS
=> Update icon registry links in documentation

umbraco-cloud/release-notes/overview-2025/2025-06-releasenotes.md, umbraco-cloud/release-notes/overview-2025/overview-2025.md
Added CI/CD v2 to cloud release notes
Cloud
When you are happy. Feature is released
=> Added CI/CD v2 to cloud release notes

umbraco-cloud/release-notes/overview-2025/2025-06-releasenotes.md, umbraco-cloud/release-notes/overview-2025/overview-2025.md
Added Umbraco 16 support to the cloud release notes
=> Added Umbraco 16 support to the cloud release notes

16/umbraco-cms/reference/scheduling.md
Currently, the changes have been applied only to v16. Once approved, I will apply it to other versions if applicable.
CMS v16 and others
Anytime
=> Formatted `IRecurringBackgroundJob` section for better readability

umbraco-cloud/databases/backups.md
Add a note about how restoring a database will prevent you from being able to try and make a backup at an earlier time that when the restore happened.
Cloud / Backups
=> Add one more limitation to Cloud/Database Backups

15/umbraco-cms/reference/configuration/cache-settings.md, 16/umbraco-cms/reference/configuration/cache-settings.md
Applied source code documentation on the usage of the `NuCacheSerializerType` to the published documentation.
See PR: https://github.com/umbraco/Umbraco-CMS/pull/19555 and issue https://github.com/umbraco/Umbraco-CMS/issues/19544
Umbraco CMS 15+ 
Any time
=> Clarified usage of NuCacheSerializerType setting

umbraco-cloud/getting-started/flexible-environments.md, umbraco-cloud/troubleshooting/deployments/README.md
Promote the `Merge Conflicts on Flexible Environments` to be a more visible on related articles
Cloud / Flexible Environments
no deadline - when convenient
=> Flexible Environments - clarify link to Merge Conflicts article

16/umbraco-cms/extending/language-files/README.md
This documents `pt` as an accepted Backoffice language
Since 16.0, the code `pt` has been accepted as a language and `pt-BR` has been made to fallback to `pt` for unknown variables.
16.0
ASAP
=> V16: Adds `pt` as an accepted language

16/umbraco-cms/customizing/foundation/fetching-data/custom-generated-client.md
The parameters for openapi-ts should be `--input` not `--url`
`generate` isn't a command as far as I can tell it gives the following error `error: too many arguments. Expected 0 arguments but got 1.` so that needed removing. Then this command works as supplied
v16+
=> Update openapi-ts command to use correct paramaters

15/umbraco-commerce/how-to-guides/limit-orderline-quantity.md, 16/umbraco-commerce/how-to-guides/limit-orderline-quantity.md
- Added Note as mentioned in the issue.
- Cleaned up article as per styleguide.
Fixes #7086 
Commerce v15 and 16
Anytime
=> Fixes Issue #7086

16/umbraco-cms/reference/webhooks/README.md
Adds information to the webhooks article about the new and improved payload types including
- What has changed.
- How long the old things keep existing.
- How to change things before it gets changed for you.
Cms V16
None, already shipped.
=> Add information about webhook payload types

15/umbraco-cms/reference/management/using-services/contentservice.md, 16/umbraco-cms/reference/management/using-services/contentservice.md
Replaced  Deprecated SaveAndPublish() method with Save(), Publish () and SaveAndPublishBranch() with PublishBranch().
CMS v15, 16
=> Replaced deprecated methods

15/umbraco-cms/reference/templating/modelsbuilder/builder-modes.md, 16/umbraco-cms/reference/templating/modelsbuilder/builder-modes.md
=> Added appSettings sample to ModelsBuilder Builder Modes article

15/umbraco-commerce/release-notes/README.md, 16/umbraco-commerce/release-notes/README.md
Umbraco Commerce v15.3.10 & v16.1.1 release notes
Umbraco Commerce v15.3.10 & v16.1.1
ASAP
=> Umbraco Commerce v15.3.10 & v16.1.1 release notes

14/umbraco-cms/fundamentals/setup/upgrading/version-specific/README.md, 15/umbraco-cms/fundamentals/setup/upgrading/version-specific/README.md, 16/umbraco-cms/fundamentals/setup/upgrading/version-specific/README.md
Some links were pointing to 404 pages, so I updated them to the latest working versions.
This PR fixes the links that would send the user to a 404 page inside the Umbraco 14 listing on the version specific upgrades page.
[Link to the page I'm talking about](https://docs.umbraco.com/umbraco-cms/fundamentals/setup/upgrading/version-specific#umbraco-14)
I did not figure out where the following two links should point to unfortunately. So if someone knows, please let me know so I can fix them too while I'm at it.
1. mfaProvider link, [from here](https://github.com/umbraco/UmbracoDocs/blob/main/16/umbraco-cms/fundamentals/setup/upgrading/version-specific/README.md?plain=1#L245)
2. authProvider link, [from here](https://github.com/umbraco/UmbracoDocs/blob/main/16/umbraco-cms/fundamentals/setup/up …
=> Fixing links in umbraco 14 change docs that are pointing to 404 pages

14/umbraco-cms/fundamentals/setup/upgrading/version-specific/README.md, 15/umbraco-cms/fundamentals/setup/upgrading/version-specific/README.md, 16/umbraco-cms/fundamentals/setup/upgrading/version-specific/README.md
=> Fixed broken link and removed unnecessary \

13/umbraco-workflow/getting-started/configuration.md, 13/umbraco-workflow/release-notes.md, 15/umbraco-workflow/getting-started/configuration.md, 15/umbraco-workflow/release-notes.md, 16/umbraco-workflow/getting-started/configuration.md, 16/umbraco-workflow/release-notes.md
=> release notes for WF 13.4.5, 15.1.7, 16.0.3

10/umbraco-cms/reference/configuration/contentsettings.md, 13/umbraco-cms/fundamentals/backoffice/variants.md, 13/umbraco-cms/reference/configuration/contentsettings.md, 14/umbraco-cms/fundamentals/backoffice/variants.md, 14/umbraco-cms/reference/configuration/contentsettings.md, 15/umbraco-cms/fundamentals/backoffice/variants.md, 15/umbraco-cms/reference/configuration/contentsettings.md, 16/umbraco-cms/fundamentals/backoffice/variants.md, 16/umbraco-cms/reference/configuration/contentsettings.md
Having investigated a reported issue on the CMS, it was clear our documentation of this setting wasn't entirely correct and was missing some changes between versions.
I've corrected the details of the default value of the setting across all versions, and updated the copy for 15 and 16 to describe the current behaviour.
https://github.com/umbraco/Umbraco-CMS/issues/19814
CMS 10+
Any time
=> Clarified documentation on the AllowEditInvariantFromNonDefault setting

10/umbraco-workflow/installation/licensing.md, 13/umbraco-workflow/installation/licensing.md, 14/umbraco-workflow/installation/licensing.md, 15/umbraco-workflow/installation/licensing.md, 16/umbraco-workflow/installation/licensing.md
A customer experienced validation issues with their Workflow license. According to their feedback:
"I changed the license value from **UMBRACO_LICENSES_UMBRACO_WORKFLOW** to **UMBRACO_LICENSES_Umbraco_Workflow** (case sensitive) and instead of using **Umbraco.Workflow** as the key, I used **Umbraco_Workflow** (underscore instead of period). The key change is not necessary but changed it for consistency (both ways work).
I'm providing this information in the hopes that the documentation is updated. This issue applies to Umbraco Engage as well. I experienced it when setting it up a couple of days/weeks ago."
Umbraco Engage v13 and v16 already have this Note. So no changes there.
I've followed the [Umbraco Documentation Style Guide](https://docs.umbraco.com/contributing/documentation/style-gu …
=> Added Note in Workflow Licensing article about using underscore instead of period

15/umbraco-ui-builder/release-notes.md, 16/umbraco-ui-builder/release-notes.md
Release notes for Umbraco UI Builder `15.1.10` and `16.0.3`
Umbraco UI Builder `15.1.10` and `16.0.3`.
=> Add release notes for UI Builder versions 15.1.10 and 16.0.3

13/umbraco-cms/reference/using-ioc.md, 14/umbraco-cms/reference/using-ioc.md, 15/umbraco-cms/reference/using-ioc.md, 16/umbraco-cms/reference/using-ioc.md
Updates an internal link in https://docs.umbraco.com/umbraco-cms/reference/using-ioc .
```bash
Before:
https://docs.umbraco.com/umbraco-cms/reference/using-ioc#registering-dependencies-in-the-programcs-file
After:
https://docs.umbraco.com/umbraco-cms/reference/using-ioc#registering-dependencies-in-the-program.cs-file
```
N/A
* [ ✅ ] Code blocks are correctly formatted.
* [ ✅ ] Sentences are short and clear (preferably under 25 words).
* [ ✅ ] Passive voice and first-person language (“we”, “I”) are avoided.
* [ ✅ ] Relevant pages are linked.
* [ ✅ ] All links work and point to the correct resources.
* [ ✅ ] Screenshots or diagrams are included if …
=> Correct an internal link in IoC page

13/umbraco-commerce/release-notes/README.md, 15/umbraco-commerce/release-notes/README.md, 16/umbraco-commerce/release-notes/README.md
Umbraco Commerce 13.2.4, 15.3.11 & 16.2.2 Release Notes
Umbraco Commerce 13.2.4, 15.3.11 & 16.2.2 
ASAP
=> Umbraco Commerce 13.2.4, 15.3.11 & 16.2.2 Release Notes

16/umbraco-cms/reference/configuration/maximumuploadsizesettings.md, 16/umbraco-cms/reference/configuration/runtimesettings.md
The intention of this pull request is to inform the reader, that it is advisable to set the `MaxRequestLength` in appsettings.json regardless of hosting platform, as Umbraco 16 uses this value to evaluate the validation for file uploads. (So instead of guessing the maximum file size, it will actively guide/advise the user that they are exceeding the file size).
16
ASAP
=> V16 CMS: Tell the developer to set `MaxRequestLength` regardless of hosting platform

10/umbraco-forms/developer/prepping-frontend.md, 13/umbraco-forms/developer/prepping-frontend.md, 14/umbraco-forms/developer/prepping-frontend.md, 15/umbraco-forms/developer/prepping-frontend.md, 16/umbraco-forms/developer/prepping-frontend.md
Defined what `Url` means in the code. Please take a look at the task for more details.
Forms v10-16
Anytime
=> Url definition

16/umbraco-cms/customizing/extending-overview/extension-types/sections/section-sidebar.md
Replaces outdated properties with "conditions"
* Replaces outdated "section" property with newer "conditions" property instead.
* Adds explanation to code example
Fixes https://github.com/umbraco/Umbraco-CMS/issues/19502
16
ASAP
=> V16 CMS: Some properties are outdated on Section Sidebar Apps

16/umbraco-cms/SUMMARY.md, 16/umbraco-cms/fundamentals/setup/upgrading/README.md, 16/umbraco-cms/fundamentals/setup/upgrading/upgrade-details.md, 16/umbraco-cms/fundamentals/setup/upgrading/upgrade-unattended.md
After more upgrade instructions have been added, I've restructure the section a tiny bit, and added more links to make it easier to navigate.
ASAP.
=> A small restructure of the Upgrade Documentation for CMS

.github/styles/UmbracoDocs/Acronyms.yml, umbraco-cloud/build-and-customize-your-solution/set-up-your-project/project-settings/README.md, umbraco-cloud/build-and-customize-your-solution/set-up-your-project/project-settings/application-settings.md, umbraco-cloud/build-and-customize-your-solution/set-up-your-project/project-settings/config-transforms.md, umbraco-cloud/build-and-customize-your-solution/set-up-your-project/project-settings/smtp-settings.md, umbraco-cloud/build-and-customize-your-solution/set-up-your-project/project-settings/upgrade-your-plan.md, umbraco-cloud/expand-your-projects-capabilities/external-services/README.md, umbraco-cloud/expand-your-projects-capabilities/external-services/application-insights.md, umbraco-cloud/explore-umbraco-cloud/what-is-umbraco-cloud/README.md, umbraco-cloud/explore-umbraco-cloud/what-is-umbraco-cloud/hosting-with-umbraco-cloud-cloud-vs.-self-hosted.md, umbraco-cloud/explore-umbraco-cloud/what-is-umbraco-cloud/key-features-and-benefits-of-using-umbraco-cloud.md
- Fixed Vale errors, like writing short sentences, defining acronyms, and removing editorializing words.
- Added SMTP to the list of exceptions in the Acronyms file. It has been defined multiple times in the docs in various articles still keeps throwing an error every time it´s mentioned in a different article. Also, SMTP is a widely known term in software.
NA
Cloud
Anytime
=> Fixed vale errors in Cloud articles - Part 2

.github/styles/UmbracoDocs/Acronyms.yml, .github/styles/UmbracoDocs/Brands.yml, .github/styles/UmbracoDocs/Editorializing.yml, .github/styles/UmbracoDocs/HeadingsPunctuation.yml, .github/styles/UmbracoDocs/LinkTextClarity.yml, .github/styles/UmbracoDocs/ListStart.yml, .github/styles/UmbracoDocs/Names.yml, .github/styles/UmbracoDocs/Repetition.yml, .github/styles/UmbracoDocs/SentenceLength.yml, .github/styles/UmbracoDocs/Spacing.yml, .github/styles/UmbracoDocs/Terms.yml, .github/styles/UmbracoDocs/UmbracoTerms.yml
- Updated some rules to exclude inline code, URL.
- Added frequently used acronyms to the exception list and the full form of all acronyms. Some are missing because I'm not sure what they are. We can take it off if it doesn't make sense 🤔
- Added Repetition rule to catch repeated words.
- Added link text rule to check for certain alt text used in Links, for example, here, read more.
- Added description to all rules mentioning the goal/purpose of the rule.
NA
Anytime
=> Updated some regex expressions to match the styleguide

16/umbraco-cms/.gitbook.yaml, 16/umbraco-cms/SUMMARY.md, 16/umbraco-cms/reference/content-type-filters.md, 16/umbraco-cms/reference/notifications/README.md, 16/umbraco-cms/reference/notifications/sendingallowedchildrennotifications.md
In Umbraco 16 (and 14 and 15) the SendingAllowedChildrenNotification no longer exists. Although the content of that page was updated to reflect the fact that it's no longer supported in Umbraco 16, after a conversion with Sofie it was decided that pages should be removed when a feature is no longer present in the CMS.
So this PR deleted this page and adds a redirect to it's replacement: content filters.
Fixes [#7332](https://github.com/umbraco/UmbracoDocs/issues/7332)
Umbraco 16
-
* ✍️ [Umbraco Documentation Style Guide](https://docs.umbraco.com/contributing/documentation/sty …
=> Remove SendingAllowedChildrenNotification

10/umbraco-forms/installation/the-licensing-model.md, 13/umbraco-forms/developer/configuration/README.md, 13/umbraco-forms/installation/the-licensing-model.md, 13/umbraco-forms/release-notes.md, 14/umbraco-forms/installation/the-licensing-model.md, 15/umbraco-forms/installation/the-licensing-model.md, 16/umbraco-forms/developer/configuration/README.md, 16/umbraco-forms/installation/the-licensing-model.md, 16/umbraco-forms/release-notes.md
This adds the release notes for Forms 13.6.0 and 16.1.0 and updates the licensing model pages with information and instructions on how to install the subscription-based license.
n/a
Forms 13.6 and 16.1
These versions will be released today, but the license changes are applicable from September 1st, 2025.
=> Add Forms 13.6.0 and 16.1.0 release notes and update licensing model page

umbraco-cloud/optimize-and-maintain-your-site/optimize-performance/README.md, umbraco-cloud/optimize-and-maintain-your-site/optimize-performance/manage-cdn-caching.md, umbraco-cloud/optimize-and-maintain-your-site/optimize-performance/migrate-between-regions.md
=> Clean up Optimize performance articles

umbraco-cloud/begin-your-cloud-journey/project-features/environments.md, umbraco-cloud/build-and-customize-your-solution/set-up-your-project/project-settings/config-transforms.md
We received some feedback about how there wasn't any docs on how to use config transforms with flexible environments.
Turns out, config transforms can be used on any environment as long as the correct environment alias is provided.
I've updated the Config Transforms article to reflect this.
I also made appSettings the main focus of the config transforms article.
Finally, I added a link from the Environments article to the Config transforms article.
=> Updates to Config Transforms

.github/lychee.toml, .github/workflows/check-broken-pr-links.yml, .gitignore, .lycheeignore
Adding Lychee to check for broken links in incoming PRs. 
To test:
1. Run the `choco install lychee` command on Windows PowerShell to install Lychee. You might want to check the command for the Linux machine.
2. Verify install using `lychee --version`.
3. Go to the local UmbracoDocs repo.
4. Add a Lychee config file in `.github/lychee.toml`.
5. Add `.lycheeignore` at the repo root.
6. Test Lychee locally. From the repo root, run: `lychee --config .github/lychee.toml --format json --output lychee_output_cm.json "16/umbraco-cms/**/*.md"`.
7. To export to Excel: 
```
$json = Get-Content lychee_output_cm.json | ConvertFrom-Json
function Flatten-Map($map, $statusType) {
$list = @()
foreach ($file in $map.PSObject.Properties.Name) {
foreach ($link in $map.$file) {
$list += [PSCustomObject]@{ …
```
=> Adding Lychee Config files

umbraco-cloud/begin-your-cloud-journey/project-features/secrets-management.md
Adding more information regarding the secret limits in the cloud portal.
Added more information under this page: https://docs.umbraco.com/umbraco-cloud/begin-your-cloud-journey/project-features/secrets-management
The information is about the max limit of the secrets being added. 
* [ x] Code blocks are correctly formatted.
* [x ] Sentences are short and clear (preferably under 25 words).
* [x ] Passive voice and first-person language (“we”, “I”) are avoided.
* [x ] Relevant pages are linked.
* [x ] All links work and point to the correct resources.
* [ x] Screenshots or diagrams are included if useful.
* [ x] Any code examples or instructions have …
=> Updating secret management page

16/umbraco-forms/editor/creating-a-form/conditional-logic.md
It wasnt possible to set a less than / greater than condition on a Date Picker field, as the default format is not a correct date.
I've updated the Conditions article to include steps on how to change the config of the Date Picker format so it's possible to use conditions again.
Task related to feedback from the GitBook feedback feature.
=> Update details on using conditions with Forms DatePicker

15/umbraco-commerce/release-notes/README.md, 16/umbraco-commerce/release-notes/README.md
Umbraco Commerce 16.3.0 & 15.3.12 Release Notes
ASAP
=> Umbraco Commerce 16.3.0 & 15.3.12 Release Notes

16/umbraco-cms/reference/querying/umbracohelper.md
This PR fixes an error in the code sample: `GetDictionaryValue` => `GetDictionaryValueOrDefault`
N/A
Umbraco 16
ASAP
=> CMS: adds explanation for `GetDictionaryValueOrDefault`

16/umbraco-cms/extending/health-check/README.md
Adds info about the CSP health check to the [health check](https://docs.umbraco.com/umbraco-cms/extending/health-check) page.
The CSP check was added in 14.3, not sure how that works for the docs though.
=> Add Content Security Policy check to built in health check list

16/umbraco-cms/tutorials/starter-kit/install-the-starter-kit.md
Provide further details about the website error that is thrown the first time the app is run.
Following the conversation on the forum [here](https://forum.umbraco.com/t/umbraco-16-starter-kit-potential-improvement/5761) this PR adds details on how to fix the initial error that is thrown on the website the first time the app is run.
Umbraco version: 16.2.0
Umbraco The StarterKit: 16.0.0
=> Add details on how to fix the website error the first time the app is run

15/umbraco-cms/tutorials/multisite-setup.md, 16/umbraco-cms/tutorials/multisite-setup.md
Cleanup article with Vale/Grammarly
NA
Anytime
=> Cleanup Multisite setup tutorial

16/umbraco-cms/SUMMARY.md, 16/umbraco-cms/fundamentals/setup/upgrading/README.md, 16/umbraco-cms/fundamentals/setup/upgrading/downgrades-and-rerunning-migrations.md
Although downgrades and re-rerunning migrations aren't supported in Umbraco, there can be cases where they are safe, and a more advanced user can determine this and decide they want to proceed with it.
In those cases, it's useful to have documented how to do this and what the caveats are, that this PR provides.
CMS 
Anytime (though please wait for a CMS team member to review too).
=> Added support indication and how to for downgrades and re-running migrations

16/umbraco-engage/developers/personalization/implement-your-own-segment-parameters.md
=> Fixed broken links

umbraco-cloud/build-and-customize-your-solution/handle-deployments-and-environments/umbraco-cicd/README.md, umbraco-cloud/build-and-customize-your-solution/handle-deployments-and-environments/umbraco-cicd/troubleshooting.md, umbraco-cloud/build-and-customize-your-solution/handle-deployments-and-environments/umbraco-cicd/umbracocloudapi.md
additions to 
- CICD Troubleshooting
- CICD Api V2
Umbraco Cloud / CICD Flow
=> CICD Updates to Troubleshooting and API v2 Documentation

13/umbraco-deploy/release-notes.md, 16/umbraco-deploy/release-notes.md
Add Deploy 13.4.2, 16.0.2 and 16.0.3 release notes.
Deploy 13.4.2
Deploy 16.0.2 
Deploy 16.0.3
=> Add Deploy 13.4.2, 16.0.2 and 16.0.3 release notes

10/umbraco-cms/reference/configuration/maximumuploadsizesettings.md, 13/umbraco-cms/reference/configuration/maximumuploadsizesettings.md, 15/umbraco-cms/reference/configuration/maximumuploadsizesettings.md, 16/umbraco-cms/reference/configuration/maximumuploadsizesettings.md, 17/umbraco-cms/reference/configuration/maximumuploadsizesettings.md
Updated Kestrel's MaxRequestLength limit to 50MB.
Increases the  documented Kestrel MaxRequestLength to 50MB to match product behaviour.
https://github.com/umbraco/Umbraco-CMS/issues/20353
CMS 13+
Any time.
=> Increase documented Kestrel MaxRequestLength to 50MB to match product behaviour

16/umbraco-cms/customizing/extending-overview/extension-types/modals/confirm-dialog.md
Refine "Confirm Dialog" documentation: updated section title, added a new "Convenience Method" example using `umbConfirmModal`, and improved TypeScript example clarity.
https://github.com/umbraco/UmbracoDocs/issues/7320
v16
N/A
=> Confirm Dialog Addition
