umbraco/UmbracoDocs

11/umbraco-forms/editor/attaching-workflows/workflow-types.md

- specifically on the path and storing

Elaborated on storing of files

---

11/umbraco-forms/developer/rendering-scripts.md

readability improvements - rendering-scripts

---

.github/styles/UmbracoDocs/Acronyms.yml

Is 'FAQ' somthing we want to add to Acronyms.yml?

Add FAQ to Acronyms.yml

---

marketplace-and-integrations/integrations/zapier-with-umbraco-forms.md

readability improvements -zapier-with-umbraco-forms

---

10/umbraco-cms/fundamentals/backoffice/README.md

readability improvements - backoffice

---

10/umbraco-cms/fundamentals/setup/server-setup/permissions.md

readability improvements - permissions

---

10/umbraco-cms/implementation/default-routing/execute-request.md

readability improvements - execute-request

---

10/umbraco-cms/README.md

Readability improvements - umbraco cms

---

marketplace-and-integrations/integrations/dynamics.md
marketplace-and-integrations/integrations/google-search-console.md
marketplace-and-integrations/integrations/hubspot.md
marketplace-and-integrations/integrations/semrush.md
marketplace-and-integrations/integrations/shopify.md

Current PR contains the documentation regarding the configuration of different providers to work with OAuth self hosted.
- Shopify
- Semrush
- Hubspot
- Dynamics
- Google Search Console

OAuth self hosted apps documentation

---

10/umbraco-cms/reference/searching/examine/README.md

readability improvements - examine

---

10/umbraco-workflow/SUMMARY.md
10/umbraco-workflow/getting-started/configuration.md
10/umbraco-workflow/release-notes.md
10/umbraco-workflow/workflow-section/workflow-settings.md
11/umbraco-workflow/SUMMARY.md
11/umbraco-workflow/getting-started/configuration.md
11/umbraco-workflow/release-notes.md
11/umbraco-workflow/workflow-section/workflow-settings.md

Adds doco for new configuration options in 10.1.2 and 11.1.2
Adds release notes for versions 10.1.0 and 11.1.0 through to current
**Release:** April 18th

Workflow 10.1.2 updates

---

10/umbraco-forms/developer/rendering-scripts.md
11/umbraco-forms/developer/rendering-scripts.md

Readability improvements - rendering scripts

---

11/umbraco-forms/developer/extending/customize-default-workflows.md

readability improvements - customize-default-workflows

---

marketplace-and-integrations/integrations/zapier.md

readability improvements - zapier

---

10/umbraco-cms/tutorials/creating-a-basic-website/css-and-images.md

readability improvements - css-and-images

---

umbraco-cloud/security.md

I ran into this this week. I was rather new to cloud and didn't know Cloudflare was used. I read the headlines and thought, oh, I dont have cloudflare, I need the second solution.
Oh boy, I was wrong :-)
After debugging, rechecking, I finally got notified on  the above part by Sebastiaan. I totally overlooked it.
I'm hoping it's a bit clearer for newer people like this.

umbraco-cloud/security: Tried to make it more clear what solution you need for your project

---

generic/contribute/getting-started.md

Think I stumbled upon a spelling mistake or phrasing. Just an idea of what it could say instead 😀

Spellingmistake / misphrase?

---

11/umbraco-cms/fundamentals/setup/install/install-umbraco-with-templates.md

After running the command, and running Umbraco by default is sql lite selected.

Incorrect information

---

new-backoffice/README.md

Was browsing the docs and found this.
It's just a suggestion as to what it could say instead 😁

Spelling mistake / misphrased?

---

umbraco-cloud/getting-started/git-repository-in-a-cloud-project.md

On the  "A source control repository with your own code"

Added link for Gitlab on how to setup it up

---

umbraco-cloud/getting-started/git-repository-in-a-cloud-project.md

Release pipelines is for Azure Devops :)

Changed info text about Gitlab

---

umbraco-cloud/product-upgrades/version-specific-upgrades/migrate-from-8-to-latest.md

Changed https://docs.umbraco.com/umbraco-deploy/deploy-settings to https://docs.umbraco.com/umbraco-deploy/deploy-settings#allowmembersdeploymentoperations-and-transfermembergroupsascontent

link seems to be wrong

---

11/umbraco-cms/reference/cache/application-cache.md

It's not super clear on this page how you need to store and retrieve values from the cache, so I extended the example a little bit with a usecase 🙂

Update cache example with an example of using the cache

---

10/umbraco-cms/reference/configuration/contentsettings.md
10/umbraco-cms/reference/configuration/securitysettings.md
11/umbraco-cms/reference/configuration/contentsettings.md
11/umbraco-cms/reference/configuration/securitysettings.md

Fixes https://github.com/umbraco/UmbracoDocs/issues/5129
- Moves AllowEditInvariantFromNonDefault from Security Settings to Content settings

Move AllowEditInvariantFromNonDefault from security settings to content settings

---

12/umbraco-cms/tutorials/getting-started-with-entity-framework-core.md

While going through the tutorial I noticed that the included snippets didn't work, so I've made some changes here to remedy that. 
* Changed the migration snippet to not run in a scope, running ef core migrations in a scope is not allowed
* I also changed the handler to be async so we can await the migrations
* Changed the controller snippet 
* Refactored the namespace to be consistent with other examples
* Updated `GetComments` to properly take in `Guid umbracoNodeKey`, since `BlockPostUmbracoKey` is a guid
* Most importantly, I added `.ToArray();` to the `GetComments` endpoint, this is actually quite important in order to force the Linq query to actually execute, otherwise it won't happen til after the scope is completed and the DB context is disposed, leading to an error

V12: Fix EF Core tutorial code snippets

---

12/umbraco-cms/test-the-release-candidate.md

add a 1 to the package name (rc1) 
the released - "release candidate" is `12.0.0-rc1`  - docs missing the 1

Update test-the-release-candidate.md - RC1

---

11/umbraco-cms/reference/routing/request-pipeline/outbound-pipeline.md

Made the code sample return `null` and added an explanation on the sequence of execution.
Solves tickets #4265 and #5073

Added explanation on return value of GetUrl

---

12/umbraco-cms/tutorials/getting-started-with-entity-framework-core.md

I am back once again, this time after a QoL PR 🕵️ 
- Should only updated when https://github.com/umbraco/Umbraco-CMS/pull/14278 is merged

Update EFCore tutorial to mention regristration step

---

11/umbraco-cms/implementation/integration-testing.md

Added corrected instructions on how to add the appsettings for integration tests.

minor correction to the process

---

10/umbraco-forms/release-notes.md
11/umbraco-forms/release-notes.md
12/umbraco-forms/release-notes.md

This PR adds the release notes for the upcoming patches, due out Tuesday 30th June. // @sofietoft

Added release notes for Forms 8.13.9, 10.3.3 and 11.1.3.

---

10/umbraco-workflow/release-notes.md
11/umbraco-workflow/release-notes.md

Will finalise when release date is confirmed.

Workflow x.2.1 release notes update

---

10/umbraco-cms/extending/content-apps.md

In addition to https://github.com/umbraco/UmbracoDocs/pull/5205/files update the v10 version as well. Excuse my mistake this could have been done in 1 PR. 
Umbraco CMS - v10

Add 'class'

---

10/umbraco-cms/fundamentals/setup/install/README.md
10/umbraco-cms/fundamentals/setup/install/install-umbraco-with-templates.md
10/umbraco-cms/tutorials/creating-and-distributing-a-package.md
11/umbraco-cms/fundamentals/setup/install/installing-nightly-builds.md
11/umbraco-cms/tutorials/creating-and-distributing-a-package.md

updated examples to hold new code for installing using .net cli

---

10/umbraco-forms/SUMMARY.md
11/umbraco-forms/SUMMARY.md

Amended a title in the summary page such that it better describes the contents of the page.
Forms 10, 11, 12

Updated a title for an expanded feature.

---

11/umbraco-cms/reference/configuration/richtexteditorsettings.md

Add missing description on richtexteditorsettings.md

---

11/umbraco-cms/reference/templating/README.md

Add missing description to README.md

---

umbraco-cloud/security.md

I added a C# example to set HSTS headers to compliment the XML suggestion
https://docs.umbraco.com/umbraco-cloud/security

Update security.md with a C# HSTS example

---

10/umbraco-cms/reference/configuration/datatypes.md

Small readability improvements. Change data type to Data Type
v 10

Change data type to Data Type

---

11/umbraco-cms/extending/property-editors/property-actions.md

Surely this is supposed to be actions

---

11/umbraco-cms/reference/cache/examples/tags.md

A small comment update to the wording (typo in 'graps')
Umbraco 10+

Update tags.md wording

---

11/umbraco-cms/reference/notifications/README.md

Updated notifications documentation grammar and description
Latest Umbraco

Update Notifications documentation README.md

---

.github/styles/UmbracoDocs/Acronyms.yml
10/umbraco-cms/reference/configuration/imagingsettings.md

Remove 'very'. 
There is also an error related to using the CPU abbreviation, but is this something to add to the acronyms list?

readability improvements - imagingsettings

---

umbraco-cloud/product-upgrades/manual-upgrades/README.md

testing stuff

---

12/umbraco-forms/developer/extending/adding-a-fieldtype.md
12/umbraco-forms/installation/version-specific.md

_Made some further updates reflecting the last changes to Umbraco Forms 12_
Forms 12
_Can go live at any time._

Further docs updates for Forms 12.

---

10/umbraco-cms/reference/management/README.md
11/umbraco-cms/reference/management/README.md

Readability Improvements management readme
v10 & v11

Readability improvements management readme

---

marketplace-and-integrations/README.md
marketplace-and-integrations/SUMMARY.md

_Re-ordered the headings/sections within the DXP space, to avoid the new "authorized services" package getting lost under all the integrations._
n/a
_Any time that is convenient,_

Re-ordered DXP navigation

---

10/umbraco-cms/extending/section-trees/trees/README.md
11/umbraco-cms/extending/section-trees/trees/README.md

Add namespace to code sample.
v10 and v11

Add namespace 

---

12/umbraco-cms/extending/section-trees/trees/README.md

In addition to https://github.com/umbraco/UmbracoDocs/pull/5266 add namaspace to code sample for v12.

Add namespace to trees v12

---

10/umbraco-cms/extending/backoffice-tours.md
11/umbraco-cms/extending/backoffice-tours.md

In addition to https://github.com/umbraco/UmbracoDocs/pull/5279, update the backoffice tours for v10 and v11 as well. 
v10 and v11

Improve backoffice tours 11 and 10

---

11/umbraco-cms/fundamentals/backoffice/README.md
12/umbraco-cms/fundamentals/backoffice/README.md

Improve the fundamentals/backoffice article.

Improve fundamentals backoffice 

---

11/umbraco-cms/extending/packages/good-practice-and-defaults.md

This PR is a remake of https://github.com/umbraco/UmbracoDocs/pull/3829.
I resolved some long sentences and fixed a few formatting things as well.
@ronaldbarendse , @KevinJump - let me know if you still think this is ready to merge.

Good Practice docs for Package development

---

12/umbraco-cms/reference/cache/application-cache.md

Readability improvements for the application cache article.
v12

Improve application cache

---

10/umbraco-cms/implementation/unit-testing.md
11/umbraco-cms/implementation/unit-testing.md
12/umbraco-cms/implementation/unit-testing.md

Readability improvements for unit testing articl. 
v10, v11 & v12

Update unit testing article

---

10/umbraco-cms/reference/cache/application-cache.md
11/umbraco-cms/reference/cache/application-cache.md

In addition to https://github.com/umbraco/UmbracoDocs/pull/5287 update the v10 & v11 versions as well.
v10 and v11

Update application cache

---

10/umbraco-cms/reference/configuration/keepalivesettings.md
11/umbraco-cms/reference/configuration/keepalivesettings.md
12/umbraco-cms/reference/configuration/keepalivesettings.md

Update keep alive settings. 
v10, 11 and 12

Update keep alive settings

---

10/umbraco-cms/reference/management/services/domainservice.md
11/umbraco-cms/reference/management/services/domainservice.md

The DomainService docs were showing code that isn't working in U10+ anymore.

Update domainservice docs

---

12/umbraco-cms/reference/content-delivery-api/README.md

Recommend for Umbraco Cloud hosting

Link Secrets management documentation

---

marketplace-and-integrations/packages/authorized-services.md

Added details of configuration amends associated with an upcoming release of Umbraco.AuthorizedServices.
Umbraco.AuthorizedServices 0.2.0
Can be reviewed and published any time on or after 19th July.  No problem if it's a few days after this date.

Added details of configuration amends associated with 0.2.0 release.

---

10/umbraco-cms/reference/configuration/serilog.md
11/umbraco-cms/reference/configuration/serilog.md
12/umbraco-cms/reference/configuration/serilog.md

Update serilog article. 
v10, 11 & 12.

Update serilog article

---

10/umbraco-forms/release-notes.md
11/umbraco-forms/release-notes.md
12/umbraco-forms/release-notes.md

Added release notes for Forms 8.13.10.
Forms 8.13.10
Any time before or on 25th July if possible please.

Added release notes for Forms 8.13.10.

---

10/umbraco-deploy/release-notes.md
11/umbraco-deploy/release-notes.md
12/umbraco-deploy/deploy-settings.md
12/umbraco-deploy/release-notes.md

Added release notes for Deploy 4.8.2/10.2.3/11.1.3/12.0.1.
Deploy 4.8.2/10.2.3/11.1.3/12.0.1
Any time before or on 25th July if possible please.

Added release notes and configuration updates for Deploy releases 4.8.2/10.2.3/11.1.3/12.0.1

---

generic/contribute/code-samples.md

Add 'Use File Scoped Namespaces' to the code-samples article in the cotribute folder as suggested in https://github.com/umbraco/UmbracoDocs/issues/5260#issuecomment-1647487697
This PR belongs to https://github.com/umbraco/UmbracoDocs/issues/5260

Add 'Use File Scoped Namespaces'

---

marketplace-and-integrations/marketplace/listing-your-package.md

Added instruction for listing Marketplace related packages in groups.
Umbraco Marketplace
Can be reviewed and go live anytime from tomorrow.

Added instruction for listing Marketplace related packages in groups.

---

10/umbraco-cms/fundamentals/design/partial-views.md

Updated code format as per style guide

updated code format

---

10/umbraco-workflow/release-notes.md
11/umbraco-workflow/release-notes.md
12/umbraco-workflow/release-notes.md

Hey docs legends, I've added release notes for the latest Workflow patches (10.2.3, 11.2.3 and 12.0.1).

release notes for 10.2.3, 11.2.3 and 12.0.1 patches

---

11/umbraco-cms/reference/templating/macros/README.md

Missing description on macros page README.md

---

commerce-add-ons/payment-providers/nets/configuring-nets.md
commerce-add-ons/payment-providers/paypal/configuring-paypal.md
commerce-add-ons/payment-providers/stripe/configuring-stripe.md

Looks like we had the wrong callback URL set so updated to be correct

Fixed wrong webhook URL

---

10/umbraco-forms/developer/themes.md
11/umbraco-forms/developer/themes.md
12/umbraco-forms/developer/themes.md

Added clarification on version to download for Umbraco Forms theme files to make the confusion discussed under https://github.com/umbraco/Umbraco.Forms.Issues/issues/1057 less likely.
Umbraco Forms 10+

Added clarification on version to download for Umbraco Forms theme files.

---

12/umbraco-cms/tutorials/add-google-authentication.md

Updated the code examples in the article concerning external login to reflect the latest interfaces as tested with Umbraco 12. These changes are needed to make the examples work.
12+

Update code examples for external authentication

---

12/umbraco-cms/reference/security/two-factor-authentication.md

Update code example based on API changes in V12
12+

docs: fix code example for configuring a twofactor provider

---

umbraco-cloud/deployment/deploy-dashboard.md

Added the deploy dashboard (Back again)

---

10/umbraco-cms/tutorials/creating-a-property-editor/part-4.md
11/umbraco-cms/tutorials/creating-a-property-editor/part-4.md
12/umbraco-cms/tutorials/creating-a-property-editor/part-4.md

umbraco-cms/tutorials/creating-a-property-editor/part-4 for 10/11/12

Using clauses updated

---

new-backoffice/extending/development-flow.md

This update contains a small amount of rewording to improve the readability of the Development Flow help page.

Updating Development Flow docs for Bellisimo to improve readabilty

---

10/umbraco-forms/release-notes.md
11/umbraco-forms/release-notes.md
12/umbraco-forms/release-notes.md

Added release notes for Forms 10.5 and 12.1.
Forms 10.5 and 12.1
To go live on Thursday 17th August please.

Release notes for Forms 10.5 and 12.1.

---

umbraco-cloud/getting-started/migrate-existing-site/README.md

Adding a couple of new bulletpoints after going through this process myself recently.  Also reworded one part as I found it confusing to understand and hopefully this makes it a bit clearer.
Made a small change to a sentence as I found it hard to understand and the v8 version was clearer. 
Added a couple of new bulletpoints to the migration steps as I did this recently and had to do the additional steps. These steps are more relavent if migrating because you're likely to have additional code and packages, unlike the demo where it's a clean Umbraco setup.

Update Migrating existing site readme

---

10/umbraco-cms/legacy-documentation/README.md
11/umbraco-cms/legacy-documentation/README.md
12/umbraco-cms/legacy-documentation/README.md

Update the legacy-documentation article:
v10

Update legacy-documentation 

---

10/umbraco-deploy/getting-started/cicd-pipeline/ci-cd-azure-dev-ops.md
11/umbraco-deploy/getting-started/cicd-pipeline/ci-cd-azure-dev-ops.md
12/umbraco-deploy/getting-started/cicd-pipeline/ci-cd-azure-dev-ops.md

Update the ci/cd azure devops aricle: 
v10, 11 & 12

Update ci cd azure dev ops

---

10/umbraco-cms/fundamentals/data/members.md
11/umbraco-cms/fundamentals/data/members.md
12/umbraco-cms/fundamentals/data/members.md

the more information section text towards data types does not make sense for the members sections to be there
removed "more information" section
CMS

updated members docs

---

umbraco-cloud/frequently-asked-questions.md

Updated the Cloud FAQs section to clarify, refresh and augment the content around whether a package works on Cloud and what steps the package developer can take to support transfer of information between environments.
Umbraco Cloud
@BoletteKern and @PratheesUmbraco should take a look to see if they have any comments too please.

Updated Cloud FAQs for package support.

---

10/umbraco-deploy/upgrades/version-specific.md
11/umbraco-deploy/upgrades/version-specific.md
12/umbraco-deploy/upgrades/version-specific.md

Update the Umbraco deploy upgrade version-specific article: 
v10, 11 & 12

Update version specific (Umbraco Deploy)

---

new-backoffice/extending/development-flow.md
new-backoffice/tutorials/creating-a-custom-dashboard.md
new-backoffice/tutorials/creating-your-first-extension.md

Made some minor adjustments to the guide on how to get started with the new backoffice. 
Some more info here: https://github.com/umbraco/Umbraco.CMS.Backoffice/discussions/831
New Umbraco Backoffice (Bellissima)

Minor adjustments to new backoffice getting started

---

commerce-add-ons/changelog-archive/mollie.md

Update mollie article:
Commerce

Update mollie article

---

commerce-add-ons/changelog-archive/stripe.md

Update stripe.md: 
Umbraco Commerce

Define acronym: SDK in stripe.md

---

new-backoffice/extending/development-flow.md

Update the development flow article:

Update development flow

---

new-backoffice/getting-started/getting-started-with-the-new-backoffice/README.md

Update the new backoffice getting started readme:
The new Backoffice

Update the new backoffice getting started readme

---

new-backoffice/tutorials/creating-a-custom-dashboard/adding-functionality-to-the-dashboard.md

Update 'Adding functionality to the dashboard':

Adding functionality to the dashboard (the new backoffice)

---

10/umbraco-forms/developer/extending/adding-a-magic-string-format-function.md
11/umbraco-forms/developer/extending/adding-a-magic-string-format-function.md
12/umbraco-forms/developer/extending/adding-a-magic-string-format-function.md

We're missing a pipe here to correctly render the value via the formatter function

Update magic string format syntax

---

10/umbraco-ui-builder/SUMMARY.md
10/umbraco-ui-builder/miscellaneous/umbraco-ui-builder-vs-ui-o-matic.md

updating broken link for ui bilder docs 
correcting the link to an article on UI builder docs
UI Builder
anytime

resolving broken link for ui builder docs

---

new-backoffice/README.md

Update the new backoffice readme:

Update the new backoffice readme

---

new-backoffice/tutorials/creating-a-property-editor.md

Update creating a property editor:

Update creating a property editor the new backoffice

---

10/umbraco-cms/reference/configuration/typefindersettings.md
11/umbraco-cms/reference/configuration/typefindersettings.md

Same as https://github.com/umbraco/UmbracoDocs/pull/5365 juts for v10 and v11
Release date: Thursday, September 7 2023

Add AdditionalAssemblyExclusionEntries to TypeFinderSettings (V10 and V11)

---

12/umbraco-cms/SUMMARY.md
12/umbraco-cms/reference/content-delivery-api/media-delivery-api.md

🛑 **Don't merge this into main until 12.2 RC is out - at the earliest** 🛑 
V12.2 features a new Media Delivery API. These are the accompanying docs.
V12.2
Ideally on September 7 when the V12.2 RC is out.

Add docs for the upcoming Media Delivery API (12.2)

---

new-backoffice/tutorials/creating-your-first-extension.md

Update creating your first extension:

Update creating your first extension (the new backoffice)

---

new-backoffice/tutorials/creating-a-custom-dashboard.md

Update creating a custom dashboard:

Update creating a custom dashboard (the new backoffice)

---

new-backoffice/getting-started/getting-started-with-the-new-backoffice/alpha-release.md

Update alpha release - the new backoffice 

---

new-backoffice/extending/localization/ui-localization.md

Update UI localization - the new backoffice

---

10/umbraco-commerce/how-to-guides/migrate-from-vendr-to-umbraco-commerce/README.md

I think this is a typo in the docs. I'm guessing the correct interface name.

Update Migrate from Vendr to Umbraco Commerce README.md

---

marketplace-and-integrations/README.md
marketplace-and-integrations/packages/authorized-services.md

Fixed a few typos/repeated words.
DXP area
Any time.

Fixed typos

---

umbraco-cloud/getting-started/migrate-existing-site/README.md

Corrected path of folders to delete during clean-up (logs folder is not in /umbraco/data/umbraco/logs)

Corrected path of folders to delete

---

10/umbraco-commerce/SUMMARY.md
10/umbraco-commerce/getting-started/installation/README.md
10/umbraco-commerce/getting-started/installation/version-specific-upgrades.md
10/umbraco-commerce/release-notes.md
10/umbraco-ui-builder/release-notes.md
12/umbraco-commerce/SUMMARY.md
12/umbraco-commerce/getting-started/installation/README.md
12/umbraco-commerce/getting-started/installation/version-specific-upgrades.md
12/umbraco-commerce/release-notes.md
commerce-add-ons/packages/SUMMARY.md
commerce-add-ons/packages/checkout/release-notes.md
commerce-add-ons/packages/deploy/release-notes.md
commerce-add-ons/payment-providers/SUMMARY.md
commerce-add-ons/payment-providers/klarna/release-notes.md
commerce-add-ons/payment-providers/mollie/release-notes.md
commerce-add-ons/payment-providers/nets/release-notes.md
commerce-add-ons/payment-providers/opayo/release-notes.md
commerce-add-ons/payment-providers/paypal/release-notes.md
commerce-add-ons/payment-providers/quickpay/release-notes.md
commerce-add-ons/payment-providers/stripe/release-notes.md

Adding release notes for commerce, commerce packages and payment providers + updating the UI builder release notes file
Adding release notes pages 
Umbraco Commerce, Commerce Payment Providers, Commerce Packages + Ui Builder
no specific date
anytime

Adding release notes for commerce, commerce packages and payment provider

---

new-backoffice/extending/customize-the-editing-experience.md

Update customize the editing experience:

Update customize the editing experience

---

commerce-add-ons/packages/checkout/release-notes.md

Add release note details for Umbraco Commerce Checkout 10.0.1

Umbraco Commerce Checkout 10.0.1 release notes

---

commerce-add-ons/packages/README.md
commerce-add-ons/packages/checkout/README.md
commerce-add-ons/packages/deploy/README.md
commerce-add-ons/packages/deploy/release-notes.md
commerce-add-ons/payment-providers/README.md
commerce-add-ons/payment-providers/SUMMARY.md
commerce-add-ons/payment-providers/install-payment-providers.md
commerce-add-ons/payment-providers/invoicing/README.md
commerce-add-ons/payment-providers/klarna/README.md
commerce-add-ons/payment-providers/mollie/README.md
commerce-add-ons/payment-providers/nets/README.md
commerce-add-ons/payment-providers/opayo/README.md
commerce-add-ons/payment-providers/paypal/README.md
commerce-add-ons/payment-providers/quickpay/README.md
commerce-add-ons/payment-providers/stripe/README.md
commerce-add-ons/payment-providers/worldpay/README.md
commerce-add-ons/payment-providers/worldpay/release-notes.md

added articles starting pages for commerce payment providers opayo and worldpay
added new articles
umbraco payment providers
none
anytime

added articles starting pages for commerce payment providers opayo and worldpay

---

10/umbraco-forms/developer/extending/adding-a-magic-string-format-function.md
11/umbraco-forms/developer/extending/adding-a-magic-string-format-function.md
12/umbraco-forms/developer/extending/adding-a-magic-string-format-function.md

added note to magic strings as per PR #5364 
added note at the top of the magic strings page that "This builds on the "adding a type to the provider model " chapter." 
Umbraco Forms
no deadline
anytime

added note to magic strings as per PR#5364

---

10/umbraco-deploy/deploy-settings.md
10/umbraco-deploy/release-notes.md
10/umbraco-forms/release-notes.md
11/umbraco-deploy/deploy-settings.md
11/umbraco-deploy/release-notes.md
11/umbraco-forms/release-notes.md
12/umbraco-deploy/deploy-settings.md
12/umbraco-deploy/release-notes.md
12/umbraco-forms/release-notes.md

Added release notes for Deploy 4.8.3 10.2.4 11.1.4 and 12.0.2
Deploy 4.8.3 10.2.4 11.1.4 and 12.0.2
Tomorrow if possible please.

Release notes for Deploy 4.8.3 10.2.4 11.1.4 and 12.0.2

---

new-backoffice/fundamentals/setup/alpha-release.md

Update alpha-release - the new backoffice

---

10/umbraco-forms/developer/themes.md
11/umbraco-forms/developer/themes.md
12/umbraco-forms/developer/themes.md

Updated the associated version numbers for the latest default theme details to match the latest Forms releases.
Forms 10.5.1 and 12.1.1
As soon as is possible please.

Updated default theme details for latest Forms releases.

---

marketplace-and-integrations/integrations/activecampaign-with-umbraco-forms.md

Fix definition of CRM 
Integrations

Update activecampaign with umbraco forms

---

new-backoffice/extending/sections-and-trees/trees/searchable-trees-isearchabletree.md

Change `jsx` to `cshap` in code samples.

Change jsx to csharp

---

new-backoffice/extending/dashboards.md
new-backoffice/extending/sections-and-trees/sections.md
new-backoffice/extending/sections-and-trees/trees/tree-actions.md

Fix code blocks in several articles:

Fix several code blocks

---

new-backoffice/extending/dashboards.md
new-backoffice/extending/sections-and-trees/sections.md
new-backoffice/extending/sections-and-trees/trees/tree-actions.md

Reverts umbraco/UmbracoDocs#5437 due to a merge conflict in Gitbook

Revert "Fix several code blocks"

---

umbraco-cloud/getting-started/migrate-existing-site/README.md

Added a new line to make sure people don't delete the umbracoDeploy.lic file - which I did by mistake!

[AMEND] Update Getting Started Page

---

new-backoffice/tutorials/creating-a-property-editor/README.md
new-backoffice/tutorials/creating-a-property-editor/adding-configuration-to-a-property-editor.md
new-backoffice/tutorials/creating-a-property-editor/integrating-services-with-a-property-editor.md

The PR updates the first part of creating a property editor for the new backoffice with best practices for naming.

New Backoffice: Create First Property Editor - code updates to follow best practices

---

10/umbraco-cms/SUMMARY.md
10/umbraco-cms/reference/security/serverside-file-validation.md
11/umbraco-cms/SUMMARY.md
11/umbraco-cms/reference/security/serverside-file-validation.md
12/umbraco-cms/SUMMARY.md
12/umbraco-cms/reference/security/serverside-file-validation.md

Added docs for the new FileStreamSecurityValidator in all affected versions.
CMS v10 and upwards
Should be published together wit the release that contains this PR
https://github.com/umbraco/Umbraco-CMS/pull/14657, minimum version numbers need to be updated before publishing

Added documentation for the new FileStreamSecurityValidator

---

new-backoffice/tutorials/creating-your-first-extension.md

Update  Creating your first extension:

Update: Creating your first extension - The new backoffice

---

new-backoffice/extending/development-flow/README.md

During development of a package, intellisense wasn't working. I've added a reference to a plugin for Visual Studio that enables it.

Add reference to Lit-Plugin for intellisense

---

new-backoffice/extending/development-flow/vite-package-setup.md

Added and highlighted some useful information in regards to Vite configuration with the new backoffice at https://docs.umbraco.com/umbraco-backoffice/extending/development-flow/vite-package-setup
Umbraco v14
N/A

Add more information on the Vite Package Setup guide

---

new-backoffice/tutorials/creating-a-custom-dashboard/extending-the-dashboard-using-umbraco-ui-library.md

Update extending-the-dashboard-using-umbraco-ui-library:
Or is this something we want to add to the list of acronyms?
extending-the-dashboard-using-umbraco-ui-library

Update extending-the-dashboard-using-umbraco-ui-library - the new backoffice

---

marketplace-and-integrations/integrations/aprimo.md

Update aprimo.md:
Marketplace integrations

Define DAM in the correct way

---

10/umbraco-cms/reference/security/serverside-file-validation.md
11/umbraco-cms/reference/security/serverside-file-validation.md
12/umbraco-cms/reference/security/serverside-file-validation.md

Updated the serverside-file-validation code examples to fit the interface and also added an example of the dependency injection.
The code examples (SvgXssSecurityAnalyzer class) and added an example of how to register it with a composer.
Umbraco CMS version 10, 11 and 12.
To be decided

Updated the serverside-file-validation code examples

---

10/umbraco-ui-builder/SUMMARY.md
10/umbraco-ui-builder/getting-started/installation.md
10/umbraco-ui-builder/getting-started/upgrading/README.md
10/umbraco-ui-builder/getting-started/upgrading/version-specific-upgrades.md
10/umbraco-ui-builder/guides/migrating-from-konstrukt-to-umbraco-ui-builder.md

Add a migration guide and upgrade steps inline with the commerce docs

UI builder migration guide & upgrade steps

---

umbraco-cloud/databases/cloud-database.md

Update: Cloud database: 
Umbraco cloud

Update: Cloud database

---

10/umbraco-deploy/release-notes.md
11/umbraco-deploy/release-notes.md
12/umbraco-deploy/release-notes.md

Added release notes for Umbraco Deploy.
Deploy 4.8.4, 10.2.5, 11.1.5, 12.0.3
As soon as is convenient please.

Added release notes for Deploy 4.8.4, 10.2.5, 11.1.5, 12.0.3.

---

umbraco-cloud/SUMMARY.md

removed article from summary file

---

umbraco-cloud/set-up/set-up.md

Remove unintended line in Umbraco Cloud set-up article
Umbraco Cloud

Remove unintended line in Umbraco Cloud set-up article

---

new-backoffice/getting-started/installing-preview-builds/README.md

Added code example for changing directory to the getting started example.
new backoffice preview build installation
Any time, this is for the new backoffice preview installation documentation.

add change directory example

---

new-backoffice/tutorials/creating-a-custom-dashboard/adding-functionality-to-the-dashboard.md

clearer description of where to add the code example to the welcome dashboard. added a note for reference to help find example.
Updated the documentation to be more specific as to where to put the code example in the welcome dashboard. Also added a note to reference the example for help.
New backoffice documentation
Anytime, new backoffice documentation.

update adding functionality documentation

---

10/umbraco-cms/extending/health-check/README.md
11/umbraco-cms/extending/health-check/README.md
12/umbraco-cms/extending/health-check/README.md

Really small update to just add abbreviations for MIME and SMTP for the v10, v11 and v12 docs

[AMEND] Add abbreviations for MIME and SMTP

---

umbraco-heartcore/api-documentation/content-management/content/README.md

Update Umbraco Heartcore api-documentation content-management content

---

umbraco-heartcore/api-documentation/content-management/language.md

Update content management language:
Umbraco heartcore

Update content management language

---

umbraco-heartcore/getting-started/the-umbraco-backoffice.md

Update the umbraco backoffice article:

Update the umbraco backoffice article (Umbraco Heartcore)

---

12/umbraco-workflow/licensing.md

I added some further detail about licensing workflow in [this PR](https://github.com/umbraco/UmbracoDocs/pull/5482), but realise I omitted updating the page for Workflow 12.  So that's in this update.
Workflow 12.

Applied updates to licensing page for Workflow to 12.

---

marketplace-and-integrations/packages/authorized-services.md

This adds a new configuration example to show how to authenticate with Meetup.com GraphQL based API that uses an oAuth flow.
Umbraco Authorized Services

Add Meetup Config for Umbraco Authorized Services

---

umbraco-heartcore/getting-started/webhooks.md

Update webhooks Umbraco Heartcore

---

10/umbraco-deploy/release-notes.md
11/umbraco-deploy/release-notes.md
12/umbraco-deploy/release-notes.md

Added release notes for Deploy 10.2.6, 11.1.6 and 12.0.4.
Deploy 10.2.6, 11.1.6 and 12.0.4.
Can go live at any time, ideally before the end of Monday 16th October please.

Added release notes for Deploy 10.2.6, 11.1.6 and 12.0.4.

---

umbraco-heartcore/client-libraries/dot-net-console.md

Update dot-net-console -  Umbraco Heartcore

---

10/umbraco-deploy/release-notes.md
11/umbraco-deploy/release-notes.md
12/umbraco-deploy/release-notes.md

Added further release notes for Deploy 10.2.6, 11.1.6 and 12.0.4
This is an addition to the already merged PR https://github.com/umbraco/UmbracoDocs/pull/5506
Deploy 10.2.6, 11.1.6 and 12.0.4
To publish on Monday if possible please.

Further release notes for Deploy 10.2.6, 11.1.6 and 12.0.4

---

generic/README.md

Update generic readme

---

10/umbraco-cms/tutorials/creating-a-basic-website/article-parent-and-article-items.md
11/umbraco-cms/tutorials/creating-a-basic-website/article-parent-and-article-items.md
12/umbraco-cms/tutorials/creating-a-basic-website/article-parent-and-article-items.md

updating aticles and article items steps with the correct document type name as per issues [5510](https://github.com/umbraco/UmbracoDocs/issues/5510)
CMS v10,11,12
anytime
anytime

updating aticles and article items steps

---

10/umbraco-cms/fundamentals/setup/install/install-umbraco-with-templates.md
11/umbraco-cms/fundamentals/setup/install/install-umbraco-with-templates.md
12/umbraco-cms/fundamentals/setup/install/install-umbraco-with-templates.md

Added some missing line breaks

Added missing line breaks

---

commerce-add-ons/payment-providers/klarna/configuring-umbraco.md

Update klarna --> configure Umbraco

---

10/umbraco-cms/fundamentals/setup/upgrading/version-specific/upgrade-from-8-to-latest.md
11/umbraco-cms/fundamentals/setup/upgrading/version-specific/upgrade-from-8-to-latest.md
12/umbraco-cms/fundamentals/setup/upgrading/version-specific/upgrade-from-8-to-latest.md

_Umrbaco_ also known as **Umbraco** 😎
We all know _Marco_ and _Jason_ 😅

Fix typo in Umbraco

---

10/umbraco-cms/fundamentals/setup/requirements.md
11/umbraco-cms/fundamentals/setup/requirements.md
12/umbraco-cms/fundamentals/setup/requirements.md

Requirements page with links to Microsoft-supported versions (as Windows 2012 is currently EOL and we follow the Microsoft version release cadence)
CMS v10,11,12
asap
anytime

updated cms and hosting requirements

---

umbraco-cloud/databases/local-database.md

Specifies where the sqlite file will be
* [ ✅ ] New content

Specifies where a sqlite database can be found in Cloud projects

---

new-backoffice/extending/context-api/variant-context.md

Update variant context

---

10/umbraco-cms/implementation/unit-testing.md
11/umbraco-cms/implementation/unit-testing.md
12/umbraco-cms/implementation/unit-testing.md

Updated unit testing docs to include multiple versions. This should help with SEO results, and clarity when reviewing the docs. 
v10, v11 and v12. 

Updated unit testing docs to include multiple versions

---

new-backoffice/extending/extension-types/workspaces/workspace-context.md

Update workspace context

---

10/umbraco-commerce/release-notes.md
12/umbraco-commerce/release-notes.md
commerce-add-ons/packages/checkout/release-notes.md
commerce-add-ons/packages/deploy/release-notes.md

Draft release nodes for
* Umbraco Commerce
* Umbraco Commerce Deploy
* Umbraco Commerce Checkout

Various release notes

---

umbraco-cloud/set-up/project-settings/umbraco-cicd/SampleCiCdPipeline.md

CICD Flow git packaging options with included files
Umbraco Cloud CICD Flow

CICD Flow git packaging

---

10/umbraco-commerce/key-concepts/pipelines.md
12/umbraco-commerce/key-concepts/pipelines.md

Fixed #5534
Updated outdated content
10, 12

Replace SendSmtpEmail with RaiseSendingEventTask

---

new-backoffice/extending/extension-types/store.md

Update store - the new backoffice

---

12/umbraco-cms/implementation/composing.md

I have added more items to the Collections table for the composing page. As it shows what other collections can be added to, amended etc

Updates to Composing: Collections Table 

---

new-backoffice/extending/localization/.net-localization.md

Update .net localization - the new backoffice:

Update .net localization - the new backoffice

---

new-backoffice/extending/umbraco-element/controllers/README.md

Update Umbraco Element Controllers:

Update Umbraco Element Controllers - The new backoffice

---

10/umbraco-cms/reference/searching/examine/indexing.md
10/umbraco-deploy/deployment-workflow/deploy-dashboard.md
11/umbraco-cms/reference/searching/examine/indexing.md
11/umbraco-deploy/deployment-workflow/deploy-dashboard.md
12/umbraco-cms/reference/searching/examine/indexing.md
12/umbraco-deploy/deployment-workflow/deploy-dashboard.md
commerce-add-ons/payment-providers/quickpay/README.md
umbraco-cloud/deployment/deploy-dashboard.md
umbraco-cloud/product-upgrades/manual-upgrades/README.md

Updated some of the broken links with correct links for user readability. Part of #5546 

Updating the broken Links

---

10/umbraco-cms/tutorials/creating-a-basic-website/article-parent-and-article-items.md
11/umbraco-cms/tutorials/creating-a-basic-website/article-parent-and-article-items.md
12/umbraco-cms/tutorials/creating-a-basic-website/article-parent-and-article-items.md

Fixed a formatting issue in v10, 11 and 12 versions of /umbraco-cms/tutorials/creating-a-basic-website/article-parent-and-article-items

Markup issue #5554

---

10/umbraco-cms/tutorials/creating-a-basic-website/article-parent-and-article-items.md
11/umbraco-cms/tutorials/creating-a-basic-website/article-parent-and-article-items.md
12/umbraco-cms/tutorials/creating-a-basic-website/article-parent-and-article-items.md

Fixing for issue #5553 'Duplicated steps in "Articles and Article Items" 
v10,11 & 12
As fast as possible

Fixing for issue #5553 'Duplicated steps in "Articles and Article Items" 

---

11/umbraco-deploy/SUMMARY.md
11/umbraco-deploy/handling-cache-refresher-notifications.md
12/umbraco-deploy/SUMMARY.md
12/umbraco-deploy/handling-cache-refresher-notifications.md

ported over v10 articles to v11 and v12 for deploy

---

umbraco-cloud/product-upgrades/minor-upgrades.md

Update Minor upgrades:
Umbacro Cloud

Update: Minor upgrades

---

umbraco-cloud/product-upgrades/product-dependencies.md

Write shorter sentence
Update product-dependencies:
Umbraco Cloud

Update product-dependencies - Umbraco Cloud

---

umbraco-cloud/product-upgrades/README.md

Update product upgrades:
Umbraco Cloud

Update product upgrades - Umbraco Cloud

---

12/umbraco-cms/reference/content-delivery-api/extension-api-for-querying.md

Add details around filter operations: the options available when defining a custom filter and how they might be applied
Content Delivery API related content (so Umbraco v12+)

Update custom filter documentation in the extension-api-for-querying page

---

13/umbraco-cms/README.md

Updated 13.0.0-rc1 version number

Updated 13.0.0-rc1 version number

---

umbraco-cloud/deployment/deployment-webhook.md

https://docs.umbraco.com/umbraco-cloud/deployments/deployment-webhook#use-cases
I made an attempt to reword this section. For example the phrase "breaking change" isn't a bad thing. A breaking change could be a new feature that just needs to be republished to use the correct published content.
Umbraco
Hacktoberfest contribution - no rush
NA

Reworded Uses cases section deployment-webhook.md

---

umbraco-cloud/troubleshooting/troubleshooting-portal.md

Update troubleshooting-portal:
Umbraco Cloud

Update troubleshooting-portal - Umbraco Cloud

---

10/umbraco-commerce/key-concepts/ui-config-files.md
10/umbraco-commerce/release-notes.md
10/umbraco-ui-builder/release-notes.md
12/umbraco-commerce/key-concepts/ui-config-files.md
12/umbraco-commerce/release-notes.md
12/umbraco-ui-builder/release-notes.md

Changes to the release notes and docs sections of changes in upcoming patch releases

Umbraco Commerce & UI Builder patch release updates

---

new-backoffice/tutorials/creating-a-property-editor/README.md

Update creating a property editor - the new backoffice

---

umbraco-cloud/deployment/cloud-to-cloud.md

Update cloud-to-cloud - Umbraco cloud

---

13/umbraco-deploy/SUMMARY.md
13/umbraco-deploy/release-notes.md
13/umbraco-deploy/upgrades/version-specific.md
13/umbraco-forms/SUMMARY.md
13/umbraco-forms/editor/creating-a-form/fieldtypes/fileupload.md
13/umbraco-forms/installation/version-specific.md
13/umbraco-forms/release-notes.md

Added release notes, migration details and new features for Forms and Deploy 13 RC1.
Forms and Deploy 13 RC1
Looking to release these early next week, so if we can release the documentation alongside them that will be great.
Feel free to review what's there, but I'll keep it in draft as we'll likely add to it over the next few days.

Updates for Forms and Deploy 13 RC 1

---

umbraco-cloud/deployment/deploying-deletions.md

Update deploying deletions:
Umbraco Cloud

Update deploying deletions - Umbraco Cloud

---

commerce-add-ons/packages/checkout/release-notes.md

Replaced "Vendr" with "Umbraco Commerce"

Replace mention of Vendr

---

umbraco-cloud/set-up/project-settings/manage-hostnames/README.md

changed A and AAAA records to the new values and added more info
ASAP

changed A and AAAA records to the new values and added more info

---

umbraco-cloud/deployment/deployment-webhook.md

Update deployment webhook:
Umbraco Cloud

Update deployment webhook - Umbraco Cloud

---

umbraco-cloud/getting-started/baselines/break-baseline.md

Update break baseline:
Umbraco Cloud

Update break baseline - Umbraco Cloud

---

umbraco-heartcore/client-libraries/dot-net-core/README.md

Update client libraries dot net core:

Update client libraries dot net core - Umbraco Heartcore

---

umbraco-heartcore/api-documentation/content-management/content/type.md

Update api documentation content management content type:

Update api documentation content management content type - Umbraco Heartcore

---

umbraco-heartcore/api-documentation/content-delivery/content.md

Update api documentation content delivery content:
Umbraco heartcore

Update api documentation content delivery content - Umbraco heartcore 

---

umbraco-cloud/set-up/application-insights.md

Update application-insights:
Umbraco Cloud

Update application-insights - Umbraco Cloud

---

marketplace-and-integrations/packages/authorized-services.md

Updated method signatures for Umbraco.AuthorizedServices 0.4
Umbraco.AuthorizedServices 0.4

Updated method signatures for Umbraco.AuthorizedServices 0.4

---

umbraco-cloud/SUMMARY.md
umbraco-cloud/set-up/project-settings/umbraco-cicd/CommonPitfalls.md
umbraco-cloud/set-up/project-settings/umbraco-cicd/Troubleshooting.md

Wanted to add a section about common pitfalls when using CICD
Umbraco Cloud CICD Flow
No deadline

add common pitfalls to cicd

---

umbraco-heartcore/api-documentation/graphql/schema-generation.md

Adds Block Grid reserved types and removes unneeded directives from types

Update Heartcore GraphQL schema generation

---

umbraco-cloud/deployment/local-to-cloud.md

deployment-local-to-cloud.md:
Umbraco Cloud

Update deployment-local-to-cloud.md -  Umbraco Cloud

---

umbraco-cloud/set-up/project-settings/team-members/README.md

I changed 'No Access' permission. It said that you can clone down the project but you can't :) So removed that part.

Updated team member permission

---

10/umbraco-forms/developer/themes.md
11/umbraco-forms/developer/themes.md
12/umbraco-forms/developer/themes.md
13/umbraco-forms/developer/themes.md

Updated latest version number on Umbraco Forms default theme download links.
Forms 10+

Updated latest version number on Umbraco Forms default theme download links.

---

new-backoffice/extending/localization/ui-localization.md

Update ui-localization:
the New Backoffice

Update ui-localization - the New Backoffice

---

umbraco-cloud/set-up/project-settings/umbraco-cicd/Troubleshooting.md
umbraco-cloud/set-up/project-settings/umbraco-cicd/UmbracoCloudApi.md

- Updated the api response examples
- added another headline to troubleshooting
Umbraco Cloud CI/CD Flow

Some refreshes to CICD docs

---

new-backoffice/extending/umbraco-element/README.md

Update extending umbraco-element:

Update extending umbraco-element - The new backoffice

---

10/umbraco-ui-builder/getting-started/licensing-model.md
12/umbraco-ui-builder/getting-started/licensing-model.md

Fixed copy/paste typos in details of UI Builder's licensing model.
UI Builder
Any time.

Fixed copy/paste typos in details of UI Builder's licensing model.

---

new-backoffice/extending/modals/README.md

Update extending/modals - the new backoffice

---

umbraco-heartcore/api-documentation/content-management/member/README.md

Update APE Documentation Content Management Member:

Update API Documentation Content Management Member - Umbraco Heartcore

---

10/umbraco-workflow/release-notes.md
12/umbraco-workflow/release-notes.md
13/umbraco-workflow/release-notes.md

Adds release note for bugfix 49
Workflow 10.3.3, 12.2.0, 13.0
Not urgent - just added in the interest of completeness in release notes.

additional update with very last minute bugfix

---

13/umbraco-forms/developer/prepping-frontend.md
13/umbraco-forms/installation/version-specific.md

Details of further breaking changes in Forms 13 that will be available in the next RC.
Forms 13.0.0-rc3
Can go live at any time (will do no harm if they are live before the next RC is released).

Details of further breaking changes in Forms 13.

---

Add-ons/Umbraco-Deploy/Deploy-Settings/index.md

Update configuration details for Deploy 4.9 in legacy documentation.
Deploy 4.9

Legacy docs: Update configuration details for Deploy 4.9.

---

10/umbraco-cms/extending/property-editors/tracking.md
11/umbraco-cms/extending/property-editors/tracking.md
12/umbraco-cms/extending/property-editors/tracking.md
13/umbraco-cms/extending/property-editors/tracking.md

Update Extending Property Editors tracking:
Umbraco v10, v11, v12 & v13

Update Extending Property Editors tracking

---

10/umbraco-cms/extending/packages/types-of-packages.md
11/umbraco-cms/extending/packages/types-of-packages.md
12/umbraco-cms/extending/packages/types-of-packages.md
13/umbraco-cms/extending/packages/types-of-packages.md

Update types of packages:
Umbraco CMS - v10,11,12 & 13

Update types of packages

---

10/umbraco-cms/extending/property-editors/property-value-converters.md
11/umbraco-cms/extending/property-editors/property-value-converters.md
12/umbraco-cms/extending/property-editors/property-value-converters.md
13/umbraco-cms/extending/property-editors/property-value-converters.md

Update property value converters:
Umbraco CMS v10, 11, 12 13

Update property value converters

---

new-backoffice/extending/context-api/README.md
new-backoffice/extending/extension-types/workspace-context.md

There has been a few change to the usage of the Context Tokens, which finally made Workspace Contexts a real thing. Hence I wrote some docs for it.
latest nightly...

Context Token and Workspace Context update

---

10/umbraco-ui-builder/release-notes.md
12/umbraco-ui-builder/release-notes.md

Release notes for versions 10.0.2/12.0.2 of `Umbraco.UIBuilder`.

UI Builder release minors updates

---

13/umbraco-forms/README.md
13/umbraco-forms/SUMMARY.md

testing sync2

---

sustainability-best-practices/backend/cache-responses.md

Adding output caching ref https://github.com/umbraco/UmbracoDocs/pull/5633 link to sustainability docs as it seems in this case that output caching is like a good practice hence suited to be on the sustainability docs
Sustainability docs
anytime

adding output cache reference link

---

umbraco-cloud/set-up/project-settings/umbraco-cicd/README.md
umbraco-cloud/set-up/project-settings/umbraco-cicd/UmbracoCloudApi.md
umbraco-cloud/set-up/project-settings/umbraco-cicd/samplecicdpipeline/README.md

Remove the "Work in Progress" boxes from CICD-docs
Umbraco Cloud
:D

Remove "Work in Progress" from CICD docs

---

10/umbraco-cms/fundamentals/data/adding-tabs.md
12/umbraco-cms/fundamentals/data/adding-tabs.md
13/umbraco-cms/fundamentals/data/adding-tabs.md

Update adding tabs:
Umbraco CMS v10,12 &13

Update adding tabs

---

10/umbraco-cms/extending/section-trees/README.md
12/umbraco-cms/extending/section-trees/README.md
13/umbraco-cms/extending/section-trees/README.md

Update Extending --> Section Trees readme:
Umbraco v10, 12 & 13

Update Extending --> Section Trees readme

---

10/umbraco-deploy/release-notes.md
11/umbraco-deploy/release-notes.md
12/umbraco-deploy/release-notes.md
13/umbraco-deploy/release-notes.md

Added release notes for Deploy 4,9. 10.3 and 12.1.
Deploy 4,9. 10.3 and 12.1.
Should go live first thing on December 11th.

Release notes for Deploy 4,9. 10.3 and 12.1.

---

12/umbraco-cms/SUMMARY.md
12/umbraco-cms/reference/security/api-rate-limiting.md
13/umbraco-cms/SUMMARY.md
13/umbraco-cms/reference/security/api-rate-limiting.md

- Adding articles (_content is the same_) about how to take advantage of the built-in rate limiting middleware of ASP.NET Core in Umbraco.
CMS v12 and v13
No deadline

(v12 and v13) Adding rate limiting documentation

---

10/umbraco-cms/fundamentals/data/users.md

Update fundamentals data users

---

commerce-add-ons/payment-providers/mollie/configuring-umbraco.md

Verified that the changes work with Umbraco Commerce v13.0.0-rc1.
=> When Umbraco Commerce v13 is released.

Update configuring-umbraco.md for Commerce v13

---

umbraco-cloud/getting-started/the-umbraco-cloud-portal/organizations.md

https://docs.umbraco.com/umbraco-cloud/getting-started/the-umbraco-cloud-portal/organizations
Umbraco Cloud
No deadline.

Grammar Update to organizations.md

---

12/umbraco-forms/developer/themes.md
13/umbraco-forms/developer/themes.md

Update links to Forms default themes for 12.2 and 13.0
Forms 12 and 13

Update links to Forms default themes for 12.2 and 13.0

---

10/umbraco-cms/reference/angular/directives/umbproperty.md
12/umbraco-cms/reference/angular/directives/umbproperty.md
13/umbraco-cms/reference/angular/directives/umbproperty.md

Update umb property: 
Umbraco-CMS v10, 12 & 13

Update umb property

---

12/umbraco-forms/release-notes.md
13/umbraco-forms/release-notes.md

Release notes for Forms 12.2.1
Forms 12.2.1
Anytime from today and before Dec 19th please.

Release notes for Forms 12.2.1

---

10/umbraco-workflow/release-notes.md
12/umbraco-workflow/release-notes.md
13/umbraco-workflow/release-notes.md

Updates release notes for 10.3.5, 12.2.2 and 13.0.1, and adds missing references for 10.3.4 and 12.2.1.
Workflow 10/12/13

Release notes for Workflow Christmas Edition 2023 :)

---

10/umbraco-forms/developer/extending/adding-a-type.md
11/umbraco-forms/developer/extending/adding-a-type.md
12/umbraco-forms/developer/extending/adding-a-type.md
13/umbraco-forms/developer/extending/adding-a-type.md

Updated reference to download of angularjs files.  The current documentation is not correct since Forms 9.
Raised in issue https://github.com/umbraco/Umbraco.Forms.Issues/issues/1134
Forms 10+

Updated reference to download of angularjs files.

---

13/umbraco-deploy/deploy-settings.md

Fixed details on Deploy wehbook registration.  What we had documented was valid for the earlier release candidates, but it changed before the final release.
Deploy 13

Fixed details on Deploy wehbook registration.

---

10/umbraco-cms/SUMMARY.md
11/umbraco-cms/SUMMARY.md
12/umbraco-cms/SUMMARY.md
13/umbraco-cms/SUMMARY.md
umbraco-cloud/SUMMARY.md

Fix links to sustainability-best-practices. 
Fixes #5715 
Umbraco CMS and Umbraco CLoud

Fix links to sustainability-best-practices

---

umbraco-cloud/set-up/project-settings/umbraco-cicd/UmbracoCloudApi.md

Updated an incorrect response model 
Umbraco Cloud CI/CD Flow

CICD Get Deployments endpoint - Update incorrect response model

---

commerce-add-ons/payment-providers/opayo/release-notes.md
commerce-add-ons/payment-providers/paypal/release-notes.md

Updates to PayPal and Opayo release notes for 13.0.1 patch release

PayPal + Opayo release notes updates

---

sustainability-best-practices/README.md
sustainability-best-practices/SUMMARY.md
sustainability-best-practices/backend/README.md
sustainability-best-practices/infrastructure/hosting.md

based on PR #5601
sustainability docs
sustainability docs
anytime

updating sustainability docs as per PR#5601

---

13/umbraco-forms/installation/version-specific.md
umbraco-cloud/set-up/project-settings/umbraco-cicd/KnownLimitationsAndConsiderations.md

Added a special considerations section to the CI/CD documentation for the usage of private NuGet feeds
Umbraco Cloud CI/CD Flow

Added CI/CD considerations for private Nuget feeds

---

10/umbraco-cms/fundamentals/backoffice/settings-dashboards.md
11/umbraco-cms/fundamentals/backoffice/settings-dashboards.md
12/umbraco-cms/fundamentals/backoffice/settings-dashboards.md
13-rc/umbraco-cms/fundamentals/backoffice/settings-dashboards.md
13/umbraco-cms/fundamentals/backoffice/settings-dashboards.md

Added telemetry descriptions for "Basic" and "Minimal" to address this issue: https://github.com/umbraco/UmbracoDocs/issues/5536
* [ ✅ ] New content
V10-13
N/A

#5536 describe telemetry data levels

---

commerce-add-ons/payment-providers/buckaroo/release-notes.md

* Migrate from `Newtonsoft.Json` to `System.Text.Json`.
* Return more meaningful exception messages when there are misconfigured settings.
* Fix minor bugs in provider settings.
It's a minor update so no rush on this.

Update release-notes.md for Buckaroo Payment provider v13.1.0

---

12/umbraco-cms/legacy-documentation/README.md

fix cms 12 sync

---

10/umbraco-cms/reference/notifications/editormodel-notifications/customizing-the-links-box.md

Update customizing the links box:
Umbraco CMS v10

Update customizing the links box

---

commerce-add-ons/payment-providers/stripe/release-notes.md

=> It's a minor release so no rush on this.

Update release-notes.md for Stripe Payment provider v13.1.0

---

13/umbraco-cms/reference/configuration/securitysettings.md

Updated the AllowConcurrentLogins default value

Updated the default value of AllowConcurrentLogins

---

13/umbraco-ui-builder/release-notes.md

Updated release notes for `Umbraco.UIBuilder` v13.

UIBuilder v13 release notes updates

---

10/umbraco-forms/developer/themes.md
12/umbraco-forms/developer/themes.md
13/umbraco-forms/developer/themes.md

Updated Forms theme version links
Forms 10.5.3, 12.2.2, 13.0.1

Updated Forms theme version links

---

Add-ons/Umbraco-Deploy/Deploy-Settings/index.md
Add-ons/UmbracoForms/Developer/Configuration/index.md

Added additional configuration option introduced in Forms and Deploy for Umbraco 8.
Forms 8.13.13 and Deploy 4.9.3
Can be reviewed and published to the legacy documentation platform at any time.

Added additional configuration option introduced in Forms and Deploy for Umbraco 8.

---

commerce-add-ons/payment-providers/klarna/release-notes.md

Added changelogs for Klarana 10.0.1, 12.0.1 and 13.0.1

Updated changelog for Klarna payment provider

---

10/umbraco-ui-builder/release-notes.md
12/umbraco-ui-builder/release-notes.md
13/umbraco-ui-builder/release-notes.md

Updated the links to the relative changelog pages as described in #5771 
fixes #5771

Update broken changelog link for all supported versions

---

umbraco-cloud/product-upgrades/version-specific-upgrades/migrate-from-8-to-latest.md

Remove double semi colon in connection string

---

13/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/rich-text-editor/README.md
13/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/rich-text-editor/configuration.md
13/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/rich-text-editor/rte-plugins.md
13/umbraco-cms/reference/configuration/richtexteditorsettings.md
13/umbraco-cms/tutorials/editors-manual/working-with-content/rich-text-editor.md

Update all TinyMCE Docs links from v5 to v6.
13
ASAP

V13: Update TinyMCE v5 to v6

---

10/umbraco-workflow/release-notes.md
12/umbraco-workflow/release-notes.md
13/umbraco-workflow/release-notes.md

Adds notes for the latest Workflow patches.
Workflow 10.3.6, 12.2.3 and 13.0.2
Whenever is convenient :)

Adds release notes for Workflow 10.3.6, 12.2.3, 13.0.2

---

new-backoffice/extending/states.md

V14, UmbState: set value example

---

umbraco-cloud/set-up/project-settings/umbraco-cicd/KnownLimitationsAndConsiderations.md

Removed an limitation, becaused it is no longer a limitation 🥇
Removed a section because it is no longer relevant after an update
Cloud 
CI/CD Flow
When convenient

Update CICD / KnownLimitationsAndConsiderations.md

---

12/umbraco-ui-builder/release-notes.md
13/umbraco-ui-builder/release-notes.md

Release notes for `Umbraco.UIBuilder` versions `12.0.3` and `13.0.2`.

Umbraco.UIBuilder - 12.0.3/13.0.2 release notes

---

commerce-add-ons/payment-providers/quickpay/release-notes.md

No pressure. Release it whenever you're ready.

Update quickpay release-notes.md - add v13.0.1 and v12.0.1

---

13/umbraco-cms/reference/routing/custom-routes.md

#5789 
Removed duplicate class declaration for the following page (https://docs.umbraco.com/umbraco-cms/reference/routing/custom-routes#custom-route-with-ivirtualpagecontroller)
* [x ] Typo/grammar fix
v13

Fix - Duplicated class declaration #5789

---

10/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/block-editor/label-property-configuration.md
12/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/block-editor/label-property-configuration.md
13/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/block-editor/label-property-configuration.md

https://docs.umbraco.com/umbraco-cms/v/10.latest-lts/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/block-editor/label-property-configuration#custom-filters 
CMS v10,12 and 13
anytime

update custom filters docs with more clear steps

---

sustainability-best-practices/SUMMARY.md
sustainability-best-practices/backend/README.md
sustainability-best-practices/editor/README.md
sustainability-best-practices/frontend/README.md
sustainability-best-practices/frontend/assets-optimisation.md
sustainability-best-practices/frontend/image-optimisation.md
sustainability-best-practices/frontend/lazy-load-resources.md
sustainability-best-practices/frontend/limit-use-of-3rd-parties.md
sustainability-best-practices/frontend/mobile-first.md
sustainability-best-practices/frontend/page-weight-budgets.md
sustainability-best-practices/infrastructure/README.md

Added ReadMe.md files in editor, frontend, and infrastructure sections. Fixed some formatting and grammar stuff.
Anytime

Added READMe.md files and some minor changes

---

10/umbraco-forms/editor/attaching-workflows/workflow-types.md
12/umbraco-forms/editor/attaching-workflows/workflow-types.md
13/umbraco-forms/editor/attaching-workflows/workflow-types.md

Update workflow types:
Umbraco Forms

Update workflow types

---

10/umbraco-forms/editor/creating-a-form/README.md
12/umbraco-forms/editor/creating-a-form/README.md
13/umbraco-forms/editor/creating-a-form/README.md

Update creating a form:
Umbraco Forms

Update creating a form

---

13/umbraco-commerce/release-notes/README.md

Umbraco Commerce 13.1.0-rc2 release notes
Umbraco Commerce 13.1.0-rc2 
ASAP

Umbraco Commerce RC2 release notes

---

new-backoffice/extending/sorting.md

Add docs about the Sorter Controller
Preview 005

v14: Sorter docs

---

10/umbraco-cms/reference/security/backofficeusermanager-and-notifications.md
12/umbraco-cms/reference/security/backofficeusermanager-and-notifications.md
13/umbraco-cms/reference/security/backofficeusermanager-and-notifications.md

Update backofficeusermanager and notifications:

Update backofficeusermanager and notifications

---

10/umbraco-cms/fundamentals/backoffice/login.md
12/umbraco-cms/fundamentals/backoffice/login.md
13/umbraco-cms/fundamentals/backoffice/login.md

Fixed the login screen XML format so that it actually works and added a note that the config file needs to be in the project root.
* [ X] Updated outdated content
10.x but think this applies to 9 onward.

Update login.md to add correct XML for login screen greetings

---

10/umbraco-cms/implementation/controllers.md
10/umbraco-cms/reference/routing/authorized.md
12/umbraco-cms/implementation/controllers.md
12/umbraco-cms/reference/routing/authorized.md
13/umbraco-cms/implementation/controllers.md
13/umbraco-cms/reference/routing/authorized.md

Removed mentioning of UmbracoAuthorizedController as it should no longer be used in v10 and up
v10 and up

UmbracoAuthorizedController cleanup

---

13/umbraco-commerce/upgrading/migrate-from-vendr-to-umbraco-commerce/README.md

SQL migration script for exports "email" in the path instead of "export"
Updated the SQL migration script - replaced 'email' with 'export'. 
* [X ] Typo/grammar fix
* [X ] Updated outdated content
Umbraco Commerce 13

Update Export Template SQL script

---

12/umbraco-cms/tutorials/add-azure-active-directory-authentication.md
13/umbraco-cms/tutorials/add-azure-active-directory-authentication.md

Fixed typo in example

---

10/umbraco-commerce/key-concepts/bulk-actions.md
12/umbraco-commerce/key-concepts/bulk-actions.md
13/umbraco-commerce/key-concepts/bulk-actions.md

Update bulk actions:
Umbraco Commerce

Update bulk actions

---

10/umbraco-cms/extending/packages/packages-on-umbraco-cloud.md
10/umbraco-cms/tutorials/add-google-authentication.md
10/umbraco-cms/tutorials/multisite-setup.md
12/umbraco-cms/extending/packages/packages-on-umbraco-cloud.md
12/umbraco-cms/tutorials/add-google-authentication.md
12/umbraco-cms/tutorials/multisite-setup.md
13/umbraco-cms/extending/packages/packages-on-umbraco-cloud.md
13/umbraco-cms/tutorials/add-google-authentication.md
13/umbraco-cms/tutorials/multisite-setup.md
sustainability-best-practices/backend/cache-responses.md
umbraco-cloud/product-upgrades/version-specific-upgrades/migrate-from-umbraco-7-to-8.md
umbraco-cloud/release-notes/overview-2023/2023-02-releasenotes.md
umbraco-cloud/set-up/manage-subscriptions/new-shop/subscription-migration-information-and-faq.md

Fixed broken links

---

10/umbraco-cms/reference/querying/udi-identifiers.md

Update udi identifiers:
Umbraco CMS v10

Update udi identifiers

---

.github/styles/UmbracoDocs/Acronyms.yml
new-backoffice/tutorials/creating-a-custom-dashboard.md
new-backoffice/tutorials/creating-a-custom-dashboard/adding-functionality-to-the-dashboard.md
new-backoffice/tutorials/creating-a-custom-dashboard/adding-localization-to-the-dashboard.md
new-backoffice/tutorials/creating-a-custom-dashboard/extending-the-dashboard-using-umbraco-ui-library.md

Updated all code examples to work with preview007.
14.0.0
ASAP (preview007 is already out)

V14 preview007: Update the "creating a custom dashboard" tutorial

---

13/umbraco-commerce/reference/shipping/realtime-rate-shipping.md

Removed \ from image filenames generated by GitBook

---

13/umbraco-forms/SUMMARY.md

Added Webhooks to Forms -> SUMMARY.md file

---

14/umbraco-cms/extending-backoffice/context-api/README.md
14/umbraco-cms/extending-backoffice/umbraco-element/README.md

Added Provide context API section, simplified some statements, fixed vale warnings

---

14/umbraco-cms/extending-backoffice/context-api/variant-context.md
14/umbraco-cms/extending-backoffice/development-flow/README.md
14/umbraco-cms/extending-backoffice/development-flow/vite-package-setup.md
14/umbraco-cms/extending-backoffice/extension-types/bundle.md
14/umbraco-cms/extending-backoffice/extension-types/conditions.md
14/umbraco-cms/extending-backoffice/extension-types/kind.md
14/umbraco-cms/extending-backoffice/extension-types/store.md
14/umbraco-cms/extending-backoffice/extension-types/workspaces/workspace-context.md
14/umbraco-cms/extending-backoffice/extension-types/workspaces/workspace-editor-views.md
14/umbraco-cms/extending-backoffice/localization/.net-localization.md
14/umbraco-cms/extending-backoffice/localization/README.md
14/umbraco-cms/extending-backoffice/localization/ui-localization.md
14/umbraco-cms/extending-backoffice/sorting.md
14/umbraco-cms/extending-backoffice/states.md
14/umbraco-cms/fundamentals/backoffice/document-blueprints.md
14/umbraco-cms/fundamentals/setup/install/preview-builds.md
14/umbraco-cms/tutorials/creating-a-basic-website/README.md
14/umbraco-cms/tutorials/creating-a-custom-dashboard/README.md

added hints for work in progress or incomplete pages

added hints for work in progress or incomplete pages

---

12/umbraco-cms/tutorials/custom-error-page.md
13/umbraco-cms/tutorials/custom-error-page.md

Update custom error page:
Umbraco CMS v12 & 13

Update custom error page

---

14/umbraco-cms/tutorials/creating-your-first-extension.md

This PR corrects the name of the folder created to match the folder name used in the command

Corrected folder name

---

13/umbraco-commerce/key-concepts/bulk-actions.md

Changed a : to ; in the code example
Umbraco Commerce

Fixes a typo in bulk action code example

---

13/umbraco-forms/developer/ajaxforms.md

Corrected query string before culture parameter

---

10/umbraco-deploy/getting-started/cicd-pipeline/ci-cd-github-actions.md
12/umbraco-deploy/getting-started/cicd-pipeline/ci-cd-github-actions.md
13/umbraco-deploy/getting-started/cicd-pipeline/ci-cd-github-actions.md

The YAML snippet example refers to v3 of the upload and download github action task. v4 has significant performance improvements as mentioned in Githubs blog here: https://github.blog/2024-02-12-get-started-with-v4-of-github-actions-artifacts/  
Anytime!

Update ci-cd-github-actions.md to use v4 artifact tasks

---

13/umbraco-cms/extending/key-vault.md

Fixes: 
https://github.com/umbraco/UmbracoDocs/issues/5787 
Update the KeyVault article so that is works for v13. I did this using an extension method to keep changes in the `Program.cs` to a minimum.
Umbraco CMS v13.

Update KeyVault config for v13

---

10/umbraco-workflow/release-notes.md
12/umbraco-workflow/SUMMARY.md
12/umbraco-workflow/getting-started/submitting-changes.md
12/umbraco-workflow/getting-started/workflow-content-app.md
12/umbraco-workflow/release-notes.md
13/umbraco-workflow/SUMMARY.md
13/umbraco-workflow/getting-started/submitting-changes.md
13/umbraco-workflow/getting-started/workflow-content-app.md
13/umbraco-workflow/release-notes.md

Shorten sentences, fix grammar

---

10/umbraco-deploy/getting-started/cicd-pipeline/ci-cd-azure-dev-ops.md
12/umbraco-deploy/getting-started/cicd-pipeline/ci-cd-azure-dev-ops.md
13/umbraco-deploy/getting-started/cicd-pipeline/ci-cd-azure-dev-ops.md

Added two links to the Microsoft documentation on how to set Secrets for your Azure DevOps pipeline.
Anytime!

Update ci-cd-azure-dev-ops.md Added links to Microsoft docs on secrets

---

10/umbraco-cms/reference/security/two-factor-authentication.md
12/umbraco-cms/reference/security/two-factor-authentication.md

Removed unused usings

---

10/umbraco-cms/.gitbook.yaml
10/umbraco-cms/SUMMARY.md
10/umbraco-cms/reference/security/README.md
10/umbraco-cms/reference/security/external-login-providers.md
10/umbraco-cms/tutorials/add-google-authentication.md
10/umbraco-cms/tutorials/add-microsoft-entra-id-authentication.md
12/umbraco-cms/.gitbook.yaml
12/umbraco-cms/reference/security/README.md
12/umbraco-cms/reference/security/external-login-providers.md
12/umbraco-cms/tutorials/add-google-authentication.md
12/umbraco-cms/tutorials/add-microsoft-entra-id-authentication.md
13/umbraco-cms/.gitbook.yaml
13/umbraco-cms/SUMMARY.md
13/umbraco-cms/reference/security/README.md
13/umbraco-cms/reference/security/external-login-providers.md
13/umbraco-cms/tutorials/add-google-authentication.md
13/umbraco-cms/tutorials/add-microsoft-entra-id-authentication.md

recreated PR: Rename azuread entra #5869
cms v10, 12 and v13
anytime

recreate PR: Rename azuread entra #5869

---

10/umbraco-cms/reference/routing/request-pipeline/README.md
12/umbraco-cms/reference/routing/request-pipeline/README.md
13/umbraco-cms/reference/routing/request-pipeline/README.md

Update request pipeline

---

10/umbraco-cms/reference/searching/examine/examine-manager.md
12/umbraco-cms/reference/searching/examine/examine-manager.md
13/umbraco-cms/reference/searching/examine/examine-manager.md

Update examine manager

---

10/umbraco-workflow/getting-started/submitting-changes.md
10/umbraco-workflow/release-notes.md
12/umbraco-workflow/getting-started/submitting-changes.md
12/umbraco-workflow/release-notes.md
13/umbraco-workflow/getting-started/submitting-changes.md
13/umbraco-workflow/release-notes.md

Release notes for 10.3.8, 12.2.5 and 13.0.5
Workflow 10, 12, 13
Whenever suits you :)

More Workflow release notes 

---

10/umbraco-workflow/workflow-section/content-reviews.md
12/umbraco-workflow/workflow-section/content-reviews.md
13/umbraco-workflow/workflow-section/content-reviews.md

Update content reviews:
Umbraco Workflow

Update content reviews

---

13/umbraco-commerce/key-concepts/pipelines.md

In a working project I noticed `Append<T>()` is obsolete and `Add<T>()` should be used instead.

Add instead of append with register pipeline task

---

10/umbraco-cms/reference/routing/custom-controllers.md
12/umbraco-cms/reference/routing/custom-controllers.md
13/umbraco-cms/reference/routing/custom-controllers.md

removed an extra 'a' and made sentence clear
Umbraco 10-13

Fixed grammar mistake

---

10/umbraco-cms/fundamentals/setup/server-setup/azure-web-apps.md
12/umbraco-cms/fundamentals/setup/server-setup/azure-web-apps.md
13/umbraco-cms/fundamentals/setup/server-setup/azure-web-apps.md
14/umbraco-cms/fundamentals/setup/server-setup/azure-web-apps.md

If a user wants to set these App Settings directly on their Azure Web App, they can use the advanced edit feature in Azure Web Apps to quickly apply these settings directly to their app.
Anytime!

Added Azure Web App Configuration JSON to Web Apps page

---

12/umbraco-workflow/getting-started/dashboards-and-buttons.md
13/umbraco-workflow/getting-started/dashboards-and-buttons.md

Fixed broken image

---

10/umbraco-forms/editor/attaching-workflows/README.md
12/umbraco-forms/editor/attaching-workflows/README.md
13/umbraco-forms/editor/attaching-workflows/README.md

Update attaching workflows:
Umbraco Forms

Update attaching workflows

---

10/umbraco-cms/fundamentals/setup/upgrading/version-specific/README.md
10/umbraco-cms/fundamentals/setup/upgrading/version-specific/upgrade-from-8-to-latest.md
12/umbraco-cms/fundamentals/setup/upgrading/version-specific/README.md
12/umbraco-cms/fundamentals/setup/upgrading/version-specific/upgrade-from-8-to-latest.md
13/umbraco-cms/fundamentals/setup/upgrading/version-specific/README.md
13/umbraco-cms/fundamentals/setup/upgrading/version-specific/upgrade-from-8-to-latest.md
14/umbraco-cms/fundamentals/setup/upgrading/version-specific/upgrade-from-8-to-latest.md
umbraco-cloud/product-upgrades/major-upgrades.md
umbraco-cloud/product-upgrades/version-specific-upgrades/migrate-from-8-to-latest.md

Currently updated text only for version 13. If it looks good, will update version 10 and 12 articles too.

Updated upgrade Note

---

10/umbraco-forms/editor/creating-a-form/fieldtypes/date.md
12/umbraco-forms/editor/creating-a-form/fieldtypes/date.md
13/umbraco-forms/editor/creating-a-form/fieldtypes/date.md

Update fieldtypes date:
Umbraco Forms

Update fieldtypes date

---

marketplace-and-integrations/packages/authorized-services.md

Added details of callback URLs for Umbraco.AuthorizedServices.  This is something we have detailed on the source code repository "read me", but didn't have in the docs.
Umbraco.AuthorizedServices

Added details of callback URLs for Umbraco.AuthorizedServices

---

14/umbraco-cms/extending-backoffice/extension-types/sections-and-trees/README.md

Added a code sample based on this thread: https://github.com/umbraco/Umbraco.CMS.Backoffice/issues/841 I guess that it might need to be improved but figured it was better than nothing =D

Added info about creating a empty section

---

10/umbraco-forms/editor/defining-and-attaching-prevaluesources/prevalue-source-types.md
12/umbraco-forms/editor/defining-and-attaching-prevaluesources/prevalue-source-types.md
13/umbraco-forms/editor/defining-and-attaching-prevaluesources/prevalue-source-types.md

Update prevalue source types:
Umbraco Forms

Update prevalue source types

---

13/umbraco-cms/reference/content-delivery-api/README.md
14/umbraco-cms/reference/content-delivery-api/README.md

fixes #6001 
cms v13 and v14
anytime

fixes broken link

---

10/umbraco-forms/release-notes.md
12/umbraco-forms/release-notes.md
13/umbraco-forms/release-notes.md

Added release notes for Forms 10.5.5, 12.2.4 and 13.1.2.
Forms 10.5.5, 12.2.4 and 13.1.2.
By Thursday if possible please.

Added release notes for Forms 10.5.5, 12.2.4 and 13.1.2.

---

10/umbraco-cms/reference/notifications/contentservice-notifications.md
10/umbraco-cms/reference/notifications/mediaservice-notifications.md
10/umbraco-cms/reference/notifications/memberservice-notifications.md
12/umbraco-cms/reference/notifications/contentservice-notifications.md
12/umbraco-cms/reference/notifications/mediaservice-notifications.md
12/umbraco-cms/reference/notifications/memberservice-notifications.md
13/umbraco-cms/reference/notifications/contentservice-notifications.md
13/umbraco-cms/reference/notifications/mediaservice-notifications.md
13/umbraco-cms/reference/notifications/memberservice-notifications.md
14/umbraco-cms/reference/notifications/contentservice-notifications.md
14/umbraco-cms/reference/notifications/mediaservice-notifications.md
14/umbraco-cms/reference/notifications/memberservice-notifications.md

adding info what happened to raiseEvents  from PR https://github.com/umbraco/Umbraco-CMS/pull/10655 
also, it fixes #5947 
cms v10, 12, 13 and v14
anytime

adding raiseEvents info

---

13/umbraco-cms/tutorials/custom-error-page.md
14/umbraco-cms/README.md
14/umbraco-cms/SUMMARY.md
14/umbraco-cms/tutorials/custom-error-page.md

replacement for ContentXPath in v14 is IContentLastChanceFinder so I have updated the article accordingly. 
Added to the article that is a work in progress only cuz there are some links in the article that will not work until we add the rest of the articles to summary.md, which will be around release time. (as currently we only add articles that have been updated in v14) 
related to #6006 as well
cms v14
anytime

update xpath replacement for v14

---

13/umbraco-cms/extending/property-editors/full-examples-value-converters.md
13/umbraco-cms/extending/property-editors/property-value-converters.md
13/umbraco-cms/reference/configuration/contentsettings.md
13/umbraco-cms/reference/configuration/index-10.0.0.md
13/umbraco-cms/reference/querying/umbracohelper.md
13/umbraco-cms/reference/routing/authorized.md
14/umbraco-cms/fundamentals/setup/upgrading/version-specific/README.md
14/umbraco-cms/reference/configuration/contentsettings.md

update xpath hints with what is replacement for contentxpath

update xpath hints

---

13/umbraco-cms/tutorials/getting-started-with-entity-framework-core.md

Added detail about storing your Table information in separate project/class library.
When using separate project/class library you need to run the EF migration script in that project's folder and add path to the Main startup Project
reference: https://github.com/dotnet/efcore/issues/15145#issuecomment-725189870 , https://stackoverflow.com/a/72036727
v13

EF info about using multiple projects

---

10/umbraco-workflow/release-notes.md
12/umbraco-workflow/release-notes.md
13/umbraco-workflow/release-notes.md

Release notes for Workflow 10.3.9, 12.2.6 and 13.0.6. Note too the correction for 13.0.4 (which doesn't exist)
Workflow 10.3.9, 12.2.6 and 13.0.6

release notes

---

13/umbraco-commerce/installation/the-licensing-model.md

Changes SUITS to Sales

---

10/umbraco-cms/fundamentals/setup/install/unattended-install.md
12/umbraco-cms/fundamentals/setup/install/unattended-install.md
13/umbraco-cms/fundamentals/setup/install/unattended-install.md
14/umbraco-cms/fundamentals/setup/install/unattended-install.md
umbraco-cloud/databases/local-database.md
umbraco-cloud/product-upgrades/version-specific-upgrades/migrate-from-8-to-latest.md

Added Note about data providers included in .net framework

---

10/umbraco-cms/SUMMARY.md
10/umbraco-cms/fundamentals/setup/upgrading/README.md
10/umbraco-cms/fundamentals/setup/upgrading/version-specific/upgrade-from-8-to-latest.md
12/umbraco-cms/fundamentals/setup/upgrading/README.md
12/umbraco-cms/fundamentals/setup/upgrading/version-specific/upgrade-from-8-to-latest.md
13/umbraco-cms/fundamentals/setup/upgrading/README.md
13/umbraco-cms/fundamentals/setup/upgrading/version-specific/upgrade-from-8-to-latest.md
14/umbraco-cms/fundamentals/setup/upgrading/version-specific/upgrade-from-8-to-latest.md

Added Note about timeout issue when connecting to DB

---

umbraco-cloud/security.md

I have added detail about open ports 
do not merge this in until I write back when it can be merged, as am waiting for an approval internally

Added detail about open ports in Umbraco Cloud

---

10/umbraco-cms/reference/notifications/README.md
12/umbraco-cms/reference/notifications/README.md
13/umbraco-cms/reference/notifications/README.md
14/umbraco-cms/reference/notifications/README.md

Update notifications readme
Umbraco CMS v10, 12, 13 &14

Update notifications readme

---

umbraco-heartcore/api-documentation/content-management/content/type.md
umbraco-heartcore/release-notes/2024-04-releasenotes.md

Additional release notes for a late-April rollout. Updated & simplified example response from `/content/type` APIs.
Heartcore
N/A

Additional April release notes for Heartcore

---

12/umbraco-forms/developer/ajaxforms.md
13/umbraco-forms/developer/ajaxforms.md

Reverts umbraco/UmbracoDocs#6077

Revert "Update querystring in forms definitions request"

---

13/umbraco-ui-builder/release-notes.md

`Umbraco UI Builder` release notes for version `13.1.3`.
`Umbraco.UIBuilder - 13.1.3`
Any time possible.

Umbraco UI Builder 13.1.3 release notes

---

13/umbraco-cms/fundamentals/setup/server-setup/iis.md

Update "Hosting Bundle" to provide microsoft link
* Updated outdated content

Update "Hosting Bundle" to provide microsoft link

---

umbraco-heartcore/SUMMARY.md
umbraco-heartcore/api-documentation/rate-limits.md

Add information about soft rate limits in Heartcore APIs.
Heartcore
N/A

Add Heartcore rate limit info

---

14/umbraco-cms/README.md
14/umbraco-cms/SUMMARY.md
14/umbraco-cms/fundamentals/backoffice/create-your-own-api.md

Added documentation about getting started with management API
V14
V14 Release 🚀

Add initial documentation for creating your own API

---

10/umbraco-cms/fundamentals/setup/install/install-umbraco-with-vs-code.md
12/umbraco-cms/fundamentals/setup/install/install-umbraco-with-vs-code.md
13/umbraco-cms/fundamentals/setup/install/install-umbraco-with-vs-code.md
14/umbraco-cms/fundamentals/setup/install/install-umbraco-with-vs-code.md

Added Note for missing .Net assets

---

14/umbraco-cms/extending-backoffice/development-flow/README.md
14/umbraco-cms/extending-backoffice/development-flow/vite-package-setup.md
14/umbraco-cms/fundamentals/setup/install/README.md
14/umbraco-cms/fundamentals/setup/install/installing-nightly-builds.md
14/umbraco-cms/fundamentals/setup/upgrading/version-specific/README.md
14/umbraco-cms/tutorials/creating-your-first-extension.md

update syntaxes to umbraco 14 rc4

update syntaxes to umbraco 14 rc4

---

umbraco-cloud/SUMMARY.md
umbraco-cloud/release-notes/2024-04-releasenotes.md
umbraco-cloud/release-notes/overview-2024.md

Added information about April cloud releases

Updated the release notes for April 2024

---

10/umbraco-cms/tutorials/creating-a-property-editor/part-3.md
12/umbraco-cms/tutorials/creating-a-property-editor/part-3.md

Incorporated changes for v10 and v12

---

14/umbraco-cms/SUMMARY.md

Added Default Property Editor Schema aliases article link in Summary.md

---

umbraco-cloud/set-up/project-settings/umbraco-cicd/KnownLimitationsAndConsiderations.md
umbraco-cloud/set-up/project-settings/umbraco-cicd/Troubleshooting.md

We are closing down the direct cicd-mailbox - hence mail is being removed from docs
Cloud / CICD Flow
As soon as possible

remove direct cicd mail

---

10/umbraco-cms/reference/templating/mvc/viewcomponents.md
12/umbraco-cms/reference/templating/mvc/viewcomponents.md
13/umbraco-cms/reference/templating/mvc/viewcomponents.md
14/umbraco-cms/reference/templating/mvc/viewcomponents.md

Added inject declaration

---

umbraco-cloud/set-up/project-settings/umbraco-cicd/KnownLimitationsAndConsiderations.md
umbraco-cloud/set-up/project-settings/umbraco-cicd/Troubleshooting.md

add back text + cicd mail

---

14/umbraco-forms/developer/extending/adding-a-fieldtype.md

Added details of client-side extension points with Forms 14.  Specifically there are a few parts of extending Forms with custom field types etc. that now require client-side components.  I've updated the page to reference these.
Forms 14
Any time is fine.

Added details of client-side extension points with Forms 14.

---

umbraco-heartcore/release-notes/core-dependency-upgrade.md

Fixed some incorrect details in Heartcore migration info.
Heartcore
5th June 2024

Heartcore migration change won't affect media

---

14/umbraco-forms/release-notes.md

Added release notes for Forms 14.0.1 
Forms 14.0.1
Ideally today or tomorrow please, or if not as soon as possible afterward.  Thanks.

Added release notes for Forms 14.0.1

---

14/umbraco-deploy/release-notes.md

Release notes for Deploy 14.0.1.
Deploy 14.0.1
Thursday June 6th 🚀

Add Deploy 14.0.1 release notes

---

14/umbraco-forms/developer/themes.md

Added details of themes download for Forms 14
Forms 14

Added details of themes download for Forms 14

---

14/umbraco-cms/implementation/controllers.md

This should either be removed entirely as its removed in Umbraco 14, or at the very least not be in a codeblock.

Remove incorrect codeblock formatting

---

14/umbraco-commerce/release-notes/README.md

Umbraco Commerce v14.0.0-Alpha2 release notes
Umbraco Commerce v14.0.0-Alpha2 
_When should the content be published?
ASAP

Umbraco Commerce v14.0.0-Alpha2 release notes

---

14/umbraco-cms/fundamentals/backoffice/README.md

Swapped "Macros" for "Partial Views" in the Backoffice fundementals article, since macros are no longer part of Umbraco 🥳 
V14
Whenever. Not urgent 😄

Do not mention Macros in the Backoffice fundementals article

---

umbraco-heartcore/release-notes/core-dependency-upgrade.md

Changed table of character substitutions in Heartcore migration to remove entries that aren't changing and provide a comprehensive list of ones that are.
Heartcore
N / A

add full character substitution details

---

umbraco-cloud/set-up/project-settings/umbraco-cicd/KnownLimitationsAndConsiderations.md
umbraco-cloud/set-up/project-settings/umbraco-cicd/Troubleshooting.md

Remove the Direct mail to the CICD-team - SWAT will handle support after Code Garden
Umbraco Cloud / CICD Flow
Should be merged after Code Garden 2024

Remove the CICD-mail from docs

---

10/umbraco-cms/reference/configuration/installdefaultdatasettings.md
12/umbraco-cms/reference/configuration/installdefaultdatasettings.md
13/umbraco-cms/reference/configuration/installdefaultdatasettings.md
14/umbraco-cms/reference/configuration/installdefaultdatasettings.md

Corrected the ISO code for English (United Kingdom)

---

13/umbraco-ui-builder/release-notes.md

Updated release notes for Umbraco UIBuilder 13.1.5.
Umbraco UIBuilder 13.1.5

Update release notes for Umbraco UIBuilder 13.1.5

---

14/umbraco-commerce/release-notes/README.md

Added Umbraco Commerce v14-alpha3 release notes
Umbraco Commerce v14-alpha3
ASAP

Added Umbraco Commerce v14-alpha3 release notes

---

14/umbraco-cms/tutorials/starter-kit/lessons/2-add-a-blog-post-publication-date/part-3.md
14/umbraco-cms/tutorials/starter-kit/lessons/3-add-open-graph/step-4.md

Fixes: #6214
Updated step 2 and 3 of the "Add a Blog Post Publication Date" lesson with correct code snippets.
Updated step 4 of the "Add Open Graph" lesson with correct code snippets.
14

Updates to the Starter Kit Guide

---

umbraco-heartcore/release-notes/core-dependency-upgrade.md

Add further information around new URL character substitution change in upcoming migration
Heartcore
Earliest convenience

Add further Heartcore URL change info

---

.github/styles/UmbracoDocs/Acronyms.yml
14/umbraco-cms/extending/package-manifest.md

Added all extension types and other properties to the reference article for Package Manifest.
14
ASAP

V14: Extend the Package Manifest article with all available types

---

13/umbraco-cms/extending/health-check/guides/contentsniffingprotection.md
13/umbraco-cms/extending/health-check/guides/crosssitescriptingprotection.md
13/umbraco-cms/extending/health-check/guides/excessiveheaders.md

Updated the health checks examples to use the new `Program.cs`
I opted to only update the v13 versions, since v13/14 should be identical, this way you only have to fix-up once 😄 
v13/14

Update healthchecks for v13

---

14/umbraco-commerce/release-notes/README.md

Umbraco Commerce v14 alpha 4 release notes
Umbraco Commerce v14 alpha 4 
ASAP

Umbraco Commerce v14 alpha 4 release notes

---

13/umbraco-cms/extending/health-check/guides/crosssitescriptingprotection.md
13/umbraco-cms/extending/health-check/guides/excessiveheaders.md
14/umbraco-cms/extending/health-check/guides/contentsniffingprotection.md
14/umbraco-cms/extending/health-check/guides/crosssitescriptingprotection.md
14/umbraco-cms/extending/health-check/guides/excessiveheaders.md

Copied changes from #6232 into Umbraco 14 articles.
+ fixes some minor grammar/structure stuff.

Update healthguides based on PR #6232

---

10/umbraco-cms/fundamentals/design/partial-view-macro-files.md

Update partial view macro files:
Umbraco v10

Update partial view macro files

---

10/umbraco-forms/developer/prepping-frontend.md
12/umbraco-forms/developer/prepping-frontend.md
13/umbraco-forms/developer/prepping-frontend.md
14/umbraco-forms/developer/prepping-frontend.md

Clarified documentation on the options for and how to setup client-side validation, addressing points raised in [this issue](https://github.com/umbraco/Umbraco.Forms.Issues/issues/1234) on the Forms tracker.
Forms 10+

Clarified documentation on the options for and how to setup client-side validation.

---

14/umbraco-cms/implementation/integration-testing.md

- Updating article with v14 code examples.
CMS v14
No deadline

V14: Integration testing article updates

---

10/umbraco-forms/editor/attaching-workflows/README.md
10/umbraco-forms/editor/creating-a-form/form-settings.md
12/umbraco-forms/editor/attaching-workflows/README.md
12/umbraco-forms/editor/creating-a-form/form-settings.md
13/umbraco-forms/editor/attaching-workflows/README.md
13/umbraco-forms/editor/creating-a-form/form-settings.md
14/umbraco-forms/editor/attaching-workflows/README.md
14/umbraco-forms/editor/creating-a-form/form-settings.md

Clarified means of "store records" setting when it comes to file uploads.
Forms 10+

Clarified means of "store records" setting in Umbraco Forms when it comes to file uploads.

---

13/umbraco-cms/reference/routing/umbraco-api-controllers/README.md

Warning start tag was missing and displayed the code in plain text rather than markdown.
v13

Fixed Note formatting

---

10/umbraco-forms/developer/magic-strings.md
12/umbraco-forms/developer/magic-strings.md
13/umbraco-forms/developer/magic-strings.md
14/umbraco-forms/developer/magic-strings.md

Applied changes from PR# [5213](https://github.com/umbraco/UmbracoDocs/pull/5213) to rest of the versions as well.
v10, v12, v13, v14
Anytime.

Added v11 changes to rest of versions

---

10/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/dropdown/README.md
10/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/rich-text-editor/README.md
12/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/dropdown/README.md
12/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/rich-text-editor/README.md
13/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/dropdown/README.md
13/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/rich-text-editor/README.md
14/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/dropdown/README.md
14/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/rich-text-editor/README.md

Added Note

---

10/umbraco-cms/extending/health-check/README.md
12/umbraco-cms/extending/health-check/README.md
13/umbraco-cms/extending/health-check/README.md

Update health checks:
Umbraco v10, 13 & 13

Update health checks

---

14/umbraco-workflow/upgrading/version-specific.md

Update minimum Umbraco version to 14.1.0
Umbraco Workflow 14

Workflow release notes - v14

---

14/umbraco-commerce/release-notes/README.md

Umbraco Commerce v14-beta1 release notes
Umbraco Commerce v14-beta1 
ASAP

Umbraco Commerce v14-beta1 release notes

---

10/umbraco-cms/extending/property-editors/package-manifest.md
12/umbraco-cms/extending/property-editors/package-manifest.md
13/umbraco-cms/extending/property-editors/package-manifest.md

Update package manifest

---

13/umbraco-forms/developer/configuration/README.md
13/umbraco-forms/release-notes.md

Added release notes and configuration updates for 13.2.0-rc2.
Forms 13.2.0-rc2.

Added release notes and configuration updates for 13.2.0-rc2.

---

umbraco-cloud/set-up/project-settings/umbraco-cicd/Troubleshooting.md

Updates to troubleshooting
Cloud / CICD Flow

Update cicd Troubleshooting.md

---

14/umbraco-cms/extending/key-vault.md

The sample code did not allow me to use KeyVault in the development environment. So I have updated with a reference to a gist that shows how it can be done

Using KeyVault in Appsettings.json

---

14/umbraco-cms/tutorials/creating-a-custom-dashboard/adding-localization-to-the-dashboard.md

Added missing steps

---

14/umbraco-forms/developer/localization.md

Update UmbracoForms Localization:
Umbraco Forms

Update UmbracoForms Localization

---

13/umbraco-forms/developer/themes.md
14/umbraco-forms/developer/themes.md

Update version labels on theme links for Umbraco Forms
Forms 13.2 and 14.1

Update version labels on theme links for Umbraco Forms

---

10/umbraco-cms/implementation/services/circular-dependencies.md
12/umbraco-cms/implementation/services/circular-dependencies.md
13/umbraco-cms/implementation/services/circular-dependencies.md

Update circular dependencies:
Umbraco CMS

Update circular dependencies

---

13/umbraco-forms/release-notes.md
14/umbraco-forms/release-notes.md

Added details of changes to partial views in Forms 13.2 and 14.1 releases.
Forms 13.2 and 14.1

Added details of changes to partial views in Forms 13.2 and 14.1 releases.

---

14/umbraco-workflow/workflow-section/approval-groups.md

As mentioned in [Issue #70](https://github.com/umbraco/Umbraco.Workflow.Issues/issues/70#issuecomment-2251479780), removing Enable offline approval feature references.
Workflow v14
Anytime

Removed enable offline approval feature

---

14/umbraco-commerce/release-notes/README.md

Umbraco Commerce RC1 Release Notes
Umbraco Commerce RC1 
ASAP

Umbraco Commerce RC1 Release Notes

---

10/umbraco-cms/extending/key-vault.md
12/umbraco-cms/extending/key-vault.md
13/umbraco-cms/extending/key-vault.md
14/umbraco-cms/extending/key-vault.md

Added a Note on where to find the database connection string on an existing project
All versions
N/A

Added a Note on where to find the database connection string on an existing project

---

umbraco-cloud/deployment/hotfixes/README.md

Cleaned up hotfix article according to our style guides
Cloud

Cleanup Hotfixes article

---

14/umbraco-cms/extending/property-dataset/README.md

Create property dataset README.md

---

14/umbraco-cms/reference/templating/modelsbuilder/understand-and-extend.md

- Updated the section title to remove Inheritance
- Fixed vale errors to shorten sentences.
CMS v14
Anytime

Removed Inheriatnce from title and fixed vale eroors

---

14/umbraco-cms/extending/customize-backoffice/README.md

Changed incorrect spelling of Bellissima. According to search, there are no other similar incorrect spellings in the repo
n/a
n/a

Fix Bellissima incorrect spelling

---

commerce-add-ons/packages/deploy/release-notes.md

Umbraco Commerce Deploy v14.0.0-rc1 release notes
Umbraco Commerce Deploy v14.0.0-rc1
ASAP

Umbraco Commerce Deploy v14.0.0-rc1 release notes

---

14/umbraco-cms/extending/backoffice-setup/extension-registry/bundle.md

Added examples for extension type of Bundle

Bundle examples

---

10/umbraco-commerce/key-concepts/overview.md
12/umbraco-commerce/key-concepts/overview.md
13/umbraco-commerce/key-concepts/overview.md

Update umbraco commerce overview:
Umbraco Commerce 10, 12 & 13

Update umbraco commerce overview

---

14/umbraco-cms/extending/section-trees/sections/README.md

Fixed the three broken links within the **Extend with Sidebar, Dashboards and more** section.
CMS v14
Anytime

Fixed broken links in Sections article

---

13/umbraco-cms/fundamentals/backoffice/content-templates.md

The number 2 (two) was in Danish, "to".
* [X ] Typo/grammar fix

Update content-templates.md - a typo

---

13/umbraco-cms/extending/filesystemproviders/azure-blob-storage.md
13/umbraco-cms/fundamentals/code/subscribing-to-notifications.md
13/umbraco-cms/reference/content-delivery-api/protected-content-in-the-delivery-api.md
13/umbraco-cms/reference/notifications/notification-handler.md
13/umbraco-cms/reference/routing/request-pipeline/icontentfinder.md
13/umbraco-cms/reference/scheduling.md
13/umbraco-cms/reference/security/serverside-sanitizing.md
13/umbraco-cms/reference/using-ioc.md
13/umbraco-cms/tutorials/add-microsoft-entra-id-authentication.md
14/umbraco-cms/extending/filesystemproviders/azure-blob-storage.md
14/umbraco-cms/fundamentals/code/subscribing-to-notifications.md
14/umbraco-cms/reference/content-delivery-api/protected-content-in-the-delivery-api.md
14/umbraco-cms/reference/notifications/notification-handler.md
14/umbraco-cms/reference/routing/request-pipeline/icontentfinder.md
14/umbraco-cms/reference/scheduling.md
14/umbraco-cms/reference/security/serverside-sanitizing.md
14/umbraco-cms/tutorials/add-microsoft-entra-id-authentication.md

Following #6243 and #5709, I've updated all references to dependency injections throughout the CMS docs.
I've made sure all relevant articles link back to the IoC article.
While I was added, I also took care of some vale warnings in the updated articles.

Opdate references to dependency injection

---

10/umbraco-commerce/key-concepts/umbraco-properties.md
12/umbraco-commerce/key-concepts/umbraco-properties.md
13/umbraco-commerce/key-concepts/umbraco-properties.md

Update Umbraco Commerce Key Concepts Umbraco Properties:
Umbraco Commerce

Update: Umbraco Commerce Key Concepts Umbraco Properties

---

commerce-add-ons/packages/deploy/release-notes.md

Umbraco Commerce Deploy v13.1.2 release notes
Umbraco Commerce Deploy v13.1.2
ASAP

Umbraco Commerce Deploy v13.1.2 release notes

---

umbraco-cloud/set-up/project-settings/umbraco-cicd/Troubleshooting.md

Added guidelines to solve an issue that can happen when you have ci/cd configured for your Umbraco Cloud live environment and then added a development environment afterward.
* [x ] New content
Umbraco Cloud
I need @jesp209i to make a final review.

Adding section to troubleshooting page.md

---

14/umbraco-cms/fundamentals/data/content-version-cleanup.md

Based on an internal discussion, I've attempted to make the article more clear on what the content version cleanup feature does.
I also removed some mentions of in which version the feature was added etc.

Add more details to the Content version cleanup article

---

10/umbraco-forms/editor/creating-a-form/fieldtypes/README.md
12/umbraco-forms/editor/creating-a-form/fieldtypes/README.md
13/umbraco-forms/editor/creating-a-form/fieldtypes/README.md

Update creating a form readme:
Umbraco Forms

Update creating a form readme

---

10/umbraco-cms/fundamentals/data/content-version-cleanup.md
13/umbraco-cms/fundamentals/data/content-version-cleanup.md

Add Content Version Cleanup changes to 13 and 10

---

14/umbraco-cms/extending/packages/README.md

Remove unnecessary WIP notes from the Packages section

Work in Progress notes removed

---

14/umbraco-cms/tutorials/creating-custom-views-for-blocklist.md

Ive updated the example of using settings data in a custom view.
And removed adding stylesheet as that does not make sense any more. With Web Components that is a web component feature that I would say is out of scope for our responsibilities. Any one can search "How to append stylesheet to web component" and find their solution.

V14: Update the example for adding settings to a Custom View

---

14/umbraco-cms/tutorials/creating-custom-views-for-blocklist.md

Update lead paragraph of creating-custom-views-for-blocklist.md

---

14/umbraco-cms/fundamentals/setup/install/README.md

taken from https://docs.umbraco.com/umbraco-cloud/set-up/working-locally#running-the-site-locally as it makes sense to have it on cms docs as well
cms v14
anytime

add hint for https when installing umbraco

---

umbraco-cloud/.gitbook.yaml
umbraco-cloud/SUMMARY.md
umbraco-cloud/getting-started/migrate-to-umbraco-cloud.md

Migrate cloud fixes

---

14/umbraco-ui-builder/README.md
14/umbraco-ui-builder/advanced/virtual-sub-trees.md
14/umbraco-ui-builder/collections/child-collection-groups.md
14/umbraco-ui-builder/collections/child-collections.md
14/umbraco-ui-builder/collections/related-collections.md
14/umbraco-ui-builder/collections/retrieve-child-collections.md
14/umbraco-ui-builder/collections/the-basics.md
14/umbraco-ui-builder/known-issues.md
14/umbraco-ui-builder/release-notes.md

Updated docs for `Umbraco.UIBuilder 14.0.0-alpha1`.
Umbraco UIBuilder 14.0.0-alpha1
Monday, September 2nd 2024

Updated Umbraco UIBuilder 14.0.0-alpha1 docs

---

14/umbraco-cms/customizing/section-trees/trees/entity-actions.md
14/umbraco-cms/customizing/section-trees/trees/entity-bulk-actions.md

I fixed faulty imports in the code examples for entityActions
v14
/

EntityActions: fixed imports in code examples

---

14/umbraco-cms/tutorials/creating-your-first-extension.md

Update the link to the "Creating a Custom Dashboard" page
Corrected the link heading to a 404 page for "Creating a Custom Dashboard"

Correct dead link - Creating a Custom Dashboard

---

14/umbraco-commerce/.gitbook.yaml

Most redirects for the Umbraco Commerce section didn't work.
This PR hopefully resolves that.

Attempt to fix redirects

---

generic/contribute/how-to-add-a-new-version.md

Update: how to add a new version: 
Generic Docs

Update: how to add a new version

---

13/umbraco-ums/SUMMARY.md

No SUMMARY

---

marketplace-and-integrations/integrations/activecampaign-with-umbraco-forms.md

- Change "CMS" section to "Forms" in Umbraco Forms integration with ActiveCampaign.
- Anytime

Incorrect information in Umbraco Forms integration with ActiveCampaign docs

---

13/umbraco-forms/release-notes.md
14/umbraco-forms/release-notes.md

Added release notes for Forms 13.2.3 and 14.1.3
Forms 13.2.3 and 14.1.3
Any time up to and including Thursday morning if possible please.

Added release notes for Forms 13.2.3 and 14.1.3

---

14/umbraco-cms/reference/umbraco-flavored-markdown.md

- Corrected code snippet for a custom UFM component
Umbraco CMS v14.3.0
Please publish once v14.3.0-RC has been released.

Corrects: UFM custom component code snippet

---

14/umbraco-deploy/release-notes.md

Added release notes for Deploy 14.1.3
Deploy 14.1.3
Today if possible please.

Added release notes for Deploy 14.1.3

---

marketplace-and-integrations/README.md

Update marketplace-and-integrations:

 Update marketplace-and-integrations

---

marketplace-and-integrations/integrations/algolia.md

Added geolocation updates for Umbraco CMS - Algolia integration.
`Umbraco.Cms.Integrations.Search.Algolia - 2.3.0 | 3.1.0`

Update Algolia geolocation docs

---

14/umbraco-forms/developer/localization.md

Update forms localization:
Umbraco Forms 14.2.0
Thursday, August 22 2024

Update forms localization

---

15/umbraco-cms/.gitbook/assets/help-menu.svg
15/umbraco-cms/tutorials/extending-the-help-menu.md

Added a tutorial on how to extend the Help Menu in v15

V15: Tutorial: Extending the Help Menu

---

14/umbraco-cms/reference/routing/umbraco-api-controllers/README.md

Applied styleguide and improved formatting
v14
Anytime

Updated Umbraco API Controllers article as per the styleguide

---

.github/styles/UmbracoDocs/Acronyms.yml
.github/styles/UmbracoDocs/Brands.yml
.github/styles/UmbracoDocs/Names.yml
.github/styles/UmbracoDocs/Terms.yml

Added some new terms and acronyms to the linter.

Updated some rules

---

14/umbraco-commerce/release-notes/README.md

Umbraco Commerce 14.0.1 release notes
Umbraco Commerce 14.0.1
ASAP

Umbraco Commerce 14.0.1 release notes

---

13/umbraco-ums/developers/introduction/dataflow-pipeline/README.md
13/umbraco-ums/developers/introduction/dataflow-pipeline/data-collection.md
13/umbraco-ums/developers/introduction/dataflow-pipeline/data-parsing.md
13/umbraco-ums/developers/introduction/dataflow-pipeline/data-storage.md

updated the uMS docs to be Umbraco'fied

---

13/umbraco-ums/developers/introduction/dataflow-pipeline/data-collection.md

fixing some minor stuff

---

13/umbraco-ums/developers/settings/setup-goals.md
13/umbraco-ums/marketers-and-editors/settings/setup-goals.md

updated duplicate article in UMS docs

---

13/umbraco-forms/developer/themes.md
14/umbraco-forms/developer/themes.md

Updated versions on latest Forms theme download links.
Forms 13 and 14

Updated versions on latest Forms theme download links

---

10/umbraco-cms/extending/health-check/guides/clickjackingprotection.md
10/umbraco-cms/extending/health-check/guides/contentsniffingprotection.md
10/umbraco-cms/extending/health-check/guides/debugcompilationmode.md
12/umbraco-cms/extending/health-check/guides/clickjackingprotection.md
12/umbraco-cms/extending/health-check/guides/contentsniffingprotection.md
12/umbraco-cms/extending/health-check/guides/debugcompilationmode.md
13/umbraco-cms/extending/health-check/guides/clickjackingprotection.md
13/umbraco-cms/extending/health-check/guides/contentsniffingprotection.md
13/umbraco-cms/extending/health-check/guides/debugcompilationmode.md
14/umbraco-cms/extending/health-check/guides/clickjackingprotection.md
14/umbraco-cms/extending/health-check/guides/contentsecuritypolicy.md
14/umbraco-cms/extending/health-check/guides/contentsniffingprotection.md
14/umbraco-cms/extending/health-check/guides/debugcompilationmode.md
15/umbraco-cms/extending/health-check/guides/clickjackingprotection.md
15/umbraco-cms/extending/health-check/guides/contentsecuritypolicy.md
15/umbraco-cms/extending/health-check/guides/contentsniffingprotection.md
15/umbraco-cms/extending/health-check/guides/debugcompilationmode.md

Belongs to: https://github.com/umbraco/UmbracoDocs/issues/6465 
Updated: 
[Health Check: ClickJacking Protection](https://docs.umbraco.com/umbraco-cms/extending/health-check/guides/clickjackingprotection)
[Health check: CSP](https://docs.umbraco.com/umbraco-cms/extending/health-check/guides/contentsecuritypolicy)
[Health Check: Content/MIME sniffing protection](https://docs.umbraco.com/umbraco-cms/extending/health-check/guides/contentsniffingprotection)
[Health Check: Debug Compilation Mode](https://docs.umbraco.com/umbraco-cms/extending/health-check/guides/debugcompilationmode)
Umbraco CMS v10, 12, 13, 14 & 15

Add descriptions to health check articles

---

13/umbraco-ums/developers/profiling/external-profile-data.md

fixed vale warnings

---

14/umbraco-commerce/release-notes/README.md

Umbraco Commerce v14.1.1 release notes
Umbraco Commerce v14.1.1 
ASAP

Umbraco Commerce v14.1.1 release notes

---

13/umbraco-ums/developers/personalization/README.md
13/umbraco-ums/developers/personalization/custom-scoring.md
13/umbraco-ums/developers/personalization/implement-your-own-segment-parameters.md
13/umbraco-ums/developers/personalization/segment-information.md
13/umbraco-ums/marketers-and-editors/personalization/extending-personalization/README.md
13/umbraco-ums/marketers-and-editors/personalization/extending-personalization/custom-scoring.md
13/umbraco-ums/marketers-and-editors/personalization/extending-personalization/implement-your-own-segment-parameters.md
13/umbraco-ums/marketers-and-editors/personalization/extending-personalization/segment-information.md

Ums cleaning articles

---

commerce-add-ons/packages/deploy/release-notes.md

Umbraco Commerce Deploy v14.1.0 release notes
Umbraco Commerce Deploy v14.1.0
ASAP

Umbraco Commerce Deploy v14.1.0 release notes

---

14/umbraco-cms/reference/management/using-services/README.md
15/umbraco-cms/reference/management/using-services/README.md

Update using services

---

13/umbraco-ums/developers/ab-testing/csharp-api.md
13/umbraco-ums/developers/ab-testing/extending-the-algorithms.md
13/umbraco-ums/developers/analytics/client-side-events-and-additional-javascript-files/additional-measurements-with-our-ums-analytics-scripts.md
13/umbraco-ums/developers/analytics/extending-analytics/README.md
13/umbraco-ums/developers/analytics/extending-analytics/getting-the-correct-ip-address.md
13/umbraco-ums/developers/analytics/extending-analytics/sending-data-to-the-gtm-datalayer.md
13/umbraco-ums/developers/personalization/README.md
13/umbraco-ums/marketers-and-editors/analytics/README.md
13/umbraco-ums/marketers-and-editors/analytics/campaigns.md
13/umbraco-ums/marketers-and-editors/analytics/device-type.md
13/umbraco-ums/marketers-and-editors/analytics/referral-traffic.md

Cleanup articles

---

10/umbraco-commerce/upgrading/migrate-from-vendr-to-umbraco-commerce/README.md
13/umbraco-commerce/upgrading/migrate-from-vendr-to-umbraco-commerce/README.md
13/umbraco-ums/developers/introduction/the-umarketingsuite-cookie/README.md
13/umbraco-ums/developers/introduction/the-umarketingsuite-cookie/module-permissions.md
13/umbraco-ums/developers/support/README.md
13/umbraco-ums/developers/support/known-issues-and-work-arounds/difference-in-analytics-between-google-analytics-and-umarketingsuite.md
14/umbraco-commerce/upgrading/migrate-from-vendr-to-umbraco-commerce/README.md
15/umbraco-commerce/upgrading/migrate-from-vendr-to-umbraco-commerce/README.md

Ums cleanup developers section

---

13/umbraco-ums/marketers-and-editors/personalization/README.md
13/umbraco-ums/marketers-and-editors/personalization/implicit-and-explicit-personalization/README.md
13/umbraco-ums/marketers-and-editors/personalization/implicit-and-explicit-personalization/campaign-scoring.md
13/umbraco-ums/marketers-and-editors/personalization/implicit-and-explicit-personalization/content-scoring.md
13/umbraco-ums/marketers-and-editors/personalization/implicit-and-explicit-personalization/implicit-personalization-scoring-explained.md
13/umbraco-ums/marketers-and-editors/personalization/implicit-and-explicit-personalization/referral-scoring.md
13/umbraco-ums/marketers-and-editors/personalization/implicit-and-explicit-personalization/setting-up-personas.md
13/umbraco-ums/marketers-and-editors/personalization/implicit-and-explicit-personalization/setting-up-the-customer-journey.md
13/umbraco-ums/marketers-and-editors/personalization/setting-up-personalization.md

fixing vale errors for UMS release

---

14/umbraco-cms/reference/security/cookies.md
14/umbraco-cms/reference/security/password-reset.md
14/umbraco-cms/reference/security/security-hardening.md

I added article descriptions to the markdown files 'cookies', 'Umbraco security hardening' and 'locking of users and password resets'

Adding descriptions

---

15/umbraco-forms/developer/configuration/README.md
15/umbraco-forms/release-notes.md
15/umbraco-forms/upgrading/version-specific/README.md

Added release and upgrade notes for Forms 15.0.0-rc1
Forms 15.0.0-rc1
I expect to try to release this on Tuesday next week, so if this could be published on or before then that would be ideal.

Added release and upgrade notes for Forms 15.0.0-rc1

---

14/umbraco-cms/extending/property-editors/integrate-validation.md

Added an initial draft for the documentation of implementing the Validation System.

Initial version on the basic features of validation system.

---

13/umbraco-deploy/release-notes.md
14/umbraco-deploy/release-notes.md
14/umbraco-forms/release-notes.md

Deploy 13.2.2 & 14.1.4
Deploy Contrib 13.3.0 & 14.2.0
Forms Deploy 14.1.0 (released in August, but was still missing) & 14.1.1
All these versions have been released yesterday, so this can be merged straight away.

Add Deploy, Deploy Contrib and Forms Deploy release notes

---

contributing/hacktoberfest/contributing.md

fixed (HacktoberfestActivityLog) link

(HacktoberfestActivityLog) was incorrect, added fix

---

14/umbraco-cms/reference/using-ioc.md
15/umbraco-cms/reference/using-ioc.md

Porting old Umbraco API Controller [IoC and Dependency injection] 

---

umbraco-cloud/product-upgrades/minor-upgrades.md

Updated Cloud Minor Upgrades article

---

13/umbraco-commerce/release-notes/README.md
14/umbraco-commerce/release-notes/README.md

Updated release notes for `Umbraco.Commerce` patches:
* `13.1.7`
* `14.1.2`
`Umbraco.Commerce 13.1.7/14.1.2`
As soon as possible.

Updated release notes for Umbraco.Commerce 13.1.7/14.1.2

---

13/umbraco-cms/extending/package-manifest.md

I suggest this error was a result of a copy/paste fail when creating the instructions for working with JetBrains Rider!

Update JetBrains Rider instructions

---

10/umbraco-forms/release-notes.md

Added release notes for Forms 8.13.15 and 8.13.16.
Forms 8.13.15 and 8.13.16
Can be published as soon as you have opportunity to do so please.

Added release notes for Forms 8.13.15 and 8.13.16

---

.github/README.md

Correct contributing guide link in README
N/A
N/A

Correct contributing guide link

---

14/umbraco-cms/reference/querying/umbraco-context.md
15/umbraco-cms/reference/querying/umbraco-context.md

Porting old Umbraco API Controller [Querying > Umbraco Context]

---

13/umbraco-engage/tutorials/how-to-create-a-persona.md
13/umbraco-engage/upgrading/migrate-from-umarketingsuite.md

Merging the technical uMarketingSuite to Engage migration article with the one currently being worked on.

Merge existing article with technical article

---

13/umbraco-commerce/release-notes/README.md
14/umbraco-commerce/release-notes/README.md

Umbraco Commerce v13.1.10 and v14.1.5 release notes
Umbraco Commerce v13.1.10 and v14.1.5
ASAP

Umbraco Commerce v13.1.10 and v14.1.5 release notes

---

umbraco-heartcore/SUMMARY.md

Added the Persisted queries to the menu
Heartcore

Adds Persisted queries page to the menu

---

13/umbraco-commerce/release-notes/README.md
14/umbraco-commerce/release-notes/README.md

Umbraco Commerce 13.1.12 & 14.1.7 release notes
Umbraco Commerce 13.1.12 & 14.1.7 
ASAP

Umbraco Commerce 13.1.12 & 14.1.7 release notes

---

13/umbraco-forms/developer/themes.md
13/umbraco-forms/release-notes.md
14/umbraco-forms/developer/themes.md
14/umbraco-forms/release-notes.md

Added release notes for Forms 13.3 and 14.2.
Forms 13.3 and 14.2
Either on or before Thursday morning if possible please.

Added release notes for Forms 13.3 and 14.2.

---

14/umbraco-workflow/release-notes.md

Adds notes for WF 14.1.1
Workflow 14.1.1
Whenever works for you 😄

Workflow 14.1.1 release notes

---

umbraco-cloud/set-up/new-shop/README.md

Removed old image from cloud docs

---

14/umbraco-cms/customizing/extending-overview/extension-types/section-sidebar.md
15/umbraco-cms/customizing/extending-overview/extension-types/section-sidebar.md

Replaces https://github.com/umbraco/UmbracoDocs/pull/6667

Update code snippet

---

15/umbraco-forms/release-notes.md

Added release notes for Forms 15.0.
Forms 15.0

Release notes for Forms 15.0

---

15/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/block-editor/block-grid-editor.md

This PR is in addition to:
https://github.com/umbraco/UmbracoDocs/pull/6510

Change UmbracoApiController to Controller

---

14/umbraco-cms/implementation/controllers.md
15/umbraco-cms/implementation/controllers.md

updated mvc training course details and link. The course is no longer focused on Visual Studio hence updated the text and link with the correct ones.
cms v14 and v15
anytime

update mvc training course details and link

---

13/umbraco-forms/release-notes.md
14/umbraco-forms/release-notes.md
15/umbraco-forms/release-notes.md

Added release notes for Forms 13.3.2, 14.2.2 and 15.0.2
Forms 13.3.2, 14.2.2 and 15.0.2
Ideally please publish any time after lunch on Wednesday and before the end of the day.  I'll release the product updates on Thursday morning.  Thanks.

Added release notes for Forms 13.3.2, 14.2.2 and 15.0.2

---

umbraco-cloud/set-up/project-settings/secrets-management.md

Update to secrets management

---

15/umbraco-cms/fundamentals/setup/upgrading/version-specific/README.md

Added information as mentioned in #[17615](https://github.com/umbraco/Umbraco-CMS/issues/17615)
CMS v15
Anytime

Added information about precompresssed files

---

umbraco-cloud/security/README.md

Removed redundant info

---

13/umbraco-forms/release-notes.md
14/umbraco-forms/release-notes.md
15/umbraco-forms/release-notes.md

Added release notes for Forms 13.3.3, 14.2.3, 15.0.3
Forms 13.3.3, 14.2.3, 15.0.3
Anytime from now to end of day on Wednesday please.

Added release notes for Forms 13.3.3, 14.2.3, 15.0.3

---

umbraco-heartcore/client-libraries/node-js.md

Refined node.js article with updated code and steps

---

15/umbraco-cms/SUMMARY.md
15/umbraco-cms/customizing/extending-overview/extension-types/entity-create-option-action.md

Added Entity Create Option Action article to v15

---

13/umbraco-ui-builder/release-notes.md
13/umbraco-ui-builder/searching/searchable-properties.md
14/umbraco-ui-builder/release-notes.md
14/umbraco-ui-builder/searching/searchable-properties.md
15/umbraco-ui-builder/release-notes.md
15/umbraco-ui-builder/searching/searchable-properties.md

* Release notes for `Umbraco.UIBuilder 13.1.6, 14.0.1, 15.0.1`
* Searchable properties updated docs
`Umbraco.UIBuilder 13.1.6, 14.0.1, 15.0.1`

Update Umbraco.UIBuilder release notes and searchable properties

---

13/umbraco-deploy/release-notes.md
14/umbraco-deploy/release-notes.md
15/umbraco-deploy/release-notes.md

Add Deploy 13.3.2, 14.2.2 and 15.0.2 release notes

Add Deploy 13.3.2, 14.2.2 and 15.0.2 release notes

---

15/umbraco-cms/reference/content-delivery-api/README.md

Fix link to Protected Content in the Delivery API

Fix link to Protected Content in the Delivery API

---

15/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/rich-text-editor/extensions.md

Add Language specifier to code block

Add Language specifier to code block

---

13/umbraco-commerce/release-notes/README.md
14/umbraco-commerce/release-notes/README.md

Umbraco Commerce v13.1.15 & v14.2.1 release notes
Umbraco Commerce v13.1.15 & v14.2.1 
ASAP

Umbraco Commerce v13.1.15 & v14.2.1 release notes

---

.github/styles/UmbracoDocs/Acronyms.yml

Added CMD to the list of accepted acronyms.

Added CMD to accept list

---

15/umbraco-cms/customizing/extending-overview/extension-types/backoffice-entry-point.md

Added missing quotes to extensions section of umbraco-package.json snippet

Update backoffice-entry-point.md missing quotes

---

13/umbraco-commerce/release-notes/README.md
14/umbraco-commerce/release-notes/README.md

Umbraco Commerce 13.1.16 & 14.3.0 release notes
Umbraco Commerce 13.1.16 & 14.3.0 
ASAP

Umbraco Commerce 13.1.16 & 14.3.0 release notes

---

15/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/rich-text-editor/extensions.md

Update TipTap Extensions

---

10/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/media-picker-3.md
13/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/media-picker-3.md
14/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/media-picker-3.md
15/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/media-picker-3.md

Update media picker 3

---

15/umbraco-commerce/README.md
15/umbraco-commerce/release-notes/README.md
commerce-add-ons/packages/checkout/release-notes.md

Umbraco Commerce v15 release notes
Umbraco Commerce v15 
ASAP

Umbraco Commerce v15 release notes

---

14/umbraco-cms/fundamentals/backoffice/login.md

Changed "Is is" to "It is"

---

13/umbraco-commerce/release-notes/README.md
14/umbraco-commerce/release-notes/README.md

Umbraco Commerce 13.1.17 & 14.3.1 release notes
Umbraco Commerce 13.1.17 & 14.3.1
ASAP

Umbraco Commerce 13.1.17 & 14.3.1 release notes

---

13/umbraco-engage/upgrading/version-specific-upgrade-notes.md

The Umbraco Engage Forms addon received a simular update as the primary package did, which is worth documenting under the version specific upgrade notes 😊
Umbraco Engage Forms v13.1.0

Updated Engage version specific upgrade notes

---

15/umbraco-cms/reference/searching/examine/corrupt-indexes.md

Documented corrupt examine index resolution
CMS v14+
Can be done now as the content is not listed in trees and is applicable to the current state of the product. The product will link to this article from v15.2 onwards.

Document corrupt examine index resolution

---

15/umbraco-cms/customizing/property-editors/composition/property-editor-ui.md

Use correct propertyname and a correct value
I think its all 14+
ASAP

Fixing example

---

15/umbraco-cms/customizing/extending-overview/extension-types/workspaces/workspace-views.md

Since we are creating a workspace view, we should call it a workspace-view, and not a dashboard (I'm thinking this is a copy/paste mistake :-D)
14+ I think
ASAP

Fixing some wording

---

13/umbraco-commerce/release-notes/README.md

Umbraco Commerce 13.1.18 release notes
Umbraco Commerce 13.1.18
ASAP

Umbraco Commerce 13.1.18 release notes

---

14/umbraco-cms/fundamentals/design/templates/README.md
15/umbraco-cms/fundamentals/design/templates/README.md

Forgot to commit the removal of links in my previous PR.

Remove broken links

---

13/umbraco-workflow/release-notes.md

Release notes for Workflow 13.3.2

Workflow 13.3.2 release notes

---

10/umbraco-commerce/key-concepts/bulk-actions.md
13/umbraco-commerce/key-concepts/bulk-actions.md

This updates the code snippets in the v10 + v13 docs for Umbraco Commerce bulk actions as the previous examples didn't work.
Umbraco Commerce 10 and 13
ASAP

Update the Umbraco Commerce bulk action example code snippets

---

13/umbraco-deploy/installation/install-configure.md

Updated the incorrect package name so that it is the correct one.
Umbraco.Deploy.Forms have been renamed to Umbraco.Forms.Deploy
13

Updating incorrect package name for the forms package for deploy.

---

umbraco-cloud/deployment/README.md

- Updated article as per the styleguide
- Removed the video tutorial section as it was a very old video (recorded by Gabriel 😲)
Cloud
Anytime

Updated Deployment article as per styleguide

---

10/umbraco-ui-builder/release-notes.md

Updated release notes for Umbraco UIBuilder version `10.0.5`.
Umbraco UIBuilder 10.0.5

Umbraco UIBuilder release notes for version 10.0.5

---

15/umbraco-cms/fundamentals/setup/install/running-umbraco-on-docker-locally.md

The command was missing a 'd'. Running the current command gives:
Error: Invalid option(s):
--DatabasePasswor
'--DatabasePasswor' is not a valid option

Correct --DatabasePassword command

---

umbraco-cloud/set-up/project-settings/secrets-management.md

Documenting that we have added the Umbraco Authorized Services config path to the allowed prefixes in Secret Management
Cloud / Secret Management
I'll give a go when this is released

Cloud Secrets Management allow AuthorizedServices 

---

15/umbraco-cms/fundamentals/setup/requirements.md

Added the note about collation to requirements.md
I think that all versions are affected, regarding to this comment from owner: https://github.com/umbraco/Umbraco-CMS/pull/18294?new_mergebox=true#discussion_r1950945095
no deadline
Cannot answer to this question, let maintainers to decide

Added note about collation to requirements.md

---

13/umbraco-commerce/release-notes/README.md
14/umbraco-commerce/release-notes/README.md
15/umbraco-commerce/release-notes/README.md

Umbraco Commerce 13.1.19, 14.4.0 and 15.1.1 release notes
Umbraco Commerce 13.1.19, 14.4.0 and 15.1.1
ASAP

Umbraco Commerce 13.1.19, 14.4.0 and 15.1.1 release notes

---

13/umbraco-forms/upgrading/migration-ids.md
14/umbraco-forms/upgrading/migration-ids.md
15/umbraco-forms/upgrading/migration-ids.md

Added missing migration IDs as mentioned in Issue #6895 
Forms v13, 14, 15
Anytime

Added missing Forms Migration IDs

---

umbraco-cloud/set-up/external-login-providers.md

Update to Entra ID guide
Entra Guide is pointing to the wrong endpoint to use as Authority
Cloud / External Login Providers

External Login Providers Entra ID Guide update

---

15/umbraco-cms/reference/configuration/securitysettings.md

Added missing information about `RequireUppercase` option. Also fixed typo (on -> one).

Update securitysettings.md - Added missing information about `RequireUppercase` option. Also fixed typo (on -> one).

---

13/umbraco-forms/release-notes.md
15/umbraco-forms/release-notes.md

Added Forms 13.4.1 and 15.1.1 release notes.
Forms 13.4.1
Forms 15.1.1
Both versions are already released, so this can be merged asap.

Add Forms 13.4.1 and 15.1.1 release notes

---

15/umbraco-cms/.gitbook.yaml
15/umbraco-cms/tutorials/creating-a-backoffice-api/documenting-your-controllers.md
15/umbraco-cms/tutorials/creating-a-backoffice-api/versioning-your-api.md

Some broken (not broken) links have been identified and fixed.
Some redirects have also bee fixed, as they were outdated or wrong.
CMS

Fixing redirects and broken links

---

15/umbraco-ui-builder/actions/the-basics.md

fix: typos in UI Builder actions docs

---

14/umbraco-cms/fundamentals/backoffice/logviewer.md
15/umbraco-cms/fundamentals/backoffice/logviewer.md

Updated logviewer article for versions 14 and 15

---

15/umbraco-ui-builder/collections/child-collection-groups.md
15/umbraco-ui-builder/collections/child-collections.md
15/umbraco-ui-builder/collections/editors.md
15/umbraco-ui-builder/collections/field-views.md
15/umbraco-ui-builder/collections/list-views.md
15/umbraco-ui-builder/collections/overview.md
15/umbraco-ui-builder/collections/related-collections.md
15/umbraco-ui-builder/collections/retrieve-child-collections.md
15/umbraco-ui-builder/collections/the-basics.md

- Updated articles in the Collections section as per styleguide. 
- Provided headings for method name and changed format for displaying syntax.
- Shortened sentences
- Updated descriptions where required
- Added descriptions to explain code samples where required.
UI Builder v15
Anytime

Updated articles as per styleguide

---

15/umbraco-workflow/SUMMARY.md

Fix URL to workspace view. In addition to: https://github.com/umbraco/UmbracoDocs/pull/6954
Umbraco Workflow

Fix URL to workspace view

---

14/umbraco-cms/.gitbook/includes/umbraco-extending-the-backoffice-training-course.md
14/umbraco-cms/.gitbook/includes/umbraco-fundamentals-training-course.md
14/umbraco-cms/.gitbook/includes/umbraco-load-balancing-training-course.md
14/umbraco-cms/.gitbook/includes/umbraco-searching-and-indexing-training-course.md

Removed title from reusable content

---

14/umbraco-cms/.gitbook/includes/umbraco-mvc-training-course.md

Removed title from reusable content v14

---

marketplace-and-integrations/integrations/activecampaign-with-umbraco-forms.md
marketplace-and-integrations/integrations/activecampaign.md
marketplace-and-integrations/integrations/algolia.md
marketplace-and-integrations/integrations/aprimo.md
marketplace-and-integrations/integrations/cookiebot.md
marketplace-and-integrations/integrations/dynamics.md
marketplace-and-integrations/integrations/emerchantpay-with-umbraco-forms.md
marketplace-and-integrations/integrations/google-search-console.md
marketplace-and-integrations/integrations/hubspot-with-umbraco-forms.md
marketplace-and-integrations/integrations/hubspot.md
marketplace-and-integrations/integrations/inriver.md
marketplace-and-integrations/integrations/semrush.md
marketplace-and-integrations/integrations/shopify.md
marketplace-and-integrations/integrations/zapier-with-umbraco-forms.md
marketplace-and-integrations/integrations/zapier.md
marketplace-and-integrations/packages/authorized-services.md

- Removed CMS version table
- Added generic statement linking to NuGet
- Added package links in the authorized services article
DXP
Anytime

Couple of Updates in DXP articles

---

15/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/content-picker.md

Updated the content picker's dynamic root custom query step example following an issue raised on the CMS tracker: https://github.com/umbraco/Umbraco-CMS/issues/18829
CMS 15+
Any time.

Update the dynamic root custom query step example

---

umbraco-heartcore/SUMMARY.md
umbraco-heartcore/release-notes/2025-04-releasenotes.md

Created releasenotes for Heartcore April 2025 describing that Workflow is now installed on Heartcore
Not relevant for Heartcore
Not relevant

Heartcore release notes for April 2025

---

16/umbraco-cms/README.md
16/umbraco-cms/release-candidate-guide.md
16/umbraco-commerce/README.md
16/umbraco-deploy/README.md
16/umbraco-forms/README.md
16/umbraco-ui-builder/README.md
16/umbraco-workflow/README.md

Added RC Guide to CMS + notes to product landing pages

Prep 16: Added RC Guide to CMS + notes to product landing pages

---

umbraco-cloud/set-up/external-login-providers.md

We are promoting the feature out of beta
Cloud / External Login Providers
not a deadline but
from midday April 15th this is okay to merge

Cloud External Login Providers- remove beta

---

13/umbraco-engage/tutorials/how-to-create-a-persona.md

I updated urls to other docs pages for the how-to-create-a-persona engage tutorial.
They currently don't work.
Umbraco Engage v13

Updated docs urls for the how-to-create-a-persona tutorial.

---

15/umbraco-commerce/release-notes/README.md

Umbraco Commerce 15.3.0 Release Notes
Umbraco Commerce 15.3.0
ASAP

Umbraco Commerce 15.3.0 Release Notes

---

15/umbraco-commerce/release-notes/README.md

Umbraco Commerce 15.3.1 Release Notes
Umbraco Commerce 15.3.1
ASAP

Umbraco Commerce 15.3.1 Release Notes

---

16/umbraco-cms/release-candidate-guide.md

Added links to updated articles.
16.0.0

Add links to updated articles

---

13/umbraco-ui-builder/release-notes.md

`Umbraco.UIBuilder` release notes for version `13.2.4`.
Umbraco.UIBuilder 13.2.4
When possible

Updated Umbraco UI Builder release notes for version 13.2.4

---

15/umbraco-workflow/release-notes.md

Workflow 15.1.3 notes

---

13/umbraco-cms/fundamentals/code/umbraco-services.md
14/umbraco-cms/fundamentals/code/umbraco-services.md

Applied changes from PR #7043 to v13 and v14 as well.
CMS v13 and v14
Anytime

Incorporated changes from v15 to v13 and v14

---

15/umbraco-ui-builder/release-notes.md

Umbraco UI Builder release notes for version `15.1.3`.
Umbraco UI Builder 15.1.3
When possible

Updated release notes for UI Builder 15.1.3

---

13/umbraco-cms/reference/configuration/securitysettings.md

Added details of security settings backported to 13
Umbraco 13
I'll publish this one, as the text is just copied from a newer version and already reviewed.

Added details of security settings backported to 13

---

16/umbraco-cms/fundamentals/setup/upgrading/version-specific/README.md

Added further details of 16 breaking changes, as collated from the team and made available in the RC blog post.
Umbraco 16
Anytime.

Further details of 16 breaking changes

---

15/umbraco-cms/fundamentals/setup/install/running-umbraco-on-docker-locally.md

Fixes Issue #7054 
CMS v15
Anytime

Updated the article to include SQLite setup as well

---

15/umbraco-cms/customizing/ui-library.md

Added keyword to help improve searchability. Related to Issue #7071 
CMS v15
Anytime

Added "Backoffice" keyword

---

14/umbraco-cms/customizing/ui-library.md
16/umbraco-cms/customizing/ui-library.md

Added "Backoffice" keyword to improve discoverability by serach engines.
CMS v14 and v16
Anytime

Added "Backoffice" keyword for v14 and v16

---

15/umbraco-ui-builder/release-notes.md

Umbraco UI Builder `15.1.4` release notes.
Umbraco UI Builder `15.1.4`
When possible.

Umbraco UI Builder 15.1.4 release notes

---

sustainability-best-practices/README.md

Removed notorious slash
Sustainability Best Practices
Anytime

Fixed broken link in sustainability docs

---

marketplace-and-integrations/integrations/aprimo.md
marketplace-and-integrations/integrations/emerchantpay-with-umbraco-forms.md

Removed wrong slashes from links
Marketplace and Integrations
Anytime

Fixed broken links in Marketplace and Integrations

---

13/umbraco-ui-builder/changelog-archive/changelog.md
13/umbraco-ui-builder/release-notes.md

Fixed broken links in UI Builder v13
UI Builder v13

Fixed broken links in UI Builder v13

---

15/umbraco-ui-builder/release-notes.md

Umbraco UI Builder 15.1.6 release notes
Umbraco UI Builder 15.1.6

Umbraco UI Builder 15.1.6 release notes

---

13/umbraco-forms/release-notes.md
15/umbraco-forms/release-notes.md
16/umbraco-forms/release-notes.md

Add Forms 13.5.0-rc, 15.2.0-rc and 16.0.0-rc, Forms Deploy 13.1.1, 15.1.1 and 16.0.0-rc3 release notes.
Forms 13.5.0-rc
Forms 15.2.0-rc
Forms 16.0.0-rc
Forms Deploy 13.1.1
Forms Deploy 15.1.1
Forms Deploy 16.0.0-rc3
All versions are already available on NuGet, so this can be published asap.

Add Forms 13/15/16 RC release notes

---

13/umbraco-engage/README.md

Another attempt at resolving sync issues with GitBook.

Fix REAdME

---

15/umbraco-workflow/release-notes.md

Quick release notes for Workflow 15.1.5

updates release notes for v15

---

umbraco-cloud/SUMMARY.md

Removed subscription-migration-information-and-faq.md entry since it's deleted/removed in PR #7145.
Cloud

Removed subscription-migration-information-and-faq.md entry..

---

security-and-privacy/README.md

The Security and Privacy community team wants to write best-practice docs.
I've created a new directory for them to get started.

Add new directory for security and privacy

---

umbraco-cloud/SUMMARY.md
umbraco-cloud/getting-started/flexible-environments.md

Removed the Beta text
No deadline :)

Removed the "Beta" text from Flexible Environments

---

16/umbraco-cms/SUMMARY.md
16/umbraco-cms/fundamentals/setup/server-setup/running-umbraco-in-docker.md

This article was never added to version 16, which is should be.

Add missing article from 15

---

13/umbraco-cms/reference/scheduling.md
14/umbraco-cms/reference/scheduling.md
15/umbraco-cms/reference/scheduling.md

Formatted IRecurringBackgroundJob section for better readability - other CMS versions

---

15/umbraco-commerce/release-notes/README.md

Umbraco Commerce 15.3.8 release notes
Umbraco Commerce 15.3.8

Umbraco Commerce 15.3.8 release notes

---

14/umbraco-cms/fundamentals/setup/server-setup/load-balancing/azure-web-apps.md
15/umbraco-cms/fundamentals/setup/server-setup/load-balancing/azure-web-apps.md
16/umbraco-cms/fundamentals/setup/server-setup/load-balancing/azure-web-apps.md

Added updates from #6610 to v15 and v16
Anytime

Added updates to v15 and v16 as per v14 PR update

---

13/umbraco-cms/reference/querying/itagquery.md
14/umbraco-cms/reference/querying/itagquery.md
15/umbraco-cms/reference/querying/itagquery.md
16/umbraco-cms/reference/querying/itagquery.md

Added updates from PR #7059 to rest of the versions
CMS v14, v15, v16

Added updates from PR# 7059

---

umbraco-cloud/.gitbook.yaml

Added redirect for a Page Not found link
Cloud

Added redirects

---

umbraco-cloud/optimize-and-maintain-your-site/monitor-and-troubleshoot/hostname-monitoring.md

This pull request adds a new section to the `hostname-monitoring.md` file, providing an example of how to use ASP.NET Core Health Checks for monitoring application health. This addition enhances the documentation by offering a practical implementation guide for developers.
* Added a new section titled "ASP.NET Core Health Checks Example" in `umbraco-cloud/optimize-and-maintain-your-site/monitor-and-troubleshoot/hostname-monitoring.md`. This section explains how to set up health checks in an ASP.NET Core application, including code examples for adding health checks and mapping a health check endpoint. It also describes how Umbraco Cloud hostname monitoring can integrate with these health checks to determine application health based on HTTP response codes.
I've followed the [Umbraco …

Document the ability to use asp.net healthchecks with hostname monitoring

---

umbraco-cloud/.gitbook.yaml

Added more redirects from GitBook's Broken URLs tab
Cloud

Added more redirects from GitBook's Broken URLs tab

---

umbraco-cloud/.gitbook.yaml

Removed duplicate redirect

---

15/umbraco-ui-builder/release-notes.md
16/umbraco-ui-builder/release-notes.md

Umbraco UI Builder release notes for versions 15.1.9 and 16.0.2
Umbraco UI Builder 15.1.9 and 16.0.2

Umbraco UI Builder release notes

---

16/umbraco-cms/reference/umbraco-flavored-markdown.md

Two new UFM filters was missing
16.0.0

Adds missing UFM filters

---

14/umbraco-cms/tutorials/custom-error-page.md
15/umbraco-cms/tutorials/custom-error-page.md
16/umbraco-cms/tutorials/custom-error-page.md

Updated implementing custom error pages article

---

13/umbraco-workflow/installation/licensing.md
13/umbraco-workflow/release-notes.md
15/umbraco-workflow/release-notes.md
16/umbraco-workflow/release-notes.md

Release notes for Umbraco Workflow
- 13.4.4
- 15.1.6
- 16.0.2

workflow patch release notes

---

16/umbraco-deploy/.gitbook.yaml

Added redirects for Deploy broken links.
NA
Deploy v16
Anytime

Added redirects for Deploy broken links

---

umbraco-cloud/begin-your-cloud-journey/creating-a-cloud-project/README.md
umbraco-cloud/begin-your-cloud-journey/creating-a-cloud-project/baselines.md
umbraco-cloud/begin-your-cloud-journey/creating-a-cloud-project/migrate-to-umbraco-cloud.md
umbraco-cloud/begin-your-cloud-journey/project-features/environments.md
umbraco-cloud/begin-your-cloud-journey/project-features/secrets-management.md
umbraco-cloud/begin-your-cloud-journey/project-features/team-members/README.md
umbraco-cloud/begin-your-cloud-journey/project-features/team-members/technical-contact.md
umbraco-cloud/begin-your-cloud-journey/project-features/users-on-cloud.md

I've fixed some warnings/errors based on our styleguide.

Cloud Docs cleanup

---

16/umbraco-cms/reference/routing/custom-controllers.md

Remove duplicate class and method declaration. Also fix broken link

Remove duplicate code in custom-controllers.md

---

16/umbraco-workflow/release-notes.md

One-liner update to add 16.0.5, which fixes a missed issue in 16.0.4

Workflow 16 0 5

---

16/umbraco-ui-builder/release-notes.md

Umbraco UI Builder release notes for version `16.0.4`.
Umbraco UI Builder 16.0.4
When possible

UI Builder 16.0.4 release notes

---

13/umbraco-workflow/workflow-section/approval-groups.md

Add note about group email restriction for offline approval

Clarify offline approval group email limitation
